### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zemse** [denoland/vscode_deno#100]
I was getting this notification in vscode, is this the extension fault or it is my system? This is the first time I'm seeing this.

[denoland.vscode-deno-unresponsive.cpuprofile.txt](https://github.com/denoland/vscode_deno/files/4866329/denoland.vscode-deno-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `1.25.0`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.46.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JohnstonCode** [comment]
Was this a one off or does it happen consistently?

**Comment by lucacasonato** [comment]
I can not reproduce - does this still occur in the latest version?

**Comment by zemse** [comment]
Didn't get it after that. Closing for now. If it ever occurs, we can reopen.
