### ISSUE TITLE
Cannot go to npm dependency definition

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/vscode_deno#1001]
**Describe the bug**

cmd+click (or ctrl+click on windows) doesn't seem to work on npm specifier paths.

**To Reproduce**

1. Create `deno.json` with these contents:
  ```json
  {
    "imports": {
      "svelte": "npm:svelte@4.2.8",
      "svelte/": "npm:/svelte@4.2.8/"
    }
  }
  ```
2. Create `foo.ts` with these contents:
  ```ts
  import * as sv from "svelte/internal";
  console.log(sv);
  ```
3. Run `deno run -A foo.ts`
4. Open `foo.ts` in vscode and try to click on the `svelte/internal` import specifier.

**Expected behavior**

cmd+click (or ctrl+click on windows) should go to the source definition.

**Screenshots**

https://github.com/denoland/vscode_deno/assets/1062408/090e1ff2-d307-4cf6-bb85-09d7b7234533

**Versions**

vscode: insiders from 2023-12-05 deno: 1.38.5  extension: v3.28.0

**Comment by darkship** [comment]
There seems to be a slight improvement, I can go to the module but definition from imported files inside of the module can't be reached.


https://github.com/denoland/vscode_deno/assets/3523710/a8dd928b-6a9d-485e-82a9-4029b897e6b1



vscode: 1.89.1
extention: 3.37.1
deno 1.43.4 (release, x86_64-unknown-linux-gnu)
v8 12.4.254.13
typescript 5.4.5
