### ISSUE TITLE
Deno fmt even when disabled

### ISSUE THREAD

**Issue by ShayBox** [denoland/vscode_deno#101]
Deno fmt keeps formatting my typescript files even when I disable the extension with the config setting, uninstalling fixes it.

**Comment by ebebbington** [comment]
Do you mean running `deno fmt` is still formatting your files? Or the plugin is still formatting your files **automatically** when it is disabled?

Can you show the contents of your `tsconfig.json` file?

**Comment by ShayBox** [comment]
I don't have a tsconfig.json, I clicked the popup that asks if I want to disable the deno extension because there's a package.json, I click it, it adds the disable option in the settings.json, but saving the ts file still formats with deno fmt, only uninstalling or disabling the extension fixes it.

**Comment by ebebbington** [comment]
From the README, it says:

> deno.autoFmtOnSave - Turns auto format on save on or off. Default is false. (Not implemented)

So it seems like the extension doesn't (or shouldn't) have the ability to format.

You might also need to restart VSCode if you haven't already when you disable it. Can you provide thorough steps on replicating this? Along with your VSCode version

**Comment by ShayBox** [comment]
That should probably just be removed from the readme, that's not how extensions implement format on save, the way eslint, tslint, and other extensions do it now:
```
"editor.formatOnSave": true,
"[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
}
```
That said, my confusion is I don't have that setup for deno, it just started auto formatting on save, and it is the extension doing it, or some link between eslint and deno fmt, disabling or uninstalling the deno extension fixes it and only leaves eslint formatting, instead of both conflicting every save.

So I both don't know what's causing it to format on save, and whatever that may be doesn't get disabled by `"deno.enable": false` or `"editor.formatOnSave": false`.

I don't know how to replicate it, I have a bunch of extensions I don't really feel like uninstalling and reinstalling, but this is my settings.json https://paste.nomsy.net/dowiziwebu.json

**Comment by mattgaspar** [comment]
I also encountered the Deno extension formatting my code even though it was disabled in settings (like @ShayBox said).

I just installed Deno yesterday and updated VS Code to 1.47 today so not sure if the bug was related to the VS Code update or not.

I was also seeing inconsistency, I had 2 VS Code projects open in different windows, both with Deno disabled in the settings and one instance of VS Code was auto formatting strangely on save and the other was not.

Note that I do have format on save enabled for VS Code, my issue is that the format on save was very different than the format on save config I have in VS Code.  For example, **I have my format settings as 4 spaces for tabs but with the Deno extension installed (but disabled in settings) my files were getting switched to 2 spaces for tabs as well as some other random things.  As soon as I disabled the Deno extension, the issue went away.**

**Comment by daemon1024** [comment]
@mattgaspar 

> Also there is a setting deno.unstable which is defaulting to true.

https://github.com/denoland/vscode_deno/pull/35 and https://deno.land/manual/runtime/stability for more info.


> The setting `autoFmtOnSave` doesn't even seem to be valid. It's lighter color and says "Unknown Configuration Setting".

As mentioned in the README and extension's homepage

_deno.autoFmtOnSave - Turns auto format on save on or off. Default is false. (Not implemented)_

`autoFmtOnSave` hasn't been implemented yet.

**Comment by jhechtf** [comment]
I'm also running into this issue. I was working on another typescript project and was running into issues with the non-deno formatter and the deno formatter were fighting when i was saving the files.

If deno is disabled for a workspace, it shouldn't format on save. I've tested this by running eslint through the files, and then disabling deno from the workspace in the extensions pane. Upon hitting save, nothing happens. If I re-enable deno for the workspace, open up a file, and hit save then the code is formatted in the deno way.

**Comment by JohnstonCode** [comment]
@mattgaspar Changing the settings directly will not disable the extension as there is no listener setup. You are correct the `autoFmtOnSave` config option is not valid and it is only mentioned in the readme. It is not used internally in the extension. This should probably be removed.

@ShayBox The behaviour you describe is the way the extension should work. It should be have like the prettier extension does. Do you have any workspace specific settings?

@jhechtf I am not able to reproduce the problem you are having. If i disable the extension and restart VSCode i don't get auto formatting and `Deno` isn't listed as a formatting provider.

What version of the extension are you all using?

**Comment by ShayBox** [comment]
I just stopped using it, it was constantly formatting my code in non deno projects even when I used the setting to disable it either globally or per workspace, the only workaround is to disable and enable the whole extension every time you switch to a deno project.

**Comment by JohnstonCode** [comment]
Been able to reproduce now. I'll see if i can figure out what is going on.

**Comment by JohnstonCode** [comment]
Created a PR which will use the `deno.autoFmtOnSave` config option to enabled/disable the build in formatter.
