### ISSUE TITLE
TypeScript "Go to definition" doesn't work with esm.sh imports

### ISSUE THREAD

**Issue by d9k** [denoland/vscode_deno#1011]
I find that I sometimes have to use types from cdn.skypack.dev or `"Go to definition"` VSCode command doesn't work with esm.sh packages.

`importMap.json`:

```
    "@types/react-data-grid": "https://cdn.skypack.dev/react-data-grid@7.0.0-beta.41?dts",
    "react-data-grid": "https://esm.sh/react-data-grid@7.0.0-beta.41?external=react",
```

Actual code:

```
// @deno-types="@types/react-data-grid"
import VendorDataGrid, {
  Column as VendorColumn,
  DataGridProps as VendorDataGridProps,
} from 'react-data-grid';
```

**Comment by d9k** [comment]
I learned about `"https://cdn.skypack.dev/...?dts` from https://github.com/lodash/lodash/issues/5411#issuecomment-1647990541

**Comment by nayeemrmn** [comment]
@d9k This is probably because your import map is not detected by the LSP. If you rename it to `deno.json` or embed it in your existing one, it should work. But your `deno.json` must be at the workspace root currently.

**Comment by d9k** [comment]
@nayeemrmn, don't think it is the source of an issue. Having

```
"importMap": "./importMap.json"
```

in `deno.json`

**Comment by nayeemrmn** [comment]
@d9k Is your `deno.json` at the workspace root?

**Comment by d9k** [comment]
@nayeemrmn, of course. Tried this too.

**Comment by d9k** [comment]
...probably I have to prepare minimal reproduction repo. I'll try to create it someday later.

**Comment by nayeemrmn** [comment]
Let's reopen this when there's a minimal reproduction if you can, or if it's a persistent and disruptive issue.
