### ISSUE TITLE
Add support for unstable sloppy imports

### ISSUE THREAD

**Issue by bcheidemann** [denoland/vscode_deno#1012]
**Is your feature request related to a problem? Please describe.**

Valid Deno code with the `--unstable-sloppy-imports` shows errors in the editor. There is currently (as of v3.29.0) no way to enable the `--unstable-sloppy-imports` flag.

![deno-vscode-sloppy-impot](https://github.com/denoland/vscode_deno/assets/56122437/f1f08976-6141-45b5-8f07-1f4d6e9617cb)

**Describe the solution you'd like**

There should be some way to configure the extension to allow unstable sloppy imports. For example:

```json
// .vscode/settings.json
{
    "deno.enable": true,
    "deno.unstableSloppyImports": true
}
```

**Comment by bcheidemann** [comment]
Happy to raise a PR for this btw

**Comment by bartlomieju** [comment]
@dsherret could you take a look at this? I thought this was supposed to work.

**Comment by dsherret** [comment]
@bcheidemann it should work if you add it to the root deno.json:

```json
{
  "unstable": ["sloppy-imports"]
}
```

**Comment by bcheidemann** [comment]
> @bcheidemann it should work if you add it to the root deno.json:
> 
> ```json
> {
>   "unstable": ["sloppy-imports"]
> }
> ```

Thanks for the quick response @dsherret @bartlomieju. This is indeed working for me :)

Excuse my ignorance, but when I have a non-root `deno.json` (for example when I use `deno.enablePaths` in the context of a monorepo), should the VSCode extension consider the configuration from the `deno.json` files specified in the enabled paths also?

Currently it doesn't - see https://github.com/bcheidemann/deno_vscode_sloppy_imports - unless I add `"deno.config": "./apps/deno-app/deno.json"` to `.vscode/settings.json`. The issue is `deno.config` only accepts a single config, effectively limiting me to sharing the same configuration across all Deno apps in my monorepo.

**Comment by bartlomieju** [comment]
I think you're looking for https://github.com/denoland/deno/pull/21029

**Comment by bcheidemann** [comment]
> I think you're looking for [denoland/deno#21029](https://github.com/denoland/deno/pull/21029)

Looks like it, thanks :)
