### ISSUE TITLE
Testing code lens settings appear ignored

### ISSUE THREAD

**Issue by jcayzac** [denoland/vscode_deno#1017]
In my workspace's `.vscode/settings.json`,

Whether I set `deno.codeLens.test` to `true` or `false` is irrelevant, I can always run my unit tests from the VSCode code lens.

Similarly, passing arguments in `deno.testing.args` does nothing. Adding the following _should_ generate coverage information, but does not:

```json
"deno.testing.args": [
  "--allow-all",
  "--no-prompt",
  "--coverage=.coverage"
]
```

---

### Versions:

- vscode: 1.85.1
- deno: 1.39.0
- extension: 3.30.0

**Comment by bartlomieju** [comment]
@nayeemrmn can you look at that? I think we bail out of analysis when using template strings right now. But we should only do it if there's actually any interpolation going on.

**Comment by nayeemrmn** [comment]
> Whether I set `deno.codeLens.test` to `true` or `false` is irrelevant, I can always run my unit tests from the VSCode code lens.

@jcayzac Can't reproduce on 1.39.2, can you share your full settings?

**Comment by jcayzac** [comment]
@nayeemrmn could you please tell me which part you cannot reproduce? I posted more context in the comments below that original post.

**Comment by nayeemrmn** [comment]
@jcayzac I can turn test code lenses off by setting `"deno.codeLens.test": false`.

https://github.com/denoland/vscode_deno/issues/1017#issuecomment-1876805471 is a separate issue which was addressed by https://github.com/denoland/deno/pull/21798.

**Comment by jcayzac** [comment]
@nayeemrmn apologies, given the flag had no effect and I wasn't seeing any test lens because of https://github.com/denoland/vscode_deno/issues/1017#issuecomment-1876805471 , I mistakenly thought what the extension called a test lens was the test gutter action, which was always shown and let me run the tests.
