### ISSUE TITLE
Deno: Initialize Workspace Configuration should not ask about linting and unstable features

### ISSUE THREAD

**Issue by matklad** [denoland/vscode_deno#1025]
Answering project creation wizard steps by default is hugely distracting. I thin the extension should unconditionally enable linting, and unconditionally disable unstable features --- both are easy to change in settings.json later on, and are reasonable defaults, so I'd say there's no need to bother humans with these choices up-front.

**Comment by bartlomieju** [comment]
We will remove unstable type checking in https://github.com/denoland/deno/pull/21825. With this change I think we'll just enable linting by default.

**Comment by bartlomieju** [comment]
@nayeemrmn could you handle this for upcoming v1.40 release?
