### ISSUE TITLE
Formatter doesn't work if `fmt.include` is not specified in `deno.json` file.

### ISSUE THREAD

**Issue by ink0rr** [denoland/vscode_deno#1029]
**Describe the bug**

Formatter doesn't work if `fmt.include` is not specified in `deno.json` file.

**To Reproduce**

1. Run `deno init`
2. Set vscode default formatter to `denoland.vscode-deno`
3. Open the `main.ts` file
4. Open command palette and select "Format Document"
5. Nothing happens...

Adding this line in the `deno.json` file fixes the issue

```json
{
  "fmt": {
    "include": [
      "**/*"
    ]
  }
}
```

**Expected behavior**

The file should get formatted without having to include it in `deno.json`

**Versions**

vscode: 1.85.1
deno: 1.39.4 
extension: 3.31.0

**Comment by dsherret** [comment]
Are you on Windows?

**Comment by ink0rr** [comment]
yes, i'm on windows

**Comment by ink0rr** [comment]
Seems like this also affects the linter as well, it won't check your files if you don't add them to `lint.include` in `deno.json` file

**Comment by dsherret** [comment]
This should be fixed in canary now (`deno upgrade --canary`). Please let me know if not.
