### ISSUE TITLE
Hide A Specific Error Warning

### ISSUE THREAD

**Issue by Barzi-Ahmed** [denoland/vscode_deno#1030]
Hello, 

I use Bun for my project, but I also use Deno and its VS Code plugin for its linter and formatter, but doing this, I get this error message (see screenshot) which is not really an error in a Bun project.  

How can someone hide this error message and/or any other error warnings specific to Deno project? 
I just want to use Deno and its VScode plugin for making use of its linter and formatter. 

![Screenshot](https://github.com/denoland/vscode_deno/assets/135956133/fcbe9f4c-ae6e-42f9-bfbe-9d93162066b0)

**Comment by nayeemrmn** [comment]
Closing in favour of #1061
