### ISSUE TITLE
When `typescript.suggest.completeFunctionCalls` is `true`, the string is inserted as is instead of a snippet

### ISSUE THREAD

**Issue by yaegassy** [denoland/vscode_deno#1036]
**Describe the bug**

The deno language server respects typescript/javascript settings, but we found a bug when `typescript.suggest.completeFunctionCalls` is set to `true`.

**DEMO (mp4)**

https://github.com/denoland/vscode_deno/assets/188642/54c0970e-14bb-420c-a19c-035fa8785d43

**To Reproduce**

...

**Expected behavior**

...

**Screenshots**

...

**Versions**

vscode: 1.85.2  deno: 1.39.4 extension: 3.32.0

**Comment by nayeemrmn** [comment]
This is the correct behaviour, the same happens on node TS server. Closing for now but feel free to elaborate on the expected snippet

**Comment by yaegassy** [comment]
Hi @nayeemrmn, thanks for checking the issue.

The `typescript-language-features` extension bundled with VSCode expands like a **placeholder**.

https://github.com/denoland/vscode_deno/assets/188642/ae2fa364-1d8e-4501-b8b5-44b731cdb149

I think this problem could be solved by changing the completion items provided by the language server itself from plain text format to snippet format.

**Comment by nayeemrmn** [comment]
@yaegassy Thanks for clearing it up. I'll investigate what the response format for that is

**Comment by yaegassy** [comment]
@nayeemrmn Before the deno language server respected typescript/javascript settings, there was a setting called `deno.suggest.completeFunctionCalls`.

- <https://github.com/denoland/deno/pull/20214>

I checked this by downgrading to the version of deno (v1.36.4?) itself at the time this feature was added, and it appears that this problem was already present from the beginning.

**Comment by yaegassy** [comment]
I think the problem can be solved by setting insertTextFormat to 2 (Snippet) instead of 1 (PlainText) in this test in deno itself and adjusting the implementation so that the test succeeds.

- <https://github.com/denoland/deno/blob/9951506506ded805ff5eb09b52fb0235c0c3df79/cli/tests/integration/lsp_tests.rs#L9041>

I don't use Rust regularly, so it's hard for me to create Pull Requests...

**Comment by nayeemrmn** [comment]
This will be fixed once https://github.com/denoland/deno/pull/22126 lands and is released in the following CLI patch. Thanks for the pointer @yaegassy!

**Comment by yaegassy** [comment]
Thanks @nayeemrmn. I built and tested the target pull request. It is now very comfortable. 🙇

**DEMO**:

https://github.com/denoland/vscode_deno/assets/188642/0a8f77b1-8fac-4973-83ac-3cca47ae13d1
