### ISSUE TITLE
Missing command "Deno: Initialize workspace configuration" starting with version 3.32.0.

### ISSUE THREAD

**Issue by cpunktbueno1** [denoland/vscode_deno#1058]
Hi,

The command "Deno: Initialize workspace configuration" is missing starting with version 3.32.0. (Version 3.31.0 doesnt have this issue). 

**To Reproduce**

1. Install version 3.32.0 or greater of the extension
2. Restart VSCode
3. Ctrl-Shift-P to bring up Command Palette
4. Type "Deno: Ini" to filter. 

**Expected behavior**

The command "Deno: Initialize Workspace Configuration" should be in the dropdown.

**Screenshots**

<img width="449" alt="image" src="https://github.com/denoland/vscode_deno/assets/86080360/7845236d-7c54-4689-8150-9b162977a469">

**Versions**

vscode: 1.85.2 (Windows User Setup) 
deno: 1.40.2 (release, x86_64-pc-windows-msvc)
extension: v3.33.3

Thank you!
Christian

**Comment by bartlomieju** [comment]
@dsherret and I also just hit it. We should revert this change and still have this command, but remove prompts for lint/unstable. 

CC @nayeemrmn

**Comment by irbull** [comment]
> @dsherret and I also just hit it. We should revert this change and still have this command, but remove prompts for lint/unstable.
> 
> CC @nayeemrmn

Could probably just alias `Initialize Workspace Configuration` to `Enable`. It's a bit jarring that there are no prompts anymore, but that's actually the point.

**Comment by irbull** [comment]
I was just going to push a PR, but I see you did this. I was wondering if we should add a "deprecation warning" Something like "Initialize Workspace Configuration (Deprecated)". You added that to the description, but I'm not sure where those are shown in the UI . Also, while testing this, I found it a bit jarring not to see a pop-up. I understand what is happening, but I wonder if others will be confused and wonder if the initialize actually did anything?.

**Comment by bartlomieju** [comment]
I think we're gonna have to leave it as is - there's a ton of references to "Initialize Workspace Configuration" in the wild.

That said, I agree about a popup - probably good to show a notification that the operation succeeded. 

@nayeemrmn could you do that?

**Comment by irbull** [comment]
Here is a PR that adds a modal info dialog. It might be a good stopgap measure as users were expecting an input dialog, and now we show them nothing. In a few releases (or maybe Deno 2.0) we can replace this with a message on the status bar.

https://github.com/denoland/vscode_deno/pull/1060
