### ISSUE TITLE
Extension fails on startup

### ISSUE THREAD

**Issue by winstonDeGreef** [denoland/vscode_deno#1063]
**Describe the bug**
Extension doesn't start, and logs:
```
Starting Deno language server...
  version: 1.36.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/winston/.deno/bin/deno
Connected to "Visual Studio Code" 1.85.2
Cannot set workspace settings: invalid type: null, expected a sequence
[Error - 11:20:23 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 11:20:23 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
```

**To Reproduce**
For me I just need to load vscode with the extension. I have no idea what is causing this, as I tried using the extension with a blank vscode profile and it still happens.

**Screenshots**
[Screencast from 11-02-24 11:24:24.webm](https://github.com/denoland/vscode_deno/assets/71840364/8b177c64-349d-4228-81e7-c9a7bad2049f)
![image](https://github.com/denoland/vscode_deno/assets/71840364/17d89ea8-4647-49ab-ab20-4ba9e9740909)
![image](https://github.com/denoland/vscode_deno/assets/71840364/851270af-4ad3-4d4d-ac1d-ac51cf78e820)

**Versions**

vscode: 1.85.2, deno: 1.36.1, extension: 3.33.3

**Comment by Nezteb** [comment]
I have this same problem. This looks similar to https://github.com/denoland/vscode_deno/issues/994.

My details:

- `vscode_deno` version 3.33.3
- VS Code Insiders:
```
Version: 1.87.0-insider
Commit: b2598b92d18ea1132e9cd35df776c8c22a7f9730
Date: 2024-02-13T05:48:27.895Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```
- Deno:
```
❯ deno --version
deno 1.35.0 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```
- [Mise 2024.2.4 macos-arm64 (2024-02-03)](https://mise.jdx.dev/) (compatible alternative to `asdf`)

I've verified that `deno` is in my path, and I've never had issues with VS Code and any other CLI tools.

```
> which deno
/Users/noah/.local/share/mise/installs/deno/1.35.0/bin/deno
```

**Comment by shaheermir** [comment]
Had the same issue on `1.31.x`. Bumping up to `1.41.0` fixed it for me.

**Comment by nayeemrmn** [comment]
Run `deno upgrade`, or downgrade the extension according to https://github.com/denoland/vscode_deno?tab=readme-ov-file#compatibility.
