### ISSUE TITLE
deno(import-prefix-missing), deno-ts(7026) and deno-ts(2304), 

### ISSUE THREAD

**Issue by LEVOGNE** [denoland/vscode_deno#1065]
**Bug Description**
I've installed Deno directly from the official website using the command **curl -fsSL https://deno.land/install.sh | sh**, which installed Deno version 1.40.4 (release, aarch64-apple-darwin) with V8 12.1.285.6 and TypeScript 5.3.3 on my Mac. Subsequently, I downloaded Fresh with **deno run -A -r https://fresh.deno.dev** (version 1.6) and started the application using **deno task start**. The application runs flawlessly; however, I am encountering issues with formatting in VSCode, suggesting a potential issue with the Deno plugin.

**Steps to Reproduce**
1.) Install Deno using the provided curl command.
2.) Install Fresh using **deno run -A -r https://fresh.deno.dev**.
3.) Start the Fresh application with **deno task start**.

**Expected Behavior**
I expected VSCode to correctly format and handle the Deno/Fresh project without any issues.

**Actual Behavior**
The application runs as expected, but VSCode does not format the code correctly, and there seem to be issues with the editor integration, potentially indicating a problem with the Deno plugin.

<img width="806" alt="Bildschirmfoto 2024-02-13 um 16 00 51" src="https://github.com/denoland/vscode_deno/assets/104150245/7cfef4e9-4476-46e8-a198-f495a62daa80">
<img width="853" alt="Bildschirmfoto 2024-02-13 um 16 00 12" src="https://github.com/denoland/vscode_deno/assets/104150245/53fc7845-abed-4e27-b241-1fc1d5f65776">

**Environment**
**Deno Version:** 1.40.4 (release, aarch64-apple-darwin)
**Fresh Version:** 1.6
**VSCode Version:** 1.86.1 (Universal)
**Deno VSCode Extension Version:** 3.33.3
**Operating System:** Darwin arm64 23.3.0

**Additional Context**
Everything works fine from a functionality standpoint, but the editor-related features (e.g., formatting) in VSCode seem to be malfunctioning. I suspect there might be an issue with the Deno plugin for VSCode.

_Please adjust any details according to your specific situation before submitting it on GitHub._

**Comment by nayeemrmn** [comment]
This is caused by #938. You have to make sure `fresh` is your workspace root.

**Comment by LEVOGNE** [comment]
Tried so many things and ended up with something so simple! Thank you :)
