### ISSUE TITLE
Ability to highlight the mod.ts or index.ts files in a folder

### ISSUE THREAD

**Issue by Mqxx** [denoland/vscode_deno#1067]
**Is your feature request related to a problem? Please describe.**
Currently I build my projects very modular, which means that I create individual modules (folders with a mod.ts file inside). Sometimes I can't find the mod.ts or index.ts files in the folder so quickly.

**Describe the solution you'd like**
It would be nice to have a way to mark files with a specific name (e.g. mod.ts, index.ts or others). For example by marking the files in bold or with an underline. This option should be adjustable, i.e. you should be able to specify the pattern for which names should be searched and that you can switch it on/off at any time.
For example like this:

![image](https://github.com/denoland/vscode_deno/assets/62719703/5add1e12-6099-4946-8dad-71ea112d47b4)

or this:

![image](https://github.com/denoland/vscode_deno/assets/62719703/e32f5a0e-386e-48bd-a093-1c9bab5354ac)

This would allow much better project management. Like this:

![image](https://github.com/denoland/vscode_deno/assets/62719703/1c11473b-6d2c-4ddc-b359-b87cbf426203)

**Comment by nayeemrmn** [comment]
I think this is out of scope for this extension. It could be a separate extension or vscode feature.
