### ISSUE TITLE
Renaming named imports mutates remote modules

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1068]
**Describe the bug**

renaming named imports for remote modules modifies remote modules when it musn't.

**To Reproduce**

```ts
import { SEPARATOR } from "https://deno.land/std@0.216.0/path/constants.ts"
```

1. use deno's stdlib
2. rename named imports (e.g `sep`)

```ts
import { SEPARATOR as sep } from "https://deno.land/std@0.216.0/path/constants.ts"
```
expected: imports are renamed correctly with `as`

```ts
import { sep } from "https://deno.land/std@0.216.0/path/constants.ts"
```
actual: the remote file itself is modified

**Expected behavior**

renames must not mutate remote Remote modules cache (`$DENO_DIR/deps`).

**Screenshots**

https://github.com/denoland/vscode_deno/assets/54838975/fb1c6b01-d64f-47fe-b213-e96481f23a00

**Versions**

vscode: 1.86.2 deno: 1.40.5 extension: v3.33.3

**Comment by nayeemrmn** [comment]
The 'Rename Symbol' functionality can't be used to create aliases, this is implemented in typescript. We should however fail to rename when a reference is found in a remote file.
