### ISSUE TITLE
auto-import for remote modules

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1069]
**Is your feature request related to a problem? Please describe.**

<img width="821" alt="image" src="https://github.com/denoland/vscode_deno/assets/54838975/fb2a21a8-1eda-45c9-a2e4-66143b798887">

(before pasting `import { slidingWindows } from "https://deno.land/std@0.216.0/collections/mod.ts"`)

<img width="821" alt="image" src="https://github.com/denoland/vscode_deno/assets/54838975/7fb9cc8c-1ba3-432b-8d32-d9565bc97c5e">

(after pasting `import { slidingWindows } from "https://deno.land/std@0.216.0/collections/mod.ts"` and saving)

to use deno stdlib it's mandatory to visit https://deno.land/std because unless manually caching the URL it will not provide auto-import.

**Describe the solution you'd like**

provide configuration to suggest auto-import for remote modules, esp. stdlib.

**Comment by nayeemrmn** [comment]
This is not feasible, every module from the configured host will have to be downloaded and loaded into the ts server runtime. Plus there's no way of probing for them.

**Comment by scarf005** [comment]
wouldn't it be possible for at least `std`? according to https://docs.deno.com/runtime/manual/advanced/language_server/imports, following endpoints seem to provide module entries:

<https://apiland.deno.dev/completions/items/std/0.218.2/>
![image](https://github.com/denoland/vscode_deno/assets/54838975/dc87ffe1-ca22-4914-96a8-91cfb8e7f52e)

<https://apiland.deno.dev/completions/items/std/0.218.2/collections>
![image](https://github.com/denoland/vscode_deno/assets/54838975/7162da44-c3ca-4f30-8b04-0ee6dbfdeed5)
