### ISSUE TITLE
VSCode Cannot find name 'Deno'  ts(2304)

### ISSUE THREAD

**Issue by nah-sonrisa** [denoland/vscode_deno#1072]
**Describe the bug**

![image](https://github.com/denoland/vscode_deno/assets/155512350/c692b717-e5dd-4a78-a21d-98d4cdb7e59c)

settings.json:
```
{
  "deno.enablePaths": [
    "supabase/"
  ],
  "deno.lint": true,
  "deno.unstable": true,
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "deno.enable": true,
  "typescript.validate.enable": true,
  "javascript.validate.enable": true,
  "deno.path": "/opt/homebrew/bin/deno",
  "typescript.tsserver.experimental.enableProjectDiagnostics": true
}
```

Output
```
Starting Deno language server...
  version: 1.40.5 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno
Connected to "Visual Studio Code" 1.86.2
Enabling import suggestions for: https://deno.land
Server ready.
Starting Deno language server...
  version: 1.40.5 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno
Connected to "Visual Studio Code" 1.86.2
Enabling import suggestions for: https://deno.land
Server ready.
Enabling import suggestions for: https://deno.land
```

I have tried to set "typescript.tsserver.experimental.enableProjectDiagnostics": true and restart, the error still exists. 

Although when I run `deno check functions/index.ts` in terminal it doesn't error, so I think it's still an issue with vscode settings.

**Versions**

vscode: 1.86.2 deno: 1.40.5 extension: v3.33.3

**Comment by nayeemrmn** [comment]
For me this only happens with `"typescript.tsserver.experimental.enableProjectDiagnostics": true`, which is an issue we haven't been able to work around. Report back here if it still happens with that setting off.
