### ISSUE TITLE
More descriptive error messages when using mis-matched Deno versions?

### ISSUE THREAD

**Issue by Nezteb** [denoland/vscode_deno#1074]
**Is your feature request related to a problem? Please describe.**

Long story short, I couldn't get `1.35.x` to work with this extension at all, despite the docs specifying "v1.13.0 or later". Bumping up to `1.40.x` resolved the issue, but the original `1.35.x` error message was quite vague:

```
Starting Deno language server...
  version: 1.35.0 (release, aarch64-apple-darwin)
  executable: /Users/noah/.local/share/mise/installs/deno/1.35.0/bin/deno
Connected to "Visual Studio Code - Insiders" 1.87.0-insider
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 12:59:53 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 12:59:53 PM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
```

See https://github.com/denoland/vscode_deno/issues/1063#issuecomment-1942934923 for more backstory.

**Describe the solution you'd like**

I am not sure because I never did figure out why `1.35.x` wasn't working, so I don't know if this is even feasible. Regarding an error message, maybe something like below?

```
[Warning - 12:59:53 PM] Current Deno version 1.35.0 does not support feature XYZ, please use 1.40.x instead
```

**Comment by nayeemrmn** [comment]
This isn't feasible because we don't track the minimum CLI version for the current extension version, we track the range of valid extension versions for each CLI version. It's not invertible and it's very hard to keep track of separately. You can use the table at https://github.com/denoland/vscode_deno?tab=readme-ov-file#compatibility.
