### ISSUE TITLE
Discoverability of the property of a destructured object lacks its usage among the references

### ISSUE THREAD

**Issue by king8fisher** [denoland/vscode_deno#1075]
File name: `*.tsx`
Using Fresh as an example.

* Shift-F12 on `prefix` on the object destructuring `{prefix, value, postfix, title}` provides a `{prefix}` among the results of references.
    ![image](https://github.com/denoland/vscode_deno/assets/140904760/70cd560a-c9c5-4d4a-ba02-fd5c12d01549)
* Shift-F12 on `prefix` on the object being destructured `prefix: string;` provides **NO** `{prefix}` usage among the results of references.
    ![image](https://github.com/denoland/vscode_deno/assets/140904760/c20c51a2-a1d5-40cd-9b02-7a81c685fe0c)

My guts tell me that the usage should be shown in both of the cases, otherwise it takes additional steps to achieve the desired list of references.

```tsx
export const GroupItems = (
  { prefix, value, postfix, title }: {
    prefix: string; // <- From here Shift-F12 won't discover the usage
    value: number;
    postfix: string;
    title: string;
  },
) => {
  return (
    <>
      <span title={title}>
        {prefix}
        <span>
          {value}
          {postfix}
        </span>
      </span>
    </>
  );
};
```

**Comment by king8fisher** [comment]
For full example: https://github.com/king8fisher/deno-bug-reports/tree/main/1075-vscode-discovery-of-properties

**Comment by nayeemrmn** [comment]
Does this happen with the Node ts server? We don't handle getting these references since we shell it out to typescript, so may be an upstream issue.

**Comment by nayeemrmn** [comment]
This is an upstream issue with typescript, there's no integration here to track.
