### ISSUE TITLE
Unable to retrieve source content

### ISSUE THREAD

**Issue by brunofrance** [denoland/vscode_deno#1077]
It seems to be a new "old" bug
(https://github.com/dotnet/aspnetcore/issues/22036)

If the directory name contains special characters, we have this bug with blazor and when we set breakpoints
In my case, it's due to recaptcha path, and I can't choose it

Thanks for your help
![image](https://github.com/denoland/vscode_deno/assets/63451637/374f6596-cea8-4005-892c-2606a21d6710)

**Comment by nayeemrmn** [comment]
Not sure this is related to this repo
