### ISSUE TITLE
Not possible to navigate to the source of a package via jsr:@.

### ISSUE THREAD

**Issue by thomas3577** [denoland/vscode_deno#1081]
This is perhaps more of a feature. When using jsr.io in deno.json, you no longer have hyperlinks. So I can no longer navigate to the source with [Ctrl+click].

**To Reproduce**

based on example deno.json:

```json
{
  "imports": {
    "@std/path": "jsr:@std/path@0.217.0"
  },
}
```

1. open deno.json in VS Code
2. press [Ctrl+Click] above "jsr:@std/path@0.217.0"
3. Nothing happens

**Expected behavior**

Press [Ctrl+Click] above "jsr:@std/path@0.217.0" should navigate to "https://jsr.io/@std/path@0.216.0". 

The same applies to a direct import in a TS file:

```ts
import * as mod from "jsr:@std/path@0.216";
```

**Versions**

vscode: v1.86.2 deno: v1.41.0 extension: v3.33.3

**Comment by nayeemrmn** [comment]
The source should open in a vscode tab, is that not working? Is the file cached?

**Comment by thomas3577** [comment]
Sorry, my description was a little imprecise.
VS Code recognizes hyperlinks and offers to open them in a browser when they are clicked (usually with [Ctrl+Click]). This works for any valid hyperlink.

"jsr:@std/path@0.216" is not a valid hyperlink. VS Code cannot do anything with it.

**This works. The tooltip says "Folow link (ctrl + click)":**
![image](https://github.com/denoland/vscode_deno/assets/8270855/3a7db2e0-05c9-4f2b-9871-bf04e32db026)

**But it doesn't work here:**
![image](https://github.com/denoland/vscode_deno/assets/8270855/24caef7e-770d-4926-8d3f-1397255f5375)

**Comment by nayeemrmn** [comment]
Okay I understand. Unfortunately ctrl+click triggers the go-to-definition which we want to open the file in vscode, it would be worse DX for the vast majority of users if it also opened a browser tab.

The best we can do is add the jsr.io link in the hover text.

**Comment by jsejcksn** [comment]
@thomas3577 Idea: you could use a URL pointing to the actual module path as the specifier in your import statement/map in order to get the built-in behavior. Example:

`example.ts`
```ts
import * as path from "https://jsr.io/@std/path/0.217.0/mod.ts";

console.log({ path });
```

Currently, it doesn't seem to be a supported pattern…

```txt
% deno --version
deno 1.41.2 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3

% deno run example.ts
error: Importing a JSR package via an HTTPS URL is not implemented. Use a jsr: specifier instead for the time being.
    at file:///Users/deno/example.ts:1:23
```

…but presumably it eventually be implemented according to this comment:

> **[dsherret](https://github.com/dsherret) commented at [2024-03-04T17:49:23Z](https://github.com/jsr-io/jsr/issues/175#issuecomment-1977142043)**
>
> > Will this ever become possible?
>
> Yes. It's just not implemented at the moment because there's some complications around it.
