### ISSUE TITLE
"unstable" flag doesn't turn recognition of unstable API's on and off

### ISSUE THREAD

**Issue by skybrian** [denoland/vscode_deno#1082]
I have one Deno project where editor recognition of unstable API's is stuck on and another where it is stuck off, and I don't know how to change them.

Changing .vscode/settings.json or deno.json can reliably be used to turn Deno support on and off, but turning unstable API recognition on and off (either in settings.json or deno.json) usually has no effect, even after closing and opening the editor.

**To Reproduce**

1. Create a new project directory
2. Add a hello.ts file:

```
const kv = await Deno.openKv();
console.log(kv);
```

At this point, VS Code doesn't recognize it as a Deno file, but it runs okay:

```
% deno run --unstable-kv hello.ts
Kv {}
```

3. Add a deno.json file containing just '{}'

At this point, Deno is turned on and it recognizes both 'Deno' and the 'openKv' call as valid, displaying the docs. (This is odd, because I haven't enabled unstable API's yet?)

4. Change deno.json to this:

```
{
    "unstable": []
}
```

No effect, even after closing and reopening the editor window.

5. Create a settings file in .vscode/settings.json that looks like this:

```
{
    "deno.unstable": false
}
```

Still no effect. openKV is recognized even after restarting the editor. So, it seems that in this case, unstable API's are stuck on and I don't know how to turn it off.

**Expected behavior**

I don't know if settings.json or deno.json should take priority, but one or the other should be able to turn unstable API recognition on and off.

**Versions**

vscode: 1.86.2 (Universal) deno: 1.41.0 extension: 3.33.3

**Comment by skybrian** [comment]
Running `deno lsp --help` lists some flags for turning unstable features on and off. However, from reading the source for the VS Code plugin, it looks like it never passes any "unstable" flags when running "deno lsp". (See [startLanguageServer](https://github.com/denoland/vscode_deno/blob/c7fefcb7fc3ebfc0405951dc30b175a0ba231d35/client/src/commands.ts#L77).)

Maybe the deno lsp process figures it out in some other way?

**Comment by skybrian** [comment]
For my project where unstable Deno API's aren't recognized, running `deno check hello.ts` from the command line doesn't report any errors on the file, even though the language server does.

I also tried deleting ~/Library/Caches/deno, but it didn't help to unstick the language server.

It seems like 'deno check' doesn't care whether unstable API's are turned on or not in deno.json. It also takes flags to turn on unstable API's, but I didn't need to pass them in?

**Comment by skybrian** [comment]
There seems to be some difference between simple Deno projects and Deno Fresh projects that causes unstable API's to not be recognized in Deno Fresh projects.

If I create a new project using `deno init` then `Deno.openKV` is recognized in VS Code. If I create one using `deno run -A -r https://fresh.deno.dev`, then it isn't.

In neither case does `deno check` report any errors.

**Comment by skybrian** [comment]
Figured it out. In a Deno Fresh project, at the top of main.ts, there is this line:

```
/// <reference no-default-lib="true" />
```

For some reason it turns off recognition of unstable API's project-wide.

In my old Deno Fresh project, I had added this line to a different file:

```
/// <reference lib="deno.unstable"/>
```

This turns unstable API's back on again, project-wide. (I had forgotten that I did this.)

**Comment by skybrian** [comment]
See: https://github.com/denoland/deno/issues/21159

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/deno/pull/21825
