### ISSUE TITLE
tRPC or Hono RPC - Can't import types from Deno folder (server) to Node folder (client)

### ISSUE THREAD

**Issue by ds315** [denoland/vscode_deno#1084]
**Describe the bug**

Can't import types from Deno folder (server) to Node folder (client).

**To Reproduce**

1. I made Deno + Hono server, export type of router from server and enable Deno Language Server for whole project (client and server). Types successfully import's in client, but alot of errors appears.
![server](https://github.com/denoland/vscode_deno/assets/118160834/e95590ff-2ba4-4145-b2cb-938c487ea8f7)
![settings](https://github.com/denoland/vscode_deno/assets/118160834/89769c21-3403-4aa5-9463-179bc00cfc7f)
![client](https://github.com/denoland/vscode_deno/assets/118160834/ad7fc2e2-c7e0-48e5-b05e-c459c23a8459)
![errors](https://github.com/denoland/vscode_deno/assets/118160834/fe79f230-3ae0-432f-b9f9-e3c34ab13940)

2. I enable Deno Language Server only for server folder. Types to router disappear's in client folder.
![settings1](https://github.com/denoland/vscode_deno/assets/118160834/994a9c8c-ae1b-4e6b-b56b-88f9a362409e)
![client1](https://github.com/denoland/vscode_deno/assets/118160834/ba5481c0-52b0-4e76-bf31-810669f79284)

3. I tried to put import to separate file and enable Deno Language Server to it. It doesn't helps.
![router](https://github.com/denoland/vscode_deno/assets/118160834/0cb6bcc1-d13d-4ef7-8bd5-3421711a7d1a)
![settings2](https://github.com/denoland/vscode_deno/assets/118160834/a592fed7-91ac-45fb-a8d3-4994e19752d3)
![client2](https://github.com/denoland/vscode_deno/assets/118160834/6eb118e3-a078-4e49-94bf-6de220b70034)

**Expected behavior**

Is that possible to Deno Language Server can work with Node projects ?

When enable Deno Language Server, it disables VS Codes Language Server. (it's clear)

As I understand, it's like - [Feature Request] Support multiple types of projects in the same repository #488 in [Q4 roadmap](https://github.com/denoland/vscode_deno/issues/968) ?

**Versions**

vscode: 1.87.0, deno: 1.40.5, extension: 3.33.3

**Comment by nayeemrmn** [comment]
Try removing `deno.enablePaths` and having a top-level `deno.json` with the following:
```js
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  }
}
```

**Comment by ds315** [comment]
Thank's much ! But now i have a problem:

![error](https://github.com/denoland/vscode_deno/assets/118160834/74b197f5-aa03-45c7-8577-6466684497d6)

How to solve it ?

**Comment by nayeemrmn** [comment]
Try adding the following to your `deno.json` and then restarting the language server:
```js
"unstable": ["byonm"]
```

**Comment by ds315** [comment]
Doesn't helps

Situation same as before, - some types are 'any' - Hono<any, any, any> and deno-ts(2344)

I can publish test projects (Hono RPC and tRPC), if it helps

**Comment by nayeemrmn** [comment]
@ds315 You'll have to push to a repo or create a smaller reproduction that I can pull so I can figure out what's wrong.

**Comment by ds315** [comment]
I'd published both Hono RPC and tRPC - https://github.com/ds315/trpc and https://github.com/ds315/hono

Both works good, only problem with types in Client in VS Code

**Comment by nayeemrmn** [comment]
I believe this was the same issue as https://github.com/denoland/deno/issues/24293. Ensure the part of your program using hono doesn't include or import any code importing react, and have them in different `deno.json` scopes. You can now move your `deno.json` into `server/deno.json` to achieve this. Closing for now, please update here if this works.
