### ISSUE TITLE
Settings.json (typescript service not disabled) and Deno.json (excluded lint rules messages persist)

### ISSUE THREAD

**Issue by pierreglibert** [denoland/vscode_deno#1085]
Hi :)

I tried Deno today and encountered 2 problems (or not ^^). It's possible that I made a mistake. You will tell me.
I used the command 'deno init' to start a project and then installed the deno extension on VSCode.

### a. settings.json :
When only "deno.enable" was true, I received 2 messages. Deno recognized itself and typescript displayed this : "Name could not be found". It seems that the typescript service was not disabled.

![Capture d’écran 2024-03-06 à 14 36 48](https://github.com/denoland/vscode_deno/assets/21291915/c51c3327-70fa-47a0-9f30-8b8d88db3cf9)
![Capture d’écran 2024-03-06 à 14 37 08](https://github.com/denoland/vscode_deno/assets/21291915/9777b0f5-0296-478b-8369-caeb3066947b)

I added "deno.enablePaths" to resolve it

![Capture d’écran 2024-03-06 à 14 40 13](https://github.com/denoland/vscode_deno/assets/21291915/b93e4f4c-8a4d-40d9-acd2-d167088294de)
![Capture d’écran 2024-03-06 à 14 40 23](https://github.com/denoland/vscode_deno/assets/21291915/90c1495b-d7a1-4a77-9d81-cda3c088d5ef)

Normally, I think it works without this parameter as in documentation.

### b. deno.json : 
I added two lint exclude rules ("no-unused-vars", "no-var") but the message persists. (The file is at the root.)

![Capture d’écran 2024-03-06 à 14 46 51](https://github.com/denoland/vscode_deno/assets/21291915/7a998fef-f3c6-4427-9ae8-65786fcead39)
![Capture d’écran 2024-03-06 à 14 47 08](https://github.com/denoland/vscode_deno/assets/21291915/3a7da12d-dabd-4e75-993e-d992815b259a)

I expected to continue without this kind of message.

As previously mentioned, it was the first time I installed deno. It's very possible that I forgot something ;)
Can you help me please ?
Thanks :)

vscode : 1.87.0
deno 1.41.1 (release, x86_64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3

**Comment by nayeemrmn** [comment]
Have you tried restarting vscode after installing the extension? Is you `deno.json` at the root of your workspace?

**Comment by pierreglibert** [comment]
Yes and yes. I just tested it with a basic directory project created with deno init command.
![Capture d’écran 2024-03-06 à 15 47 15](https://github.com/denoland/vscode_deno/assets/21291915/72138d56-c127-4154-8c8b-2fac21769486)

![Capture d’écran 2024-03-06 à 15 46 51](https://github.com/denoland/vscode_deno/assets/21291915/05aaa3f1-0408-4d24-9438-8b318695c2f6)

**Comment by nayeemrmn** [comment]
Check that you don't have `{"typescript.tsserver.experimental.enableProjectDiagnostics": true}` in your workspace or user settings, this setting conflicts with Deno which unfortunately is not possible for us to workaround in our plugin.

**Comment by pierreglibert** [comment]
I have this : 
![Capture d’écran 2024-03-06 à 16 12 15](https://github.com/denoland/vscode_deno/assets/21291915/b4d6841d-8382-446a-839f-a75c1eda3faf)

**Comment by nayeemrmn** [comment]
Okay, so try removing `workbench.settings.appllyToAllProfiles`.

**Comment by pierreglibert** [comment]
nothing change :(

**Comment by nayeemrmn** [comment]
What's in your `.vscode/settings.json`

**Comment by pierreglibert** [comment]
`{
    "deno.enable": true,
    "deno.enablePaths": ["./"]
}`

**Comment by nayeemrmn** [comment]
Ah yes, that's the current expected behaviour for (b). For (a), this was an issue I wasn't aware of -- will look into it.

**Comment by pierreglibert** [comment]
I have nothing in it ^^

**Comment by pierreglibert** [comment]
> Ah yes, that's the current expected behaviour for (b). For (a), this was an issue I wasn't aware of -- will look into it.

So, for (b), I can't have several projects directories in my workspace. Will Deno extension server always auto resolve path to the first project directory ? did I understand correctly?

**Comment by pierreglibert** [comment]
@nayeemrmn Thank you for your help and the fix ;) Have a nice day.
