### ISSUE TITLE
When using custom deno.json in workspace settings, fmt settings don't work and imports cause errors

### ISSUE THREAD

**Issue by JouriR** [denoland/vscode_deno#1097]
**Describe the bug**
When defining my own `deno.json` file in my `.vscode/settings.json` file, my formatting settings in the `deno.json` file are not being used. When I use the `deno fmt` command it formats using the right settings, but when I format using VS Code it does not. Also my imports defined in the file cause the following error when trying to use them: `Relative import path "$std/assert/mod.ts" not prefixed with / or ./ or ../`. The code still runs fine without any errors. So the error only shows in VS Code.

**To Reproduce**
1. Install Deno extension
2. Run `deno init` to generate boilerplate code
3. Add fmt options & imports to `deno.json` file (my settings can be found in a screenshot below)
4. Set up VS Code workspace settings (my settings can be found in a screenshot below)
5. Format using `deno fmt` to see the expected result
6. Format using VS Code (Left CTRL + Left ALT + F) to see what really happens
7. Try using an import like `import { assertEquals } from '$std/assert/mod.ts';` to get the error

**Expected behavior**
1. I expect VS Code to format my code according to my settings
2. I expect imports to still work as described in the [Deno documentation](https://docs.deno.com/runtime/manual/getting_started/first_steps#configure-your-project-with-denojson)

**Screenshots**
`deno.json`:
![image](https://github.com/denoland/vscode_deno/assets/60195349/13794185-47e2-4274-97d1-4d165680372a)

`.vscode/settings.json`:
![image](https://github.com/denoland/vscode_deno/assets/60195349/2b50785a-a58a-4d21-a523-a0e9a4dd3447)

Import error:
![image](https://github.com/denoland/vscode_deno/assets/60195349/38ca115e-0f48-40ef-91d4-5ebcc5ee412f)

File structure:
![image](https://github.com/denoland/vscode_deno/assets/60195349/22e0dcf4-30eb-4cfa-b8ad-8aad269e5521)

**Versions**
Deno: v1.42.0
VS Code: v1.87.2
Deno extension: v3.36.0
OS: Windows 11 (Using WSL - Ubuntu 22.04)

**Comment by bartlomieju** [comment]
@nayeemrmn can this be related to https://github.com/denoland/deno/pull/23123?

**Comment by nayeemrmn** [comment]
Paths in `settings.json` are resolved relative to the project root, not `settings.json`. Just change `../deno.json` to `deno.json` and it should work
