### ISSUE TITLE
Nothing works :(

### ISSUE THREAD

**Issue by aspizu** [denoland/vscode_deno#1098]
Keep getting typescript errors, even tried "disabling" the builtin typescript extension which apparently doesn't actually disable the extension at all. Trying to contribute to a deno fresh project, the repo contains a `.vscode/settings.json` with `deno.enable: true`.

I get errors such as:
```json
[{
	"resource": "/home/aspizu/Documents/Projects/Contrib/jsr/frontend/routes/package/versions.tsx",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2318",
	"severity": 8,
	"message": "Cannot find global type 'Promise'.",
	"source": "typescript",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

```
Deno Version: 3.36.0
VSCode Version: 1.87.2 (AUR visual-studio-code-bin)
```

**Comment by nayeemrmn** [comment]
Check if you have `typescript.tsserver.experimental.enableProjectDiagnostics` enabled in your **user** settings. If so you'll have to turn that off.

**Comment by aspizu** [comment]
I don't have that setting in my user settings.

**Comment by codinronan** [comment]
@aspizu what was your resolution? I have this same issue now. When I use Command + Shift + P and do "Deno language server status" NONE of the settings match the ones in my `.vscode/settings.json` NOR `deno.jsonc` files. They're all apparently the defaults so it doesn't even see my deno configs at all. This has broken imports, type checking, formatting, the lot.

What was your fix?

**Comment by nayeemrmn** [comment]
@codinronan Are those relative to your root directory? Please show a screenshot or paste of your explorer view

**Comment by codinronan** [comment]
@nayeemrmn I found the answer in another issue, https://github.com/denoland/vscode_deno/issues/1099 about deno.jsonc now needing to be specified. Once I did that it worked!

(Fwiw yes they're relative to the root directory).

**Comment by aspizu** [comment]
The extension for [Civet](https://civet.dev/) creates this issue, which needs to be disabled. Should this disable that extension, or should it be up to the user?
