### ISSUE TITLE
Inconsistent deno fmt result between 1.41.3 and 1.42.0

### ISSUE THREAD

**Issue by jeiea** [denoland/vscode_deno#1099]
### Steps to reproduce

1. Environment
   - deno: 1.42.0 (release, x86_64-pc-windows-msvc)
   - vscode_deno: v3.36.0
   - vscode: 1.87.2 (system setup)
2. Clone the repository and be careful with branch `fmt-ignored`.
   `git clone https://github.com/jeiea/deno_report.git -b fmt-ignored`
3. Open cloned directory with vscode and vscode_deno.
4. Press `Ctrl+s` on main.ts.

### Expected behavior

The file should remain unchanged compared to when it was run with Deno version 1.41.3 or when the command `deno fmt` was executed.

### Actual behavior

https://github.com/denoland/vscode_deno/assets/4188984/82f3f8a3-8363-46d5-a970-3d0cbb384e82

**Comment by nayeemrmn** [comment]
Do you have `deno.documentPreloadLimit: 0` set in your vscode user settings? If so this will be fixed by https://github.com/denoland/deno/pull/23123.

**Comment by nayeemrmn** [comment]
Ah, okay your `deno.enablePaths` must include `deno.json` now. This is an intentional change in behaviour from 1.41.3, it makes sense. Closing for now but comment here if it's not fixed.

**Comment by jeiea** [comment]
It's fixed, just I think this should be documented because it's hard to expect and silent breaking change.
