### ISSUE TITLE
Deno extension doesn't work in workspaces properly

### ISSUE THREAD

**Issue by nikitavoloboev** [denoland/vscode_deno#1104]
Opened issue about it in Deno GitHub too: https://github.com/denoland/deno/issues/23245

In short:

I want is not to have the `deno.enable: true` inside my `.code-workspace` I open.

But I want VSCode Deno extension to use this:

<img width="616" alt="image" src="https://github.com/denoland/deno/assets/6391776/083f60d5-e0c8-494b-b746-a6e880c72719">

This should be enough to not have Deno extension breaking down.

<img width="1116" alt="image" src="https://github.com/denoland/deno/assets/6391776/b5bc1588-c576-468f-9063-5b05e278a371">

Currently above workflow breaks down for me.

**Comment by nikitavoloboev** [comment]
VSCode extension actually ignores these comments too:

<img width="1220" alt="image" src="https://github.com/denoland/vscode_deno/assets/6391776/7e5e57f5-3a25-4e64-8689-15c23fc9c539">

Which seems like a big bug too.

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/deno/issues/23245#issuecomment-2197271295.
