### ISSUE TITLE
deno.importMap setting is ignored if deno.json includes an import map

### ISSUE THREAD

**Issue by jollytoad** [denoland/vscode_deno#1106]
**Describe the bug**

I sometimes like to change my import mappings when developing. I prefer to use a separate import map for this, to avoid accidentally committing changes to the regular import map.

With deno cli, I can just use `--import-map` to do this, but I also need vscode to use this alternative map too, so I tried to use the `deno.importMap` setting, but unfortunately it seems to get completely ignored if the `deno.json` contains `imports` or `importMap`.

**To Reproduce**

1. add `imports` into `deno.json`
2. add a separate `import_map.json` file with different mappings
3. set `deno.importMap` vscode setting to point to the `import_map.json` file
4. attempt to cross-reference imports within vscode (the ones that have been remapped)
5. you'll find the mapping from 'deno.json' is active rather than the `import_map.json`

I've created a minimal project to demonstrate: https://github.com/jollytoad/deno_import_map_override_bug

**Expected behavior**

I'd expect `deno.importMap` setting to override the `deno.json` config in the same way that the `--import-map` flag does.

**Versions**

vscode: 1.88.0 deno: 1.42.1 extension: 3.36.0

**Comment by nayeemrmn** [comment]
This is the intended behaviour going forward, it's easier to avoid obscure conflicts between CLI and editor behaviour if the workspace settings are given lowest priority. Really the `deno.importMap` setting is legacy from before `deno.json`, it shouldn't normally be used if there's a `deno.json`.
