### ISSUE TITLE
Package.json causes repeated prompt

### ISSUE THREAD

**Issue by newtack** [denoland/vscode_deno#111]
I need a package.json in the root directory because of VSCode issues with typing and each time I open the folder I get asked the question whether I want to disable the extension.

Can you add a workspace settings so that I can say "don't ask"?

**Comment by promethyttrium** [comment]
My solution to this is simply to uninstall this extension; it appears to be "not ready for prime time".

**Comment by brandonkal** [comment]
The prompt should simply not exist and is very annoying. We have to explicitly enable the deno extension with "deno.enable" setting. Why on earth would we then want a nagging prompt to disable it.

**Comment by lucacasonato** [comment]
It is disabled by default now and the prompt has been removed.
