### ISSUE TITLE
Global types (reference types) not being applied

### ISSUE THREAD

**Issue by thorwebdev** [denoland/vscode_deno#1115]
**Describe the bug**

Importing global types via `/// <reference types="https://esm.sh/v135/@supabase/functions-js@2.3.0/src/edge-runtime.d.ts" />` used to work. However I found that recently they aren't being applied anymore. 

Same issue when importing through JSR `/// <reference types="jsr:@supabase/functions-js/edge-runtime.d.ts" />` it correctly caches the dependency from the registry but doesn't apply the global types. 

getting "Cannot find name 'Supabase'." for `const model = new Supabase.ai.Session("gte-small");`

**To Reproduce**

1. import `/// <reference types="jsr:@supabase/functions-js/edge-runtime.d.ts" />`
2. Write code: `const model = new Supabase.ai.Session("gte-small");`
3. See vscode error unable to find type. 

**Expected behavior**

Correctly apply global types. 

**Screenshots**

<img width="747" alt="image" src="https://github.com/denoland/vscode_deno/assets/5748289/2ea9ec3f-1f76-4556-8fe8-f4ff311ae52e">

**Versions**

vscode: 1.89.1 (Universal) deno: 1.43.3 extension: 3.37.1

**Comment by nayeemrmn** [comment]
Thanks for bringing attention to this. The usage of `/// <reference types="..." />` is to replace the export types of that module so it's not the correct syntax here, you can just do `import "jsr:@supabase/functions-js/edge-runtime.d.ts"`. The other seemed to work unintentionally prior to https://github.com/denoland/deno/pull/23259, and also it still works in `deno check`. We'll need to reconcile that.

Does `import "jsr:@supabase/functions-js/edge-runtime.d.ts"` work for you?
