### ISSUE TITLE
URL.parse() not available in v3.37.1 using Deno v1.43.4

### ISSUE THREAD

**Issue by waptik** [denoland/vscode_deno#1116]
**Describe the bug**
I upgraded to v1.43.4 of deno whilst working on a project and saw the update about `URL.parse()` so i decided to give it a try but vscode is screaming that the `.parse` static method doesn't exit. The method does work perfectly if you run the code.

**To Reproduce**

1. Make sure you're on both versions of deno, vscode_deno as mine
2. create a new dummy file, eg. url_parse.ts, open it inside vscode and paste the following ` console.log(URL.parse("scooby doo")` and save the file
3. open your terminal if you haven't and run `deno run -A url_parse.ts`

**Expected behavior**

Vscode intellisense should popup and error saying the method doesn't exist.

**Screenshots**

<img width="784" alt="image" src="https://github.com/denoland/vscode_deno/assets/1687551/d452ad7e-a6c3-4c29-aa3e-68ff79ebb00c">

**Versions**

vscode: v1.89.1 deno: v1.43.4 extension: v3.37.1

**Comment by nayeemrmn** [comment]
Fixed by https://github.com/denoland/deno/pull/23893.
