### ISSUE TITLE
Import maps not recognized for nested deno projects

### ISSUE THREAD

**Issue by nandorojo** [denoland/vscode_deno#1117]
**Describe the bug**

If you have a Deno project in a sub-folder of your repository, then its `deno.json` won't get recognized. It looks like the VSCode Extension only checks the root of your project for a `deno.json` file. However, it should also be checking `deno.enablePaths` locations.

As a result, monorepos using deno cannot use `imports` properly.

<img width="553" alt="Screenshot 2024-05-17 at 11 41 36 AM" src="https://github.com/denoland/vscode_deno/assets/13172299/33f931ce-c896-4ef5-b878-83c39d424f00">

**To Reproduce**

1. Create a subfolder, like `./projects/deno`
2. In `.vscode/settings.json`, enable Deno and add `deno.enablePaths: './projects/deno'`
3. Add a `deno.json` file at `./projects/deno/deno.json`
4. In `deno.json`, add `imports` like so:

```json
{
  "imports": {
    "~public/": "./public/"
  }
}
```

5. Create a file at `./projects/deno/public/test.ts`: `export default 1`
6. Create a file at `./projects/deno/root.ts`: `import test from '~public/test.ts`
7. Watch as it errors.

Workaround: Open `./projects/deno` in VSCode directly (not desired).

**Expected behavior**

Import paths should work relative to the location of the `deno.json` file. And in fact, they do. However, the VSCode extension doesn't seem to pick them up.

The workaround is to open the nested folder in VSCode directly. However, this is a workaround at best.

**Screenshots**

See above.

**Versions**

vscode: 1.89.1 
deno: 1.43.3 
extension: v3.37.1

Thank you for your help.

**Comment by nayeemrmn** [comment]
Tracked in #787.
