### ISSUE TITLE
Deno cannot be selected as default formatter in Vscode after updating extension to 3.37.1

### ISSUE THREAD

**Issue by katohs** [denoland/vscode_deno#1119]
**Describe the bug**
deno extension v3.37.1 does not allow selection of deno as default formatter

**To Reproduce**

This issue occurs when you update the extension version to 3.37.1. Reverting to 3.37.0 resolves the issue

To Reproduce

Happens on literally any of my Deno projects.

**Screenshots**

v3.37.0
![image](https://github.com/denoland/vscode_deno/assets/52311439/6d5ec93d-b285-42e2-b129-5a44e3b37216)

v3.37.1
![image](https://github.com/denoland/vscode_deno/assets/52311439/afc9a759-f887-449d-86cc-e2a05de3f359)

**Versions** deno: v1.43.5 vscode: v1.89.1 extension: v3.37.1

**Comment by nayeemrmn** [comment]
@katohs This must be happening because you have `deno.enable: false`, you have to enable it now or the language server which does the formatting won't start.
