### ISSUE TITLE
Add deno fmt global settings

### ISSUE THREAD

**Issue by carafelix** [denoland/vscode_deno#1121]
**Is your feature request related to a problem? Please describe.**
Some project's forbidden the use of semicolons at the end of each line. It is possible to add:
```json
{
  "fmt": {
    "options": {
      "semiColons": false
    }
  }
}
```
In the deno.json of the working directory.

EDIT: I added the deno.json but on saving it is still adding the semicolons

**Describe the solution you'd like**

I would like to have a global setting for the vscode server.

**Comment by nayeemrmn** [comment]
> I added the deno.json but on saving it is still adding the semicolons

Ensure the deno lsp is configured as the formatter: https://github.com/denoland/vscode_deno?tab=readme-ov-file#formatting. We're trying to avoid editor specific configuration methods, things should be specified in the `deno.json` for alignment between CLI and LSP.
