### ISSUE TITLE
import autocompletion not working

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1125]
**Describe the bug**

import suggestions stopped working.

**To Reproduce**
<img width="664" alt="image" src="https://github.com/denoland/vscode_deno/assets/54838975/87644fc2-a8c2-40d2-b824-ff2247cbbcec">
<img width="782" alt="image" src="https://github.com/denoland/vscode_deno/assets/54838975/f5f28064-8dc6-411b-9595-e9f72f04cd72">

1. create a file with import
```ts
import {} from "https://esm.sh/@nrsk/sigma@3.8.0"
```
2. trigger import suggestion autocomplete

**Expected behavior**

it shows list of exported symbols.

EDIT: fixed by reloading caches then extension, but this feels very flaky. related: #875 

**Screenshots**

**Versions**

vscode: 1.90.0 deno: 1.44.4 extension: v3.37.1

**Comment by nayeemrmn** [comment]
@scarf005 Can you check if this is fixed in `deno upgrade --canary`?

**Comment by scarf005** [comment]
![image](https://github.com/denoland/vscode_deno/assets/54838975/787e2bf7-54fe-46ad-ade4-6c42f82808a6)

i think so. could you also point out which commit it got resolved?

**Comment by nayeemrmn** [comment]
Most likely https://github.com/denoland/deno/pull/24353, not certain.
