### ISSUE TITLE
Intellisense broken in 1.44.3 & 1.44.4

### ISSUE THREAD

**Issue by timothy-b** [denoland/vscode_deno#1126]
**Describe the bug**
Intellisense doesn't work for imported code with Deno 1.44.3 or 1.44.4, but does work with 1.44.2 and 1.44.1.

**To Reproduce**

1. Create a new directory + `main.ts`
2. Paste in:
	```ts
	// @deno-types="npm:@types/express@4.17.15"
	import express from "npm:express@4.18.2";

	const app = express();

	app.get("/", (req, res) => {
	  res.send("Welcome to the Dinosaur API!");
	});

	app.listen(8000);
	```
3. Run `Deno: Enable` in VS Code Command Palette, `deno upgrade --version 1.44.3` in terminal, and then `Developer: Reload Window` in Command Palette.
4. Put your cursor somewhere in the editor and try `app.`

**Expected behavior**
I expect Intellisense to suggest a list of members of the `Express` interface.

**Screenshots**
![untitled](https://github.com/denoland/vscode_deno/assets/17421603/9738b49c-0f59-45a8-b9e3-952e30a2bedd)

**Versions**

vscode: 1.90.2 deno: 1.44.3 - 1.44.4 extension: v3.37.1

**Comment by nayeemrmn** [comment]
This was fixed by https://github.com/denoland/deno/pull/24353, please try out `deno upgrade --canary` to check.

**Comment by timothy-b** [comment]
That works, thank you!
