### ISSUE TITLE
mismatch between vscode and deno test error reporting

### ISSUE THREAD

**Issue by uriva** [denoland/vscode_deno#1127]
deno 1.44.4 (release, x86_64-unknown-linux-gnu)
v8 12.6.228.9
typescript 5.4.5

extension version v3.37.1

## description

vscode shows a typing error

running `deno run` on that file works

I've added `// @ts-expect-error`

now `deno test` yields

`error: TS2578 [ERROR]: Unused '@ts-expect-error' directive.`

## reproduction

```ts
import { Filter } from "npm:mongodb";

const x: Filter<{ outer: boolean; inner: { field: boolean } }> = {
    outer: false,
    // @ts-expect-error
    "inner.field": true,
};
```

**Comment by nayeemrmn** [comment]
Can you try with `deno upgrade --canary`? This may be a fixed bug. Also remove the `// @ts-expect-error`.

**Comment by uriva** [comment]
ok seems to work - doesn't report error

fyi it doesn't alert on errors it used to with this typing (it used to report on fields which are not nested)
