### ISSUE TITLE
importmap support is broken in folders

### ISSUE THREAD

**Issue by brandonkal** [denoland/vscode_deno#113]
An example reproduction:
```
$ cat subproject/import_map.json
{
	"imports": {
		"mod": "./my-mod.ts"
	}
}
$ cat .vscode/settings.json
{
	"deno.enable": true,
	"deno.importmap": "./subproject/import_map.json"
}

$ cat subproject/example.ts
import * as mod from 'mod' // TS error
export const x = mod.action() // TS error
```

Using an absolute path in subproject/import_map.json fixes the VSCode errors. But I can't use absolute paths for obvious reasons. So it is clear the extension is acting as if the import_map.json file was in the workspace root where relative imports would not work.

So this needs to be fixed.

**Comment by brandonkal** [comment]
And now I open my project back up and it doesn't even work with absolute paths...
This is just a mess.

**Comment by dicarne** [comment]
This work now:
`.vscode/settings.json`
```json
{
    "deno.enable": true,
    "deno.import_map": "./import_map.json"
}
```

**Comment by lucacasonato** [comment]
@brandonkal is this still the case?

**Comment by brandonkal** [comment]
Yes.

**Comment by lucacasonato** [comment]
This has been resolved in version 3.x of the extension.
