### ISSUE TITLE
Failed to import package that contained deno workspace

### ISSUE THREAD

**Issue by Kesin11** [denoland/vscode_deno#1131]
**Describe the bug**
Deno workspace feature (not VSCode workspaces) supported from [v1.45](https://deno.com/blog/v1.45).
I tried minimal sample code that written in [Deno document](https://docs.deno.com/runtime/manual/basics/workspaces/), however importing package that contained workspace rise these error in VSCode editor window.

```
Relative import path "@scope/add" not prefixed with / or ./ or ../ and not in import map from "file:///home/kesin/github/kesin11/deno_workspace_vscode/main.ts"deno(resolver-error)

Relative import path "@scope/add" not prefixed with / or ./ or ../ and not in import map from "file:///home/kesin/github/kesin11/deno_workspace_vscode/main.ts"deno(resolver-error)
```

It works with `deno run` and `deno check`. Does this extension not support Deno workspace yet?

**To Reproduce**
Follow the [Monorepo example document](https://docs.deno.com/runtime/manual/basics/workspaces/#monorepo-example).

1. Create `@scope/add` and `@scope/subtract` packages.
2. Set `workspace` to root deno.json
3. Open root main.ts in VSCode

**Expected behavior**

Importing `@scope/add` and `@scope/subtract` at main.ts works correctly in VSCode editor window. 

**Screenshots**

![deno_workspace_vscode_issue](https://github.com/user-attachments/assets/b5114f83-3391-4497-b1c0-abb3b3a859f2)

**Versions**

vscode: 1.9.0 deno: 1.45.2 extension: v3.38.0

**Comment by Hajime-san** [comment]
upstream https://github.com/denoland/deno/pull/24627

**Comment by nayeemrmn** [comment]
Fixed

**Comment by Kesin11** [comment]
I tested it with the latest version of Deno, 1.45.4. The error messages have disappeared, and the code jump is now functioning properly. Thank you!

#### Versions

vscode: 1.9.1 deno: 1.45.4 extension: v3.38.0
