### ISSUE TITLE
Formating documents with deno disabled

### ISSUE THREAD

**Issue by galiazzi** [denoland/vscode_deno#1135]
I was using deno extension to formatting files with this config in `settings.json`:

```json
{
   "deno.enable": false,
    "[javascript][json][jsonc][markdown]": {
       "editor.defaultFormatter": "denoland.vscode-deno"
    }
}
```

This is not working any more, becose `deno.enable` is false. 

I can't enable deno in some projects, some are in PHP, and a I use deno as a tool to formating and checking format on ci/cd.

Is this intentional?

There is a way to use formating tool without enable deno?

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/vscode_deno/issues/1119#issuecomment-2179239834
