### ISSUE TITLE
Property 'cron' does not exist on type 'typeof Deno'.deno-ts(2339)

### ISSUE THREAD

**Issue by devsheva** [denoland/vscode_deno#1137]
**Describe the bug**
I have tried to enable unstable Cron API, but what i get is this 
`Property 'cron' does not exist on type 'typeof Deno'.deno-ts(2339)`

**To Reproduce**

`deno.jsonc`

```jsonc
{
  "unstable": ["cron"],
  "exclude": ["dist", "node_modules"],
  "compilerOptions": {
    "lib": ["deno.window", "DOM", "DOM.Iterable", "ESNext"],
    "strict": true,
    "allowJs": true
  }
}
```
Put this in any file

```ts

Deno.cron('Log a message', '* * * * *', () => {
  console.log('This will print once a minute.')
})
```

**Expected behavior**

It should not lead to type error.

**Screenshots**

<img width="844" alt="Screenshot 2024-07-27 at 01 20 07" src="https://github.com/user-attachments/assets/f6cb5301-8901-4ee6-99ac-2945531e2b65">

**Versions**

vscode: 1.91.1 deno:1.45.4 extension: 3.38.0

**Comment by nayeemrmn** [comment]
Include `deno.unstable` in `compilerOptions.lib`:
```json
{
  "unstable": ["cron"],
  "exclude": ["dist", "node_modules"],
  "compilerOptions": {
    "lib": ["deno.window", "deno.unstable", "DOM", "DOM.Iterable", "ESNext"],
    "strict": true,
    "allowJs": true
  }
}
```

**Comment by devsheva** [comment]
oh, that worked. maybe it should be added to docs?
