### ISSUE TITLE
`useTabs: true` not respected when formatting via vscode deno extension

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1140]
**Describe the bug**

when using deno vscode extension, it converts tabs to spaces despite `useTabs` is true in `deno.jsonc` .

**To Reproduce**

1. create following structure
```
.vscode/settings.json
main.ts
deno.jsonc
```
```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "deno.config": "./deno.jsonc",
  "[json][jsonc][markdown][typescript][typescriptreact]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  }
}
```
```ts
const foo = () => {
    console.log("hello")
}
```
```json
{
    "fmt": {
        "semiColons": false,
        "lineWidth": 100,
        "useTabs": true,
        "proseWrap": "never"
    }
}
```

2. format files using `Format Document With... > Deno`
3. `useTabs: true` is not respected in Deno VSCode extension
4. format the file with `deno fmt`
5. `useTabs: true` is respected in CLI

**Expected behavior**

1. useTabs option works
2. deno extension behavior matches with deno cli fmt behavior

**Screenshots**

![image](https://github.com/user-attachments/assets/68e8e8a9-f35b-4bb8-8c04-c2ecacda5d41)

**Versions**

vscode: 1.92.0 deno: deno 1.45.5+18b9b43 (canary, x86_64-unknown-linux-gnu) extension: 3.38.0

**Comment by nayeemrmn** [comment]
The vscode extension prioritises the editor indent settings selected in the status bar as per another request https://github.com/denoland/deno/issues/23257. You have to change it to tabs there.

**Comment by heygarrett** [comment]
I ran into the same problem as @scarf005 in Neovim. The editor settings taking priority over the deno settings feels backwards; this would be a source of conflict in any project where multiple devs have different default editor settings. Isn't the point of the deno formatting settings to ensure consistency in the project?
