### ISSUE TITLE
Updating to version v3.38.1 shows errors

### ISSUE THREAD

**Issue by CalvinWilkinson** [denoland/vscode_deno#1145]
**Describe the bug**

When updating to version `v3.38.1`, VSCode shows errors for all uses of the `Deno` object as well as for imports.
When changing to version `v3.38.0`, no errors are shown.

VSCode shows errors when using `deno.enabled` and `deno.enablePaths`.

**To Reproduce**

1. If on version `v3.38.1`, downgrade to version `v3.38.0` and observe the errors disappear.  If not on version `v3.38.0`, upgrade to version `v3.38.1` and watch the errors appear.

**Expected behavior**

With unchanged and valid code, I expect that using version `v3.38.1` would show no errors when using the settings `deno.enable` or `deno.enablePaths`

**Screenshots**

With errors on version `v3.38.1`:
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/644d21ca-34f0-4ab8-9e10-3471a041ce32">

Without errors on version `v3.38.0`:
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/fcc98a46-44e5-44dd-8d62-6479f19010c8">

**Versions**

vscode: v1.92.1
deno: v1.45.5
extension: v1.38.1

**Comment by botikho** [comment]
+1. Seems like new version doesn't mute typescript

**Comment by e-osuna-g** [comment]
+1 For me, Deno was working, but all imports failed on TS.

**Comment by Miklos24** [comment]
+1. Rolling back to v3.38.0 fixed the issue, so seems like an issue with the new version.

**Comment by dsherret** [comment]
Thanks for reporting! This is now fixed in 3.38.2.

Cause was vsce 2.31.1 somehow breaking the extension. Fixed by downgrading vsce to 2.31.0 in https://github.com/denoland/vscode_deno/pull/1147 -- Opened https://github.com/denoland/vscode_deno/issues/1149 for investigation.

**Comment by CalvinWilkinson** [comment]
No problem!  Thanks for the quick fix.  Greatly appreciate it.  😀
