### ISSUE TITLE
Add Linter support.

### ISSUE THREAD

**Issue by MartinChavez** [denoland/vscode_deno#116]
It would be great to have the linter "baked-in", the same way the formatter works, this is:

- Show problems in the Problems tab
- Show problems directly in the source code

I understand that lint functionality is unstable. However, there is no reason to not implement this, and add a note.

**Comment by MartinChavez** [comment]
Thank you so much @bartlomieju !

**Comment by lucacasonato** [comment]
Also huge thanks to @axetroy for the actual implementation in the extension :-)
