### ISSUE TITLE
Import map not recognized for sub-packages when using workspaces and deno.enablePaths

### ISSUE THREAD

**Issue by WilcoKruijer** [denoland/vscode_deno#1162]
**Describe the bug**

Given a workspace 

```
{
  "workspace": [
    "./apps/backend"
  ],
}
```

And a package with `./apps/backend/deno.json` that has an import map

```
{
  "imports": { "hono": "jsr:@hono/hono@^4.6.2",}
}
```

And a file `app.ts` with `import { Hono } from "hono";`

We get the error `Relative import path "hono" not prefixed with / or ./ or ../` WHEN Deno is only enabled for certain sub-folders in VSCode. (I.e. `.vscode/settings.json` contains  `  "deno.enablePaths": ["./apps/backend"]`.

When enabling Deno fully for this project, the problem goes away.

`deno run` and `deno lint` both do not report this problem. (i.e. they work fine)

**Workaround**
Use `deno.enable: false` with `deno.disablePaths` (as opposed to true and `enablePaths` 

**To Reproduce**

```
git clone git@github.com:WilcoKruijer/deno-bug-reproduction.git 
code deno-bug-reproduction
```
**Expected behavior**

No problems detected.

**Versions**

Deno 1.46.3
vscode_deno: 3.40

**Comment by nayeemrmn** [comment]
Try including your workspace root config in the setting:
```json
{
  "deno.enablePaths": ["./deno.json", "./apps/backend"]
}
```
