### ISSUE TITLE
Relative import with ~/ triggers deno(import-prefix-missing)

### ISSUE THREAD

**Issue by birkskyum** [denoland/vscode_deno#1164]
deno 2.0.0-rc.3

This code executes just fine, but I get this language server squiggly line that I don't know if intentional deno opinion or accidental oversight.

The  ~ for relative path, can in some cases be a rather convenient alternative to the ../../../../../ .

<img width="986" alt="Screenshot 2024-09-19 at 14 15 27" src="https://github.com/user-attachments/assets/a8567023-cfcd-47b5-9a0a-bf981f081478">

Copied text:

Relative import path "~/components/ui/dialog" not prefixed with / or ./ or ../
  hint: If you want to use a JSR or npm package, try running `deno add jsr:~/components/ui/dialog` or `deno add npm:~/components/ui/dialog`deno(import-prefix-missing)

**Comment by nayeemrmn** [comment]
Do you have `~/` in an your `deno.json` import map? Can you share your config?

**Comment by birkskyum** [comment]
I don't have a deno.json, just a package.json

**Comment by nayeemrmn** [comment]
Are you executing it with Deno?

**Comment by birkskyum** [comment]
Yes, with deno 2 rc.3

**Comment by nayeemrmn** [comment]
I guess just add a `deno.json` like:
```json
{
  "imports": {
    "~/": "./"
  }
}
```
Let me know if it works.

**Comment by birkskyum** [comment]
It just changes the error to a no-local module loading issue, but it's not really a package, it's just a .tsx file with exports. The code still executes fine though, with / without the .tsx extension.

<img width="953" alt="Screenshot 2024-09-19 at 18 08 57" src="https://github.com/user-attachments/assets/8f290b5b-2553-4224-9570-aa239fd5f08b">

**Comment by nayeemrmn** [comment]
Is that file URL in the error message the correct path? If not, you have to adjust the import map value accordingly, where it says `"./"`.

**Comment by birkskyum** [comment]
Made a repro in here:
https://github.com/birkskyum/squiggly

It's appear to be because the tsconfig.json compilerOptions.path isn't applied properly:

```json
{
  "compilerOptions": {
    "paths": {
      "~/*": [
        "./src/*"
      ]
    }
  }
}
```

**Comment by nayeemrmn** [comment]
We don't read `tsconfig.json`, change the `deno.json` to:
```json
{
  "imports": {
    "~/": "./src/"
  }
}
```

**Comment by birkskyum** [comment]
That works, thanks.

Okay, I didn't realize the tsconfig.json was completely ignored - that seems like an important thing to be aware of when working with deno.

**Comment by birkskyum** [comment]
@nayeemrmn , it's really not clear anywhere that tsconfig.json isn't read by deno, so if it's the case I think it's important to educate more on. See i.e. this article: https://deno.com/blog/intro-to-tsconfig#from-js-to-ts
