### ISSUE TITLE
Unable to load schema error on `deno.json`

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1165]
**Describe the bug**

![image](https://github.com/user-attachments/assets/d535a09c-8575-4a28-bb0f-e841a34b4986)

**To Reproduce**

1. open vscode.
2. open `deno.json(c)`.
3. get following error: `
Unable to load schema from 'https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/config-file.v1.json': .(768)`

**Expected behavior**

Schema is correctly loaded. seems to be vscode issue as the json can be fetched without issue.

```
 curl https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/config-file.v1.json | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26059  100 26059    0     0  27070      0 --:--:-- --:--:-- --:--:-- 27060
    606    2479   26059
```

**Versions**

vscode: 1.93.1 deno: deno 2.0.0-rc.4+4b02210 (canary, release, x86_64-unknown-linux-gnu) extension: 3.40.0

**Comment by bartlomieju** [comment]
Are you using some kind of proxy or VPN? I can load the schema from the GH link without a problem and it works fine in VSCode too. Can it be an intermittent error maybe?

**Comment by scarf005** [comment]
after running `Start Extension Bisect`, it fixed by itself. will close as it's not reproducible.

**Comment by quackerex** [comment]
I'm facing the same issue in VSCode 1.125.1 and Deno VSCode extension 3.52.0.

Full message: 
Unable to load schema from 'https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/lint-rules.v1.json': Location https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/lint-rules.v1.json is untrusted.
