### ISSUE TITLE
Add schema support for deno.lock v4

### ISSUE THREAD

**Issue by LitoMore** [denoland/vscode_deno#1168]
The new lockfile v4 was introduced in https://deno.com/blog/v2.0-release-candidate

**Comment by mayank99** [comment]
Just adding more information: using lockfile v4 currently raises a bunch of IDE warnings.

<img width="666" alt="" src="https://github.com/user-attachments/assets/6ef52e4f-200b-420c-8566-35037331b1a9" width="50%">

The CLI commands work fine with the latest `rc` (x-ref: https://github.com/denoland/deno/issues/25144)
