### ISSUE TITLE
--inspect-brk Always get Outbound Breakpoint Result

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/vscode_deno#118]
Here is my launch.json configuration on my visual studio code :

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Deno",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/v1/api-client",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "run",
        "--inspect-brk",
        "-A",
        "--unstable",
        "index.ts"
      ],
      "port": 9229
    }
  ]
}
```
the path is accurate & name file is right.

Here is the debug console :  
![image](https://user-images.githubusercontent.com/5908094/88276511-5dc7db00-cd09-11ea-9142-7536aba9db07.png)

when i am tried to add breakpoint , its always outbound.. normally before update deno its working normal.
![image](https://user-images.githubusercontent.com/5908094/88276384-29541f00-cd09-11ea-8f62-7d297ea79d2f.png)

**Comment by David-Else** [comment]
Try `"debug.javascript.usePreview": false,`, the answer depends on a few things and is hidden in here https://github.com/denoland/vscode_deno/issues/12

**Comment by kitsonk** [comment]
Closing as stale.

If the problem still exists in a recent version of the extension and Deno, we can investigate.
