### ISSUE TITLE
[bug ✨] Cannot find module (in vs code)

### ISSUE THREAD

**Issue by devlopersabbir** [denoland/vscode_deno#1181]
**Describe the bug**
I recently created a **deno jsr** package for exciting purposes. this is my package called [@devloeprsabbir/hello](https://jsr.io/@devlopersabbir/hello)

**Expected behavior**
as I set a screenshot.. I'm getting errors on VS code but the code works perfectly when I run my code with `deno main.ts` also I'm not getting any check errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/1145c416-95fd-48bb-9e02-40ee9dc2d37b)

**Versions**
DENO 2 🐸

vscode: xxx deno: xxx extension: xxx

**Comment by nayeemrmn** [comment]
That error is coming from the built-in TS server for node. You can enable Deno and suppress those errors by adding a `deno.json` or setting `"deno.enable": true` in your workspace settings. Please comment here if that didn't work. Closing for now.
