### ISSUE TITLE
An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled

### ISSUE THREAD

**Issue by khanakia** [denoland/vscode_deno#1184]
**Describe the bug**
I just did a fresh install and opened the project in vscode and getting weird typescript errors

I have enabled Deno and followed the steps here https://docs.deno.com/runtime/reference/vscode/#troubleshooting still no luck
**To Reproduce**

1. deno run -A -r https://fresh.deno.dev
2. cd fresh-project
3. deno task start

**Expected behavior**

**Screenshots**

![Screenshot 2024-10-16 at 11 25 30 PM](https://github.com/user-attachments/assets/fa2376b3-b10b-4dd8-9e8f-38def77b499e)

![Screenshot 2024-10-16 at 11 25 43 PM](https://github.com/user-attachments/assets/31253ef3-ae59-4df0-90ab-84ffacc77377)
![Screenshot 2024-10-16 at 11 25 57 PM](https://github.com/user-attachments/assets/c4293c55-b4a9-43e2-ba9c-78565ba5e4a2)

**Versions**

vscode: 1.94.2 (Universal) deno: 2 extension: lastest

**Comment by nayeemrmn** [comment]
Check your user settings for `"typescript.tsserver.experimental.enableProjectDiagnostics": true`, and disable it. Those errors are coming from the built-in TS server, and our plugin can't supress errors caused by that setting.

Please verify if that was the problem.

**Comment by khanakia** [comment]
thanks this fixed the issue
