### ISSUE TITLE
Code generated by `deno init` gives an error in VS Code

### ISSUE THREAD

**Issue by mike-lischke** [denoland/vscode_deno#1190]
deno 2.0.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2

The generated code is as expected:

```ts
export function add(a: number, b: number): number {
  return a + b;
}

// Learn more at https://docs.deno.com/runtime/manual/examples/module_metadata#concepts
if (import.meta.main) {
  console.log("Add 2 + 3 =", add(2, 3));
}
```

however, this gives me the error:

> The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.ts(1343)

![Bildschirmfoto 2024-10-23 um 17 19 59](https://github.com/user-attachments/assets/178565ca-97cd-4932-be9f-1bed66e743c0)

All I did was to create a new folder, opened that in VS Code and ran `deno init`. Then I opened main.ts and got this. Not a good first impression, even though `deno main.ts` (or `deno run main.ts` for that matter) run fine.

Further info: I have tsc 5.2.2 installed globally on my box and .vscode/settings.json just contains:

```json
{
    "deno.enable": true
}
```

**Comment by nayeemrmn** [comment]
Check your user settings for `"typescript.tsserver.experimental.enableProjectDiagnostics": true`, and disable it. Those errors are coming from the built-in TS server, and our plugin can't supress errors caused by that setting.

Please verify if that was the problem.

**Comment by mike-lischke** [comment]
That was it @nayeemrmn! Removing this key from the settings.json file made the TS diagnostics go away.

**Comment by mike-lischke** [comment]
Thanks for analyzing this problem with me. It's obviously a user-generated problem. Would be good if this setting could be checked by the extension and a warning be shown to inform the user about possible conflicts. Thanks!

**Comment by nayeemrmn** [comment]
@mike-lischke No problem! I've already opened a PR for this: #1191.
