### ISSUE TITLE
The extension resolves NPM packages even if they are not imported in deno.json

### ISSUE THREAD

**Issue by sant123** [denoland/vscode_deno#1194]
**Describe the bug**
When setting `vendor: true` in deno.json, the extension resolves all dependencies found on deno.json but also all the NPM packages in the project in other files (not in deno.json)

**To Reproduce**

### deno.json
```json
{
  "lock": false,
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  },
  "imports": {
    "react": "npm:react@^18.3.1"
  }
}
```

### jsr.ts
```ts
import { yellow } from 'jsr:@std/fmt/colors';
console.log(`Hello ${yellow('colors!')}`);
```
### npm.ts
```ts
import chalk from 'npm:chalk';
console.log(`Hello ${chalk.yellow('chalk!')}`);

```

Now add `vendor: true` with VSCode and Deno extension. You will see `node_modules` magically generated, now inspect the contents and you will find `chalk` but that NPM package is not specified in deno.json. Also notice JSR packages are not resolved which is expected.

However `deno install` works as expected. Delete the `node_modules` folder and enter `deno install` in a terminal and you will see only packages set on deno.json.

**Expected behavior**

Deno extension should work the same as `deno install` when `vendor: true` is set.

**Screenshots**

Adding `vendor: true` and being solved by the Deno extension
![image](https://github.com/user-attachments/assets/7f931d0b-4d44-440f-bdb7-04ed2823e32a)

Deleting node_modules, preserving the `vendor: true` and `deno install`
![image](https://github.com/user-attachments/assets/8db58c94-d769-4e5f-9d1a-e5553801cdb2)

**Versions**

vscode: 1.94.2 deno: 2.0.2 extension: 3.42.0

Thanks

**Comment by nayeemrmn** [comment]
This is intended. The import map is not meant to act as an exhaustive dependency manifest (at least not technically, maybe conventionally) but for adding aliases. We walk files in the workspace to find dependencies. If you want to exclude files from this, use a setting like: `"deno.disablePaths": ["npm.ts"]`.

**Comment by sant123** [comment]
But is intended for NPM packages only? Note that this does not happen with JSR packages. I feel this is unexpected @nayeemrmn 🤔

**Comment by sant123** [comment]
> We walk files in the workspace to find dependencies.

This would make sense if JSR and other URL packages are included as well.

**Comment by nayeemrmn** [comment]
Ah you're talking about npm deps being auto-installed. I think that's a consequence of auto-caching `jsxImportSource`, by necessity of taking into account all npm deps when installing any of them. The language server doesn't do this for JSR.

This all has nothing to do with things being listed in `deno.json`, though.

**Comment by sant123** [comment]
So if `jsxImportSource` is set with a NPM dependency like `react`, the language server will auto-install it along with all NPM imports it finds in the project without explicitly being set in `deno.json`? That's a strange behavior, the language server may save the scanning in the project reading from `deno.json` and add those dependencies into `node_modules`; that is how `deno install` is currently working and that result is expected.
