### ISSUE TITLE
deno-ts errors in regular JSX markup?

### ISSUE THREAD

**Issue by mo** [denoland/vscode_deno#1198]
**Describe the bug**

I pasted some react javascript code into a new buffer without even saving it.
VS Code detects it correctly as "Javascript JSX".
However, I got lots of  weird deno-ts squiggle lines complaining about "Unreachable code" in normal text inside normal HTML element in the JSX?

**To Reproduce**

paste this code into a new buffer in VS Code:

```
export default function Home() {
  return (
        <h3>Points management</h3>
  )
}
```

**Expected behavior**

Why is it even running any deno stuff at all here?

**Screenshots**

![image](https://github.com/user-attachments/assets/35831120-f5b6-480c-bc6e-16c336c0ac92)

![image](https://github.com/user-attachments/assets/b6693cde-bcc1-4d82-902e-d83afebe5e2d)

**Comment by mo** [comment]
The error goes away when I save using .jsx file extension but why deno-ts do this for unsaved buffers? I have tons vscode plugins installed and only deno plugins does this to unsaved buffers?

**Comment by nayeemrmn** [comment]
Let's track this in https://github.com/denoland/deno/issues/26393.
