### ISSUE TITLE
Deno Extension doesn't work

### ISSUE THREAD

**Issue by ianlibanio** [denoland/vscode_deno#120]
Hello, so i'm having a problem with Deno VS Code plugin, i tried a lot of times but it doesn't work. 

It always say: `The remote module "https://deno.land/std/ws/mod.ts" has not been cached locallyts(10002)`

How can i solve this problem?

**Comment by taigah** [comment]
The extension does not fetch imports automatically so you need to cache the module manually. For that you can execute your script or use `deno cache https://deno.land/std/ws/mod.ts`. Once the module is cached, reopen the file and the error should be gone.

**Comment by ianlibanio** [comment]
Thanks.
