### ISSUE TITLE
having `deno.json` at workspace root doesn't enable deno extension

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1215]
**Describe the bug**

> Deno: Enable - will enable Deno on the current workspace. Alternatively you can create a deno.json or deno.jsonc file at the root of your workspace.

despite https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno, having `deno.json` **does not** enable deno extension.

**To Reproduce**

1. create a directory
2. run deno init
3. open directory
 
**Expected behavior**

deno extension is enabled when there's `deno.json` or `deno.jsonc`

**Screenshots**

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/4a0eb2e5-0144-4e68-b779-9d06feea165b">

**Versions**

vscode: 1.95.3 deno: 2.1.1 extension: v3.42.0

**Comment by nayeemrmn** [comment]
Please share your vscode settings. Workspace settings and user settings related to `deno.enable/disable`.

**Comment by scarf005** [comment]
deno.json:
```json
{
  "fmt": {
    "semiColons": false,
    "useTabs": true,
    "proseWrap": "never",
    "lineWidth": 120
  },
  "compilerOptions": {
    "lib": ["dom"],
    "types": ["./types.d.ts"],
    "checkJs": true
  },
  "lock": false
}
```
workspace settings: (doesn't exist)

global settings `deno.enable`: (doesn't exist)

<img width="598" alt="image" src="https://github.com/user-attachments/assets/a407748b-3c69-4016-82de-c427d2eec13e">

**Comment by nayeemrmn** [comment]
What does the output panel say?

**Comment by scarf005** [comment]
```
shutdown request received, shutting down
exit notification received, stopping
Starting Deno language server...
  version: 2.1.1 (release, aarch64-apple-darwin)
  executable: /Users/nemo/.local/share/deno/bin/deno
Connected to "Visual Studio Code" 1.95.3
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Couldn't open workspace "file:///Users/nemo/repo/codeit/": Error reading config file 'file:///home/scarf/deno.jsonc'.
Could not set npm package requirements: Error getting response at https://registry.npmjs.org/typed-query-selector for package "typed-query-selector": An npm specifier not found in cache: "typed-query-selector", --cached-only is specified.
Could not set npm package requirements: Error getting response at https://registry.npmjs.org/typed-query-selector for package "typed-query-selector": An npm specifier not found in cache: "typed-query-selector", --cached-only is specified.
Server ready.
```

looks like it was due to this rogue line:
```
"deno.config": "/home/scarf/deno.jsonc",
```
