### ISSUE TITLE
Extension is enabled even if deno.json is not present

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1226]
**Describe the bug**

![image](https://github.com/user-attachments/assets/524631eb-f87f-47b7-9727-82e56c21a5b5)

Despite `deno.json` and `deno.lock` not in workspace root, deno extension is enabled. This is contradictory to description of `deno.enabled`.

**To Reproduce**

create and open a bun project on vscode (e.g https://elysiajs.com/tutorial.html)

**Expected behavior**

Deno extension is not enabled on a {project without deno.json[c]/deno.lock,bun project} 

**Screenshots**

![image](https://github.com/user-attachments/assets/73801b1c-f799-45dd-8f34-16aca426273c)
![image](https://github.com/user-attachments/assets/8068f9f7-677d-42ed-a278-a18a2a629088)

**Versions**

vscode: 1.95.3 deno: 2.1.4 extension: 3.43.1

**Comment by nayeemrmn** [comment]
1. Make sure you don't have `deno.enable: true` in user or workspace settings.
2. Please share your output panel content, it will show if a `deno.json` has been detected (higher up in your dir hierarchy for example).

**Comment by scarf005** [comment]
1. `deno.enable` is not set.
2. there's `~/deno.jsonc` at `$HOME` but $HOME isn't workspace root
```
Starting Deno language server...
  version: 2.1.4 (release, x86_64-unknown-linux-gnu)
  executable: /home/scarf/.deno/bin/deno
Connected to "Visual Studio Code" 1.95.3
Enabling import suggestions for: https://deno.land/
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///home/scarf/deno.jsonc"
  Resolved .npmrc: "/home/scarf/.npmrc"
  Resolved lockfile: "file:///home/scarf/deno.lock"
  Resolved Deno configuration file: "file:///home/scarf/repo/etc/learn-deno/deno.jsonc"
  Resolved .npmrc: "/home/scarf/.npmrc"
  Resolved lockfile: "file:///home/scarf/repo/etc/learn-deno/deno.lock"
Server ready.
```

**Comment by scarf005** [comment]
my bad, `deno.config` again.
