### ISSUE TITLE
Click thru definitions don't have syntax highlighting

### ISSUE THREAD

**Issue by lukepighetti** [denoland/vscode_deno#13]
If you click thru to a definition the syntax highlighting/lang server features are missing

Target:
<img width="778" alt="Screen Shot 2020-05-12 at 9 50 32 AM" src="https://user-images.githubusercontent.com/666539/81699967-08806b00-9436-11ea-88c9-5490b74f6414.png">

Issue:
<img width="739" alt="Screen Shot 2020-05-12 at 9 51 11 AM" src="https://user-images.githubusercontent.com/666539/81700050-277efd00-9436-11ea-95d1-cdf5ec7a11b3.png">

**Comment by justjavac** [comment]
I will fix it today, use meta file to determine the file type

**Comment by lukepighetti** [comment]
Glad to hear, this is one of the most powerful features of Dart with inline comments and click thru to definition with full lang server features (including debugging breakpoints in packages, but this issue doesn't cover that).
