### ISSUE TITLE
namespace deno does not work on version 2.0.4

### ISSUE THREAD

**Issue by buttercubz** [denoland/vscode_deno#139]
after updating the extension to version 2.0.4 vscode it stopped recognizing the Deno namespaces.

I was testing and versions greater than 1.26 have this problem.

![image](https://user-images.githubusercontent.com/47539192/90074676-b582b200-dcc9-11ea-8d8f-37621a189f30.png)
![image](https://user-images.githubusercontent.com/47539192/90074861-10b4a480-dcca-11ea-8397-74da143514d3.png)

**version 1.26.0 works fine**

![image](https://user-images.githubusercontent.com/47539192/90075142-b700aa00-dcca-11ea-9361-6fa5aa90b2d3.png)

vscode: 1.47.3
deno: 1.2.3
extension: 2.0.4

**Comment by lucacasonato** [comment]
Add `"deno.enable": true` to your `.vscode/settings.json` (workspace settings) file.

**Comment by buttercubz** [comment]
@lucacasonato 
global settings not working? or you need to use local configuration

**Comment by jeroenptrs** [comment]
@buttercubz setting it globally isn't advised, locally works best i think

**Comment by lucacasonato** [comment]
you need to use local configuration. global configuration is not supported

**Comment by nayeemrmn** [comment]
This is the same as #131. Unless setting it in the workspace settings worked, @buttercubz?

**Comment by iugo** [comment]
VS Code has workspace settings, you can set the extension to be available in the workspace.

**Comment by buttercubz** [comment]
@lucacasonato @nayeemrmn 
thanks, I see the advantages of it being a local configuration 😊
