### ISSUE TITLE
no intellisense because the mapped file name is not ended with '.ts'

### ISSUE THREAD

**Issue by heroboy** [denoland/vscode_deno#14]
deno: 1.0.0-rc3
v8: 8.4.300
typescript: 3.8.3

![图片](https://user-images.githubusercontent.com/54468/81766621-0e934c00-9509-11ea-934b-b7a33805c337.png)

**Comment by justjavac** [comment]
maybe a Deno's issue:

```shell
deno cache https://deno.land/std/fs/mod.ts
...
Found 12 errors.
```

**Comment by heroboy** [comment]
no error
```
D:\>deno cache https://deno.land/std/fs/mod.ts
D:\>deno -V
deno 1.0.0-rc3
D:\>
```

**Comment by heroboy** [comment]
ok. I know what you mean.
add '--unstable'
```
D:\>deno cache https://deno.land/std/fs/mod.ts --reload --unstable
Download https://deno.land/std/fs/mod.ts
Compile https://deno.land/std/fs/mod.ts
Download https://deno.land/std/fs/empty_dir.ts
Download https://deno.land/std/fs/ensure_dir.ts
Download https://deno.land/std/fs/ensure_file.ts
Download https://deno.land/std/fs/ensure_link.ts
Download https://deno.land/std/fs/ensure_symlink.ts
Download https://deno.land/std/fs/exists.ts
Download https://deno.land/std/fs/expand_glob.ts
Download https://deno.land/std/fs/move.ts
Download https://deno.land/std/fs/copy.ts
Download https://deno.land/std/fs/read_file_str.ts
Download https://deno.land/std/fs/write_file_str.ts
Download https://deno.land/std/fs/read_json.ts
Download https://deno.land/std/fs/write_json.ts
Download https://deno.land/std/fs/walk.ts
Download https://deno.land/std/fs/eol.ts
Download https://deno.land/std/path/mod.ts
Download https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/posix.ts
Download https://deno.land/std/path/common.ts
Download https://deno.land/std/path/separator.ts
Download https://deno.land/std/path/interface.ts
Download https://deno.land/std/path/glob.ts
Download https://deno.land/std/path/_constants.ts
Download https://deno.land/std/path/_util.ts
Download https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/fmt/colors.ts
Download https://deno.land/std/testing/diff.ts
Download https://deno.land/std/path/_globrex.ts
Download https://deno.land/std/fs/_util.ts
```

**Comment by heroboy** [comment]
not deno's bug. The filename is intent to be a hash.
https://github.com/denoland/deno/blob/e34a3b61f449cf6197b6d701770a85d9205c2a7b/cli/http_cache.rs#L56-L70

**Comment by justjavac** [comment]
I will fix it

**Comment by rodolphocastro** [comment]
Just to add to the discussion: Still happening on deno 1.0.0

![image](https://user-images.githubusercontent.com/2666310/81998433-d7b45780-9628-11ea-984c-4c8becc5bd4d.png)

```
deno: 1.0.0
v8: 8.4.300
typescript: 3.9.2
```

Extension currently on Version 1.28.0 and it's reproductible on the following repository: https://github.com/rodolphocastro/deno-todo

Currently running on Windows

**Comment by justjavac** [comment]
There is no problem on my MBP, I will test it on win10 at night

**Comment by rodolphocastro** [comment]
> There is no problem on my MBP, I will test it on win10 at night

Just checked on an Ubuntu 18.04 running on WSL2 and the same issue happened:

![image](https://user-images.githubusercontent.com/2666310/82055453-e46f9480-9696-11ea-9cc9-dbeb67cc979e.png)

```
Found deno, version:
deno: 1.0.0
v8: 8.4.300
typescript: 3.9.2
```

@justjavac are there any logs I could enable to help you with this?

**Comment by ibrahimduran** [comment]
Problem seems to be caused by the non-matching import paths in cached modules since deno internally translates file names into hashes.

![image](https://user-images.githubusercontent.com/6016901/82062230-7b0d7700-96d2-11ea-8f72-93e4374abf6a.png)

![image](https://user-images.githubusercontent.com/6016901/82062272-8bbded00-96d2-11ea-95bc-682a194b5c33.png)

**Comment by justjavac** [comment]
@rodolphocastro I have reproduced this bug and found the cause of the bug.

thanks @ibrahimduran, it is this reason
