### ISSUE TITLE
Typescript language service died 5 times ...

### ISSUE THREAD

**Issue by newtack** [denoland/vscode_deno#149]
Using latest version (2.0.13) on Ubuntu 20.04 and latest version of VSCode. It worked 3 days ago, 2.0.10 caused issue #140, with 2.0.13 I now have the error that the Typescript language service repeatedly dies. 

Here are relevant excerpts of the log:

(just before file watchers):
Info 23 [11:51:51.508] DirectoryWatcher:: Added:: WatchInfo: /home/ralf/dev/play/scripts 1 undefined Project: /home/ralf/dev/play/scripts/tsconfig.json WatchType: Wild card directory
Info 24 [11:51:51.509] Elapsed:: 1ms DirectoryWatcher:: Added:: WatchInfo: /home/ralf/dev/play/scripts 1 undefined Project: /home/ralf/dev/play/scripts/tsconfig.json WatchType: Wild card directory
Info 25 [11:51:51.509] Loading global plugin typescript-vscode-sh-plugin
Info 26 [11:51:51.509] Enabling plugin typescript-vscode-sh-plugin from candidate paths: /usr/share/code-insiders/resources/app/extensions/typescript-language-features,/home/ralf/.vscode-insiders/extensions/denoland.vscode-deno-2.0.13,/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 27 [11:51:51.510] Loading typescript-vscode-sh-plugin from /usr/share/code-insiders/resources/app/extensions/typescript-language-features (resolved to /usr/share/code-insiders/resources/app/extensions/typescript-language-features/node_modules)
Info 28 [11:51:51.512] typescript-vscode-sh-plugin initialized. Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
Info 29 [11:51:51.512] Plugin validation succeded
Info 30 [11:51:51.512] Loading global plugin typescript-deno-plugin
Info 31 [11:51:51.512] Enabling plugin typescript-deno-plugin from candidate paths: /usr/share/code-insiders/resources/app/extensions/typescript-language-features,/home/ralf/.vscode-insiders/extensions/denoland.vscode-deno-2.0.13,/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 32 [11:51:51.512] Loading typescript-deno-plugin from /usr/share/code-insiders/resources/app/extensions/typescript-language-features (resolved to /usr/share/code-insiders/resources/app/extensions/typescript-language-features/node_modules)
Info 33 [11:51:51.536] Loading typescript-deno-plugin from /home/ralf/.vscode-insiders/extensions/denoland.vscode-deno-2.0.13 (resolved to /home/ralf/.vscode-insiders/extensions/denoland.vscode-deno-2.0.13/node_modules)
Info 34 [11:51:51.551] [typescript-deno-plugin] "Create typescript-deno-plugin"
Info 35 [11:51:51.552] Plugin validation succeded

(near the end)

Err 8240 [11:51:59.199] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/home/ralf/dev/play/scripts/gen-deps.ts","fileContent":"//todo: using deps.json as input, generate all other relevant files (import map, package.json, etc.)\n//from it\n\nimport { run, runWithStringOutput } from "./platform/shared/utils.ts";\n\n//1. get unique list of dependencies with version and without\n\ninterface Dependencies {\n [s: string]: Dependency;\n}\n\ninterface Dependency {\n version: string;\n dependencies?: Dependencies;\n}\n\nconst packageWithVersions = new Map<string, string[]>();\nconst packages = new Map<string, Set>();\nconst childVersions = new Set();\n\nfunction getNameAndVersion(name: string, version: string) {\n return ${name}.v${version};\n}\n\nfunction read_dep(\n ancestors: string[],\n name: string,\n dep: Dependency,\n level: number,\n) {\n const depName = getNameAndVersion(name, dep.version);\n packageWithVersions.set(depName, []);\n for (const ancestor of ancestors) {\n \n packageWithVersions.get(ancestor)!.push(depName);\n }\n if (!packages.has(name)) {\n const versions = new Set();\n versions.add(dep.version);\n packages.set(name, versions);\n } else {\n const versions = packages.get(name)!;\n if (!versions.has(dep.version)) {\n versions.add(dep.version);\n }\n }\n if (dep.dependencies === undefined) {\n return;\n }\n const newAncestors = [...ancestors, depName];\n read_deps(newAncestors, dep.dependencies, level + 1);\n}\n\nfunction getPackageName(fullName: string) {\n const index = fullName.indexOf(".v");\n return fullName.substr(0, index);\n}\n\nfunction read_deps(\n ancestors: string[],\n dependencies: Dependencies,\n level: number,\n) {\n for (const [key, value] of Object.entries(dependencies)) {\n const depName = getNameAndVersion(key, value.version);\n read_dep(ancestors, key, value, level);\n }\n}\n\nasync function getPackageVersion(\n node_modules_dir: string,\n packageName: string,\n) {\n const filePath = ${node_modules_dir}/${packageName}/package.json;\n const contents = await Deno.readTextFile(filePath);\n const json = JSON.parse(contents) as { version: string };\n return json.version;\n}\n\nasync function generateEsm(nodeModulesDir: string, vendorDir: string) {\n const json = await runWithStringOutput({\n cwd: nodeModulesDir,\n cmd: ["npm", "ls", "-json"],\n });\n const deps = JSON.parse(json) as Dependency;\n\n read_deps([], deps.dependencies!, 0);\n\n for (const key of packages.keys()) {\n const values: Set = packages.get(key)!;\n if (values.size > 1) {\n const rootVersion = await getPackageVersion(nodeModulesDir, key);\n for (const value of values) {\n const fullName = ${key}.v${value};\n const isRoot = rootVersion === value;\n if (!isRoot) {\n childVersions.add(fullName);\n }\n }\n }\n }\n\n let maxCount = 0;\n let maxKey = "";\n console.log("all packages with version:");\n for (const key of packageWithVersions.keys()) {\n const packageName = getPackageName(key);\n //console.log(key);\n const deps = packageWithVersions.get(key)!;\n if (maxCount < deps.length) {\n maxCount = deps.length;\n maxKey = key;\n }\n const excludeDeps = deps.filter((d) => !childVersions.has(d)).map((d) =>\n external:${getPackageName(d)}\n );\n const options = {\n cwd: nodeModulesDir,\n cmd: [\n "esbuild",\n "--bundle",\n ./${packageName}/index.js,\n --outdir=${vendorDir}/${packageName},\n "--format=esm",\n ...excludeDeps,\n ],\n };\n //console.log(options);\n try {\n await run(options);\n console.log(successfully generated package ${packageName});\n } catch (e) {\n //console.log(Error generating package ${packageName}: ${e});\n }\n\n //esbuild --bundle ./react/index.js --outdir=/home/ralf/dev/vendor/dev/react --format=esm --minify --external:object-assign\n }\n console.log(max dep count is: ${maxCount} for ${maxKey});\n}\n\n/\n#!/usr/bin/env -S deno run -A --unstable --importmap=import_map.json\nimport { getFileHash } from "./platform/shared/fileUtils.ts";\nconst hash = await getFileHash("./run.ts");\n\n//esbuild for graphql: esbuild --bundle ./types/node_modules/graphql/index.js --sourcemap --outdir=./web --format=esm --minify\n//esbuild --bundle ./types/node_modules/react/index.js --sourcemap --outdir=./web --format=esm --minify\nesbuild --bundle ./types/node_modules/react/index.js --sourcemap --outdir=./web --format=esm --minify --define:process.env.NODE_ENV="production"\n//"graphql": "./types/node_modules/graphql/index.d.ts",\nconsole.log(hash);\n\n/\n\nawait generateEsm(\n "/home/ralf/dev/play/types/node_modules",\n "/home/ralf/dev/vendor/dev",\n);\n\n//get for each package the complete list of dependencies (recursive)\n","projectRootPath":"/home/ralf/dev/play/scripts","scriptKindName":"TS"}]}}:

Debug Failure. False expression.

Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107121:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107156:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106893:50)
    at Object.finishCachingPerDirectoryResolution (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106898:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148266:38)
    at ConfiguredProject.Project.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148197:42)
    at ConfiguredProject.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149131:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150835:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151733:44)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152056:97
    at Object.flatMap (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152056:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:153075:46)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154947:88
    at IOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154938:28)
    at IOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154947:33)
    at IOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154971:35)
    at Interface.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157187:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by lucacasonato** [comment]
This should be fixed now. Can you try again with 2.2.0?

**Comment by stefano77it** [comment]
Having the same error message **_Typescript language service died 5 times_** on Windows 10, VsCode version 1.52.1, Deno version 1.6.2, Deno extension version 2.3.3, TypeScript version 4.1.3. 

`settings.json` file content

    {
        "deno.enable": true,
        "deno.unstable": true,
        "deno.lint": true,
        "deno.import_map": "./src",
        "deno.import_intellisense_origins": {
            "https://deno.land": true,
        }
    }

Resolved removing the line 

    "deno.import_map": "./src",

**Comment by lucacasonato** [comment]
This has been resolved in version 3.x of the extension.
