### ISSUE TITLE
Patching 2.0.10 -> 2.0.13 breaks colorization

### ISSUE THREAD

**Issue by qqspaniard** [denoland/vscode_deno#150]
### test

**Describe the bug**
Switching from 2.0.10 -> 2.0.13 breaks colorization. All types of colored texts have miscolored characters within, e.g.:
![image](https://user-images.githubusercontent.com/42599134/90354633-b3d52900-dffe-11ea-84ad-997709eeeea3.png)

**To Reproduce**
Upgrade from 2.0.10 -> 2.0.13
type some stuff

vscode: 8.6.334
deno: 1.3.0
extension: 2.0.13

**Comment by lucacasonato** [comment]
I doubt this is related to the Deno extension. Could you restart VS Code to check if the error persists?

**Comment by qqspaniard** [comment]
I've been working with extension version 2.0.10 for a while without issue.
Updating to 2.0.13 and reloading caused a recurrence of the issue: 
![image](https://user-images.githubusercontent.com/42599134/90670118-92935900-e207-11ea-9538-532fdb0306c4.png)

**Comment by Pumych** [comment]
Same is for me, happens only when Deno plugin is enabled, all other plugins are disabled

**Comment by lem0nify** [comment]
Not onlu colorization btw. For me, there is no `Deno` namespace in the IntelliSense also. And hints lie much. Looks like there are huge problems with extension.

**Comment by stonetwig** [comment]
![I can also confirm this issue, it is quite hard to read..](https://user-images.githubusercontent.com/47466/92327493-5ad73e80-f05a-11ea-80c6-e9fd8cf8c335.png)

**Comment by CGQAQ** [comment]
The reason is we are poking around typescript language server through the tsserver plugin, and causing many holes that makes the "ship" so fragile

**Comment by lucacasonato** [comment]
Should be resolved in version 3.x of the extension.
