### ISSUE TITLE
Settings from workspace configuration file not working

### ISSUE THREAD

**Issue by pestapever** [denoland/vscode_deno#157]
**Describe the bug**
 If I enable the extensione from .vscode/settings.json with
{
    "deno.enable": true,
}
all is working.

But if I open a workspace from file my.code-workspace with 
{
	"settings": {
		"deno.enable": true,
	}
}
nothing is working.

**Expected behavior**
Deno extension settings loaded also from workspace configuration file.

**Versions**
vscode: 1.48.2
deno: 1.3.1
extension: 2.0.13

**Comment by lucacasonato** [comment]
This is currently expected behaviour, but it does not seem desirable.

@axetroy Do you think we can somehow get to the actual config from vscode in the `typescript-deno-plugin`, rather than manually parsing `.vscode/settings.json`? That would solve all of these issues.

**Comment by axetroy** [comment]
> @axetroy Do you think we can somehow get to the actual config from vscode in the `typescript-deno-plugin`, rather than manually parsing `.vscode/settings.json`? That would solve all of these issues.

In the plug-in, we cannot actively obtain the information about vscode

But we can monitor changes in configuration files

https://github.com/denoland/vscode_deno/blob/6d7295be794b189b8b17565799cc2f7648f5f276/typescript-deno-plugin/src/plugin.ts#L546-L552

**Comment by lucacasonato** [comment]
Is there a way to communicate between the `client` (or is it the `server`) which can access VS Code APIs, and the `typescript-deno-plugin`. Ideally we would read the config on the VS Code side, with the VS Code APIs and then send it to the `typescript-deno-plugin`.

**Comment by lucacasonato** [comment]
This has been resolved in version 3.x of the extension.
