### ISSUE TITLE
Deno Variables are not available for autocompletion

### ISSUE THREAD

**Issue by LinoBert** [denoland/vscode_deno#163]
**Describe the bug**
After upgrading to Extension version 2.0.15 the global Deno Variables like Signal, permissions etc. are not available anymore.

**To Reproduce**

1. install deno (a new fresh install)
2. install vscode_deno plugin
3. create a settings file (.vscode/settings.json)
{
  "deno.enable": true,
}
4. create a .ts file
5. type Deno.Signal

**Expected behavior**
VSCode should generate autocompletion for built-in Deno Variables listed in the documentation
https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/dts/lib.deno.unstable.d.ts#Deno.Signal

**Screenshots**

![Deno_Signal](https://user-images.githubusercontent.com/23521683/91639053-158c8e80-ea14-11ea-89b6-00e81226df50.png)

**Versions**

vscode: 1.48.2
deno: 1.3.1
extension: 2.0.16

Question: Is it removed because it is labeled as unstable?

**Comment by ry** [comment]
I believe there is a setting for turning on unstable

**Comment by lucacasonato** [comment]
Set the `"deno.unstable": true` option.

**Comment by LinoBert** [comment]
@ry @lucacasonato thank you very much, the option works as expect :+1:
So when I am right the better option would be to use the platform specific Enum right?
`Deno.signal(Deno.LinuxSignal.SIGTERM).then(() => {
  Deno.exit(1);
});`

**Comment by LinoBert** [comment]
Problem solved - case closed
