### ISSUE TITLE
[regression] deno enable/disable command palette entries removed

### ISSUE THREAD

**Issue by jsejcksn** [denoland/vscode_deno#170]
There is no longer a VS Code command palette option to "Enable Deno" or to "Disable Deno" (it seems I must manually create the workspace settings file in every new workspace).

**Screenshots**

<img width="286" alt="vscode-command-palette-deno" src="https://user-images.githubusercontent.com/868251/91784562-d3587e00-ebc8-11ea-9181-98fbdfc51902.png">

**Versions**

vscode: `1.48.2`
deno: `1.3.2`
extension: `2.0.16`

**Comment by calvinlauco** [comment]
I think it is removed in this commit: https://github.com/denoland/vscode_deno/commit/bacff2abf89b6b4d80c3afb8fcd37b6032e3c30e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

@jsejcksn are you currently working on this? If not I could try to add it back.

**Comment by jsejcksn** [comment]
@calvinlauco No, I'm not—go for it!

**Comment by axetroy** [comment]
In fact, I don’t like the `enable/disable` command. I think it is redundant.

Keep it as simple as possible for the user.

If you must add a command, Then add a command `deno.init` to create a configuration of Deno.

**Comment by calvinlauco** [comment]
@axetroy Yes, keeping it simple to the user is important. Personally, the `enable/disable` command can help me quickly enable it when I work on deno projects (I disable the plugin by default). But this action is not frequent and I could easily do that by going to settings. So if we want to keep things simple this is not a must for me.

I have some free time recently so I am looking to see what I could contribute to the project.

Regarding the `deno.init`, I usually go to VSCode settings panel and create one. If it is needed I can also go for it. Or else I could help on any higher priority tasks in your roadmap first.

**Comment by jsejcksn** [comment]
> If you must add a command, Then add a command `deno.init` to create a configuration of Deno.

@axetroy Can you describe what this command would create?

> Keep it as simple as possible for the user.

Choosing a command palette entry to select is **much** simpler than having to create a workspace configuration directory and then create a settings file and then input the Deno-specific JSON settings.

**Comment by calvinlauco** [comment]
> > If you must add a command, Then add a command `deno.init` to create a configuration of Deno.
> 
> @axetroy Can you describe what this command would create?
> 
> > Keep it as simple as possible for the user.
> 
> Choosing a command palette entry to select is **much** simpler than having to create a workspace configuration directory and then create a settings file and then input the Deno-specific JSON settings.

Hi @jsejcksn , perhaps can you also share your use case of the enable/disable. For me as I mentioned this is a quick way to enable it because I disable the plugin by default coz I don't want the new workspace to be overwhelmed with unneeded plugins. So it does save me a few clicks if it is available. But at the same time if it's only me that finds this useful and I may be the minority, then I respect the decision to keep the plugin simple.

**Comment by jsejcksn** [comment]
> can you also share your use case of the enable/disable in command palette

@calvinlauco The Deno extension is disabled by default. I agree that it should be disabled by default because of conflicts with all non-Deno environments.

For every new VS Code workspace which will use the extension, it must be enabled. These are the steps to manually enable the extension in a new workspace:

1. Create a directory in the workspace root named `.vscode`.
2. Create a file in the `.vscode` directory named `settings.json`.
3. Add these contents to the file created in step 2:

```json
{
  "deno.enable": true
}
```

If you only use a few workspaces, it is not a big deal to do that, but if you are frequently working in new Deno workspaces, it is not a scalable solution, and it's **much** simpler to use the command palette like this:

1. <kbd>shift</kbd> + <kbd>ctrl/cmd</kbd> + <kbd>p</kbd>
2. <kbd>d</kbd><kbd>e</kbd><kbd>n</kbd><kbd>o</kbd><kbd> </kbd><kbd>e</kbd><kbd>n</kbd><kbd>Enter</kbd>

The same is true for disabling it in a workspace where it is enabled.

That is why I have labeled this issue as a regression—it removed an accessibility feature that's never in the way, but it's a huge help to anyone who used it.

**Comment by lucacasonato** [comment]
We have `Deno: Initalize Workspace Configuration` command in version 3.x. We won't implement seperate enable and disable commands.
