### ISSUE TITLE
Cached remote modules with non-default ports are not resolved

### ISSUE THREAD

**Issue by jsejcksn** [denoland/vscode_deno#171]
See https://github.com/denoland/vscode_deno/issues/24#issuecomment-649918614 for details.

Before the project switched from @justjavac's code to @axetroy's code, there was a bug where the extension did not resolve module URLs with non-default ports. This issue persists after the extension switched codebases. Previously, I tracked down the bug to `typescript-deno-plugin` and [patched it](https://github.com/justjavac/typescript-deno-plugin/pull/63), but I'm guessing it's not going to be merged into this extension now, so I'm filing this issue.

**Versions**

vscode: `1.48.2`
deno: `1.3.2`
extension: `2.0.16`

**Comment by axetroy** [comment]
https://github.com/denoland/vscode_deno/blob/84478514f2fc3ce3e930291d0228187256334a27/core/module_resolver.ts#L69-L79

PRs are welcome

**Comment by jsejcksn** [comment]
@axetroy Done.
