### ISSUE TITLE
deno.ignore setting

### ISSUE THREAD

**Issue by Vehmloewff** [denoland/vscode_deno#174]
**Is your feature request related to a problem? Please describe.**

Often I need to embed bits of a Nodejs project in my Deno project.

When `deno.enable` is `true` the Nodejs typescript files display all sorts of errors due to the differences between conventional typescript and Deno typescript.

**Describe the solution you'd like**

The best solution I can think of right now would be to add a `deno.ignore` setting to this extension.

```json
// .vscode/settings.json
{
	"deno.enable": true,
	"deno.ignore": [ "src/embeded-node-project/**/*" ]
}

**Comment by MarkTiedemann** [comment]
Another option would be to allow enabling Deno only for a specific set of files:

```json
{
    "deno.enable": [
        "src/deno/*"
    ]
}
```

**Comment by kitsonk** [comment]
This will be addressed by supporting "workspace folders" (see: #348)

Closing as redundant of that feature.
