### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jdahlborg** [denoland/vscode_deno#175]
- Issue Type: `Bug`
- Extension Name: `vscode-deno`
- Extension Version: `2.0.16`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14390,
		"activateCallTime": 1,
		"activateResolvedTime": 6039,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "denoland.vscode-deno",
				"_lower": "denoland.vscode-deno"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by lucacasonato** [comment]
What is not working? Just sending some debug output does not help us understand what the error is. Please open a new issue with an actual description of the error, along with the debug output.
