### ISSUE TITLE
Set current default version to 1.26.0

### ISSUE THREAD

**Issue by hazae41** [denoland/vscode_deno#182]
**Problem**
Versions 2.X are **broken** and unusable. People who install the latest version and expect it to work fine can't use Deno properly.

**Solution**
VSCode should install the latest **working** version, which is 1.26.0, by default. And leave 2.X versions as development versions.

**Comment by David-Else** [comment]
v2.1.2 is the latest stable full working version, 1.26 is nothing special, it is anceint and forgotten. 

2.x are not development, I suggest you file a bug report if you have a problem. There were some hiccups along the way with some recent versions, but v2.1.2 should be fantastic and fully awesome.

**Comment by lucacasonato** [comment]
If you have issues with 2.x, please open issues... the 2.x extension is working fine for me on my PC and Laptop. It is the latest stable, and 1.x is not maintained anymore.
