### ISSUE TITLE
improve Deno Language Server

### ISSUE THREAD

**Issue by axetroy** [denoland/vscode_deno#187]
The current Deno Language Server seems to work very well, but it has many improvements

### 1. Deno Language Server always starts running even `deno.enable = false`

https://github.com/denoland/vscode_deno/blob/0fa031dbf7e3dd98852512c7d746a43a31604514/client/src/extension.ts#L635-L641

even if it is not a Deno project, the `Deno Language Server` is started.

When deno.enable is changed, the LSP should be `enabled/disabled`

### 2. deno formatting is always enabled even `deno.enable = false`

ref: #101

### 3. `Deno Language Server` is a singleton even multiple workspaces have been opened

This will cause many problems, such as different workspaces and different environment variables. I think multiple LSP instances can solve these problems.

One LSP instance serves only one workspace.

This greatly simplifies the code and mental burden.

We don’t worry about what happens when an instance serves multiple workspaces

example: https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-multi-server-sample

NOTE: **Multiple instances will increase memory consumption, Average 50-70M per instance**

**Comment by David-Else** [comment]
Regarding point 2, I don't think Deno formats your code unless you tell it to?!
```
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  ```
If you tied the formatter to `deno.enable` then it would not work on non-deno code, which would be a disaster. I assume it is meant to work for all JS/TS?

**Comment by kyeotic** [comment]
@David-Else That is not the case, the deno formatter will run even without that configuration. It will run in JS files even if you have

```json
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

**Comment by David-Else** [comment]
@kyeotic Well, that is not good! I thought that bug had gone. 

I just want to make sure that we can always run the formatter without the language server running with`"editor.defaultFormatter": "denoland.vscode-deno"`. Hopefull Markdown with code blocks will be supported soon too https://github.com/denoland/deno/issues/7352

**Comment by kitsonk** [comment]
This is now stale, closing.
