### ISSUE TITLE
bug: 'ignore for this line' quickfix does not work on line 1

### ISSUE THREAD

**Issue by lucacasonato** [denoland/vscode_deno#188]
**Describe the bug**

If you try to use the `ingore 'rule' for this line` quickfix for the `deno lint` integration on the first line, this will fail with error `Illegal value for 'line'`.

**To Reproduce**

Create file:
```ts
for (;;) {}
```
Try to use the `ignore 'no-empty' for this line` quickfix on line 1.

**Expected behavior**

This should work.

**Versions**

vscode: 1.48.2
deno: 1.3.3
extension: 2.2.0

cc @axetroy

**Comment by axetroy** [comment]
Here to read the previous line of code, but the first line of code has not the previous line, this is the problem

https://github.com/denoland/vscode_deno/blob/0fa031dbf7e3dd98852512c7d746a43a31604514/client/src/extension.ts#L599-L622
