### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by FreedomGift** [denoland/vscode_deno#202]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `2.2.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\hp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by lucacasonato** [comment]
@FreedomGift You have not attached the CPU profile. Please do so as you even mentioned yourself in the issue...

**Comment by CGQAQ** [comment]
🤣

**Comment by macjabeth** [comment]
Ran into the same issue and have attached mine.

[denoland.vscode-deno-unresponsive.cpuprofile.txt](https://github.com/denoland/vscode_deno/files/5355269/denoland.vscode-deno-unresponsive.cpuprofile.txt)

**Comment by lucacasonato** [comment]
This has likely been resolved in the 3.x branch of the extension.
