### ISSUE TITLE
Support nest land

### ISSUE THREAD

**Issue by CGQAQ** [denoland/vscode_deno#208]
Add [nest.land](https://nest.land/) support to import enhancement feature

**Comment by kitsonk** [comment]
Instead of supporting a specific package repository outside of `deno.land/x`, there should be a generic interface to allow end users to specify repositories, and a convention for supplying and caching the packages/modules.  (Actually the integration to `deno.land/x` should migrate to that as well.

**Comment by CGQAQ** [comment]
> Instead of supporting a specific package repository outside of `deno.land/x`, there should be a generic interface to allow end users to specify repositories, and a convention for supplying and caching the packages/modules. (Actually the integration to `deno.land/x` should migrate to that as well.

Here is my implementation

```typescript
export type Optional<T> = T | undefined;

export interface Entry {
  type: "file" | "folder";
  value: string;
}

export interface ModContents {
  readonly update_time: string;
  readonly contents: Entry[];
}

export interface ModVersionMap {
  [key: string]: ModContents;
}

export interface ModInfo {
  readonly name: string;
  readonly description?: string;
  // this array should well sorted
  // latest version should in versions[0]
  readonly versions?: string[];
}
export type ModInfoList = ModInfo[];

export interface Registry {
  readonly REGISTRY_ID: string;
  // Allow registry don't have std module mirror
  std(): Promise<Optional<ModInfo>>;
  stdContents(version: string[]): Promise<Optional<ModVersionMap>>;
  modList(): Promise<ModInfoList>;
  modVersionList(mod: string): Promise<ModInfo>;
  modContents(mod: string, version: string[]): Promise<ModVersionMap>;
}

```

``` typescript
export const Registries: { [key: string]: Registry } = {};

Registries[DENOLAND_ID] = new DenoLand();
Registries[NESTLAND_ID] = new NestLand();

export type SupportedRegistry = keyof typeof Registries;
```

Just need to implement `Registry` interface and add to `Registries`, is enough
