### ISSUE TITLE
Support @deno_types

### ISSUE THREAD

**Issue by whinc** [denoland/vscode_deno#21]
the [@deno_types](https://deno.land/manual/getting_started/typescript#compiler-hint) directive don't work correctly in vscode type check. For example:
a.js
```javascript
export const a = 100
```

a.d.ts
```typescript
declare const a: boolean
export {a}
```

Variable `a` should has type `boolean` instead of  number literal `100` in vscode type checker.
![image](https://user-images.githubusercontent.com/5096493/81935869-e1878c00-9623-11ea-8ade-8e6c361e762d.png)

deno builtin type checker is correct when i run the program.
![image](https://user-images.githubusercontent.com/5096493/81935899-eb10f400-9623-11ea-8f18-6dc09dfdf550.png)

**Comment by justjavac** [comment]
WIP

**Comment by xcatliu** [comment]
Still report error after update vscode deno plugin version to 1.24.0

![image](https://user-images.githubusercontent.com/5453359/83401446-5be34900-a437-11ea-9abb-1fabf04b484a.png)
