### ISSUE TITLE
Being able to disable deno format (to use Prettier instead)

### ISSUE THREAD

**Issue by MaximeBernard** [denoland/vscode_deno#211]
**Is your feature request related to a problem? Please describe.**

I have a monorepo (react/node with yarn workspaces) and one package is a deno app. I use some prettier config at the root folder and I'd like to use the same settings for my deno app. 

Deno seems to be against a config file that and @lucacasonato [suggested I could use prettier instead](https://github.com/denoland/deno/issues/3827#issuecomment-692030811). 

**Describe the solution you'd like**

I'd like a way to tell my vscode to stop using `deno fmt`
   
Bonus: if I could tell the extension to use prettier instead, that would be awesome (but I understand it's way more complex and brings a lot more questions/issues that you don't want to deal with)

**Comment by lucacasonato** [comment]
Just install the Prettier extension and switch your default formatter to prettier. The deno extension doesn't force the use  of deno fmt.

**Comment by MaximeBernard** [comment]
Thank you 🙏  

Had the Prettier extension installed already but it wouldn't work and I had no idea why.

For those looking:
- Open `Command Palette...`(`Cmd` + `Shift` + `P`)
- Select `Format Document With...`
- Select `Configure Default Formatter...`
- Select `Prettier - Code formatter`

It's actually obvious once you know.

**Comment by kitsonk** [comment]
That would be a question for the prettier extension people.
