### ISSUE TITLE
v2.2.3 conflict with built-in vscode extension

### ISSUE THREAD

**Issue by aodelta** [denoland/vscode_deno#214]
### vscode built-in extension conflict with version 2.2.3

When I open an index.ts file (or whatever .ts file), the TypeScript and JavaScript Language Features built-in vscode extension can't start _(vscode.typescript-language-features)_

I tested with older versions, and they all worked

**To Reproduce**

1. Enable the vscode.typescript-language-features extension
2. Enable the denoland.vscode-deno extension
3. Reload VS Code
4. Open a .ts file

**Expected behaviour**

Make the built-in vscode extension launch properly

**Screenshots**

https://gyazo.com/ff9ba5cd7de7232a22ec5f88d96b95fb (I wanted to create a Discord bot using Denodiscord instead of discord.js (node.js), and this is a template file)

**Versions**

vscode: 1.49.0
deno: 2.2.3
extensions: denoland.vscode-deno & vscode.typescript-language-features

**Comment by lucacasonato** [comment]
you currently can not use "deno.enable: true" in a folder that also contains node code, or the extension will crash? Is this what you are experiencing?

**Comment by aodelta** [comment]
No, here are my folders: https://gyazo.com/b59617158561f91b913a6055bf349b83
I just can't use the vscode built-in extension with "deno-enable: true" with the latest version because it just can't launch properly after 5 tries, but it works with the and older version.

And I don't really know what you mean by "node-code" sorry ^^', the files with code are the one shown above, and the other which just export a variable named "config" with the "token" attribute

**Comment by lucacasonato** [comment]
What does your tsconfig look like?

**Comment by aodelta** [comment]
Ok I think you found the problem xD

In fact, I just copy & paste the tsconfig.json I used for node js because I thought it would be the same because it was about TypeScript, not the framework node.js/deno itself, but it is apparently not.

The problem might come from the "target" and "module" variable

I give you the file if you want to get it to create a kind of error message if the error occurs to another one anyway 🥇 
`
{
    "compilerOptions": {
      /* Basic Options */
      // "incremental": true,                   /* Enable incremental compilation */
      "target": "es6",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
      "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
      // "lib": [],                             /* Specify library files to be included in the compilation. */
      // "allowJs": true,                       /* Allow javascript files to be compiled. */
      // "checkJs": true,                       /* Report errors in .js files. */
      // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
      // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
      // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
      "sourceMap": true,                     /* Generates corresponding '.map' file. */
      // "outFile": "./",                       /* Concatenate and emit output to single file. */
      "outDir": "./dist/",                      /* Redirect output structure to the directory. */
      // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
      // "composite": true,                     /* Enable project compilation */
      // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
      // "removeComments": true,                /* Do not emit comments to output. */
      // "noEmit": true,                        /* Do not emit outputs. */
      // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
      // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
      // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
  
      "resolveJsonModule": true,
      /* Strict Type-Checking Options */
      "strict": false,                           /* Enable all strict type-checking options. */
      // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
      // "strictNullChecks": true,              /* Enable strict null checks. */
      // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
      // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
      // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
      // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
      // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
  
      /* Additional Checks */
      // "noUnusedLocals": true,                /* Report errors on unused locals. */
      // "noUnusedParameters": true,            /* Report errors on unused parameters. */
      // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
      // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
  
      /* Module Resolution Options */
      // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
      // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
      // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
      // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
      // "typeRoots": [],                       /* List of folders to include type definitions from. */
      // "types": [],                           /* Type declaration files to be included in compilation. */
      // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
      "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
      // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
      // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */
  
      /* Source Map Options */
      // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
      // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
      // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
      // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
  
      /* Experimental Options */
      // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
      // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  
      /* Advanced Options */
      "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
    },
  
    "include": [
      "src/**/*", "main.ts"
    ],
  
    "exclude": [
        "node_modules",
        ".vscode"
    ]
  }
`

**Comment by lucacasonato** [comment]
You don't need to specify a tsconfig for Deno. It has one built in.

It still shouldn't brutally crash like this. I'll open another issue about that.

**Comment by lucacasonato** [comment]
Actually I can't reproduce it with this tsconfig. Can you send me the contents of all of the files? (`index.ts`, `config.ts`, `.vscode/settings.json`)

**Comment by lucacasonato** [comment]
Oh nvm i managed to reproduce.
