### ISSUE TITLE
deno.land/x module list failed to cache!

### ISSUE THREAD

**Issue by macjabeth** [denoland/vscode_deno#216]
**Describe the bug**

I just installed the deno on my machine and the VSCode extension. I made sure the path variables were correctly pointing to the right spots as well, but for some reason it doesn't like me.

**To Reproduce**

1. start vscode
2. open a typescript file
3. see error pop up in bottom right

**Expected behavior**

I would expect a successful caching of the module list.

**Screenshots**

![image](https://user-images.githubusercontent.com/8473052/93371918-1b121300-f821-11ea-9feb-ac9422724f1b.png)

![image](https://user-images.githubusercontent.com/8473052/93372257-a25f8680-f821-11ea-9ada-c1516b3add86.png)

**Versions**

![image](https://user-images.githubusercontent.com/8473052/93372701-3d586080-f822-11ea-803f-2145511235c1.png)

![image](https://user-images.githubusercontent.com/8473052/93372755-552fe480-f822-11ea-8432-0e1914612626.png)

![image](https://user-images.githubusercontent.com/8473052/93373120-e30bcf80-f822-11ea-93be-6ed78f13a109.png)

**Comment by lucacasonato** [comment]
Can you access `https://api.deno.land/modules` from the browser?

**Comment by macjabeth** [comment]
> Can you access `https://api.deno.land/modules` from the browser?

Yes.

![image](https://user-images.githubusercontent.com/8473052/93484791-56b7e600-f8d0-11ea-97a3-c51b8096a77d.png)

**Comment by macjabeth** [comment]
I decided to log the error that was being thrown. This is what I got:
```json
{
  "name": "RequestError",
  "code": "SELF_SIGNED_CERT_IN_CHAIN",
  "timings": {
    "start": 1600356049469,
    "socket": 1600356049482,
    "lookup": 1600356049559,
    "connect": 1600356049586,
    "error": 1600356049646,
    "phases": {
      "wait": 13,
      "dns": 77,
      "tcp": 27,
      "total": 177
    }
  }
}
```
I'll keep looking into this, but thought I would share.

**Comment by lucacasonato** [comment]
Are you behind a corporate proxy?

**Comment by macjabeth** [comment]
> Are you behind a corporate proxy?

Yes, I should have specified I'm installing from a work laptop.

**Comment by tdillon** [comment]
Can the extension use the `DENO_CERT` environment variable if it is already set?  Otherwise, a config option would be reasonable.

**Comment by lucacasonato** [comment]
I'll investigate this today. There is a good chance our http requests don't respect proxies at the moment.

**Comment by dannybucksch** [comment]
Same for me.
I am behind a corporate proxy....this feature would be great.

thanks a lot

**Comment by kitsonk** [comment]
This should no longer be an issue with the v3 version of the extension.  If there are issues, please open a new issue.
