### ISSUE TITLE
[Feature Request] Format untitiled files

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#218]
(assuming you have set Deno to be the default format option for JS/TS)

At the moment trying to format a JS/TS file that has not been saved gets `Deno cannot format '/Untitled-1'`. Prettier can format un-saved files, it would be a nice feature for Deno.

**Comment by kitsonk** [comment]
There has been a change in behaviour with vscode, where untitled files indicate that a language should be selected.  Selecting a language, which the formatter can format, makes it a lot better then getting a situation where we have to try to format any arbitrary file.

![Cursor_and_Untitled-1_—_oak](https://user-images.githubusercontent.com/1282577/126235824-ad971800-f03c-4021-a49f-68112fa28b8f.png)

So I am going to close this suggestion, as implementing would be non-trivial and there are better solutions.
