### ISSUE TITLE
importmap using local files

### ISSUE THREAD

**Issue by btrauma8** [denoland/vscode_deno#22]
I can't get local files working using deno.importmap and the plugin. works from deno.
(deno rc1), plugin 1.28.0, windows.

![image](https://user-images.githubusercontent.com/4399964/81937213-f3801500-95b8-11ea-8c9e-174cf8e79c42.png)

**Comment by btrauma8** [comment]
btw, i found this...kinda interesting...the second one works plugin-wise, but not from deno!

        "abc1": "file://c:/junk/deno3/abc.ts",    works in deno, not in plugin
        "abc2": "c:\\junk\\deno3\\abc.ts",        works in plugin, not in deno
        "abc3": "./abc.ts"                                  works in deno, not in plugin

also, i'm now on deno 1.0.0...same problem.

**Comment by justjavac** [comment]
fixed by https://github.com/justjavac/typescript-deno-plugin/commit/bf84e5ce772105a7e8eb28c87c42dda544d38e27
