### ISSUE TITLE
Try to refactoring the typescript-deno-plugin

### ISSUE THREAD

**Issue by CGQAQ** [denoland/vscode_deno#227]
Currently, the TDP has various problems, see #199 #220 #215, and don't respect the `enable` config field until restart VSCODE or reload window.
I'm researching a way to refactoring it. After refactoring, #196 and #197 will work

**Comment by CGQAQ** [comment]
Not going to do for now

**Comment by David-Else** [comment]
@CGQAQ Thanks so much for trying!

Can't really use Deno in mixed projects until we get include/exclude, so I hope Deno LSP will appear sooner rather than later :)

**Comment by lucacasonato** [comment]
This should be resolved in the 3.x branch of the extension.
