### ISSUE TITLE
Add an options for enabling the extension only for some ts files

### ISSUE THREAD

**Issue by AliBasicCoder** [denoland/vscode_deno#228]
**Is your feature request related to a problem? Please describe.**

my problem is i have ts npm package that i need to make a deno version of it
so i need to enable deno only in one file and NOT in the HOLE folder 

**Describe the solution you'd like**

an option for making the extension only work for a given list of files

**Comment by lucacasonato** [comment]
This is currently not possible due to restrictions in TypeScript Language Server.
