### ISSUE TITLE
Extension does not work with asdf-installed deno

### ISSUE THREAD

**Issue by Nitive** [denoland/vscode_deno#231]
Hello! I run into issue with loading deno modules after switching from homebrew-installed deno to [asdf](https://github.com/asdf-vm/asdf) and [asdf-deno](https://github.com/asdf-community/asdf-deno).

I had errors like this for all my imports
![Error in vscode](https://user-images.githubusercontent.com/6770225/94133642-9a2ec900-fe69-11ea-938f-cf6d321dc9ec.png)
But could run `deno run` on files without any errors.

It was happening because asdf-deno stores deno cache in `~/.asdf/installs/deno/1.4.0/.cache/deno` but extension looking for it in `~/Library/Caches/deno` (on macOS).

The other thing is that issue started to appear not right after I switched my installation method, because deno already had all my modules cached in `~/Library/Caches/deno`. So a long time can pass before users run into problems.

I think it should be fixed on asdf-deno side (I left a comment there) https://github.com/asdf-community/asdf-deno/issues/17#issuecomment-698261897
But I also decided to create an issue here to help people find a workaround more easily.

**Workaround**
Explicitly set `DENO_DIR` in your rc file (`~/.profile`, `~/.bashrc`, `~/.zshrc`, `~/.config/fish/config.fish`, depending on your shell)
``` bash
source /usr/local/opt/asdf/asdf.fish
export DENO_DIR="$HOME/Library/Caches/deno" # macOS
# export DENO_DIR="$HOME/.cache/deno" # Linux
```

**Comment by Nitive** [comment]
I intentionally closed an issue because it's not really a problem with extension and exists just for a search purposes

**Comment by smorimoto** [comment]
Due to the current implementation of asdf-deno and vscode_deno, your current solution is correct.

**Comment by smorimoto** [comment]
Well, I'm going to change that, so the next commit should solve it.
