### ISSUE TITLE
could not find deno in path, please install deno

### ISSUE THREAD

**Issue by JSchermers** [denoland/vscode_deno#234]
I hoped for intellisence on deno commands in .ts files and .js files when installing this extension.

I'm on Ubuntu , gnome

**Steps to reproduce**

1. i created a docker container 
2. started container
3. connected vscode to docker container
4. inside container switched user, added sudo rights
5. installed deno with curl according the docs.
6. updated .bashrc for new user with export path
7.reload vscode
8. `deno` works in terminal
9. installed deno vscode extension
10 added .vscode/settings.json to root of project 
{
    "deno.enable": true
}
11. added .ts or .js file to project and tried deno. --> no intellisence, only "Could not find 'deno in your $PATH'......." at bottom right of screen

**Allready tried **
1. reinstalling extension
2. reinstalling deno under root user
3. changed settings.json to different locations

tnx for any advice or help

**Comment by lucacasonato** [comment]
you have to connect vscode after updating the .bashrc

**Comment by JSchermers** [comment]
tnx for your help. Maybe i do misunderstand you but I allready reconnected many times again. 

1. started vscode on ubuntu
2. started docker container from vscode
3. connected vscode to docker container
4. inside that vscode i added the extension

**Comment by lucacasonato** [comment]
If you open a terminal through VS Code in the container, is `deno` available there?

**Comment by JSchermers** [comment]
yes... step 7. from my steps to reproduce

**Comment by kitsonk** [comment]
@JSchermers `which deno` and `echo $PATH` from the integrated terminal within vscode please...

**Comment by JSchermers** [comment]
Hello and thx for your help. When i echo $PATH, this is the result

root@371b4a54741e:/# echo $PATH
/root/.deno/bin:/root/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by kitsonk** [comment]
And `which deno` from the integrated terminal within vscode?

**Comment by JSchermers** [comment]
root@371b4a54741e:/# which deno
/root/.deno/bin/deno

**Comment by jcc10** [comment]
I would like to add that this is not isolated to a single user. I am on Pop!_OS 20.04 which is based off the same Ubuntu version.
deno is in path and can be run by any terminal and, in fact, the terminal within vscode itself.

```
digitalkitsune@pop-os:~/github/oak_websoket_middleware$ which deno
/home/digitalkitsune/.deno/bin//deno
```

**Comment by jcc10** [comment]
Could I request a interim fix being a option to override to a manually entered path to a Deno Executable?

I would add that just in general as a backup as sometimes you may want to run a specific version of Deno as opposed to the global one and a workspace override would allow for that.

**Comment by alfredzh** [comment]
I have the same issue!
My install steps is almost same as JSchermers!

**Comment by losintikfos** [comment]
I have the same issue

**Comment by jcc10** [comment]
Seeing as @losintikfos fix works. (But don't forget to change to your home directory!) I think this may be a issue in vscode-languageserver, possibly [L422-L435 in `client/src/node/main.ts`](https://github.com/microsoft/vscode-languageserver-node/blob/7a62c5c54c626dd90ffc464f8b98564ee48f11d6/client/src/node/main.ts#L422-L435)

If someone who knows how to debug VSCode extensions could verify the path being used that would help. It may be that the `ExecutableOptions` needs to be set with the `cwd` or `env` option. (If I am reading the src correctly, I may not be. Seriously, don't trust me.)

**Comment by gilbertoalbino** [comment]
> I had the same issue. I resolved it with:
> 
> * `sudo ln -s /home/losintikfos/.deno/bin/deno /usr/bin`
> * Restart vscode.

Same solution here! Thanks 👍

**Comment by teroyks** [comment]
I have the same issue on macOS. Screenshot is from the VS Code internal terminal.

<img width="858" alt="Screenshot 2021-02-01 at 12 32 14" src="https://user-images.githubusercontent.com/2240765/106446958-92230d80-6489-11eb-8ff6-4ac4a9c1bf96.png">

**Comment by teroyks** [comment]
_Note:_ for me, the workaround is not starting VS Code “normally” (ie. from the /Applications folder or the Launchpad). When I instead navigate to my project directory in the terminal and then start VS Code with `code .` it works.

**Comment by tim-field** [comment]
Same issue, perhaps related to fish shell 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/1326910/107108503-529b5d80-689d-11eb-91de-f121e6cafc01.png">

**Comment by andreyddk** [comment]
Same problem, I use flatpak vscode. Tried install deno via script and pacman.
vscode terminal:
```
$ deno --version
deno 1.7.4 (release, x86_64-unknown-linux-gnu)
v8 9.0.123
typescript 4.1.4
```

```
echo $PATH
/home/whiteserk/.nvm/versions/node/v12.20.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by lucacasonato** [comment]
This has likely been resolved in the 3.x branch of the extension.

**Comment by rsgilbert** [comment]
It hasnt been resolved yet but the work around of using ln works

**Comment by vicary** [comment]
I still have this issue, installed Deno via Homebrew but the extension can't seem to find the executable.

I have to manually set `deno.path` in VS Code `settings.json` as a workaround.

`which deno` shows `/opt/homebrew/bin` which is already in `echo $PATH`.

I am using `oh-my-zsh` so I suspect that VS Code gives a different environment to the extension, without loading up the omz plugins? The homebrew PATH comes from `~/.zprofile` instead of `~/.zshrc` which maybe the clue here.

The contents of my `.zprofile` has only one line:
```
eval $(/opt/homebrew/bin/brew shellenv)
```

**Comment by anilf01** [comment]
In linux, I fix this issue by using this command
```shell
sudo ln -s /home/desktop-name/.deno/bin/deno /usr/local/bin/deno
```

**Comment by vixalien** [comment]
@andreyddk did you find a solution for using deno inside a flatpak VS Code?

**Comment by andreyddk** [comment]
> @andreyddk did you find a solution for using deno inside a flatpak VS Code?

Hi! Actually I dont remember exactly, but you cant try install deno via script on official site in `$HOME/.deno`, next install the Flatseal and set permissions for vscode to file system of `$HOME/.deno`

**Comment by vixalien** [comment]
Thanks. That worked! Didn't need to give the flatpak access to that
directory since it already has host access.

**Comment by CristianFigueredo** [comment]
in my case, I put the path "which deno" gives me in deno.path field in vscode's settings.json

**Comment by fulcanelly** [comment]
it's still issue
