### ISSUE TITLE
tsconfig.json's lib is not respected

### ISSUE THREAD

**Issue by jeiea** [denoland/vscode_deno#236]
**To reproduce**
`vscode/settings.json`
```
{
  "deno.enable": true
}
```
`tsconfig.json`
```
{
  "compilerOptions": {
    "noLib": true,
    "target": "ES2015",
    "module": "esnext",
    "lib": ["DOM", "ES2015"],
    "strict": true
  }
}
```
`a.ts`
```
''.replaceAll('', '');
```

**Expected behavior**

`replaceAll` should be prohibited.

**Actual behavior**

Intellisense accepts `a.ts` with no error.

**Versions**

vscode: 1.49.2 (system setup) e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
deno: 1.4.2
extension: 2.3.1
OS: Windows_NT x64 10.0.19041

**Comment by ihack2712** [comment]
Same happens for me.

vscode: 1.50.1
deno: 1.4.6
ext: 2.3.2
OS: Mac OS X 10.15.6 (Catalina)

**Comment by jon49** [comment]
Is there a work around for this? I would like to mix the DOM and Deno code and tried using version 3 but haven't figured out how to get it to work either.

The only thing that has worked for me is to do a clear separation and put Deno code into its own siloed area.

**Comment by kitsonk** [comment]
We likely won't be resolving this bug in the version 2 of the extension, but will resolve in the canary/v3 version which uses the language server built into the Deno CLI.

**Comment by ihack2712** [comment]
You can use a ts reference to the file, `/// <reference path="./don.lib.d.ts" />` worked for me ;)

**Comment by lucacasonato** [comment]
This has been resolved in the 3.x branch of the extension.

**Comment by jeiea** [comment]
@lucacasonato Could you check this issue? I just tested it against 3.1.0, but it doesn't seem to be resolved.

**Comment by lucacasonato** [comment]
What Deno version are you on? Please update to 1.8.0. (`deno upgrade`)

**Comment by jeiea** [comment]
```
>deno --version
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by lucacasonato** [comment]
Did you point vscode to the tsconfig using the deno.config option

**Comment by jeiea** [comment]
I've just inserted ` "deno.config": "./tsconfig.json"` in the first comment, but nothing changed. `"./tsconfig.json"` emitted an file not found error.

**Comment by jeiea** [comment]
Very wierd.. If I open a file which includes `/// <reference lib="dom" />` first after reloading window, there's no error in a file not having reference pragma. But if I open the file not having the pragma first, red squiggle appears regardless of tsconfig.json `lib: ['dom']`.
