### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by midgethoen** [denoland/vscode_deno#241]
### test

**Describe the bug**
- intellisense is not working 

**To Reproduce**

1. Run vscode 1.50.0 with all extensions disabled
1. install/enable vscode_deno 2.3.2
1. open folder & run "Deno: init" command
1. import remote module & try intellisense
1. import relative module & try intellisense

**Expected behavior**
- locally/relative imported modules should have intellisense working based on type information  
![image](https://user-images.githubusercontent.com/4599476/96000258-01bbb100-0e37-11eb-8ba4-fcba38d11007.png)  
![image](https://user-images.githubusercontent.com/4599476/95999775-835f0f00-0e36-11eb-8820-5075405a4e8f.png)

-  modules imported by url should have intellisense working based on type information  
![image](https://user-images.githubusercontent.com/4599476/96000026-c325f680-0e36-11eb-964d-a290f4e8eb15.png)
expected `overwrite` option to be known ([reference](https://deno.land/std@0.74.0/fs/copy.ts#L20)) 

**Versions**

vscode: 1.50.0
extension: 2.3.2
deno: 1.4.6

**Comment by midgethoen** [comment]
i noticed the "problem"-underlines with the first import later:  
![image](https://user-images.githubusercontent.com/4599476/96000951-c372c180-0e37-11eb-87fd-361ff6e051e0.png)

I don't think this was there before i attempted this clean reproduction of the error. I resolved it by running the script:

```sh
$ deno --unstable run test.ts
Check file:///home/midgethoen/projects/repository%20management/test.ts
error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'boolean'.
localModule("true");
            ~~~~~~
    at file:///home/midgethoen/projects/repository%20management/test.ts:4:13
```

**Comment by midgethoen** [comment]
Additionally, intellisense for the Deno namespace is not working:

![image](https://user-images.githubusercontent.com/4599476/96001555-717e6b80-0e38-11eb-8f49-fd536b5b50c4.png)

**Comment by midgethoen** [comment]
FYI: when i switch to the [deprecated extension](https://github.com/denoland/vscode_deno), everything seems to work

**Comment by lucacasonato** [comment]
Did you restart VS Code after running `deno: Init`=

**Comment by midgethoen** [comment]
Probably, I’ve been trying to get it to work for a while. I’ll try tuning it off and on again today

**Comment by lucacasonato** [comment]
This has likely been resolved in the 3.x branch of the extension.
