### ISSUE TITLE
Unable to find 'deno' in the PATH on macOS and even Windows with the latest version of the plugin

### ISSUE THREAD

**Issue by oumarbarry** [denoland/vscode_deno#243]
Hello.

Here is the shown error :    Could not find `deno` in your $PATH. Please install `deno`, then restart the extension.

![Screen Shot 2020-10-14 at 16 16 35](https://user-images.githubusercontent.com/55247230/96017024-01241a00-0e39-11eb-9f3b-374830fad075.png)

But deno is exported in my .zshrc file.

![Screen Shot 2020-10-14 at 16 12 13](https://user-images.githubusercontent.com/55247230/96016326-22383b00-0e38-11eb-9324-ab4652fcfad6.png)

I have already worked with this 'deno' vscode-plugin on both windows and mac in August, and everything worked well.

**Comment by MarkTiedemann** [comment]
> But deno is exported in my .zshrc file.

Are you starting `code` from `zsh`?
