### ISSUE TITLE
Extension not respecting deno.enable on startup

### ISSUE THREAD

**Issue by tristan957** [denoland/vscode_deno#244]
**Describe the bug**

The extension is not respecting `deno.enable` on startup. Because it ignores the setting, for some ungodly reason, the extension attempts to start the language server even when I open up a fresh window. Mind you I have never used Deno, but I have the extension installed. Deno is not installled on my system. Because I don't have Deno in my PATH, the extension sends a notification that I don't have deno installed so it can't startup the language server.

**To Reproduce**

1. deno.enable to false
2. startup a vscode window (no folders open)
3. notice that the language server is starting up in the status bar
4. notice that you get an error notification when the extension cannot find Deno in your path (this is really just a sypmtom of 3)

**Expected behavior**

Not start the language server when I am not in a deno project or file

**Versions**

vscode: 1.50.1
deno: not installed
extension: 2.3.2

**Comment by lucacasonato** [comment]
This has likely been resolved in the 3.x branch of the extension.
