### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by saberap** [denoland/vscode_deno#245]
Hi everyone,
When I tried to install the Deno extension, after I installed vscdoe showed me an error that 'Unexpected end of JSON input'.
and the Deno extension didn't work for me. but when I installed [Deprecated] Deno it worked.

Vscode version : 1.50.1
OS : Linux x64 5.4.0-52generic snap
Deno version : 1.4.2
Extension version : 2.3.2 

What's the problem?

**Comment by lucacasonato** [comment]
Did you run the `deno: Init` VS Code command in your project?

**Comment by saberap** [comment]
No, 
but I used `sudo snap install deno.` 
First I removed it with  `sudo snap remove deno‍‍`
then I put this to the end of `~/.bashrc `  :
`export DENO_INSTALL="/home/$USER/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"`
And I restarted my computer.
After these things, I installed the Deno extension and it's worked well.

**Comment by lucacasonato** [comment]
Nothing actionable here, so I am closing this.
