### ISSUE TITLE
Allow configuring lib option from tsconfig.json

### ISSUE THREAD

**Issue by renatoathaydes** [denoland/vscode_deno#247]
Currently trying to develop a Deno app for the browser. I configure the Deno bundler via `tsconfig.json` so that I can compile with a command like this:

```
deno bundle --unstable -c tsconfig.json src/index.ts dist/bundle.js
```

This will work even when I use the DOM API because in `tsconfig.json`, I have declared:

```json
{
  "lib": ["DOM", "ESNext"]
}
```

**Describe the solution you'd like**

It would be nice if the `-c` option Deno accepts could be also specified to this plugin via the `.vscode/settings.json` file:

```json
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.bundle.config": "tsconfig.json",
}
```

If I don't enable Deno support in my project, VSCode doesn't show errors when using browser APIs, so I guess the solution to this problem should be rather easy: just let VSCode assume the DOM API is available in case `tsconfig.json` (as specified in the `.vscode/settings.json` file) includes the "DOM" lib?

**Comment by renatoathaydes** [comment]
Here's the error VSCode reports when I access `document`:

```
Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.ts(2584)
```

Despite `tsconfig.json` having `DOM` in `lib` already (again, it only errors when Deno support is enabled).

**Comment by renatoathaydes** [comment]
I think this ticket may be a duplicate of https://github.com/denoland/vscode_deno/issues/236

Sorry if it's the same issue (I'm not entirely sure, the other ticket seems to be the opposite: the user gets no error when it should?).

**Comment by kitsonk** [comment]
This should work with v3.x of the extension.
