### ISSUE TITLE
VS Code Deno extension crashed?

### ISSUE THREAD

**Issue by callionica** [denoland/vscode_deno#248]
Was using VS Code as normal with no errors
Suddenly noticed errors listed in VS Code's Problems pane for working code
Looked at status bar at bottom of VS Code window and the Deno version was no longer listed, only the Typescript version, indicating that the Deno extension had crashed or been unloaded somehow?? 

Restarting VS Code fixed the issue.

The only recent change I made was installing Deno 1.50 yesterday, but had restarted VS Code multiple times since then and things seemed to be working.

Sorry for lack of repro.

If it helps I was in a multi project workspace in VS Code and had recently been viewing diffs and switching between files in the editor. Think I was in diff view when the problem started.

**Versions**

vscode: 1.50.1

extension: 2.3.2

deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

VS CODE:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

**Comment by RA80533** [comment]
Having the same issue. It crashes the built-in TypeScript server every file change.

**Comment by RA80533** [comment]
Related https://github.com/denoland/vscode_deno/issues/220

**Comment by lucacasonato** [comment]
This should be resolved in the 3.x branch of the extension.

**Comment by nielsbom** [comment]
I still had this problem with Deno 1.6. 
Upgrading to 1.7.5 and restarting VSCode fixed the problem.
