### ISSUE TITLE
Go to definition on cached dependancy results in non-syntax highlighted code

### ISSUE THREAD

**Issue by MisterJimson** [denoland/vscode_deno#25]
Not sure if this extension is at fault for this, but hopefully this can be improved in some way.

When using VS Code's "Go to definition" on a type that comes from the cache, the resulting file opened in VS Code does not have syntax highlighting.

Example
```ts
import { serve } from "https://deno.land/std/http/server.ts";

const body = "Hello World\n";

const s = serve({ port: 8000 });
for await (const req of s) {
  req.respond({ body });
}
```

Right click > Go to Definition on `serve`

It correctly opens the file, but the file name does not end in `ts`, which is why I am assuming its not highlighted.

<img width="825" alt="Screen Shot 2020-05-14 at 1 47 50 PM" src="https://user-images.githubusercontent.com/7351329/81967842-85077b00-95e9-11ea-8984-a6516df1b89b.png">

**Comment by justjavac** [comment]
fixed by #16
