### ISSUE TITLE
Invalid Version: nightly 2020.10.31 (2a36e2f)

### ISSUE THREAD

**Issue by lrowe** [denoland/vscode_deno#252]
### test

**Describe the bug**

Running vscode with a nightly deno build from https://github.com/maximousblk/deno_nightly I see the error
```
Invalid Version: nightly 2020.10.31 (2a36e2f)
Source: Deno (Extension)
```

**To Reproduce**

1. Install deno nightly build following instructions at https://github.com/maximousblk/deno_nightly
2. Follow the printed instructions to add its install location to your path.
3. Restart vscode (quit, then run code from a terminal window with the updated path)
4. Error appears shortly after

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/290859/97772918-86c9ea00-1b08-11eb-9fe8-3bb05e69dfd7.png)

**Versions**

vscode: Version: 1.50.1
deno: nightly 2020.10.31 (2a36e2f)
extension: v2.3.2

**Comment by lucacasonato** [comment]
The extension doesn't know how to deal with these nightly versions. I'll take a look.

**Comment by RA80533** [comment]
/cc @lucacasonato 

It's an exception thrown by the semver package here:

https://github.com/denoland/vscode_deno/blob/0e1ad0a7afa5230174f0f6fa94c3eb3a4732ff75/server/src/deno.ts#L68-L70

At the very least, that should be surrounded by a try-catch. Additional logic would be necessary to handle non-semver-conforming versions, however.

**Comment by lucacasonato** [comment]
This should be resolved in the 3.x branch of the extension.
