### ISSUE TITLE
Replace the deprecated vscode package

### ISSUE THREAD

**Issue by RA80533** [denoland/vscode_deno#254]
> This package is deprecated in favor of @types/vscode and vscode-test. For more information please read: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest

The package is currently used to install the typings for VS Code. It can be swapped with the @types/vscode package with no additional tooling.

**Comment by lucacasonato** [comment]
This should be resolved in the 3.x branch of the extension.
