### ISSUE TITLE
deno.unstable setting is true by default when using the command palette entry "deno: Init"

### ISSUE THREAD

**Issue by jsejcksn** [denoland/vscode_deno#257]
When selecting the VS Code command palette entry "deno: Init", the resulting data is added to `.vscode/settings.json`:

```jsonc
{
  "deno.enable": true,
  "deno.lint": false, // depends on selection
  "deno.unstable": true // <-- this line
}
```

This is undesirable because unstable features should be opt-in, NOT the default.

**To Reproduce**

1. <kbd>shift</kbd> + <kbd>cmd</kbd>/<kbd>ctrl</kbd> + <kbd>p</kbd>
2. <kbd>d</kbd> <kbd>e</kbd> <kbd>n</kbd> <kbd>o</kbd> <kbd>i</kbd> <kbd>n</kbd> <kbd>i</kbd> <kbd>t</kbd> <kbd>Enter</kbd>
3. Make a choice about using deno lint
4. (Resulting data is added to file)

**Expected behavior**

`deno.unstable` to be `false`, but, instead it is `true`

**Versions**

vscode: `1.51.0`
deno: `1.5.1`
extension: `2.3.2`

**Comment by RA80533** [comment]
This doesn't seem ideal.

According to the README:

> NOTE: Since `deno lint` is still an experimental feature, you need to set `deno.unstable = true` in your VS Code settings. This function may change in the future.

Maybe it would be best for an additional input pane to appear informing the user about `unstable` and asking if they would like to enable it?

**Comment by lucacasonato** [comment]
This has been resolved in the 3.x branch of the extension.
