### ISSUE TITLE
Mention extension name in readme

### ISSUE THREAD

**Issue by dpyzo0o** [denoland/vscode_deno#26]
Which one is the right one? I suggest to at least mention it in the readme.

![Screen Shot 2020-05-15 at 11 39 01](https://user-images.githubusercontent.com/24768249/82008985-b2fbc680-96a0-11ea-91c9-ac72c2d4ea8c.png)

**Comment by hastebrot** [comment]
Yes. And please update `Releases.md` with version number, release date and list of changes. And a new git tag on every release.

I currently scroll through the latest commits to find out what changed. There are commits like `bump typescript-deno-plugin@1.25.0 (#23)` so I also have to browse to the plugin to see what was changed in it.

**Comment by Nothing-Works** [comment]
I agree that atm it's very confusing from vscode market place. Hoping this will be fixed/clean up soon. And even on the [official doc](https://deno.land/manual/getting_started/setup_your_environment#editors-and-ides), it's suggesting a deprecated plugin.

**Comment by justjavac** [comment]
https://github.com/denoland/deno/pull/5292

**Comment by lucacasonato** [comment]
Use `denoland.vscode-deno` extension from VS Code Marketplace.
