### ISSUE TITLE
Cannot find name deno

### ISSUE THREAD

**Issue by esquevin** [denoland/vscode_deno#260]
### test

**Describe the bug**

I get a  "Cannot find name deno". Most of my types fallback to `any`, I cannot use the goto feature as well.

**To Reproduce**

I've attached a video showcasing my issue.
Deno is enabled, I've disabled all but the deno extension.

I got the "Cannot find name Deno" error.

But when I downgrade the deno extension, and then reinstall the last version, I can see for a brief moment Deno being recognized as a namespace.

So the deno extension seems to work, but to be overriden by something else… I'm clueless about what since I've disabled every extension.

**Expected behavior**

I'd expect the deno namespace to be recognized, types to work, as well as the goto feature

**Screenshots**

[Cannot find name deno.mp4.zip](https://github.com/denoland/vscode_deno/files/5581863/Cannot.find.name.deno.mp4.zip)

**Versions**

vscode: 1.51.1
deno: 1.4.0
extension: 2.3.3

**Comment by lucacasonato** [comment]
What does your workspace look like?

**Comment by esquevin** [comment]
I may have found the origin of the issue while trying to create a minimal repo that'd show it: https://github.com/esquevin/vscode_deno_error

It seems that the `compilerOptions` in the tsconfig.json file breaks the deno extension.

**Comment by mvolkmann** [comment]
Is having a `tsconfig.json` file required in order for the intellisense to be aware of the global variable `Deno`?
If so, what must be in it?

**Comment by lucacasonato** [comment]
No. A tsconfig is not required.

**Comment by mvolkmann** [comment]
After installing the Deno VS Code extension, I added this to my settings.json file:

```json
  "deno.enable": true,
  "deno.import_intellisense_origins": {
    "https://deno.land": true,
    "https://deno.land/x": true
  },
  "deno.lint": true,
  "deno.unstable": true,
```

When I open a `.ts` file I see "Deno 1.5.3" at the bottom of the VS Code window indicating that the extension is activated.
When I type "Deno." I don't get any intellisense, but I do get intellisense for imports suggesting "https://deno.land".
Isn't it supposed to offer hints for "Deno."?
What other configuration could I be missing?

**Comment by c-dinkel** [comment]
I'm having the same issue with Deno 1.7.2 and TypeScript 4.1.2

**Comment by ebebbington** [comment]
@mvolkmann @c-dinkel Can you restart your ide if you haven't done so already?

**Comment by kitsonk** [comment]
Because of the substantial changes to v3 of this extension and Deno 1.7.5 I am closing this as stale. Please try again and report a new issue if there are problems.
