### ISSUE TITLE
Turn on Deno VSCode for Certain File Pattern

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/vscode_deno#264]
**Is your feature request related to a problem? Please describe.**

Some projects use denoify to convert NPM packages to Deno modules.

**Describe the solution you'd like**

It would be great if it was possible to enable the Deno VSCode thing for files that match a certain pattern or something so I don't get a ton of Typescript errors when importing with a `.ts` file extension with modules ending in `.deno.ts`.

**Comment by lucacasonato** [comment]
This is currently not possible due to limitations in VS Code typescript server. See https://github.com/denoland/vscode_deno/pull/196.

It might be possible in the future once we use our own `deno lsp`. See https://github.com/denoland/deno/pull/8515.

**Comment by borekb** [comment]
Is this something this extension can do on its own or does it also need support from the (built-in) TS/JS language server of VSCode?

I'm trying the Canary version of this extension (v3) that utilizes `deno lsp` already but there are still a lot of errors in our monorepo that mixes Node.js and Deno projects.

**Comment by lucacasonato** [comment]
Covered by https://github.com/denoland/vscode_deno/issues/314

**Comment by borekb** [comment]
@lucacasonato I'm trying Deno 1.10.1 + extension [v3.4.0](https://github.com/denoland/vscode_deno/releases/tag/3.4.0) right now and I'm not sure if I'm using it right but the experience is not great. Overall, I think that this issue which is about _file patterns_ (vs. workspace folders which #314 uses) is still valid and could be reopened.

First, we don't use multi-root workspaces and are trying to avoid them – they add complexity, things like file picker (cmd-p) or search or the SCM panel are complicated with workspace-related concepts that we simply don't need in a monorepo we work in.

Anyway, I've tried creating this workspace setup just to test things:

```
.
├── .vscode/
│   └── settings.json         ← our current settings.json
├── nodejs-project-a/
│   └── index.ts
├── nodejs-project-b/
│   └── index.ts
├── deno-scripts/
│   ├── .vscode/
│   │   └── settings.js       ← new one, with `deno.enable = true`
│   └── deno.ts
└── test.code-workspace
```

This silenced errors in `deno.ts` but I don't get any autocompletion anyway:

<img width="824" alt="Screen Shot 2021-05-12 at 11 15 36" src="https://user-images.githubusercontent.com/101152/117950396-6c709480-b313-11eb-8109-80bf327ab664.png">

The Output panel doesn't indicate anything wrong:

<img width="998" alt="Screen Shot 2021-05-12 at 11 17 03" src="https://user-images.githubusercontent.com/101152/117950560-99bd4280-b313-11eb-99ae-b2e28203c876.png">

Even if this worked, workspaces have downsides for us as noted above and we'd love to be able to do something like this:

```js
// Plain .vscode/settings.json in our repo root:
{
  "deno.enableForPaths": ["deno-scripts"]
}
```

_(Not a great name, just trying to illustrate the point.)_

Would this be possible? Would help us a lot.
