### ISSUE TITLE
can't run deno fmt

### ISSUE THREAD

**Issue by mvolkmann** [denoland/vscode_deno#267]
When I try to format a file I get "Extension 'denoland.vscode-deno' is configured as formatter but not available."

**To Reproduce**

1. Create `.vscode/settings.json` in project directory containing:

```json
{
  "deno.enable": true,
  "deno.import_intellisense_origins": {
    "https://deno.land": true,
    "https://deno.land/x": true
  },
  "deno.lint": true,
  "deno.unstable": true,
  "[javascript]": {
    "editor.defaultFormatter": "denoland.vscode-deno",
  },
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno",
  }
}
```
2. Open a `.ts` file in the project.
3. Select "Format Document" from the Command Palette.
4. See the error message.

**Expected behavior**

It should format the file using `deno fmt`.

**Versions**

vscode: 1.51.1
deno: 1.5.4
extension: 2.3.3

**Comment by lucacasonato** [comment]
This should be resolved in the 3.x branch of the extension.
