### ISSUE TITLE
Tilda is not recognized in `deno.import_map` settings

### ISSUE THREAD

**Issue by al6x** [denoland/vscode_deno#268]
VSCode fails to recognize import map `~/.import_map.json` when I change it to `/Users/alex/.import_map.json` it works.

**Is your feature request related to a problem? Please describe.**

I would like to use same, universal location for import map config.

**Describe the solution you'd like**

Path with tilda in VSCode Deno setting should work

```
{
  "deno.enable": true,
  "deno.unstable": true,
  "deno.import_map": "~/.import_map.json",
}
```

**Comment by jasikpark** [comment]
Does using `$HOME/.import_map.json` work for you?

**Comment by al6x** [comment]
No, still doesn't recognize it.

**Comment by lucacasonato** [comment]
This is expected as paths in the settings file need to be absolute. `~` would usually be expanded to `/home/user` by your shell.
