### ISSUE TITLE
Extension didn’t initialize as expected

### ISSUE THREAD

**Issue by zaydek** [denoland/vscode_deno#269]
I noticed when installing the VSCode extension it flat out didn’t work.

Adding:

```
// .vscode/settings.json
{
	"deno.enable": true
}
```

Seemed to help but ultimately it wasn’t until I hard restarted VSCode that everything started to work as expected.

I recommend marking in the readme (for the extension page) to emphasize that VSCode should be restarted in order for changes to take effect. In my experience, this is not necessary for _most_ plugins, so I this misstep can easily lead to confusion for devs.

**Comment by lucacasonato** [comment]
This has been resolved in the 3.x branch of the extension.
