### ISSUE TITLE
Better Auto-Imports

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/vscode_deno#27]
One of the problem with importing files at the moment is that it does not do it properly. For example here we can see that when I auto-import this file it will create:

```ts
import { cache } from "utils/cache";
```
![image](https://user-images.githubusercontent.com/23035000/82051528-09104000-9688-11ea-8e54-2f859b912744.png)

However the actual path is `./utils/cache.ts`
It is missing the `./` and the ending of `.ts`
![image](https://user-images.githubusercontent.com/23035000/82051545-14636b80-9688-11ea-9999-09dc822b1820.png)

![image](https://user-images.githubusercontent.com/23035000/82051386-c0588700-9687-11ea-9281-4837222aa49e.png)

**Note:** These were all working on Axetroys extension but after switching over this is have quite a few issues. 

Thank you

**Comment by Skillz4Killz** [comment]
Here is another issues related to imports. When you have cached code and you want to jump through it to maybe easily read source code, you get a lot of issues.

![image](https://user-images.githubusercontent.com/23035000/82077082-cad94780-96ac-11ea-9227-0ca044764f30.png)

The main issue here is that these imports become `any` since they arent seen as valid imports. This makes all the typings below it useless which trickles down to end users by causing types being imported from deno libs as broken.

![image](https://user-images.githubusercontent.com/23035000/82077148-ecd2ca00-96ac-11ea-8342-41d38db2df44.png)

But message is not supposed to be any 
![image](https://user-images.githubusercontent.com/23035000/82077197-04aa4e00-96ad-11ea-90aa-264e3f246b41.png)
![image](https://user-images.githubusercontent.com/23035000/82077272-23104980-96ad-11ea-8ed4-5c76ee8053fe.png)
![image](https://user-images.githubusercontent.com/23035000/82077278-29062a80-96ad-11ea-9ad8-031e7ce2c9c9.png)

**Comment by Skillz4Killz** [comment]
Another issue noted with imports:

![image](https://user-images.githubusercontent.com/23035000/82077308-37544680-96ad-11ea-8ff8-645666881067.png)

![image](https://user-images.githubusercontent.com/23035000/82077342-42a77200-96ad-11ea-9d21-b8f126934cd9.png)


What it should be doing:
![image](https://user-images.githubusercontent.com/23035000/82077378-4cc97080-96ad-11ea-8a95-8efd3a30fa16.png)

**Comment by justjavac** [comment]
@Skillz4Killz I have found a solution for this bug, I will fix it later. Thank you.
