### ISSUE TITLE
Absolute path import from node_modules

### ISSUE THREAD

**Issue by losintikfos** [denoland/vscode_deno#271]
**Issue**

Currently `Deno Language Server` expects all imports to be in the form of URL or relative path. This as a result ignores projects _e.g._ `VueJS` which has dependencies installed through `npm` or `pnpm` held in `node_modules` .

These dependency imports are flagged with errors.

**Actual behavior**

```shell
import livereload from 'rollup-plugin-livereload'
[..]
```

Generate Error:

> Import` module "rollup-plugin-livereload" must be a relative path or remote HTTP URL.Deno Language Server(1000)

**Expected behavior**

`Deno Language Server` should avoid flagging errors for relative imports if `nodule_modules` is present.

**Comment by lucacasonato** [comment]
Deno does not support `node_modules`. Why do you have the Deno extension enabled in a node project?

**Comment by losintikfos** [comment]
I am working with vue and some of the modules are held in node_modules. I may probably have to disable deno and use node in the meantime.

**Comment by lucacasonato** [comment]
You are using both Deno and Node in the same VS Code workspace?

**Comment by losintikfos** [comment]
Yes I have both Node and Deno installed global on the host. Do you think disabling Node will help?

**Comment by ebebbington** [comment]
@losintikfos having node installed, and using node in a workspace are different things

**Comment by losintikfos** [comment]
> @losintikfos having node installed, and using node in a workspace are different things

Totally! ideally "Deno Language Server" shouldn't deprive other dependencies and engines. It would be awesome if it works unrestricted to allow the developer the freedom of setup. The marriage setup is possible - if deno runtime or VSCode environment accept there's a possibility of other runtime environments - this will give developers a huge adaptation freedom to operate. But for such freedom to occur deno and language server needs to be _slightly_ agnostic.

**Comment by lucacasonato** [comment]
There is nothing actionable for us here, as i think your issue is covered by https://github.com/denoland/vscode_deno/issues/314.
