### ISSUE TITLE
Why can't you enter TypeScript in the console?

### ISSUE THREAD

**Issue by schuelermine** [denoland/vscode_deno#277]
AFAIK, deno intends to be a runtime for TypeScript. But, when I open deno interactively, I can't type something like
```typescript
const x: number = 27
```

Why?

**Comment by bartlomieju** [comment]
That's because Deno doesn't support TypeScript in REPL yet: https://github.com/denoland/deno/issues/1158

**Comment by schuelermine** [comment]
Thanks for the info! Good to know this is already know.
