### ISSUE TITLE
Github README and VSCode README are not up to date w/ each other

### ISSUE THREAD

**Issue by jasikpark** [denoland/vscode_deno#282]
**Describe the bug**
I was told by the extension README to simply add 
```json
{
  "deno.enable": true
}
```

to my `.vscode/settings.json`, but this repo says to just run `deno: init` from the vscode command prompt.

I only discovered this because I was getting wild and weird autocomplete when I typed too fast for the extension, though now I am having no problems with 

```json
{
  "deno.enable": true,
  "deno.unstable": true,
  "deno.lint": true
}
```
**To Reproduce**

Open the README for the extension from within vscode / open https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno

**Expected behavior**

The instructions in this repo's README should match the extension's README

**Screenshots**

**Versions**

vscode: 1.51.1
deno: 1.5.4
extension: 2.3.3

**Comment by kitsonk** [comment]
As mentioned in the README on GitHub...

![denoland_vscode_deno__Visual_Studio_Code_plugin_for_Deno](https://user-images.githubusercontent.com/1282577/101584492-e71a4880-3a31-11eb-832c-cd1c390eef09.png)

The version of the extension you have installed is accurate for the version you have installed.  The version of the for the extension you have installed is the v2 branch: https://github.com/denoland/vscode_deno/tree/v2

**Comment by jasikpark** [comment]
Hmmmm ok - is that on the vscode marketplace :sweat_smile:

**Comment by kitsonk** [comment]
As noted in the README... it is under Deno Canary: https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno-canary.  It requires Deno 1.6 (or later for future readers) installed and available in your path.  It is highly experimental at the moment.
