### ISSUE TITLE
2x hover over results in canary 0.0.6 on non deno files

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#290]
The extension is meant to be turned off unless it is enabled, but instead, it is corrupting output with duplicates unless the extension is disabled (Linux, latest stable VS Code):

![Screenshot from 2020-12-28 23-52-33](https://user-images.githubusercontent.com/12832280/103249757-a0e94280-4968-11eb-8658-f0e705f8be3c.png)
![Screenshot from 2020-12-28 23-52-52](https://user-images.githubusercontent.com/12832280/103249758-a21a6f80-4968-11eb-82cf-9a4b9991d906.png)

**Comment by kitsonk** [comment]
What version of Deno do you have installed?

**Comment by David-Else** [comment]
I had `1.6.1`, updated to `1.6.2`, and fixed it. Sorry to waste your time.
