### ISSUE TITLE
Support Test configuration template

### ISSUE THREAD

**Issue by domoritz** [denoland/vscode_deno#294]
**Is your feature request related to a problem? Please describe.**

I would like to debug tests in VSCode. 

**Describe the solution you'd like**

I would like to have a launch configuration templaye that supports running tests. Something along the lines of. 

```
{
    "type": "node",
    "request": "launch",
    "name": "Run Tests",
    "runtimeExecutable": "deno",
    "cwd": "${workspaceFolder}",
    "runtimeArgs": [
        "test",
        "--inspect-brk=127.0.0.1:9229",
    ],
    "port": 9229,
    "console": "integratedTerminal"
}
```

When I use the config above, I get this error `Could not load source '[...]/std@0.83.0/fmt/colors.ts': Unable to retrieve source content.`

**Comment by kitsonk** [comment]
I ran the following in vscode 1.59 and Deno 1.13 and it worked as expected:

```json
  {
      "type": "pwa-node",
      "request": "launch",
      "name": "Run Tests",
      "runtimeExecutable": "deno",
      "cwd": "${workspaceFolder}",
      "runtimeArgs": [
        "test",
        "--inspect-brk=127.0.0.1:9229",
      ],
      "port": 9229,
      "console": "integratedTerminal"
    }
```

There may have been issues in the past, but this does not seem to be a problem anymore.
