### ISSUE TITLE
VSCode's debugger cannot debug Deno

### ISSUE THREAD

**Issue by lirannl** [denoland/vscode_deno#300]
**Describe the bug**
I can no longer debug Deno using the extension's default configuration
**To Reproduce**
1. Install vscode 1.52.1
2. Try to debug using the Deno runtime (with the extension's default launch configuration)

**Expected behavior**
The program should run, stopping at breakpoints.

**Screenshots**

![](https://cdn.discordapp.com/attachments/684911491035430919/797296253225402408/unknown.png)

**Versions**

vscode: 1.52.1
deno: 1.6.3
extension: 2.3.3

**Comment by karasamil** [comment]
I have the same issue. Downgrading to 1.6.1 solves the problem.

**Comment by Soremwar** [comment]
Same here

**Comment by lucacasonato** [comment]
This should be fixed in canary.
