### ISSUE TITLE
The img src links in the extension page are broken

### ISSUE THREAD

**Issue by Khobalt** [denoland/vscode_deno#305]
The images are missing on the extension's landing page:
https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
![image](https://user-images.githubusercontent.com/848683/105562519-7f217800-5ce8-11eb-9750-f42f52c4526f.png)

It seems as though they used to be hosted in this repository in the v2 branch:
https://github.com/denoland/vscode_deno/raw/master/screenshot/screenshot.gif

**Comment by Khobalt** [comment]
Perhaps consider updating to links like these:
https://github.com/denoland/vscode_deno/blob/v2/screenshot/screenshot.gif

**Comment by lucacasonato** [comment]
This is resolved in version 3.x of the extension.
