### ISSUE TITLE
Extension does not recognize a relative import while using an import map

### ISSUE THREAD

**Issue by romdotdog** [denoland/vscode_deno#306]
**Describe the bug**
 When I use the import map mentioned below and attempt to make a relative import, the vscode plugin doesn't recognize the module.

* `deno lint` passes without errors.
* `deno run` compiles and runs successfully.

**To Reproduce**
> /import/main.ts
```ts
import { constant } from "./constants.ts";

console.log(constant)
```

> /import/constants.ts
```ts
export const constant = "Hello, world!";
```

> /import_map.json
```json
{
  "imports": {
    "/": "./import/",
    "./": "./"
  }
}
```

> /.vscode/settings.json
```json
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.lint": true,
    "deno.import_map": "./import_map.json"
}
```

Error happens on line 1 of `/imports/main.ts`
`Could not find module "C:\Users\rom\Documents\deno-issue\constants.ts" locally.`

**Expected behavior**

I expected `./constants.ts` to be recognized and imported in the linter.

**Screenshots**

![Screenshot](https://i.imgur.com/MRaWTKu.png)

**Versions**

vscode: 1.52.1
deno: 1.7.0
extension: 2.3.3

**Comment by lucacasonato** [comment]
This is resolved in version 3.x of the extension.
