### ISSUE TITLE
Deno extension & incorrect "include" path in tsconfig.json cause TypeScript language service to crash

### ISSUE THREAD

**Issue by tomchen** [denoland/vscode_deno#309]
**Describe the bug**

VS Code's built-in TypeScript language service crashes when Deno VS Code extension is installed (and enabled via `{"deno.enable": true}` in `vscode/settings.json`), and incorrect "include" path is set in tsconfig.json.

**To Reproduce**

File tree:

```
|   index.ts
|   package.json
|   tsconfig.json
|   yarn.lock
|   
+---.vscode
|       settings.json
|       
\---node_modules
    |   .yarn-integrity
    |   
    |   ......
```

index.ts is empty

package.json:

```
{
  "name": "a",
  "devDependencies": {
    "typescript": "^4.1.3"
  }
}
```

Execute `yarn` to install the typescript devDependency

tsconfig.json:

```
{
  "include": ["src/**/*"]
}
```

(`include` is set incorrectly, src folder doesn't exist)

/vscode/settings.json:

```
{
  "deno.enable": true
}
```

(Deno extension is enabled via /vscode/settings.json. If it is enabled globally (via the first entry in the Settings), the problem seems to disappear)

Open the project folder with VS Code, and TypeScript language service will crash, showing:

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

**Expected behavior**

Maybe do not crash TypeScript language service, instead, maybe show a "include path in tsconfig.json is set incorrectly" notification?

**Versions**

vscode: 1.52.1
deno: 1.6.3
deno vscode extension: at least 2.3.0 - 2.3.3 all have this problem
other non built-in vscode extensions are all disabled
os: win10

**Comment by lucacasonato** [comment]
This is resolved in version 3.x of the extension.
