### ISSUE TITLE
Semicolon added on paste

### ISSUE THREAD

**Issue by lgarron** [denoland/vscode_deno#313]
This is a re-filed version of issue #102. This is happening for me on every single paste, and is a rather discouraging experience for someone trying to see if Deno can match the normal TypeScript development experience. 😢

> I'm still having this issue. Deno plugin is 2.3.3 and VSCode is 1.52.1.

I'm also encountering this. Every single paste is appended with an extra semicolon, which also makes the formatter freak out and pop up an error message every time.

<img width="969" alt="Screen Shot 2021-01-31 at 17 19 35" src="https://user-images.githubusercontent.com/248078/106404756-9814e200-63e8-11eb-8553-d71e2aa7f5cc.png">

(My instinct is to press the "X" to make the message go away, which takes me to the `OUTPUT` panel. I always have to click back to `TERMINAL` manually.)

macOS 10.15.7
VSCode Version: 1.52.1
Deno extension version 2.3.3

> deno --version
deno 1.7.1 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3

**Comment by bartlomieju** [comment]
I believe this has now been fixed internally in Deno. Please let me know if the issue persists.
