### ISSUE TITLE
local cache file is referenced instead of external location on autocomplete

### ISSUE THREAD

**Issue by WhatzGames** [denoland/vscode_deno#320]
### local cache file is referenced instead of external location on autocomplete
After i fetch a module (ctrl + .) and try to use autocomplete, the local cache file is referenced inside of the file instead of the remote location

**To Reproduce**
1. go into a file with a reference to an external module
2. fetch the module
3. go into another file and use autocomplete to use something from the very same module

**Expected behavior**

The remote location to be displayed/referenced inside the file

**Screenshots**

![grafik](https://user-images.githubusercontent.com/9288008/107282048-c8005d00-6a5a-11eb-9f7f-a627351bb33d.png)
![grafik](https://user-images.githubusercontent.com/9288008/107282088-d2225b80-6a5a-11eb-9181-b84f8416d9cd.png)
![grafik](https://user-images.githubusercontent.com/9288008/107284546-45799c80-6a5e-11eb-96ca-1640307ca7d8.png)
![grafik](https://user-images.githubusercontent.com/9288008/107282341-1f063200-6a5b-11eb-9ea9-34647645f5f7.png)
![grafik](https://user-images.githubusercontent.com/9288008/107284325-ea47aa00-6a5d-11eb-868d-190a42ee0778.png)

**Versions**

vscode: 1.53
deno: 1.7.2
extension: Deno, SQLTools, SQLTools Postgresql/Redshift Driver

**Comment by lucacasonato** [comment]
This does not happen with the new extension based on `deno lsp` anymore (`Deno (Canary)` on the VSC marketplace).

**Comment by lucacasonato** [comment]
This is resolved in version 3.x of the extension.
