### ISSUE TITLE
Type is not linted when using snake case

### ISSUE THREAD

**Issue by lc-kondo** [denoland/vscode_deno#321]
### Type is not linted when using snake case

**Describe the bug**

<img width="995" alt="スクリーンショット 2021-02-09 19 55 18" src="https://user-images.githubusercontent.com/11921019/107390158-c3ab7100-6b3a-11eb-9220-5942e9d5d405.png">

<img width="995" alt="スクリーンショット 2021-02-09 19 55 34" src="https://user-images.githubusercontent.com/11921019/107390187-c9a15200-6b3a-11eb-8579-e29c027e4dcf.png">

**Expected behavior**

Behaves the same as deno lint when I have to use snake case.

**Versions**

vscode: 1.53.0
deno: 1.7.1

**Comment by lc-kondo** [comment]
v1.7.4 seems to fix it, so close the issue.

**Comment by kitsonk** [comment]
I am unable to reproduce in v3.2.0 and Deno 1.8.3:

![_Extension_Development_Host__-_snake_case_ts_—_vs_test](https://user-images.githubusercontent.com/1282577/113646128-880ccd80-96cb-11eb-84a7-9394936ca02a.png)

If it is still a problem, please provide your `.vscode/settings.json` and the output of the _Deno Language Server_ panel in vscode.

**Comment by lc-kondo** [comment]
I checked this issue again, but it didn't reproduce.
Thank you for your help!

**Versions**

vscode_deno: v3.4.0
deno: 1.9.0
