### ISSUE TITLE
"deno.ns" is not accepted value in lib in tsconfig.json 

### ISSUE THREAD

**Issue by searchableguy** [denoland/vscode_deno#326]
![vscode screenshot showing error when adding deno.ns in lib](https://user-images.githubusercontent.com/73341821/107854548-8b5da880-6e42-11eb-9970-96cd42f25f09.png)

It errors when I try to add it in tsconfig.json on vscode with deno canary plugin (v0.10)

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["esnext", "dom", "deno.ns"]
  }
}
```

**Comment by kitsonk** [comment]
It is an error that comes from the built in TypeScript in vscode. It has no impact on the operation of the file in Deno or using the plugin.

I am not sure how we can suppress that error, but we can look into it.

**Comment by stexxart** [comment]
It's not ideal, but I managed to suppress the error by using a different filename for the config e.g. `deno.tsconfig.json`

**Comment by SnoCold** [comment]
Same thing happening for dom.asynciterable, not sure if it is related
<img width="1552" alt="Screenshot 2021-07-14 at 12 07 19 AM" src="https://user-images.githubusercontent.com/15018167/125506861-b56c688e-a717-4f49-ad4f-883b2c204d5b.png">

**Comment by kitsonk** [comment]
It is the same root issue.

**Comment by nayeemrmn** [comment]
I investigated this previously, IIRC it was not something we could fix with the TS server plugin API. Now we use `deno.json` and no one has been bit by this since. Closing for now

**Comment by tkafka** [comment]
I am totally bit by it, as I have a project with multiple services, that is migrating from ts to deno, and I would like some of the files to mention deno without ts linter going berserk :/.
