### ISSUE TITLE
Extension commands do not work until js/ts file has been opened

### ISSUE THREAD

**Issue by lucacasonato** [denoland/vscode_deno#334]
**Describe the bug**

The VS Code actions on the command palette provided by this extension do not work (error out) until the user has opened a JS/TS file in the workspace.

**To Reproduce**

1. Open a VS Code workspace with the extension disabled (no files open)
2. Open command palette and run `Deno: Welcome`
3. See this error: `Command 'Deno: Welcome' resulted in an error (command 'deno.welcome' not found)`

**Expected behavior**

The `Deno: Welcome` and `Deno: Initialize Workspace Configuration` options should always work, and all other commands should only be present in the command palette if the lsp has been started and is ready to receive commands.

**Versions**

vscode: 1.53.2
deno: deno 1.7.4
extension: 3.0.1

**Comment by kitsonk** [comment]
I will check if there is a way to activate the extension in more general scenarios.
