### ISSUE TITLE
Update import map name to reflect conventional usage

### ISSUE THREAD

**Issue by MichaelCurrin** [denoland/vscode_deno#338]
### test

**Describe the bug**

The extension recommends `import-map.json` with a **dash**, in a few places.

It would be preferable to recommend `import_map.json` with an **underscore**, to match the Deno docs - [Import maps](https://deno.land/manual/linking_to_external_code/import_maps).

This is not a big deal, but I am fan of consistency. I'd rather encourage users to use the same convention as in the official Deno docs. And avoid someone overlooking a hyphen and an underscore and scratching their head at results.

**To Reproduce**

This affects someone reading the help text / docs in README.md.

Also, when editing the settings, start editing the import map field and use the auto-fill feature, or wait for the help text to pop up.

> The file path to an import map. This is the equivalent to using `--import-map` on the command line

**Expected behavior**

All messaging in the settings help and  the docs should to `import_map.json` as the first option.

**Screenshots**

Deno docs:

<img width="486" alt="docs" src="https://user-images.githubusercontent.com/18750745/108601832-5653d780-73a7-11eb-83cb-c3ac22e184e9.png">

Hover:

<img width="961" alt="hover" src="https://user-images.githubusercontent.com/18750745/108601834-59e75e80-73a7-11eb-9c15-2c1d042112bf.png">

Autofill

<img width="567" alt="autofill" src="https://user-images.githubusercontent.com/18750745/108601837-5bb12200-73a7-11eb-9a95-5e632cceab4e.png">

Search for affected areas: [q=import-map](https://github.com/denoland/vscode_deno/search?q=import-map)

**Versions**

vscode: not relevant
deno: 1.7 but not relevant
extension: v3.0.1

**Comment by MichaelCurrin** [comment]
Thanks.

**Comment by kitsonk** [comment]
A PR adjusting this would be accepted.

**Comment by MichaelCurrin** [comment]
Thanks for the quick response and PR.
