### ISSUE TITLE
Lots of deno-ts errors when using lib "dom"

### ISSUE THREAD

**Issue by bxantus** [denoland/vscode_deno#341]
**Describe the bug**
I'm using deno to help create a client side web app, using typescript.
Since the 3.0.1 update of the extension, I get lots of deno-ts reported issues for types in the `dom` library, like:
```
Cannot find name 'HTMLCanvasElement'.
```
I configured the extension to use the same `tsconfig.json` file as the `deno bundle` command, but it didn't help.

**To Reproduce**
Here's my tsconfig.json file:
```
{
    "compilerOptions": {
        "lib": ["esnext", "dom"],
        "jsx": "react",
        "jsxFactory": "h",
        "inlineSourceMap": true,
        "noImplicitAny": false,
        "strictNullChecks": false
    }
}
```

1. Use any of dom types in a .ts or .tsx file
2. Activate the extencion (open a .ts, .tsx file)

When using the deno bundle command, I get no errors:
```
deno bundle --config src/tsconfig.json src/myApp.ts --unstable --watch out/bundle.js
```

**Expected behavior**

No errors reported for missing dom types. Code complete, go to definition for dom types should work.

**Versions**

vscode: 1.53.2
deno: 1.7.1
extension: 3.0.1

**Comment by kitsonk** [comment]
What is your `deno.config` setting for the workspace?

Just like the command line, the extension does not automatically notice `tsconfig.json` files. (note the config option in the README: https://github.com/denoland/vscode_deno#configuration)

**Comment by lucacasonato** [comment]
Update your Deno version to 1.7.5. This has been fixed.

**Comment by bxantus** [comment]
Thanks!
The 1.7.5 upgrade fixed this issue
