### ISSUE TITLE
Rename Releases.md to CHANGELOG.md

### ISSUE THREAD

**Issue by bxantus** [denoland/vscode_deno#342]
**Is your feature request related to a problem? Please describe.**

It would be beneficial for this project to use a changelog.
When new updates arrive, users can check what's new, what has changed, what steps are necessary to ensure the correct working of the extension.

**Describe the solution you'd like**

Create a `CHANGELOG.md` file next to `README.md` and update it at least when new releases are created.
vscode will automatically show the changes next to extension's documentation.

You can use [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) for format.
Here's the changelog for one of my own extensions: https://github.com/bxantus/mdoc/blob/master/CHANGELOG.md

**Comment by lucacasonato** [comment]
We have a Releases.md file: https://github.com/denoland/vscode_deno/blob/main/Releases.md

**Comment by kitsonk** [comment]
@lucacasonato but if we moved it do CHANGELOG.md it would appear as part of the extension documentation, which makes it worth considering in my opinion.

<img width="330" alt="Extension__Code_Spell_Checker_—_deno" src="https://user-images.githubusercontent.com/1282577/108705458-7c24dc00-7561-11eb-873a-1b89f36ca1c2.png">
