### ISSUE TITLE
Allow editing of files in cache

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/vscode_deno#345]
**Describe the bug**
When you hold CMD + click on a function, it opens a READ ONLY mode where you can not edit anything. This makes it really difficult to debug.

This used to be a really cool advantage of Deno over Node that you could debug third party code so much easier. Deno has also always stated that deps code is "your" code and thats why it all runs in the same configs with tsconfig and such. Deps aren't treated differently. Yet when I jump to the code, I can no longer edit it.

This was an amazing way to debug libs code without having to fork, push, pull, change and repeat for each and every console.log

**To Reproduce**

When you hold CMD + click on a function, it opens a READ ONLY mode where you can not edit anything. This makes it really difficult to debug.

**Expected behavior**

Open it in non-read only like before this recent update.

**Screenshots**

![image](https://user-images.githubusercontent.com/23035000/108875920-add28d00-75cb-11eb-936d-352cdba37d51.png)

**Versions**

vscode: Latest stable
deno 1.7.5 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4
extension: Latest stable

**Comment by kitsonk** [comment]
Files in the cache should be treated as read only from an editor perspective, as they represent remote modules, or in the case of data urls, decoded specifiers.

It was a problem with the previous editor that it allowed editing of modules in the cache. Editing files in the cache is a very dangerous behaviour, and I am personally don't think it is a good idea to encourage that.  You don't edit files in your browsers cache.

That being said, it might be worth considering allowing a command to open up the cached source file, but I don't think it should be the default behaviour.

**Comment by somebody1234** [comment]
Note that IIRC you can edit source files in chrome at least. It gets rid of it... eventually, not sure when.
Regradless, I think that it is a Very Bad Idea to edit files in cache, ever. If anything, I'd prefer the ability to copy a module in the cache to a location of your choosing; since I'd imagine most projects use deps.ts or similar it'd simply be a matter of changing a single path

**Comment by vsDizzy** [comment]
Then what is the best approach to edit/mock third party .ts file? Also I'd like to have possibility to search in/navigate to these files as far as they're part of the project.

**Comment by kitsonk** [comment]
Using an import map.

**Comment by kitsonk** [comment]
I think this causes a lot more challenges/problems than it would in solving problems.  Substituting remote modules for a local one should be accomplished via an import map. The cache should be opaque to everyone, and I don't think we should encourage anyone to edit files in the cache, it causes all sorts of problems (like cached build files having invalid hashes).
