### ISSUE TITLE
Launching server using command deno failed.

### ISSUE THREAD

**Issue by sinyo-matu** [denoland/vscode_deno#349]
Hi I'm new to Deno. When I installed Deno extension on my vscode and open a .ts file, 
instantly I got this error:
`[Error - 9:44:52 PM] Starting client failed
Launching server using command deno failed.`
from Deno Language Server output.
And my Deno CLI works with no problem.
 Can I get some help?

**Comment by lucacasonato** [comment]
What platform are you on? Is Deno in your path?

**Comment by sinyo-matu** [comment]
Thanks for your reply.
> What platform are you on? Is Deno in your path?

macOS Big Sur 11.2.1 with arm64 processor. 
Deno is in my path.

**Comment by Soremwar** [comment]
@sinyo-matu What is the output of `deno --version`?

In order to use the Deno Language Server, you must use Deno 1.6 or greater

**Comment by sinyo-matu** [comment]
> @sinyo-matu What is the output of `deno --version`?
> 
> In order to use the Deno Language Server, you must use Deno 1.6 or greater

@Soremwar below is the output of deno --version:
`deno 1.7.5 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4`

**Comment by sinyo-matu** [comment]
Oh.. Seems like I am using x86_64 distribution of Deno instead of aarch64. I will try aarch64

**Comment by sinyo-matu** [comment]
Very appreciate your help. 
after I changed to aarch64 distribution. It works.

**Comment by sinyo-matu** [comment]
Sorry for my hasty behavior. I have to reopen this issue.
The same problem happens now, even use `deno 1.7.5 (release, aarch64-apple-darwin)`
**my problem  is :**

> When I installed Deno extension on my vscode and open a .ts file,
> instantly I got this error:
> `[Error - 9:44:52 PM] Starting client failed Launching server using command deno failed.`
> from Deno Language Server output.

**platform :** 
macOS Big Sur 11.2.1 with arm64 processor, use vscode-insiders

**versions**
```
deno 1.7.5 (release, aarch64-apple-darwin)
v8 9.0.123
typescript 4.1.4
```

**Comment by lucacasonato** [comment]
Is it actually the same error, or is it a different error?

**Comment by kitsonk** [comment]
And what is the output of `which deno` in the terminal within vscode?

**Comment by sinyo-matu** [comment]
> Is it actually the same error, or is it a different error?

@lucacasonato it's the same error


> And what is the output of `which deno` in the terminal within vscode?

@kitsonk   
`/Users/user/.deno/bin/deno`

**Comment by joppe** [comment]
I was struggling with this issue too. Creating a symlink in `/usr/local/bin` fixed it.

**Comment by sinyo-matu** [comment]
@joppe thanks.


> I was struggling with this issue too. Creating a symlink in `/usr/local/bin` fixed it.

this seems like doesn't work for me. I created a symlink in `/usr/local/bin` for `User/user/.deno/bin/deno`, 
hence `which deno`'s output was `usr/local/bin/deno` in the terminal within vscode.
but same error still happened for me.

**Comment by sinyo-matu** [comment]
Setting `deno.path` the deno executable's path fixed it. 
but the executable path really in my environment path.

**Comment by kitsonk** [comment]
Yeah, I don't understand why sometimes VSCode can't seem to resolve that, but there have been a few reports.  So I am not sure we can fix it, but as you state, the new `deno.path` setting (in v3.1.0 and later) should work, so I am going to close this issue.

**Comment by lkiii** [comment]
I can confirm this happened in my case also. I am using wls (`Linux DESKTOP-aaa 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`) ubuntu inside windows.

After adding the path to `deno.path` it started working:
```
Starting Deno language server...
  version: 1.8.1 (release, x86_64-unknown-linux-gnu)
Connected to "Visual Studio Code" 1.54.3
language server initialized
Server ready.
```
