### ISSUE TITLE
Output spam when working with a CSS file

### ISSUE THREAD

**Issue by LukeChannings** [denoland/vscode_deno#356]
When working with a CSS file, the plugin spams the following message to the console, causing the focus to continuously jump to the output window (even if closed):

```
Error processing TypeScript request: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///Users/luke/Developer/moviematch/web/app/src/components/AutoSuggestInput.css", old_length: 811, old_version: "1614806827118", version: "1614809394004" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getReferencesAtPosition (deno:cli/tsc/00_typescript.js:149911:13)
[Error - 10:10:24 PM] Request codeLens/resolve failed.
  Message: Internal error
  Code: -32603 
```

I've attached the complete log: [log.txt](https://github.com/denoland/vscode_deno/files/6079563/log.txt)

**Expected behaviour**

The extension should ignore files that it can't handle.

**Versions**

vscode: VSCodium 1.53.2
deno: 1.8.0
extension: 3.1.0

**Comment by kitsonk** [comment]
I assume you have some sort of `import * as css "AutoSuggestInput.css"` in your application?  How are you doing that with a Deno related project, as we don't allow imports of CSS in Deno.

**Comment by LukeChannings** [comment]
Hey @kitsonk 

I've structured it so the frontend is colocated in the same repository (it's [here](https://github.com/LukeChannings/moviematch) if you want more detail). 

I structured the source based on [Standard Go Project Layout](https://github.com/golang-standards/project-layout), so:

- `{internal,cmd}/` is all Deno code (and the import map is in `config/import_map.json`
- `web/` is a React web app with imports using Snowpack CDN directly with ESM, so Deno cache can import the TS definitions

I just switched from the Deno Canary extension and started experiencing this issue, it seems like 3.x can't handle "go to definition" for web anymore...

**Comment by kitsonk** [comment]
We can fix the bug, but you need workspace folders support, which will allow you to only enable Deno for certain folders of your workspace.  That is going to be a bit longer.

**Comment by LukeChannings** [comment]
Hey @kitsonk 

I've been thinking about this a little bit, and I'm not sure workspace folders will actually solve my problems (although it is absolutely valuable).

The UI code I have depends on ESM CDNs and imports code with fully qualified paths (e.g. `../components/Avatar.tsx`).
So far this extension is the only one that:

a) supports imports including the extension (tsc errors on this, and it looks like configuring it *not to* is not possible right now)
b) supports actually fetching TypeScript definitions for CDN imports (Using `?dts` in Skypack sends the `X-TypeScript-Types` header Deno cache needs)

I'm so very tired of NPM (and `snowpack add` isn't a great alternative because now I need a `package.json` for Skypack dev dependencies *and* a `snowpack.deps.json`). I've been using vanilla [`esbuild`](https://esbuild.github.io) and Deno, and it's been a pretty good experience (recent extension bugs notwithstanding).

I know this is a bit of a niche (experimental) architecture, and it might not be on your radar, but it's been a pretty great experience not worrying about installing (or uninstalling) dependencies.

**Comment by LukeChannings** [comment]
This is resolved with the latest Deno + extension.
