### ISSUE TITLE
Highlight lack of support for Prettier (and possibly other third-party formatters)

### ISSUE THREAD

**Issue by nrwinner** [denoland/vscode_deno#360]
**Is your feature request related to a problem? Please describe.**

This extension doesn't seem to play well with the Prettier formatter. I had the Prettier extension installed globally and I was routinely losing type information related to inheritance. Disabling Prettier and switching to the Deno formatter seems to have resolved the issue. I didn't think to disable Prettier until I noticed the pattern of typings lost on format.

**Describe the solution you'd like**

Should there be some mention of this in the extension installation directions? I can't be the only person to have been frustrated by this. I would suggest adding something like "Switch workspace formatter to the Deno formatter" to the installation directions to avoid confusion.

**Comment by lucacasonato** [comment]
What exactly is the issue? Prettier extension works perfectly fine for me side by side with `deno fmt`.

**Comment by nrwinner** [comment]
@lucacasonato I'm having trouble replicating now. I was able to replicate several times before posting, but I've since restarted vscode and the issue no longer seems to be related to Prettier.
