### ISSUE TITLE
Working with executable scripts that have extension-less filenames

### ISSUE THREAD

**Issue by wsmd** [denoland/vscode_deno#37]
Hi @justjavac - thank you for your work on `vscode-deno`!

I encountered a couple of issues related to executable scripts.

### 1. Auto detection of Deno executable scripts (without .ts file extension)

This is more of a suggestion for `vscode-deno` (however, the 2nd point below is directly related to this and seems like an issue).

It might be a good addition to this extension if it can recognize executable scripts (especially .ts extension-less ones) as possible Deno scripts.

For example, let's say I have some Deno executable scripts (without a `.ts` extension)

```
.
└── bin
   ├── setup
   ├── build
   └── deploy
```

And the content of those scripts looks something like this:

```ts
#! /usr/bin/env deno run --allow-read --allow-write

import * as fs from "https://deno.land/std/fs/mod.ts";
import * as path from "https://deno.land/std/path/mod.ts";

// ...
```

Currently, when I open such files in VS Code, they show up as `plaintext`.

If I have `vscode-deno` installed, it would be nice if it automatically switches the file language to `typescript`. This can be done by scanning the first line of the document - for example:

```ts
function setTextDocumentLanguageByFirstline(document: vscode.TextDocument) {
  if (document.lineAt(0).text.match(/^\#!.*\bdeno\b/)) {
    await vscode.languages.setTextDocumentLanguage(document, 'typescript');
  }
}

vscode.workspace.textDocuments.forEach(setTextDocumentLanguageByFirstline);
vscode.workspace.onDidOpenTextDocument(setTextDocumentLanguageByFirstline);
```

Worth mentioning that VSCode already does something like this with Node (and a plenty of other languages)! If I create a file without an extension and the first line in the file is `#! /usr/bin/env node`, VSCode automatically sets the language to `javascript`.

### 2. Deno features are not enabled when changing the language mode from Plain Text to TypeScript

Now, dealing with the same files above, when I try to manually change the language of a given script from `plaintext` to `typescript`, that does not seem to trigger the Deno Language Server/Service for those files.

It seems that Deno specific features are only available if the file has `.ts` extension in its filename. Axetroy's implementation, on the other hand, works with extension-less filenames after changing the language manually from `plaintext` to `typescript`.

**Comment by kitsonk** [comment]
This is more complicated than it sounds, as the extension does not get visibility of types of documents it doesn't support (like `plaintext`).

The easiest way to support this is to click on the `Plain Text` file type in the status bar and select the `TypeScript` file type.  Once that is done, it behaves exactly as you would expect it.

While it isn't the most elegant solution, it is the most practical solution.  Respectfully closing.
