### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rdazvd** [denoland/vscode_deno#382]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.2.0`
- OS Version: `Linux x64 5.11.7-200.fc33.x86_64` (Fedora 33)
- VSCode version: `1.54.3`

[denoland.vscode-deno-unresponsive.cpuprofile.txt](https://github.com/denoland/vscode_deno/files/6239382/denoland.vscode-deno-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kitsonk** [comment]
Could you please provide the version of Deno, the vscode settings for `deno.*` and any output from the _Deno Language Server_ output.

**Comment by rdazvd** [comment]
I've been repeatedly uninstalling/reinstalling both Deno and the Deno vscode extension trying to reproduce this error, to no avail. After installing then manually adding the required paths to `~/.bashrc`, I successfully intialized vscode and the DLS without any errors (and without modifying any vscode settings). It seems to me that this issue is not directly related to Deno. Sorry for the inconvenience.

If this information is still of any worth, the installed Deno version is 1.8.3, and the Deno vscode extension is 3.2.0. The json for the vscode workspace settings follows below:

```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "workbench.settings.editor": "json"
}
```
Successful DLS output:
```
Starting Deno language server...
  version: 1.8.3 (release, x86_64-unknown-linux-gnu)
Connected to "Visual Studio Code" 1.54.3
language server initialized
Server ready.
```
