### ISSUE TITLE
Bug: Weird path resolving

### ISSUE THREAD

**Issue by MierenManz** [denoland/vscode_deno#386]
### Weird path resolving

**Describe the bug**

The extention resolves the relative path but not exactly how it should be

**To Reproduce**

use deno v1.8.3 and above with extention version 3.2.0

**Expected behavior**

resolve the path to `./utils` and not the path deno came up with.
The path that deno came up with is good but only for this pc

**Video**
https://i.gyazo.com/456594d4f6651aa4bb19117f70208c4f.mp4

**Versions**

vscode: 1.55.0
deno: 1.8.3 & 1.8.3+2c52c0a
extension: 3.2.0

**Comment by kitsonk** [comment]
I think this is related to denoland/deno#9744

**Comment by kitsonk** [comment]
I have checked https://github.com/denoland/deno/pull/10034 with this bug and it fixes this one too.
