### ISSUE TITLE
[deno-canary] Property 'serveHttp' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by ynwd** [denoland/vscode_deno#387]
Property 'serveHttp' does not exist on type 'typeof Deno'

<img width="479" alt="Screen Shot 2021-04-12 at 17 08 07" src="https://user-images.githubusercontent.com/10122431/114378202-ae41da00-9bb1-11eb-9c1c-2659ff8f0d1c.png">

**To Reproduce**
1. Update deno to the latest canary
2. Copy https://github.com/denoland/deno/blob/main/cli/bench/deno_http_native.js
3. Paste to vscode

**Comment by lucacasonato** [comment]
Set the `deno.unstable` setting to true. `serveHttp` is unstable.

**Comment by lucacasonato** [comment]
You also might need to restart VS Code after updating Deno.

**Comment by ynwd** [comment]
> You also might need to restart VS Code after updating Deno.

but there is still an error: `Property 'core' does not exist on type 'typeof Deno'`

<img width="468" alt="Screen Shot 2021-04-12 at 17 39 10" src="https://user-images.githubusercontent.com/10122431/114382082-25796d00-9bb6-11eb-9594-6f4507afb0b7.png">

**Comment by bartlomieju** [comment]
`Deno.core` is not a public interface. Use `TextEncoder` instead.

**Comment by kitsonk** [comment]
As mentioned `Deno.core` is not a public API.
