### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Pherwerz** [denoland/vscode_deno#389]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\fawaz\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by lucacasonato** [comment]
You did not attach the CPU profile like it says in the issue.
