### ISSUE TITLE
vscode_deno shows errors when working with typescript files in node

### ISSUE THREAD

**Issue by trentjones21** [denoland/vscode_deno#39]
After installing vscode_deno, all of my node typescript files had errors like
```
import express from "express"; // cannot find module 'express'
```
Even though express was installed and in my node_modules folder.  Uninstalling vscode_deno fixes the problem.

**Comment by wsmd** [comment]
@trentjones21 `vscode_deno` does not currently distinguish between a regular Node/TypeScript project and a Deno project (there isn't really an easy way to determine that). Therefore, you need to set `deno.enabled` to `false` in the workspace setting.

```json
{
  "deno.enabled": false
}
```

See https://github.com/denoland/vscode_deno#configuration

**Comment by egoist** [comment]
Is there a way to manually enable/disable this extension for a directory/file? A lot of people would like to use Deno in an existing Node.js/webpack project.

**Comment by justjavac** [comment]
@egoist Deno and Node.js are too [different](https://github.com/denoland/vscode_deno/issues/17#issuecomment-628457462), there is no very good way to support both.

But we are also trying some methods, such as:

## vs code config for extension

```json
{
    "deno.include": ["src/deno/**/*"],
    "deno.exclude": ["node_modules", "**/*.spec.ts"]
}
```

## tsconfig for [typescript-deno-plugin](https://www.npmjs.com/package/typescript-deno-plugin)

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-deno-plugin",
        "include": ["src/deno/**/*"],
        "exclude": ["node_modules", "**/*.spec.ts"]
      }
    ]
  },
  "include": ["src/node/**/*"]
}
```

**Comment by egoist** [comment]
@justjavac awesome, that's exactly what I want 👏

**Comment by lucacasonato** [comment]
Should be resolved in version 3.x of the extension.

**Comment by danger-ahead** [comment]
`deno.include` and `deno.exclude` seems to be outdated.

This works for me:
```json
{
   "deno.enable": true,
   "deno.enablePaths": ["supabase/functions/"],
}
```
**`deno.enable` enables it for the full workspace.**
**Whereas if you enable `deno.enablePaths`, `deno.enable` is ignored and only enables deno in the selected paths.**
