### ISSUE TITLE
LSP doesn't automatically start when vscode starts

### ISSUE THREAD

**Issue by MierenManz** [denoland/vscode_deno#391]
**Describe the bug**
The lsp doesn't want to start with extention v3.3.0 eventho it works fine on v3.2.0

**To Reproduce**
1. upgrade deno
2. update extention
3. restart vsc

**Expected behavior**
the lsp would start

**Config**
```json
{
  "deno.enable": true,
  "deno.lint": true
}
```

**Versions**

vscode: 1.55.2
deno: 1.9.0 release
extension: 3.3.0

**Comment by kitsonk** [comment]
What do you mean it doesn't start?  You get some sort of error message?

The extension never activates until you have a file open in your editor (like a `.ts` or `.js` file) open in your editor.

**Comment by MierenManz** [comment]
well, the extension doesn't seem to activate even when I have a `.ts` file open.
I'll upload a small video to youtube showing what I mean. It will be up a few minutes

**Comment by MierenManz** [comment]
https://www.youtube.com/watch?v=x1vSsvd-xOI this is the video link
I hope this shows the problem

**Comment by MierenManz** [comment]
also, pressing F1 and then restarting it manually does seem to work fine

**Comment by kitsonk** [comment]
There should be a `Deno Language Server` drop down under the `OUTPUT` tab in the terminal section.  What gets logged there when you are on version 3.3.0?

Also are you using WSL, and how did you install Deno?

**Comment by MierenManz** [comment]
The `deno language server` was not in the drop down. So no output. I have wsl installed but I don't use it and I installed the first version of deno via the PS script and every other update via `deno upgrade`

**Comment by MierenManz** [comment]
Closing this issue, it was one of my settings that created this issue for me

I am really sorry for the inconvenience
