### ISSUE TITLE
Syntax for "deno.suggest.imports.hosts" (Rename property?)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/vscode_deno#395]
[The documentation](https://github.com/denoland/vscode_deno/blob/8ed3af98cbc52aa04dc68807936a644317041394/docs/ImportCompletions.md#configuration) states this:

> ### Configuration
> 
> Settings for configuring registries for auto completions:
> 
> - `deno.suggest.imports.hosts` - These are the _origins_ that are configured to
>   provide import completions. The target host needs to support Deno import
>   completions (detailed below). The value is an object where the key is the host
>   and the value is if it is enabled or not. For example:
> 
>   ```json
>   {
>     "deno.suggest.imports.hosts": {
>       "https://deno.land/": true
>     }
>   }
>   ```

However, I'm confused about the host value in the example, because it not a valid `host`. It is also not a valid `origin` because it ends in a `/` (which would also be invalid for a host — it is part of the path[name]).

Here are references for juxtaposing those components of a `URL` (they include links to the specs):

- [`host`](https://developer.mozilla.org/en-US/docs/Web/API/URL/host)
- [`hostname`](https://developer.mozilla.org/en-US/docs/Web/API/URL/hostname)
- [`origin`](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin)
- [`pathname`](https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname)

So here are my questions:

1. Is the slash simply a typo in the documentation?
2. Should each key of that property be valid `host`, `hostname`, or `origin` (or some other type)?

If the values should be hostnames or origins, then I think the property should reflect that by being renamed. e.g. `deno.suggest.imports.hostnames` or `deno.suggest.imports.origins`

**Comment by kitsonk** [comment]
While it might not be 100% correct, it was the form used in the version 2.0 of the extension, and it is documented, and there are lots of people who have it configured.  I don't think the naming causes confusion, and if there is any confusion, it is documented.  Respectfully declined.
