### ISSUE TITLE
"deno.suggest.imports.hosts" should work with import maps

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/vscode_deno#399]
I import map `"std/": "https://deno.land/std@0.93.0/",`, but import suggestions don't work with this.

![image](https://user-images.githubusercontent.com/65446343/115479885-bd4d1a00-a28c-11eb-9974-ccf28a75f65f.png)
![image](https://user-images.githubusercontent.com/65446343/115479909-cb9b3600-a28c-11eb-9a2c-9b8f89723a44.png)

**Comment by kitsonk** [comment]
Duplicate of #393
