### ISSUE TITLE
Unclear how to indicate tsconfig to plugin

### ISSUE THREAD

**Issue by Ragzouken** [denoland/vscode_deno#40]
I'm using a tsconfig.json to add "DOM" to the lib compilerOptions for typescript, and running `deno bundle -c tsconfig.json whatever.ts`. I can't see any way to get the plugin to acknowledge the existing of the DOM lib though. Is this supported?

**Comment by makoven** [comment]
@Ragzouken 
There is an option in the configurator ("deno.tsconfig"), but it doesn’t seem to work.

**Comment by TTSKarlsson** [comment]
I also have this problem, can someone confirm that the deno.tsconfig setting doesn't work, or if we're just doing it wrong?

**Comment by justjavac** [comment]
I will fix it

**Comment by TTSKarlsson** [comment]
@Ragzouken , unrelated to actually setting the tsconfig.json but related to your "dom" problem that you wanted to solve. I got it working by introducing a triple slash reference.
```ts
/// <reference lib="dom" />
document.getElementById("foo");
```

**Comment by lucacasonato** [comment]
The extension will automatically pick up any extensions at the root of the project called `tsconfig.json`. If you need an option to make this configurable, please open an issue.
