### ISSUE TITLE
tagged template not imported but not error

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/vscode_deno#405]
a.ts
```ts
function c(a: TemplateStringsArray, ...b: string[]) {}
```
b.ts
```ts
c``
```

vscode shows now errors but this is invalid code as it's not imported.

**Comment by kitsonk** [comment]
This is a TypeScript limitation (microsoft/TypeScript#18232) and there is no control Deno or Deno extension has over it.  While Deno only deals with ES Modules, the TypeScript type checker will treat files without any imports or exports as conventional scripts, which means they share the same global namespace, just as if you used them as scripts in a browser.

**Comment by KotlinIsland** [comment]
@kitsonk Could there be a lint rule that could alert users to this bizarre behaviour?

**Comment by kitsonk** [comment]
I am not sure what the lint rule would be, and it only applies to editing code in an editor, as this won't occur on the CLI, because the CLI only deals with modules.

**Comment by KotlinIsland** [comment]
Something like "warning, this file doesn't have any imports/exports and is therefore falsely considered global"
