### ISSUE TITLE
I got "Failed to load configuration file" when set "deno.config":"./tsconfig.json"

### ISSUE THREAD

**Issue by kyaruary** [denoland/vscode_deno#413]
here is my .vscode/setting.json
```
{
    "deno.enable": true,
    "deno.unstable": true,
    "typescript.validate.enable": false,
    "javascript.validate.enable": false,
    "deno.lint": true,
    "deno.path": "/usr/local/bin/deno",
    "deno.config": "./tsconfig.json",
}
```

If there is no deno.config everything is fine。

An error was reported when I tried to use DOM and configure deno.config。

My Deno version is 1.10.1 & The plugin's version is 3.4.0.

is there any suggestion for me : ( tks

**Comment by newtack** [comment]
We have the same issue as original poster

**Comment by kitsonk** [comment]
@bartlomieju any ideas? I will look into it later, but likely related to the config file refactor.

**Comment by bartlomieju** [comment]
Most likely https://github.com/denoland/deno/issues/10619 which will be fixed by https://github.com/denoland/deno/pull/10620

**Comment by bartlomieju** [comment]
I'm gonna close this issue as fix has already landed in `main` branch of Deno and will be released next week in `1.10.2`

**Comment by kyaruary** [comment]
@bartlomieju 
there is no error any more since deno@1.10.2.
however, i got an error "can not find name deno" when i use "deno.config".
something wrong ?

**Comment by lucacasonato** [comment]
> @bartlomieju
> there is no error any more since deno@1.10.2.
> however, i got an error "can not find name deno" when i use "deno.config".
> something wrong ?

What does your tsconfig file look like?

**Comment by kyaruary** [comment]
like this
```
{
    "compilerOptions": {
        "lib": ["DOM", "ESNext"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}

```

**Comment by kitsonk** [comment]
That is "working as designed"... try:

```json
{
    "compilerOptions": {
        "lib": ["DOM", "ESNext", "deno.ns" ],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

**Comment by kyaruary** [comment]
> That is "working as designed"... try:
> 
> ```json
> {
>     "compilerOptions": {
>         "lib": ["DOM", "ESNext", "deno.ns" ],
>         "experimentalDecorators": true,
>         "emitDecoratorMetadata": true
>     }
> }
> ```

thks, it'ok : )
