### ISSUE TITLE
Inherited Class Properties Not Recognized

### ISSUE THREAD

**Issue by Clive-Ward-Cron** [denoland/vscode_deno#421]
I'm trying to find the clearest way to explain this.

I'm having an issue with the visual feedback that I'm getting for linting with the vscode_deno extension.

I have a base class `Entity` that has the properties `id` and `name`.
I have a `User` class that extends `Entity`.

When importing and using the `User` class in other files as a typed variable I'm being told that the properties `id` and `name` don't exist on type `User` even though they are properties of the base `Entity` class.

I don't receive any message when running `deno lint` from the console so I'm thinking that it's coming from this extension in some way. 

While in VS Code I'm receiving the following problem:

```
{
	"resource": "/E:/DenoWebSocket/message.ts",
	"owner": "deno",
	"code": "2339",
	"severity": 8,
	"message": "Property 'name' does not exist on type 'User'.",
	"source": "deno-ts",
	"startLineNumber": 29,
	"startColumn": 19,
	"endLineNumber": 29,
	"endColumn": 23
}
```

**Comment by kitsonk** [comment]
A more complete reproduction would need to be required to be able to identify the problem, including:

- the `settings.json`
- the version of Deno and VScode (this can be found by going under _View | Output_ and then in the drop down to _Deno Language Server_ and should be at the top of the output)
- what the output of `deno cache message.ts` is

**Comment by kitsonk** [comment]
No information provided. Closing.
