### ISSUE TITLE
The plugin hates .md files

### ISSUE THREAD

**Issue by jcoonrod** [denoland/vscode_deno#428]
### test

Include a README.md file in your folder

**To Reproduce**

1. Include a README.md file in your folder
2. look at all the Problems!

**Expected behavior**

No errors

**Screenshots**
![Screenshot 2021-06-01 10 59 03 AM](https://user-images.githubusercontent.com/54367582/120348380-2338b280-c2cb-11eb-9e79-512235c6b711.png)

**Versions**

vscode: 1.56.2 deno: 1.10.2 extension: 3.5.0

**Comment by lucacasonato** [comment]
Update Deno to 1.10.3.

I will mark this as a bug, because md integration should only be enabled for 1.10.3 and up.

**Comment by jcoonrod** [comment]
Wow! Thanks for the quick response!

**Comment by kitsonk** [comment]
@lucacasonato yeah, but we don't feature flag things.  We can bump the semver in the extension, but I don't want to get into different code paths based on versions of Deno.

**Comment by lucacasonato** [comment]
Let's do that then. Should help with getting people on 1.10.2 and above anyway.

**Comment by kitsonk** [comment]
Yeah, just raised the PR. I can do the release of `3.5.1` after that.

**Comment by technovangelist** [comment]
the comments above imply to me that getting about 1.10.2 and 3.5.1 will solve this issue. but I am on deno 1.11.1 and Deno-vscode 3.6.1 and experiencing this issue. Is there a way to disable the formatting of markdown?

**Comment by technovangelist** [comment]
ahh, looks like something updated and vscode needed an restart even though there was no indication that it needed one.
