### ISSUE TITLE
Make refactoring available

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#433]
It seems that there is no refactoring available when using this extension?

With extension off:
![Screenshot from 2021-06-03 17-26-02](https://user-images.githubusercontent.com/12832280/120679459-1a91d900-c491-11eb-9cbd-7b03513dd975.png)

With it on:
![Screenshot from 2021-06-03 17-25-41](https://user-images.githubusercontent.com/12832280/120679529-2da4a900-c491-11eb-8652-0586db8b3d9f.png)

**Comment by Pangeli70** [comment]
Having the same issue. Very frustrating.

**Comment by jeanp413** [comment]
@kitsonk are you working on this or can I send a PR for this in the Deno repo?

**Comment by kitsonk** [comment]
@jeanp413 feel free... it is on my TODO list, but it is a bit of a ways down, so would be glad for a contribution.
