### ISSUE TITLE
3.6.0 fails to disable built-in TypeScript intellisense

### ISSUE THREAD

**Issue by voltrevo** [denoland/vscode_deno#439]
**Describe the bug**

Getting intellisense from both Deno and built-in TypeScript support, e.g.:

<img width="480" alt="Screen Shot 2021-06-08 at 10 43 16 am" src="https://user-images.githubusercontent.com/9291586/121104921-5dafcb80-c846-11eb-9c95-a7407f73fabe.png">

Downgrading to 3.5.1 resolves the issue.

**To Reproduce**

Blank project:
```
.vscode/settings.json:
  {
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": false,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "denoland.vscode-deno"
  }

hello.ts
  Deno.readFile;
```

**Expected behavior**

No red underline under `Deno`, intellisense from deno extension only and not built-in TypeScript.

**Screenshots**

See above.

**Versions**

vscode: 1.56.2 deno: 1.10.3 extension: 3.6.0

**Comment by kitsonk** [comment]
> Info 34   [10:51:20.947] Couldn't find typescript-deno-plugin

Something has gone wrong with the plugin that mutes those messages... Grr....

**Comment by kitsonk** [comment]
It was a breaking change in a minor release of the packaging tool for Visual Studio Code: https://github.com/microsoft/vscode-vsce/issues/576.  Trying to figure out how to fix it now.

**Comment by matklad** [comment]
>Trying to figure out how to fix it now.

I often dream about npm-ecosystem-less way of developing extensions for VS Code. At it's core, an extension is just an archive with some JavaScript, and it'd be cool to "just" use deno batteries-included tools to cook it, rather than relying on the ever-improving npm tooling. But this doesn't look like the most high-priority yak to shave :D
