### ISSUE TITLE
'TSServer exited with code: 3221225477' since new VSCode version

### ISSUE THREAD

**Issue by omirobarcelo** [denoland/vscode_deno#44]
Since the last version update of VS Code the extension causes the following error.

```
[Info  - 08:09:30.553] Starting TS Server 
[Info  - 08:09:30.553] Using tsserver from: c:\Users\Dev\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 08:09:30.557] <syntax> Forking...
[Info  - 08:09:30.567] <syntax> Starting...
[Info  - 08:09:30.571] <semantic> Forking...
[Info  - 08:09:30.580] <semantic> Starting...
[Error  - 08:09:35.702] TSServer exited with code: 3221225477
```

After 5 retries it crashes and disables the TypeScript Language Service.

My `tsconfig.json` is:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "plugins": [
      {
        "name": "typescript-deno-plugin"
      }
    ]
  }
}
```

The settings in VS Code for the extension are the defaults.

I am using Windows 10, and this is the VS Code version:
> Version: 1.45.1 (user setup)
> Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> Date: 2020-05-14T08:27:35.169Z
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

**Comment by justjavac** [comment]
Try to upgrade typescript-deno-plugin to the latest version.

**Comment by omirobarcelo** [comment]
VS Code automatically updated the extension and it's working. Thanks!
