### ISSUE TITLE
Hybrid node-w-ts and Deno workspace setup?

### ISSUE THREAD

**Issue by jessekrubin** [denoland/vscode_deno#448]
How would I set up a hybrid ts+node and Deno workspace? 

I have several repos that are ts + node but I have a growing number of build/util scripts that are written in ts for Deno. Could there be a shebang-y solution?

**Comment by kitsonk** [comment]
Duplicate of #297 

See: https://github.com/denoland/vscode_deno/blob/main/docs/workspaceFolders.md
