### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by metatronic** [denoland/vscode_deno#449]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.6.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Dell\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by lucacasonato** [comment]
You didn't attach the requested files.
