### ISSUE TITLE
Renaming a variable also renames all instances of the text in a string

### ISSUE THREAD

**Issue by oganexon** [denoland/vscode_deno#450]
### test

**Describe the bug**

When renaming variables with `F2`, if the text of the variable is inside a string, the value of the string is changed as well.

**To Reproduce**

1. create a variable
2. create a string with the text of the variable inside
3. rename the variable using `F2`

**Expected behavior**

The string should be left unchanged !
I had a lot of problems with it because I changed some texts that I shouldn't have, and I realized it quite late.

**Screenshots**

![rename string](https://user-images.githubusercontent.com/52361520/122436489-25706180-cf99-11eb-9f5b-df64c9916e40.gif)

**Versions**

vscode: 1.57.0 deno: 1.11.0 extension: 3.6.1

**Comment by dsherret** [comment]
It also happens within comments:

```ts
const foo = 0;
let bar = "I'm a string with foo inside"; // foo
```

I've opened https://github.com/denoland/deno/pull/11041
