### ISSUE TITLE
Skip type checking in js files

### ISSUE THREAD

**Issue by yubaoquan** [denoland/vscode_deno#456]
**Is your feature request related to a problem? Please describe.**

I have some js files in my ts project. I have already set `allowJs` and `checkJs` to false. But when I open these files, deno still checks them and report errors like this

```text
Parameter 'b' implicitly has an 'any' type.deno-ts(7006)
```

**Describe the solution you'd like**

Maybe there should be a config option to skip ts check in js files.

**Comment by kitsonk** [comment]
What is the output of the "Deno Language Server" and what is your `.vscode/settings.json` settings?

**Comment by yubaoquan** [comment]
output of the "Deno Language Server":

```text
Starting Deno language server...
  version: 1.10.3 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.57.1
language server initialized
Server ready.
```

.vscode/settings.json:

```json
{
  "deno.enable": true,
  "deno.unstable": true,
}

```

Additional: actually, the js file which triggers deno error is named xxx.mjs, if change filename to xxx.js, errors gone.
![mjs](https://user-images.githubusercontent.com/2340296/123578584-c1576400-d808-11eb-8ea6-438cf55e5aaa.jpg)

**Comment by kitsonk** [comment]
Duplicate of denoland/deno#10475
