### ISSUE TITLE
Squiggly lines

### ISSUE THREAD

**Issue by ATakaSKY** [denoland/vscode_deno#46]
Still seeing squiggly lines even after installing the extension.

<img width="446" alt="Screenshot 2020-05-19 at 12 14 55 PM" src="https://user-images.githubusercontent.com/17201629/82293612-71358d80-99ca-11ea-827c-808b8f073778.png">

<img width="624" alt="Screenshot 2020-05-19 at 12 15 06 PM" src="https://user-images.githubusercontent.com/17201629/82293683-8a3e3e80-99ca-11ea-8823-e6d68b887281.png">

**Comment by lucacasonato** [comment]
You have to enable the extension by setting “deno.enable”: true in your vs code config.

**Comment by ATakaSKY** [comment]
Added it at the end of settings.json but still getting the warning:

![settingsVSCode](https://user-images.githubusercontent.com/17201629/82297991-1489a100-99d1-11ea-8a8b-8c1f4f30c19a.png)

**Comment by lucacasonato** [comment]
Did you restart vs code after you changed the setting? Also is the error different to the one displayed previously?

**Comment by ATakaSKY** [comment]
Tried restarting. Didn't work. Also getting the same warning as before.

**Comment by MisterJimson** [comment]
I was seeing this too and it only went away after running `deno run`.

**Comment by justjavac** [comment]
@ATakaSKY This problem has been fixed, can you provide the tsserver.log

**Comment by ATakaSKY** [comment]
@justjavac 
Please find it attached.

[tsserver.log](https://github.com/denoland/vscode_deno/files/4655858/tsserver.log)

**Comment by justjavac** [comment]
in line 27:

> Info 21   [14:56:32.207] Loading typescript-deno-plugin from /Users/aakash.t/.vscode/extensions/**justjavac.vscode-deno-1.3.3** 

The latest version is 1.32.0

**Comment by ATakaSKY** [comment]
I tried installing the plugin again with `deno install -Af --unstable https://deno.land/x/denon/denon.ts` but go this error:

<img width="765" alt="Screenshot 2020-05-22 at 8 08 02 AM" src="https://user-images.githubusercontent.com/17201629/82625660-60239100-9c03-11ea-95c9-e54aaa073a59.png">

**Comment by lucacasonato** [comment]
I am going to close this because a lot has changed since you opened this issue (completely different extension now). If you still encounter this error, please open a new issue.
