### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MexieAndCo** [denoland/vscode_deno#461]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.6.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Larry\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kitsonk** [comment]
Please attach the request file.

**Comment by kitsonk** [comment]
Information not provided, closing.
