### ISSUE TITLE
Ability to initialize workspace without changing workspace settings on a one-off basis

### ISSUE THREAD

**Issue by dsherret** [denoland/vscode_deno#468]
**Is your feature request related to a problem? Please describe.**

There are times when I'm working in another non-deno repo and I want to write a quick temporary script in the folder to do something and then I delete the script afterwards. For these scenarios, it's not so nice to have to edit the workspace settings to get the extension going because then it requires manually removing these settings afterwards.

**Describe the solution you'd like**

I'm not sure about the solution, but perhaps another command that is similar to the "Initialize Workspace Configuration" except it doesn't change or initialize the configuration. The problem is that I'm not sure how this could be named without confusing users. Maybe an "Activate on File" that only appears in non-initialized workspaces when viewing a TypeScript file.

**Comment by kitsonk** [comment]
While the protocol allows for per file configuration, vscode does not support it meaning the settings apply to the whole workspace, and it is a requirement for both the Language Server but also the TypeScript plugin which suppresses the file to have some sort of setting to flag it. I can't conceive of an easy practical way to implement such a feature.

I personally keep a workspace named _scratch_ open for such a thing.

**Comment by dsherret** [comment]
> it is a requirement for both the Language Server but also the TypeScript plugin which suppresses the file to have some sort of setting to flag it

Too bad. Yeah, I just tried hardcoding enabled as true and it doesn't work. Does this magically happen right now based on the "enable" flag being true in the config? I don't see how it's connected.

**Comment by kitsonk** [comment]
It was all refectored when supporting workspace folders in vscode. The lsp request from the client the configuration, supplying the URI.

To mute the built in language server, we have to use the language server plugin. When we see a configuration change in the client we update the configuration of the plugin and this allows the plugin to determine on a per file basis if it should mute the built in language service. Because the plugin and built in language service run in a separate worker, functions/callbacks can't be sent across the boundary and I wasn't sure if postMessage was there, as we are already quite into unsupport land with our hackery.

**Comment by dsherret** [comment]
Ah, ok I think I'm beginning to understand. So on configuration update, we send the deno language server a configuration update, but then it [calls back](https://github.com/denoland/deno/blob/642dd3d3c433efb56e59e64f0b75c6951153b571/cli/lsp/language_server.rs#L774) to the client asking for the config and that's controlled by vscode-languageclient which always [reads from the vscode workspace settings](https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/client/src/common/configuration.ts#L45).

So, I've found I'm able to get this to work by not having it call back to the client to get the configuration and instead always providing the configuration in the `workspace/didChangeConfiguration` event. It seems like that was done though because the items on the event were unreliable, but why don't we just call `vscode.workspace.getConfiguration(EXTENSION_NS)` there? If we can't do that, I can submit a PR to add a comment about why we can't.

![image](https://user-images.githubusercontent.com/1609021/125381333-b3095c00-e361-11eb-957a-b76016bf57f8.png)

By the way, to clarify, my desire here is basically the ability to do `"deno.enable": true` in a workspace for one-off purposes without having to create/delete or modify/revert a `.vscode/settings.json` file.

**Comment by bartlomieju** [comment]
`// @deno-enable` or `// @deno` pragma could be used for this. Not extremely elegant, but does the job and there's a lot of prior art in the community that use these kinds of solutions

**Comment by nayeemrmn** [comment]
> `// @deno-enable` or `// @deno` pragma could be used for this. Not extremely elegant, but does the job and there's a lot of prior art in the community that use these kinds of solutions

Closing in favour of #813.
