### ISSUE TITLE
Debugger doesn't start

### ISSUE THREAD

**Issue by grian32** [denoland/vscode_deno#476]
**Describe the bug**

Debugger crashes with an error(VSCode wouldn't let me copy paste so I put the screenshot below) as soon as I click the start button, my `launch.json` was automatically generated. 

I'd gotten the debugger to start up by making some breakpoints on a couple test's code but it didn't show variables or let me step through code and for some reason it made my julia extension and the julia language server start up. 

**To Reproduce**

1. Make a file with this code named main.ts:
```js
let msg = "hello world";
console.log(msg);
```
2. Make this your launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deno: Run",
            "request": "launch",
            "type": "pwa-node",
            "program": "main.ts",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": [
                "run",
                "--unstable",
                "--inspect",
                "--allow-all"
            ],
            "attachSimplePort": 9229
        }
    ]
}
```
3. Try to run debugger

**Expected behavior**

The debugger to start, show me variables, let me step through breakpoints, all that stuff that a debugger's meant to do.

**Screenshots**

![image](https://user-images.githubusercontent.com/54550982/126995290-dabb74f6-d3fd-40b4-ad77-9dd2c2f01288.png)

**Versions**

vscode: 1.58.2 
deno: 1.12.1
extension: 3.7.0

**Comment by bartlomieju** [comment]
I'm not sure if it will work with `program` argument, have you tried using example config from manual?

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Deno",
      "type": "pwa-node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": ["run", "--inspect-brk", "-A", "${file}"],
      "attachSimplePort": 9229
    }
  ]
}
```

**Comment by grian32** [comment]
@bartlomieju That worked, thanks a bunch, I didn't realize I needed to get the example config from the manual, since there was one automatically generated.
