### ISSUE TITLE
import intellisense doesn't list versions after `@`

### ISSUE THREAD

**Issue by maximousblk** [denoland/vscode_deno#482]
**Describe the bug**

**To Reproduce**

1. Add `"https://cdn-dev.nest.land/": true,` to `deno.suggest.imports.hosts`
2. Try importing a module from `cdn-dev.nest.land`
3. Observe that the `user` and `module` segments work as expected but after the `@` sign the intellisense breaks down.

<details>
<summary>config</summary>

[deno-import-intellisense.json](https://cdn-dev.nest.land/.well-known/deno-import-intellisense.json)

```jsonc
{
  "version": 1,
  "registries": [
    {
      "schema": "/:user([a-zA-Z0-9_]*)/:module([a-zA-Z0-9_]*)@:version([a-z0-9-]*)/:path*",
      "variables": [
        {
          "key": "user",
          "url": "https://api.nest.land/imports/x"
        },
        {
          "key": "module",
          "url": "https://api.nest.land/imports/x/${user}"
        },
        {
          "key": "version",
          "url": "https://api.nest.land/imports/x/${user}/${module}"
        },
        {
          "key": "path",
          "url": "https://api.nest.land/imports/x/${user}/${module}/${version}"
        }
      ]
    }
  ]
}
```

</details>

**Expected behavior**

list all the module versions when the user types `@` after the module name.

**Screenshots**

current behaviour:

![](https://cdn.discordapp.com/attachments/689420767620104201/870069417122361344/unknown.png)

expected behaviour:

![](https://cdn.discordapp.com/attachments/689420767620104201/870069352890769458/unknown.png)

and somehow the versions are listed under `path`:

![](https://cdn.discordapp.com/attachments/689420767620104201/870069651164504094/unknown.png)

**Versions**

- vscode: `1.58.2` 
- deno: `deno 1.12.2 (release, x86_64-unknown-linux-gnu)`
- extension: `v3.7.0`

**Comment by maximousblk** [comment]
😑😑😑

it was a problem with my regex (missing `.`)

still doesn't explain the "version as path" thing that was happening but the problem got solved so i'm closing it.

**Comment by kitsonk** [comment]
I think it was acting weird because the way it breaks down the path-to-regex to be incremental. Because we were "missing" the version, it was screwing up trying to create the final URL.  I will take a look at that failure scenario.
