### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by psantos10** [denoland/vscode_deno#483]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.7.0`
- OS Version: `Darwin x64 20.5.0`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`

[denoland.vscode-deno-unresponsive.cpuprofile.txt](https://github.com/denoland/vscode_deno/files/6923103/denoland.vscode-deno-unresponsive.cpuprofile.txt)denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kitsonk** [comment]
> ⚠️ Make sure to attach this file from your home-directory:

No file attached.
