### ISSUE TITLE
VS Code extension complaint about top-level await

### ISSUE THREAD

**Issue by win-t** [denoland/vscode_deno#484]
**Describe the bug**
VS Code extension complains about top-level await

**To Reproduce**
Following code will produce problem in visual code
```typescript
// file: main.ts
export const sleep = (ms: number) => new Promise((ok) => setTimeout(ok, ms));

await sleep(1000);

console.log("hello world");
```
but, it works well when I run `deno run main.ts`

**Expected behavior**
No error

**Screenshots**

![image](https://user-images.githubusercontent.com/1589120/128195194-d443b507-230b-4ceb-9a95-0726b78358d9.png)
![image](https://user-images.githubusercontent.com/1589120/128195545-167b6047-ca3f-4515-93a6-0ab7a988274c.png)

**Versions**

vscode: 1.58.2 deno: 1.12.2 extension: 3.7.0

**Comment by win-t** [comment]
and also, it complains about not being a `esmodule` without `import` or `export` statement
![image](https://user-images.githubusercontent.com/1589120/128196460-70654b45-f233-40ea-a705-f0b550e4f26e.png)

**Comment by win-t** [comment]
Wow, I work now after I restart VS Code, :thinking:

**Comment by kitsonk** [comment]
Probably caused by what #474 fixed but hasn't been released yet.
