### ISSUE TITLE
Semantic Highlighting is broken while extension is enabled.

### ISSUE THREAD

**Issue by TheCymaera** [denoland/vscode_deno#486]
Semantic Highlighting is broken while the extension is enabled. "deno.enable" does not need to be set to true. Note that the identifier "test" is not highlighted in the second image to indicate that it is readonly.

<img width="1389" alt="Screenshot 2021-08-07 at 6 10 05 AM" src="https://user-images.githubusercontent.com/69355340/128576067-0c7095dd-4167-4d4b-a227-ca3210cd6a73.png">
<img width="1390" alt="Screenshot 2021-08-07 at 6 10 35 AM" src="https://user-images.githubusercontent.com/69355340/128576073-2e9a572a-c5cc-41bf-acfd-0b4c4a5732bd.png">

vscode: 1.59.0 (Universal)
deno: 1.12.0 (release, x86_64-apple-darwin) 
extension: v3.7.0

**Comment by kitsonk** [comment]
In the broken one, what is the output of the _Deno Language Server_ and what is the output of _Deno: Language Server Status_ from the command pallet?

**Comment by TheCymaera** [comment]
```
"deno.enable": false
```
```
Starting Deno language server...
  version: 1.12.0 (release, x86_64-apple-darwin)
  executable: /usr/local/bin/deno
Connected to "Visual Studio Code" 1.59.1
{"type":"mark","name":"update_tsconfig"},
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"configure","compilerOptions":{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window"],"module":"esnext","noEmit":true,"strict":true,"target":"esnext","useDefineForClassFields":true}}},
{"type":"measure","name":"request","count":1,"duration":1},
{"type":"measure","name":"update_tsconfig","count":1,"duration":104},
{"type":"mark","name":"request","count":2,"args":{"id":3,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":2,"duration":0},
{"type":"measure","name":"initialize","count":1,"duration":105},
language server initialized
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
{"type":"measure","name":"update_registries","count":1,"duration":0},
Server ready.
{"type":"mark","name":"did_open","count":1,"args":{"textDocument":{"uri":"<<FILE_PATH>>","languageId":"json","version":1,"text":"<<FILE_TEXT>>"}}},
{"type":"measure","name":"did_open","count":1,"duration":0},
```

<img width="681" alt="Screenshot 2021-08-22 at 4 50 34 PM" src="https://user-images.githubusercontent.com/69355340/130348646-75fc7164-2878-4368-b4cc-9fc6b227a90e.png">

**Comment by kitsonk** [comment]
Why do you have `deno.internalDebug` enabled?

I am able to re-create this. If `deno.enable` is `true` then semantic tokens are provided from the Deno Language Server, but if `deno.enable` is `false` then semantic tokens are still not provided from the built in TypeScript language server.

**Comment by kitsonk** [comment]
I've done some investigation into this and I can't seem to find a way to fix it.  The API calls are happening with the internal TypeScript plugin, but for some reason, the semantic tokens are either not being returned or applied.

**Comment by astanciu** [comment]
Any updates on this? Ran into the same thing

**Comment by bartlomieju** [comment]
Sorry for a slow response. Can you still reproduce this problem when using latest Deno (v1.35)?

**Comment by hw104** [comment]
Same here
deno: v1.36.4
vscode_deno: v3.22.0

**Comment by bartlomieju** [comment]
@nayeemrmn could you please investigate this issue?

**Comment by nayeemrmn** [comment]
This is caused by the extension intercepting TS (etc.) files irrespective of `deno.enable`/`deno.enablePaths`, due to: https://github.com/denoland/vscode_deno/blob/ec0b9c0bd30d9319fa485ff1b8f29016be25223c/client/src/extension.ts#L219-L232 Specifically when a language client is started with those options: https://github.com/denoland/vscode_deno/blob/ec0b9c0bd30d9319fa485ff1b8f29016be25223c/client/src/commands.ts#L179 We can probably solve that for global `enable` but that's incomplete. I'll look into solutions more.
