### ISSUE TITLE
Deno runtime using files opened with VSCode in the background

### ISSUE THREAD

**Issue by felipeqq2** [denoland/vscode_deno#491]
**Describe the bug**
Since I installed the Deno VSCode extension (Windows 10), I noticed that the deno executable keeps using arbitrary files and folders in the background, keeping me from deleting it. It only happens if I open the folder on VSCode, with the deno extension enabled, even if I don't initialize the workspace.

For instance, I just created a new folder, opened VSCode and created some files. Now, if I close VSCode and try to delete it, it keeps saying that "The action can't be completed because the folder is open in another program". If I open the Resource Monitor, I can see that the deno executable is the program using it.

**To Reproduce**

1. Create a new folder
2. Open it with VSCode (deno extension enabled)
3. Close VSCode
4. Try to delete the folder 
5. Kill deno on task manager
6. You should be able to delete the folder

**Expected behavior**

The folder should not be used by the deno process, and I would be able to delete it.

**Screenshots**

![image](https://user-images.githubusercontent.com/71830138/128883579-6a06d459-455b-41cf-8299-345f7b5ea21d.png)

**Versions**

vscode: 1.58.2 deno: 1.12.2 extension: 3.8.0

**Comment by dsherret** [comment]
I think this is #374 (though I've never been able to reproduce it on Windows). It should be fixed in 1.13 which was just released.

**Comment by felipeqq2** [comment]
It was solved in 1.13, thanks!
