### ISSUE TITLE
Format of generated config file conflicts with what `deno fmt` prefers

### ISSUE THREAD

**Issue by magurotuna** [denoland/vscode_deno#498]
On initializing, the plugin generates a config JSON file with 4-space indent, but it conflicts with `deno fmt` since it prefers 2-space indent. It is a kind of annoying that running `deno fmt` formats `.vscode/settings.json` just after it's generated.
It would be better if we could make the plugin generate a JSON file whose format `deno fmt` likes.

However, from my quick browse, unfortunately it seems like the VSCode Extension API doesn't provide a way of configuring the indent size of config files. https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration

**Comment by kitsonk** [comment]
Correct, I don't think there is anything we can do about it, we don't actually write a file, we simply access APIs that persist the data as vscode sees fit.

So I am going to close this as a design limitation.

**Comment by ry** [comment]
Could we hardcode into deno fmt to not format `vscode/settings.json` ?

**Comment by kitsonk** [comment]
I suspect some people would want to `deno fmt` the file, right?

**Comment by ry** [comment]
Maybe we'd allow it if someone does `deno fmt .vscode/settings.json` but a normal `deno fmt` call could ignore the `.vscode` directory by default.

**Comment by kitsonk** [comment]
Opened a suggestion in `deno_lint`.

**Comment by ry** [comment]
Why in deno_lint? Shouldn't it be in deno/cli/tools/fmt.rs ?

**Comment by caspervonb** [comment]
> Why in deno_lint? Shouldn't it be in deno/cli/tools/fmt.rs ?

The predicate we use is in `cli::fs_util`.
Just expand that with a `is_supported_fmt_path` one.

Maybe we should just ignore dotfiles in general?

**Comment by kitsonk** [comment]
Moved the issue to deno then. 🤷
