### ISSUE TITLE
Feature request - disable Deno extension in Node.js projects

### ISSUE THREAD

**Issue by rjkz808** [denoland/vscode_deno#50]
As I understand it is only possible to disable Deno extension manually with `"deno.enable": false` in vscode `settings.json`. But I think it can be more comfortable if extension would automatically being disabled in projects that have `package.json` file or `node_modules` folder inside.

**Comment by wk989898** [comment]
when i disable deno ,typescript will check out my code continue。i always get `Parameter '*' implicitly has an 'any' type.`. is other setting to be set ?

**Comment by justjavac** [comment]
https://github.com/denoland/vscode_deno/pull/7

**Comment by BobFrankston** [comment]
Until I Deno can coexist with Node projects in different instances of VSC running at the same time I can't use this extension. So I strongly support per-project use of Deno.

**Comment by rjkz808** [comment]
@justjavac this prompt does the trick, but there are still some problems with formatting (see #57)

**Comment by BobFrankston** [comment]
The settings seem to be global -- how do I do it per project?

**Comment by rjkz808** [comment]
@BobFrankston you can create `.vscode` folder inside your project and also a `settings.json` file inside of it. Then you can insert this configuration snipper in `settings.json` file:

```json
{
  "deno.enable": false
}
```

In VSCode `.vscode/settings.json` stands for local IDE settings to apply in specific folder.

**Comment by BobFrankston** [comment]
THanks. that makes it more useful

**Comment by garysb** [comment]
For others looking through this, please also refer to #70, #75 as all of these are related.

**Comment by lucacasonato** [comment]
Extension is disabled by default now. For other node compat issues refer to https://github.com/denoland/vscode_deno/issues/314
