### ISSUE TITLE
TS prompt error when setting importmap to import package

### ISSUE THREAD

**Issue by FE-Mars** [denoland/vscode_deno#51]
![image](https://user-images.githubusercontent.com/7720916/82541060-73424c80-9b82-11ea-9018-c041ae5e315d.png)
![image](https://user-images.githubusercontent.com/7720916/82541405-0085a100-9b83-11ea-9c13-1b6a832e57cd.png)

**Comment by ipriel** [comment]
I have the same issue.

**Comment by justjavac** [comment]
do you config the import maps by `deno.importmap`

you will get:

![](https://user-images.githubusercontent.com/359395/82620730-cca28e00-9c0b-11ea-87fe-ad85c0d214b9.png)

**Comment by FE-Mars** [comment]
> do you config the import maps by `deno.importmap`
> 
> you will get:
> 
> ![](https://user-images.githubusercontent.com/359395/82620730-cca28e00-9c0b-11ea-87fe-ad85c0d214b9.png)

Thanks. It's okay
