### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 02818bea-9a08-4b24-a53f-8d4ad597fe20** [denoland/vscode_deno#512]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.8.1`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.59.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kitsonk** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\ADMINI~1\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt

**Comment by kitsonk** [comment]
No info provided, closing.
