### ISSUE TITLE
Unable to set breakpoints on remote URLs

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#516]
Currently you cannot set breakpoints on remote URL open in the editor.  If you try to do so, vscode prompts you to try to save the file locally.  Not sure exactly what is going on.

**Comment by jd1378** [comment]
I'm facing the same issue
running `>Debug: Diagnose Breakpoint Problems` command in vscode and clicking `Why my breakpoints don't bind`, in there I see it tries to put breakpoint on a wrong location inside the project folder. I dont know maybe the extension can help vscode find the local file inside `DENO_DIR` path or wherever the default cache is located and set breakpoint in there ?

**Comment by jd1378** [comment]
the thing is it works when it stops at the first line and automatically opens the remote file like this: 
![image](https://user-images.githubusercontent.com/6196533/181698495-62c36eb1-7f66-470b-b362-a931fef2beca.png)
But not when you manually open the remote file, and the path becomes like this:
![image](https://user-images.githubusercontent.com/6196533/181698860-2d2eae60-c02b-4299-ae57-13e5bd08ba87.png)

also when using the chromium debugger, by revealing the file on the sidebar and exploring the project I can set breakpoints easily, so I don't really know whats wrong here.

**Comment by nayeemrmn** [comment]
This should work in vendored files now, they are opened as files as far as VSCode is concerned.
