### ISSUE TITLE
Type defs for `Deno` namespace are not found

### ISSUE THREAD

**Issue by colinknebl** [denoland/vscode_deno#52]
![Screen Shot 2020-05-21 at 9 49 49 AM](https://user-images.githubusercontent.com/24233575/82565539-98b26480-9b48-11ea-8342-12cd2af21577.png)

The test runs and passes. 

extension: 1.32.0
deno 1.0.1
v8 8.4.300
typescript 3.9.2

**Comment by colinknebl** [comment]
I ended up re-installing VS Code and that has solved the problem - closing the issue.

**Comment by Liamolucko** [comment]
To any future readers, I was able to solve the same issue without a reinstall by disabling any other JavaScript-related extensions (in my case, Angular Language Service) for the workspace.

**Comment by warwr1ck** [comment]
> To any future readers, I was able to solve the same issue without a reinstall by disabling any other JavaScript-related extensions (in my case, Angular Language Service) for the workspace.

I dont have Angular Language Service...
and i meet the same issue too..what should i do?
Reinstall VS code is not a good way to solve this problem..

**Comment by colinknebl** [comment]
As @Liamolucko said, I believe the root problem I had was with the other extensions I had. Re-installing VS Code probably wasn't necessary, or what actually solved my problem (I had removed some extensions during the re-install). 

I would start by disabling all extensions in the workspace (may need to restart VS Code's TypeScript server).

**Comment by newtack** [comment]
I still have the issue and could not resolve it so far. I uninstalled and reinstalled VSCode and disable all other extensions. Please note that it works on my Windows machine with this extension, but not on my Ubuntu machine.

**Comment by shardyMBAI** [comment]
<img width="483" alt="Screen Shot 2020-06-04 at 3 36 25 AM" src="https://user-images.githubusercontent.com/27963753/83764222-ae934f80-a647-11ea-90bf-71326c845ddc.png">

I seem to have the same issue only `deno test` also fails
