### ISSUE TITLE
Option for deno plugin to be enabled in only some directories. 

### ISSUE THREAD

**Issue by dustinroepsch** [denoland/vscode_deno#54]
It would be great if I could specify whether the plugin was enabled per directory.
My use-case is the following directory structure:

server/  <- deno sources for my server code
web/ <- the typescript here will be bundled using parcel and served by the server code

When the deno plugin is enabled, the server/ code autocompletes just fine but the web/ code breaks with errors like "cannot find name document". 

I know that you can use the .vscode/settings.json to enable and disable the deno plugin, but as far as I'm aware that doesn't work in the case where I want to have both of these folders open and the extension to run depending on which path the file I'm editing is in.

**Comment by justjavac** [comment]
a idea is here: https://github.com/denoland/vscode_deno/issues/39#issuecomment-629892685

**Comment by dustinroepsch** [comment]
That looks great! Closing this issue since it's being discussed elsewhere.
