### ISSUE TITLE
Deno extension stopped working v3.9.0

### ISSUE THREAD

**Issue by sant123** [denoland/vscode_deno#542]
**Describe the bug**
Deno extension is no longer working

- Deno namespace is not enabled
- Can't create a Deno Workspace

**To Reproduce**

1. Open VSCode
2. Initialize the current folder as a Deno Workspace
3. Not working

**Expected behavior**

Should initialize the workspace and enable Deno namespace

**Screenshots**

![image](https://user-images.githubusercontent.com/7959437/133348092-db8e6834-deef-4439-a0b4-9a93fcc72997.png)

![image](https://user-images.githubusercontent.com/7959437/133348107-41dc463c-213d-4276-94f6-055827dda648.png)

**Versions**

vscode: 1.60.1 deno: 1.14 extension: 3.9.0

**Comment by velxe** [comment]
Same here

**Comment by lts372005** [comment]
can confirm.
downgrade to v3.8.1 works

**Comment by nhrones** [comment]
Working fine here on Windows 10
Deno v3.9.0
deno 1.14.0 (release, x86_64-pc-windows-msvc)
v8 9.4.146.15
typescript 4.4.2

**Comment by bartlomieju** [comment]
We are working on fixing the problem, a fix will be released shortly.

**Comment by lts372005** [comment]
> Now errors on 'initialize workspace options'
No initialize workspace options errors? what about Deno namespace? does vsc give autocomplete for Deno namespace?

**Comment by nhrones** [comment]
@lts372005  Cannot find name 'Deno'.ts(2304)

**Comment by sant123** [comment]
https://github.com/denoland/vscode_deno/pull/543

**Comment by bartlomieju** [comment]
The problem should now be fixed with v3.9.1 released https://github.com/denoland/vscode_deno/releases/tag/3.9.1

**Comment by nhrones** [comment]
Confirm 3.9.1 working again

**Comment by sant123** [comment]
Yes working again 

![image](https://user-images.githubusercontent.com/7959437/133351855-fac759c9-f5c0-40b5-9ce4-51bcfedd0cfa.png)

Thank you !!!
