### ISSUE TITLE
Deno Language Server crash

### ISSUE THREAD

**Issue by lawilog** [denoland/vscode_deno#546]
**Describe the bug**
On a fresh vscode install, in an empty folder, the Language Server crashes with error "The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.". "Output":
```
[Info  - 11:53:15 AM] Connection to server got closed. Server will restart.
[Info  - 11:53:15 AM] Connection to server got closed. Server will restart.
[Info  - 11:53:15 AM] Connection to server got closed. Server will restart.
[Info  - 11:53:15 AM] Connection to server got closed. Server will restart.
[Error - 11:53:15 AM] Connection to server got closed. Server will not be restarted.
```

I tried this on two different machines. Both with VsCode and Codium.

**To Reproduce**
Under Kubuntu 20.04.3 LTS (Focal Fossa)
1. sudo snap install --classic code
2. sudo snap install deno
3. mkdir test; cd test; code .
4. in VSCode, Extension -> search for "Deno", install it. restart code (to be safe)
5. Ctrl+Shift+P >Deno: Initialize Workspace Configuration
6. [crash]

**Versions**

vscode:
Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-77-generic snap

deno:
deno 1.12.2 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.5

extension: v3.9.1

**Comment by kitsonk** [comment]
What happens when you upgrade to Deno 1.13 or 1.14?

**Comment by lawilog** [comment]
Works! :) I downloaded the "deno" binary version 1.13.2, configured it as "Deno: path" in the Extension Settings and the Language Server no longer crashes.
