### ISSUE TITLE
I get "Import 'https://cdn.esm.sh/.well-known/deno-import-intellisense.json' failed: 500 Internal Server Error"

### ISSUE THREAD

**Issue by CanRau** [denoland/vscode_deno#552]
**Describe the bug**
When I open VSCode or reload `Deno: Restart Language Server` a popup shows up
```
Import 'https://cdn.esm.sh/.well-known/deno-import-intellisense.json' failed: 500 Internal Server Error
```

Uh maybe it's because I've got
```json
"deno.suggest.imports.hosts": {
    "https://deno.land": true,
    "https://esm.sh": true
},
```
`esm.sh` in my `.vscode/settings.json` 🤔 So maybe I should open an issue with them cause they provide the intellisense file?

**Screenshots**

<img width="451" alt="Screen Shot 2021-09-23 at 20 24 06" src="https://user-images.githubusercontent.com/5196971/134604264-00e84d74-4221-4a86-9d30-d42aee480f9d.png">

**Versions**

vscode: 1.60.2 deno: 1.14.1 extension: 3.9.1

**Comment by kitsonk** [comment]
It does not look like `esm.sh` supports import completions, and you are simply seeing the error reported back.

What made you believe that `esm.sh` supports completions?

**Comment by CanRau** [comment]
Good question, I didn't actually now how they work and think it was added automatically by the plugin, at least after confirming some popup I believe, but I guess I've set it to `true`
Just saw that the plugin also added
```json
    "http://esm.sh": false,
    "https://e": false,
    "https://esm": false,
    "https://esm.": false
```
Not really sure how that happened 🤷🏻‍♂️

So I tried to set it to `false` then restarted the language server which still resulted in the error, only removing it completely solved the error after restarting.

So I'm closing then, thanks for your time ☺️

**Comment by kitsonk** [comment]
When you complete a "new" host in the editor (like by typing `https://esm/something`) and you have import suggestions turned on, Deno will automatically probe the host for the configuration JSON.  If it finds it, it will prompt you to see if you want to configure it, if it doesn't find it, it will go ahead and add it to your config, like the above, so it doesn't keep checking again and again for the configuration file.

If you manually turn it to `true` at some point, and the host doesn't support it, you will get errors like you were seeing.
