### ISSUE TITLE
Running Deno tests in the editor should not use fuzzy test name matching

### ISSUE THREAD

**Issue by tatemz** [denoland/vscode_deno#554]
**Describe the bug**

Testing a `Deno.test` runs multiple tests with the same prefix

**To Reproduce**

```ts
import { assertEquals } from "https://deno.land/std@0.109.0/testing/asserts.ts";

Deno.test({
  name: "foo",
  fn: () => {
    assertEquals(true, true);
  },
});

Deno.test({
  name: "foo bar",
  fn: () => {
    assertEquals(true, true);
  },
});

Deno.test({
  name: "foo bar baz",
  fn: () => {
    assertEquals(true, true);
  },
});
```

**Expected behavior**

When the "Run Test" button is clicked, I expect only that test to run and no other.

**Screenshots**

![2021-10-02 15 49 28](https://user-images.githubusercontent.com/2190655/135731437-17277d3f-7437-4601-a7bc-a6da6a6f2396.gif)

**Versions**

deno: 1.14.2 extension: 3.9.1

**Comment by kitsonk** [comment]
The code action simply re-leverages the CLI''s filter command, and so has no way of expressing exact matching...  We would need to support exact matching in the CLI.

**Comment by caspervonb** [comment]
> The code action simply re-leverages the CLI''s filter command, and so has no way of expressing exact matching... We would need to support exact matching in the CLI.

You can do a more exact match with a regex @kitsonk

**Comment by clemens-tolboom** [comment]
I cannot reproduce as I get one test running

> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out (10s)

The UI shows

![deno-test-single-test](https://user-images.githubusercontent.com/371014/148949460-35d3fb2f-d773-490c-beac-4c1c4e86375b.png)

```
deno --version
deno 1.17.1 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```
