### ISSUE TITLE
Some people may not expect this extension formatting Markdown files outside of Deno projects

### ISSUE THREAD

**Issue by FToovvr** [denoland/vscode_deno#555]
Hello.

This extension formats my Markdown texts, even if I put ` { "deno.enable": false } ` in my workspace's `.vscode/settings.json`.

I think it would be better not to let it do that when the file is not in a Deno project, or at least provide an option to disable this behavior.

A little bit earlier, I noticed that my Markdown files started to be formatted automatically on saving. Although I found it a little annoying, I just left it as is. Until today, I found It corrupts Markdown tables inside lists when there are no leading empty lines[^1]:

It took me some time to figure out that the Markdown formatter is from this extension, who would have thought?
So, I think it might make sense to make this extension, by default, format Markdown files only if it is inside a Deno project (i.e. `"deno.enable": true` in `.vscode/settings.json`).

[^1]: According to [this line of comment](https://github.com/denoland/deno/blob/f1d3a170430501b4fab1a2d2abb5d77528251c77/cli/tools/fmt.rs#L136), It seems the bug is from [dprint-plugin-markdown](https://github.com/dprint/dprint-plugin-markdown) and furtherly from [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark), so I opened [an issue](https://github.com/raphlinus/pulldown-cmark/issues/540) there.

**To Reproduce**

1. Install this extension.
2. create a markdown file and save it on the disk. (Don't need to be in a workspace)
3. it formats that markdown file.

**Expected behavior**

It does not do anything.

**Versions**

vscode: 1.60.2 deno: 1.14.2 extension: v3.9.1

**Comment by ahuigo** [comment]
Vote up `deno.formatting.markdown` setting.
I think in the Unix philosophy, professional people are supposed to do professional things:
1. The markdown formatter in Deno may do not perform as well as some people expected.
2. Some people may have other better customizable markdown formatter which conflicts with Deno.

**Comment by domnantas** [comment]
I was also extremely surprised to find that Deno extension was formatting my markdown files in a non-Deno project

**Comment by nayeemrmn** [comment]
You have to specify the formatter per-language:
```js
{
  "[typescript]": { "editor.defaultFormatter": "denoland.vscode-deno" },
  "[javascript]": { "editor.defaultFormatter": "denoland.vscode-deno" },
}
```
Or disable it for markdown:
```js
  "editor.defaultFormatter": "denoland.vscode-deno"
  "[markdown]": { "editor.defaultFormatter": null },
```
This has to be done independently of `"deno.enable": false` because VSCode can't account for other settings when deciding what formatter to apply to what file.
