### ISSUE TITLE
Option to enable single quotes

### ISSUE THREAD

**Issue by zemse** [denoland/vscode_deno#56]
I have Prettier Single Quote enabled. When the plugin is installed, the prettier single quotes settings are overwritten to double quotes. That's fine when in a deno project. But when I went back to a node.js project, existing single quotes in the file gets converted to double quotes. Saw the Prettier Single Quote check in the settings was enabled but still double quotes are getting created. So I tried unchecking and checking it back making the Prettier single quote setting overwrite on the Deno plugin double quote setting and single quotes get set as expected.

So, if Deno plugin is disabling itself when in a node js project, it should also remove it's double quote setting so that user's Prettier settings get restored. When user gets back to a deno project, it can enable the double quotes.

**Comment by zemse** [comment]
I just got a VSCode notification asking for a default `.ts` code formatter which had options: Deno and Prettier. Is there any workaround to enable Deno formatter in deno project and the usual Prettier in other projects?

**Comment by justjavac** [comment]
edit `.vscode/settings.json` for per project:

```json
{
  "[typescript]": {
    "editor.defaultFormatter": "justjavac.vscode-deno"
  }
}
```

**Comment by zemse** [comment]
Thanks @justjavac
