### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 02818bea-9a08-4b24-a53f-8d4ad597fe20** [denoland/vscode_deno#560]
- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `3.9.1`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.61.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\userl\AppData\Local\Temp\denoland.vscode-deno-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kitsonk** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory:

**Comment by kitsonk** [comment]
Info not provided.
