### ISSUE TITLE
Declaration merging is detected only if the file is open is VSCode

### ISSUE THREAD

**Issue by yooneskh** [denoland/vscode_deno#561]
**Explain the bug**
Declaration merging is detected by the VSCode only if the file that specifies the additional interface options is fully open. as soon as the file closes, VSCode gives out errors.

**To Reproduce**
These are the files needed
``` typescript
// a.ts
export interface IUser {
  name: string;
}

// b.ts
import './a.ts'; // this import is needed and is also needed in tsc itself

declare module './a.ts' {
  interface IUser {
    phoneNumber: string;
  }
}

// c.ts
import { IUser } from './a.ts';

const user: IUser = {
  name: '---',
  phoneNumber: '---'
};
```
1. Create the above files
2. Open them all in the vs code
3. Everything is ok
4. Close the `b.ts` file and as soon as you make a change in `c.ts` file (to trigger linting i guess) an error is given which indicates `phoneNumber` is invalid.
5. Open the `b.ts` file again and make a change in `c.ts` file and everything is ok

**Expected behavior**
A file being open or close should not change the linting behavior. Also note that the deno itself is ok with this and correctly handles declaration merging.

**Versions**
vscode: 1.61.0 deno: 1.14.3 extension: 3.9.1

**Comment by yooneskh** [comment]
Is this still being worked on? Is there a workaround for this?

**Comment by bartlomieju** [comment]
@dsherret could you recent refactor to the LSP fix this problem?

**Comment by dsherret** [comment]
No. If the file is closed and isn't discoverable by the module graph from the current file then it won't be found. The way to make it work is to ensure the declaration merging occurs is to import `User` from a place that imports `a.ts` and does declaration merging there, or even better to not use declaration merging and instead extend the type with a new type then use that.

**Comment by yooneskh** [comment]
Thank you for your quick response @dsherret @bartlomieju 

Is this planned to be fixed in the future?

**Comment by yooneskh** [comment]
One workaround for this is to have a file (i name it `declarations.helper.ts`) and do a simple import to all of your files that have declaration merging inside them, then have this file open all the time (preferably pin it in vscode).

```ts
// declarations.helper.ts
import '../a.ts'; // have declaration merging inside them (declare module)
import '../b.ts';
import '../c.ts';
```

This helps a lot if you have some amount of files that does this.
