### ISSUE TITLE
Add setting to disable some language validations

### ISSUE THREAD

**Issue by Sembiance** [denoland/vscode_deno#567]
With Deno installed, it overrides the built in JavaScript and TypeScript language servers and uses `deno lsp` instead.

This is ok, but the deno plugin doesn't offer any way to disable certain language validations.

For example, it ignores the `javascript.validate.enable` and `typescript.validate.enable` settings and does not provide it's own version.

Simple reproducible steps:
1. Start up VSCode
2. Create a workspace (with deno **disabled**), with a `test.js` file with content:
```
const a = {abc : 123};
a.hello = "goodbye";
```
3. Notice VSCode shows an underline hint under `a.hello`:
![underline](https://user-images.githubusercontent.com/81436/137634527-d5e90647-f0a8-45a6-b384-f15dfd035e9c.png)
4. Go to VSCode settings, search for `validate` and disable `JavaScript > Validate:`
![disable_validation](https://user-images.githubusercontent.com/81436/137634533-ffe9ea9c-1fad-44ca-bb03-8b02d2b3c469.png)
5. Underline hint disappears. This is expected, proper behavior.
![no_underline](https://user-images.githubusercontent.com/81436/137634601-089a04aa-9a46-443e-b9f8-f341f5da5f98.png)
6. Modify workspace settings to enable Deno: ` "settings" : {  "deno.enable" : true } `
7. Underline hint reappears!
![underline](https://user-images.githubusercontent.com/81436/137634527-d5e90647-f0a8-45a6-b384-f15dfd035e9c.png)

Those underlines are not a linting thing, so I can't disable them via that method.

My goal is to get rid of those underlines, haven't found **ANY** way to do it with Deno.

Since this is lilely coming from `deno lsp`, maybe this is an issue to file over on `deno` proper.

Issue #455 is slightly related to this.

**Comment by kitsonk** [comment]
The Deno LSP has different design goals than the built in editor.  If you have Deno enabled for the project, the LSP does the following:

- Treats most diagnostics as errors in TypeScript files.
- Treats most diagnostics as warnings in JavaScript files.

The behaviour of JavaScript files can be modified on a per file basis.  For example if you use `// @ts-check` in a JavaScript file (or you enabled `checkJs` in a config files compiler options), the warnings become errors.  If you put `// @ts-nocheck` then even the warnings go away.
