### ISSUE TITLE
Getting unwanted tsc warnings.

### ISSUE THREAD

**Issue by manuelaguirre** [denoland/vscode_deno#576]
I'm getting ts warnings like "Cannot find name 'Deno' '

1. created folder
2. initialized workspace config
3. created a file `mod.ts`

**Expected behavior**

No spurious errors

**Screenshots**

my language server settings:
```
{
  "enable": true,
  "cache": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": true
  },
  "internalDebug": false,
  "lint": true,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {}
    }
  },
  "unstable": true
}
```

**Versions**

vscode: 1.62.1 deno: 1.16.0 extension: 3.9.2

am I missing something?

**Comment by kitsonk** [comment]
Can you provide the source of the "cannot find name 'Deno'" error.  It should be in text after the error message.  Also if you could provide the output of _View | Output_ and then _Deno Language Server_ from the drop down.

**Comment by jdelarubia** [comment]
Check your **workspace** settings specifics for Deno.
`deno.enable` must be set to `true` and, in some instances, you have to set your `deno.path` too.

**Comment by kitsonk** [comment]
Information not provided. Closing.
