### ISSUE TITLE
launch configs don't work in wsl

### ISSUE THREAD

**Issue by DetachHead** [denoland/vscode_deno#577]
**Describe the bug**

when running a launch config in wsl, nothing happens. nothing shows up in any of the output logs or debug console

![debug](https://user-images.githubusercontent.com/57028336/141613856-0fcceb5b-41f6-4f3d-935d-78be1c3044bd.gif)

**To Reproduce**

1. open project in wsl (F1 > "Remote-WSL: reopen folder in WSL")
2. create a launch config eg: (this is the generated default one)
    ```json
    {
        "version": "0.2.0",
        "configurations": [
            {
                "request": "launch",
                "name": "Launch Program",
                "type": "pwa-node",
                "program": "${workspaceFolder}/main.ts",
                "cwd": "${workspaceFolder}",
                "runtimeExecutable": "deno",
                "runtimeArgs": [
                    "run",
                    "--inspect",
                    "--allow-all",
                ],
                "attachSimplePort": 9229
            }
        ]
    }
    ```
3. hit f5

**Expected behavior**

it runs

**Versions**

vscode: 1.62.1 deno: 1.15.3 extension: 3.9.2

**Comment by kitsonk** [comment]
Are you sure it isn't a duplicate of #557?

**Comment by DetachHead** [comment]
Don't think so, I have that issue as well when trying to debug on windows, but this behaviour is different in wsl because it doesn't even seem to start the debugger (window never turns orange and nothing appears in the debug console)

**Comment by bartlomieju** [comment]
Sorry for a slow response @DetachHead. Do you still experience this problem when using latest Deno version?

**Comment by DetachHead** [comment]
seems to work now, thanks!
