### ISSUE TITLE
Auto imports strictly uses .ts extension even on .tsx files

### ISSUE THREAD

**Issue by ibrahimduran** [denoland/vscode_deno#58]
Considering it's possible to import .js(x) and .ts(x) files with deno out of the box, auto imports should respect the target file extension.

Extension version: 1.33.0
VSCode version: 1.45.1

**Comment by ibrahimduran** [comment]
Another case is auto importing from `dir/index.ts` results in `./dir.ts`

**Comment by rjkz808** [comment]
@ibrahimduran this is off topic, but in Deno.js projects it's a bad practice to use index files for directory imports. The preferred way is to do `dir/mod.ts` and import it as `./dir/mod.ts`. Deno is inspired by rust lang in some way 😄

**Comment by lucacasonato** [comment]
This should be fixed now. If both files exist, the extension will prefer tsx.
