### ISSUE TITLE
Enable autocompletion for deno.land (and nest.land) by default

### ISSUE THREAD

**Issue by piscisaureus** [denoland/vscode_deno#580]

**Comment by kitsonk** [comment]
For context, we discussed that maybe we should enable "know" supports of the registry completions by default, as it would increase the visibility that we support registry completions, which a lot of folks don't realise.

The origins that support it currently:

- deno.land
- nest.land
- crux.land

And we would gladly accept requests for auto enabling any others.

We avoided it in the past as to "not pick sides", but the increase to discovery probably outweighs any downsides.
