### ISSUE TITLE
Unable to configure correctly a workspace with Deno and Typescript compiler 

### ISSUE THREAD

**Issue by llgcode** [denoland/vscode_deno#581]
Hi,
I have a client with typescript files transpiled with **Typescript compiler**. And a server that uses **Deno** as a runtime.
But it's not working, see the screenshot below. I've created a repository that reproduce the issue [llgcode/deno-client-server-ts-template](https://github.com/llgcode/deno-client-server-ts-template/).

I've set `deno.enable: true` in [server/.vscode/settings.json](https://github.com/llgcode/deno-client-server-ts-template/blob/master/server/.vscode/settings.json) as defined by your documentation [workspaceFolders.md](https://github.com/denoland/vscode_deno/blob/main/docs/workspaceFolders.md).

I've seen these closed issues #448 and #297 that seems to be a duplicate of mine.

![image](https://user-images.githubusercontent.com/524083/143579995-1c059e8f-ec2f-4dbb-ac59-37d6543d4c5f.png)

Regards.

**Comment by kitsonk** [comment]
Can you please provide the output of _View | Output_ and then the _Deno Language Server_ drop down and then also the first section of output from _Deno: Language Server Status_ from the command pallette.

**Comment by llgcode** [comment]
Output view:
> Starting Deno language server...
>   version: 1.16.3 (release, x86_64-pc-windows-msvc)
>   executable: C:\Users\xxx\.deno\bin\deno.EXE
> Connected to "Visual Studio Code" 1.62.3
> language server initialized
> Server ready.

Deno Language Server Status
Workspace Settings
```json
{
  "enable": false,
  "cache": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": true
  },
  "internalDebug": false,
  "lint": false,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://deno.land": false
      }
    }
  },
  "unstable": false
}
```

You can also quickly clone the project, it's a simple template project with no dependency in it.
Thanks

**Comment by kitsonk** [comment]
The project is not enabled for deno, as indicated by the configuration.  This is likely because your workspace root is one level up from where the configuration is stored, and VSCode is not finding it.

What happens when you go to _Settings_ and change the _Workspace_ tab and choose to enable Deno there (or use _Deno: Initialize Workspace Configuration_ from the command palette)?

**Comment by llgcode** [comment]
When enabling globally, typescript client file have issues because they seems to be checked by deno extension.

![image](https://user-images.githubusercontent.com/524083/144625642-811351b2-1e13-4397-89b6-78bfb33581e4.png)

note that I'm just using this doc as a reference:
https://deno.land/manual@main/vscode_deno#workspace-folders

**Comment by kitsonk** [comment]
I didn't suggest enabling globally, suggested enabling it for the workspace.

You haven't setup a multi-root workspace, as per the vscode documentstion: https://code.visualstudio.com/docs/editor/multi-root-workspaces. You have setup a sub folder of a workspace with some config, which is not how multi workspaces work.

**Comment by llgcode** [comment]
Hi @kitsonk, this is already a multi workspace see [workspace.code-workspace](https://github.com/llgcode/deno-client-server-ts-template/blob/master/workspace.code-workspace) and I open it using this file. Have you got a sample that work?

**Comment by kitsonk** [comment]
I just tried with this project locally: https://github.com/kitsonk/multi-root and everything works as expected, the `/server/` code is checked by Deno and the `client` code is checked with the buil-in language support.

**Comment by nhrones** [comment]
Not working on VSCode on Windows.
I downloaded your example, opened `workspace.code-workspace` in vscode

This does not work for me.
server.test.ts errors with ...
```
An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std/testing/asserts' instead.ts(2691)
```
The setting.json has an error ...
```
Unknown Configuration Setting
```
It seems you can only set Deno extension to work on the Workspace, not a folder in the workspace!
This takes care of the errors above, but now the client is a Deno folder!
``` 
// client.index.js
Unable to load a local module: "file:///C:/Users/nhron/Desktop/temp-work/multi-root/client/common".
  Please check the file path.deno(no-local)
```

**Comment by kitsonk** [comment]
@dsherret could you check the example project on windows?

**Comment by llgcode** [comment]
on my side:
![image](https://user-images.githubusercontent.com/524083/144823573-a8db9ff9-b3bf-480f-930d-ea1ff4295488.png)

**Comment by nhrones** [comment]
To enable multi-root, how should the Deno extension be configured?
```
a. Enabled Globally
b. Disabled Globally
c. Enabled Workspace
d. Disabled Workspace
```
With the extension set to enabled Workspace, Deno is enabled for the entire multi-root workspace, even with:
server.vscode.setting.json = `"deno.enable": true`
client.vscode.setting.json = `"deno.enable": false`

If you set `"deno.enable": true` in the `workspace.code-workspace` file, Deno is enabled in both client and server folders?

With any of these configuration options, Deno is either enabled in both server and client, or neither server nor client.  
What could I be doing wrong?

**Comment by nhrones** [comment]
On Windows, the following multi-root configuration is now working for me:
In VScode, the `Deno` extension is set to enabled `globally`
```
// workspace.code-workspace file
{
	"folders": [
		{
			"path": "server"
		},
		{
			"path": "client"
		}
    ],
    "settings": {
        "deno.enable": true,
    }
}
```
```
// server.vscode.settings.config
{
"deno.enable": true
}
```
```
// client.vscode.settings.config
{
"deno.enable": false
}
```

**Comment by mathe42** [comment]
I have the same problem and @nhrones doesn't fix it for me as the typescript service for the not Deno part is not enabled. I get syntaxhihlighting but nothing more.

As this semes to be a windows only bug so I think this could be a path problem as windows uses often \ and not / as path seperator...

**Comment by luisnoresv** [comment]
On mac os i put the workspace on the root folder after i install the app and then i reload vsCode 
I use this simple configuration

`
{
	"folders": [
		{
			"path": "."
		}
   ],
   "settings": {"deno.enable" : true}
}`

**Comment by snarfblam** [comment]
> I have the same problem and @nhrones doesn't fix it for me as the typescript service for the not Deno part is not enabled. I get syntaxhihlighting but nothing more.
> 
> As this semes to be a windows only bug so I think this could be a path problem as windows uses often \ and not / as path seperator...

Same here. I can only get one of two things to happen. Either Deno is enabled globally and works for Deno roots but there is no language server available for non-Deno roots, or Deno is not enabled globally and Deno roots are checked by the normal Typescript language server. There seems to be no way of fixing one without breaking the other.

Is there a definitive guide to setting up a multiroot workspace with Deno?

**Comment by mathe42** [comment]
I never got it working I use multiple vscode instances

**Comment by ragrag** [comment]
any updates or workarounds for this one? seems to still be a problem.
using windows with ```deno.enablePaths``` will make the paths defined work normally for Deno but other paths will not be working as expected with the built in TypeScript language server

**Comment by nayeemrmn** [comment]
We have `deno.enablePaths`, `deno.disablePaths`, #488 open for auto-detection. Closing in favour of that one.
