### ISSUE TITLE
Re-open 347

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/vscode_deno#584]
@kitsonk There are no import maps being used ever.

_Originally posted by @Skillz4Killz in https://github.com/denoland/vscode_deno/issues/347#issuecomment-886220902_

**Comment by kitsonk** [comment]
The issue as described in #347 cannot be occurring as described.  Import completion with import maps does not work and is covered by https://github.com/denoland/deno/issues/10951 which is still open.
