### ISSUE TITLE
auto-publish with github actions

### ISSUE THREAD

**Issue by ry** [denoland/vscode_deno#59]
are there any examples of other plugins that do this?

**Comment by ry** [comment]
https://github.com/marketplace/actions/vscode-plugin-release-action

**Comment by justjavac** [comment]
@ry official documentation https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing

Single-line command `vsce publish --yarn` can publish the extension with `VSCE_PAT`
