### ISSUE TITLE
Error when selecting linter message in jsdoc comment.

### ISSUE THREAD

**Issue by jespertheend** [denoland/vscode_deno#591]
**Describe the bug**
```
invalid parameters for "textDocument/codeAction" request
[Error - 10:12:51 PM] Request textDocument/codeAction failed.
  Message: invalid type: null, expected u32
  Code: -32602
```

**To Reproduce**

1. Download [deno_vscode_error.zip](https://github.com/denoland/vscode_deno/files/7695548/deno_vscode_error.zip)
2. Install the recommended extensions ([vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and deno.
3. Select all lines in `foo.js`

**Or to manually reproduce:**
1. `npm init`
2. `npm i eslint`
3. `npm i eslint-plugin-jsdoc`
4. Install 
5. Create `.eslintrc.json`
```json
{
	"plugins": ["jsdoc"],
	"rules": {
		"jsdoc/require-description-complete-sentence": "error"
	}
}
```
6. Create `foo.js`
```js
/**
 * This is a message
 */
function foo() {

}
```
7. Select all or hover over the linter message.

**Versions**

vscode: `1.63.0` deno: `1.16.3` extension: `3.9.2`

**Comment by kitsonk** [comment]
It appears that `vscode-eslint` is generating an invalid code action request which is being sent to the Deno language server, and the Deno language server logged the failure.

**Comment by jespertheend** [comment]
Is this something that should be fixed in `vscode-eslint`?
Fixing all the invalid positions in `eslint-plugin-jsdoc` could also be a solution, but there is a lot of rules where `eslint-plugin-jsdoc` generates invalid positions like this. So I'm not sure that'd be possible without a significant amount of work.

**Comment by kitsonk** [comment]
I'm not sure what you expect the Deno language server to do about another process that generates invalid positions that don't adhere to the publish protocol.  It can just magic up "valid" positions from an invalid message. 😕

**Comment by jespertheend** [comment]
Ah yes that makes sense. I was hoping the notifications/errors could be suppressed somehow. Logging errors isn’t an issue per se but the console pops up every time I select a wrong piece of code and it keeps spamming notifications.

**Comment by jespertheend** [comment]
This seems fixed now, either way I can no longer reproduce it.
