### ISSUE TITLE
Can not disable ts type check with vscode settings in node.js project

### ISSUE THREAD

**Issue by yoyo837** [denoland/vscode_deno#60]
Node.js project still reports ts error after disable deno in `.vscode/settings.json`

```json
"deno.enable": false
```

**Comment by justjavac** [comment]
Which version of typescript are you using in your nodejs project, VS Code's? or Workspace's?

**Comment by justjavac** [comment]
fixed via https://github.com/justjavac/typescript-deno-plugin/pull/42

**Comment by yoyo837** [comment]
I use js to code my node project, not ts.

**Comment by justjavac** [comment]
try the latest version(1.33.0)

**Comment by yoyo837** [comment]
latest version(1.24.0) Did you forget to release it.

**Comment by justjavac** [comment]
[justjavac.vscode-deno](https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno) is a daily-building version, published by me. v1.33.0 is the last version and will not be updated in the future.

[denoland.vscode-deno](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) is the official version, latest v1.24.0. published by ry. https://github.com/denoland/vscode_deno/issues/59

**Comment by yoyo837** [comment]
OK, i got it.

**Comment by lucacasonato** [comment]
Do you still encounter this error?

**Comment by lucacasonato** [comment]
Extension is disabled by default now. For other node compat issues refer to https://github.com/denoland/vscode_deno/issues/314
