### ISSUE TITLE
EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by kinghat** [denoland/vscode_deno#609]
**Describe the bug**
i get this extension error when opening vscode. no project dir or workspace:
> EOF while parsing a value at line 1 column 0

**To Reproduce**
1. have vscode_deno installed
2. open vscode with empty untitled document

**Expected behavior**
deno extension/language server shouldnt load, run or error :thinking: 

**Screenshots**
![image](https://user-images.githubusercontent.com/16073360/149461814-b27cf2c0-ab2c-4048-bdd1-d2be6d2ccff9.png)

**Versions**
vscode_deno: 3.10.0
> Starting Deno language server...
  version: 1.17.3 (release, x86_64-unknown-linux-gnu)
  executable: /home/kinghat/.deno/bin/deno
Connected to "Visual Studio Code" 1.63.2
{"type":"mark","name":"update_cache"},
{"type":"measure","name":"update_cache","count":1,"duration":0},
{"type":"mark","name":"update_tsconfig"},
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"configure","compilerOptions":{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window"],"module":"esnext","noEmit":true,"resolveJsonModule":true,"strict":true,"target":"esnext","useDefineForClassFields":true,"useUnknownInCatchVariables":false}}},
{"type":"measure","name":"request","count":1,"duration":5},
{"type":"measure","name":"update_tsconfig","count":1,"duration":203},
{"type":"mark","name":"request","count":2,"args":{"id":3,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":2,"duration":1},
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
Enabling import suggestions for: https://deno.land
Download https://deno.land/.well-known/deno-import-intellisense.json
Enabling import suggestions for: https://cdn.nest.land
{"type":"measure","name":"initialize","count":1,"duration":1114},
language server initialized
Server ready.

> Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-46-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 11.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500

**Comment by Jamalam360** [comment]
I get the same error, recurs every 5 or so minutes when I'm just normally going about my business. Zorin OS, I can provide more specs and details if you need.

**Comment by kitsonk** [comment]
@kinghat I tried to recreate it, but was unable.

Could you please recreate it and then provide the contents of document that can be view by selecting _Deno: Language Server Status_ from the command pallette?

**Comment by kinghat** [comment]
> @kinghat I tried to recreate it, but was unable.
> 
> Could you please recreate it and then provide the contents of document that can be view by selecting _Deno: Language Server Status_ from the command pallette?

# Deno Language Server Status

## Workspace Settings

```json
{
  "enable": false,
  "cache": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": true,
    "references": true,
    "referencesAllFunctions": true,
    "test": true
  },
  "internalDebug": true,
  "lint": false,
  "suggest": {
    "completeFunctionCalls": true,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://crux.land": true,
        "https://deno.land": true,
        "https://cdn.nest.land": true
      }
    }
  },
  "unstable": false
}
```

## Workspace Details

  - <details><summary>Documents in memory: 0</summary>

    - 

  </details>

  - <details><summary>Performance measures: 6</summary>

    - initialize (161ms)
    - update_import_map (0ms)
    - request (0ms)
    - update_tsconfig (156ms)
    - request (1ms)
    - update_cache (0ms)

  </details>

## Performance

|Name|Duration|Count|
|---|---|---|
|initialize|161ms|1|
|request|1ms|2|
|update_cache|0ms|1|
|update_import_map|0ms|1|
|update_tsconfig|156ms|1|

**Comment by kinghat** [comment]
the deno path setting was empty but had the blue highlight like it had been changed, i reset that to default and it looks like the issue went away for now :man_shrugging: 

![image](https://user-images.githubusercontent.com/16073360/149632838-6e7caabf-b1ad-418a-808b-02053f39d34c.png)

**Comment by kitsonk** [comment]
@kinghat there are several settings that are not their default setting.  Have you modified your user configuration defaults, if so, why?

Specifically these are not their default value:

- `deno.codeLens.implementations` should be `false`
- `deno.codeLens.references` should be `false`
- `deno.codeLens.referencesAllFunctions` should be `false`
- `deno.internalDebug` should be `false`

That being said, looking at the output, I am seeing this:

```
Enabling import suggestions for: https://deno.land
Download https://deno.land/.well-known/deno-import-intellisense.json
Enabling import suggestions for: https://cdn.nest.land
```

And it seems to stop before getting to the third one that is autoconfigured.  Do you happen to be in a location that restricts connectivity, like the China and dealing with the GFC?  I think we need to handle "bad" or "unavailable" registry configuration files better than we do at the moment, as I suspect a blocked/bad/whatever config file is being served and this is causing the error to be sent to the client, while it should just be logged to the debug output and ignored.

**Comment by kinghat** [comment]
> @kinghat there are several settings that are not their default setting. Have you modified your user configuration defaults, if so, why?
> 
> Specifically these are not their default value:
> 
>     * `deno.codeLens.implementations` should be `false`
> 
>     * `deno.codeLens.references` should be `false`
> 
>     * `deno.codeLens.referencesAllFunctions` should be `false`
> 
>     * `deno.internalDebug` should be `false`
> 

i dont remember changing those or why. i removed and installed the extension prior to filing the bug, figuring it would bring defaults, which might not have been the case with the settings sync turned on :man_shrugging: 

> That being said, looking at the output, I am seeing this:
> 
> ```
> Enabling import suggestions for: https://deno.land
> Download https://deno.land/.well-known/deno-import-intellisense.json
> Enabling import suggestions for: https://cdn.nest.land
> ```
> 
> And it seems to stop before getting to the third one that is autoconfigured. Do you happen to be in a location that restricts connectivity, like the China and dealing with the GFC? I think we need to handle "bad" or "unavailable" registry configuration files better than we do at the moment, as I suspect a blocked/bad/whatever config file is being served and this is causing the error to be sent to the client, while it should just be logged to the debug output and ignored.

im in the US. it looks like `v3.10.1` has fixed the issue though. i also have hopefully set everything back to defaults now. i will close the issue as fixed after i play with it for a couple days if thats ok?

**Comment by kitsonk** [comment]
Well there is denoland/deno#13383 that needs to be fixed, because there is a real issue there.

**Comment by kinghat** [comment]
> Well there is denoland/deno#13383 that needs to be fixed, because there is a real issue there.

I'll just leave this open to be closed with that.

**Comment by jespertheend** [comment]
I started getting this today as well. I'm on `v3.10.1`. I think nest.land is occasionally having connection issues because x.nest.land is the last entry for me as well.

**Comment by johnbendi** [comment]
@kitsonk  Now that [#13418](https://github.com/denoland/deno/pull/13418) is closed. What next?

**Comment by binyamin** [comment]
@kitsonk This is still breaking for me. What causes this error?

**Comment by binyamin** [comment]
> This is still breaking for me. What causes this error?

For me, the solution was to reload the "import registries cache".
