### ISSUE TITLE
Cannot find module 'react-redux'. or any js module

### ISSUE THREAD

**Issue by Mzaien** [denoland/vscode_deno#61]
### used **React** latest version  in vscode
i think it forces all imports to be in ts but i'm not using it **so...**

![The vscode issue](https://user-images.githubusercontent.com/43112535/83052551-282faa00-a058-11ea-8163-5b19b8d6ea4a.png)

even tho the app is working but it is _annoying_  😀

**Comment by justjavac** [comment]
see https://github.com/denoland/vscode_deno/issues/39

**Comment by lucacasonato** [comment]
The extension is disabled by default now, so only projects that explicitly enable the extension via the vscode **project** settings will use it. The extension will not interfere with Node projects anymore.
