### ISSUE TITLE
`typescript-deno-plugin` re-uses instances when "muting" results

### ISSUE THREAD

**Issue by heroboy** [denoland/vscode_deno#614]
Install this extension in vscode.

https://marketplace.visualstudio.com/items?itemName=heroboy.generate-switch-case-for-enum-type

Looks like the "Generate Switch Case" menu item is never being removed. It will become more and more.

![图片](https://user-images.githubusercontent.com/54468/151118380-107f2172-3776-41ed-bd85-1be3825e508c.png)

**Comment by kitsonk** [comment]
This is not an issue with the Deno language server, so moved to vscode_deno.

The extension uses a TypeScript language service plugin to function.  When Deno is enabled for a workspace, it "mutes" a lot of the language server messages and that muting is likely causing an issue with the extension.  It would seem the muting of the built in language server and this extension are not compatible.  We cannot really "unmute" the built in language server when

If you can provide more information about what is missing and causing the extension to generate excessive quick fixes it might be possible to modify the [typescript-deno-plugin](https://github.com/denoland/vscode_deno/blob/main/typescript-deno-plugin/src/index.ts) to be able to accomodate things, but also the language server plugin could be changed to ensure it doesn't generate excessive quick fixes.

**Comment by heroboy** [comment]
I think this is a language server issue. Because the code is executed in the lsp process. In vscode side, it tells the lsp which plugins to load.
So what about just disable all these plugins? Becuase they are designed for original typescript language server.

**Comment by kitsonk** [comment]
The LSP does not load any language server plugins.  This extension code does not touch the Deno LSP at all.  The Deno LSP does not support, recognise, load, whatever language server plugins.

The "original TypeScript language server" is still running in the background on vscode when Deno is enabled.  `vscode_deno` uses the `typescript-deno-plugin` mentioned above as a language server plugin to the built in TypeScript language server to "mute" diagnostics coming from the built in language server.

Trust me, I know how it works, since I wrote the code.

**Comment by heroboy** [comment]
Thank you for your explanation. I am sorry for the wrong guess.
Here is part of the plugin code, and I add some logs:
```javascript
//proxy the function according to 
//https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin
proxy.getApplicableRefactors = function (fileName, positionOrRange) {
	logx('start getApplicableRefactors');
	//call the original function
	var refactors = info.languageService.getApplicableRefactors.apply(this, arguments) || [];
	var isadd = false;
	if ( /* some condition */ ) {
		isadd = true;
		//add the menu item
		refactors.push({
			name: 'generate-switch-case',
			description: 'generate switch case desc',
			actions: [{ name: 'generate-switch-case', description: 'Generate Switch Case' }]
		});
	}
	logx('end getApplicableRefactors add=' + isadd + ', length=' + refactors.length);
	return refactors;
};
```
Here is the log output:
```
[6376]2022-01-27T05:27:38.529Z:  start getApplicableRefactors
[6376]2022-01-27T05:27:38.534Z:  end getApplicableRefactors add=true, length=1  (when cursor move to 'switch')
[6376]2022-01-27T05:27:45.191Z:  start getApplicableRefactors
[6376]2022-01-27T05:27:45.192Z:  end getApplicableRefactors add=true, length=2 (when cursor move to 'switch')
[6376]2022-01-27T05:27:49.769Z:  start getApplicableRefactors
[6376]2022-01-27T05:27:49.769Z:  end getApplicableRefactors add=true, length=3 (when cursor move to 'switch')
[6376]2022-01-27T05:27:54.670Z:  start getApplicableRefactors
[6376]2022-01-27T05:27:54.670Z:  end getApplicableRefactors add=false, length=3 (when cursor move to somewhere else)
[6376]2022-01-27T05:27:54.864Z:  start getApplicableRefactors
[6376]2022-01-27T05:27:54.864Z:  end getApplicableRefactors add=false, length=3
[6376]2022-01-27T05:28:14.451Z:  start getApplicableRefactors
[6376]2022-01-27T05:28:14.451Z:  end getApplicableRefactors add=false, length=3
[6376]2022-01-27T05:28:19.082Z:  start getApplicableRefactors
[6376]2022-01-27T05:28:19.083Z:  end getApplicableRefactors add=false, length=3
```
And this is the ts server log
```
Info 32   [13:27:35.202] Loading generate-typescript-switch-case-for-enum-type-language-service-plugin from c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features (resolved to c:/Program Files/Microsoft VS Code/resources/app/extensions/typescript-language-features/node_modules)
Info 33   [13:27:35.203] Loading generate-typescript-switch-case-for-enum-type-language-service-plugin from c:\Users\herob\.vscode\extensions\denoland.vscode-deno-3.10.1 (resolved to c:/Users/herob/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules)
Info 34   [13:27:35.204] Loading generate-typescript-switch-case-for-enum-type-language-service-plugin from c:\Users\herob\.vscode\extensions\heroboy.generate-switch-case-for-enum-type-0.0.9 (resolved to c:/Users/herob/.vscode/extensions/heroboy.generate-switch-case-for-enum-type-0.0.9/node_modules)


....
....


Info 113  [13:27:38.529] request:
    {"seq":10,"type":"request","command":"getApplicableRefactors","arguments":{"file":"d:/project/TestDeno/main.ts","startLine":7,"startOffset":6,"endLine":7,"endOffset":6}}
Perf 114  [13:27:38.534] 10::getApplicableRefactors: elapsed time (in milliseconds) 5.2347
Info 115  [13:27:38.534] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":10,"success":true,"body":[{"name":"generate-switch-case","description":"generate switch case desc","actions":[{"name":"generate-switch-case","description":"Generate Switch Case"}]}]}
Info 125  [13:27:45.191] request:
    {"seq":14,"type":"request","command":"getApplicableRefactors","arguments":{"file":"d:/project/TestDeno/main.ts","startLine":7,"startOffset":7,"endLine":7,"endOffset":7}}
Perf 126  [13:27:45.192] 14::getApplicableRefactors: elapsed time (in milliseconds) 1.0016
Info 127  [13:27:45.192] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":14,"success":true,"body":[{"name":"generate-switch-case","description":"generate switch case desc","actions":[{"name":"generate-switch-case","description":"Generate Switch Case"}]},{"name":"generate-switch-case","description":"generate switch case desc","actions":[{"name":"generate-switch-case","description":"Generate Switch Case"}]}]}





```

Because I log the pid, I believe the plugin is not loaded in the `deno.exe`. 
But I find the deno code load the `tsc`, and process the lsp json. I really don't know how deno lsp works.
So I make above test, hope it will help you to find what is the problem.

**Comment by heroboy** [comment]
I know what's the problem. See the code:
```
const callIfDisabled: CallIfDisabledFunction = (
      fn,
      fileNameArg,
      emptyReturn,
    ) => {
      // deno-lint-ignore no-explicit-any
      const target = (ls as any)[fn];
      return (...args) => {
        const enabled = fileNameArg !== undefined
          ? this.#getSetting(args[fileNameArg] as string, "enable")
          : this.#getGlobalSettings().enable;
        return enabled ? emptyReturn : target.call(ls, ...args);
      };
    };
const getApplicableRefactors = callIfDisabled(
      "getApplicableRefactors",
      0,
      [],
    );
```
When `callIfDisabled` is called. The `emptyReturn` is always been the same instance. So if someone get the return value `emptyReturn`, and push something. Then the `emptyReturn` eternally be modified.
So is it my fault that I modified the return value `refactors`, or I should treat it as read only array and copy it.

**Comment by kitsonk** [comment]
Both, I guess.  We shouldn't re-use arrays like that, but also I think if you are proxying things, you shouldn't just append to arrays.

I will fix `typescript-deno-plugin`.
