### ISSUE TITLE
"Format Document" with deno,  doesn't comply with deno.json, prettier or editorconfig.

### ISSUE THREAD

**Issue by Abhinav1217** [denoland/vscode_deno#616]
**Describe the bug**
I have the following structure currently
```
Data-Structures/
--------------- Javascript/
---------------------------- Stacks.js
---------------------------- Sets.js
---------------------------- .editorconfig
---------------------------- .prettierrc
---------------------------- deno.json
```

In `.editorconfig`, `.prettierrc` and `deno.json` , I have configured tab width to be of size 4. 
I have also made sure that deno is the default formatter for js files. 
But still when I save file, or use "Format Document" from command pallet, My file is saved with tab width of 2. 
When I use `deno fmt Stacks.js` from terminal, it does follow the configuration, also when I change formattor to vscode-inbuilt or prettier, using "Format Document with ..." option, they all follow my configuration, except deno extension. 

> **P.S.**
I initially had the config files at the root of workspace, but when It didn't work, I moved them to the same level as the working file, it still didn't work. 

**To Reproduce**

1. Install Deno Extension in vscode.
2. Enable linting in "Deno: Initilize Workspace Configuration".
3. Create relevent deno config file, set `indentWidth: 4` in deno.json
4. Choose Deno as default formattor for JS files. 
5. Create a js file and format it using "Format Document" option in command pallet

**Expected behavior**
The files should be indented with configured width value of 4, not with 2 which I assume is default value.

**Screenshots**
![Indenting with only 2 spaces](https://user-images.githubusercontent.com/740584/151777829-bb8b96e0-6ae4-4999-a026-17a133f56921.png)

![Deno is set as default formattor](https://user-images.githubusercontent.com/740584/151777951-ad8cd19d-9df7-457b-850c-0b5da0d0aae4.png)

**Versions**

**vscode:** 
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-17T15:31:24+02:00
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.21-210.current

**deno:** 
deno 1.18.1 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2

**extension:**

v3.10.1

**Comment by jsejcksn** [comment]
See https://github.com/denoland/vscode_deno/issues/660#issuecomment-1135262165

**Comment by rollercodester** [comment]
This is still an issue as of evaluating latest Deno in 11/2022. My team is accustomed to format on save in VS Code and the `deno.jsonc` is not being honored on save whereas `Format document with...` Deno does honor the config as does cmd line fmt command.

**Comment by bbqsrc** [comment]
Yes, this behaviour continues.

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/vscode_deno/issues/933#issuecomment-1731884519
