### ISSUE TITLE
deno-ts reports no class property initializer errors in vscode also when disabled

### ISSUE THREAD

**Issue by SalvatorePreviti** [denoland/vscode_deno#618]
**Describe the bug**

deno-ts missing class initializer error squiggles are enabled also if deno extension is disabled

**To Reproduce**

1. open a node project in vscode
2. (optional) set .vscode/settings.json "deno.enable": false
3. write a class with not initialized fields

It shows "Property 'property' has no initializer and is not definitely assigned in the constructor.deno-ts(2564)"

**Expected behavior**

No error is shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/6913178/151992780-7548cffd-0ef9-4523-bb6e-f83a59bb7acc.png)

**Versions**

vscode: Version: 1.63.2 (Universal)
deno extension: v3.10.1
deno: deno 1.18.1 (release, aarch64-apple-darwin)

**Comment by kitsonk** [comment]
Can you provide the output of _Deno: Language Server Status_ from the command palette when this occurs?

**Comment by SalvatorePreviti** [comment]
Starting Deno language server...
  version: 1.18.1 (release, aarch64-apple-darwin)
  executable: /Users/sp/.deno/bin/deno
Connected to "Visual Studio Code" 1.63.2
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://deno.land
language server initialized
Server ready.

**Comment by SalvatorePreviti** [comment]
![image](https://user-images.githubusercontent.com/6913178/152181587-01dbfcb7-1924-43eb-b657-bed652b32203.png)

**Comment by SalvatorePreviti** [comment]
Of course, disabling the extension globally solves the problem.

**Comment by SalvatorePreviti** [comment]
Deno Language Server Status:

{
  "enable": false,
  "cache": null,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": true
  },
  "internalDebug": false,
  "lint": false,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://crux.land": true,
        "https://x.nest.land": true,
        "https://deno.land": true
      }
    }
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": false
}


Workspace Details
Documents in memory: 2
file:///..../Code/User/settings.json
file:///..../bp-sap/xxx.ts
Performance measures: 16
update_diagnostics_ts (775ms)
request (772ms)
did_close (0ms)
did_open (0ms)
op_get_text (0ms)
op_get_length (0ms)
update_diagnostics_lint (0ms)
update_diagnostics_deps (0ms)
did_open (0ms)
initialize (740ms)
update_registries (696ms)
update_import_map (0ms)
request (0ms)
update_tsconfig (43ms)
request (0ms)
update_cache (0ms)

**Comment by SalvatorePreviti** [comment]
Weirdly enough it happens also with other errors - 
```
var process: NodeJS.Process
Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.deno-ts(2580)
```

**Comment by hazae41** [comment]
Same error on Windows when opening a Next.js app

```
Starting Deno language server...
  version: 1.18.1 (release, x86_64-pc-windows-msvc)
  executable: C:\ProgramData\chocolatey\lib\deno\deno.exe
Connected to "Visual Studio Code" 1.64.2
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://deno.land
language server initialized
Server ready.
```

No User settings or Workspace settings are set

**Comment by barnabasmolnar** [comment]
Quick update:

Upgraded to deno v1.19.3 and the issue seems to have disappeared. Was on v1.18.1 previously.

**Comment by bartlomieju** [comment]
I believe this is now fixed. Please let me know if the problem persists with latest Deno version.
