### ISSUE TITLE
Path Autocomplete on Windows is broken

### ISSUE THREAD

**Issue by lts20050703** [denoland/vscode_deno#623]
### Describe the bug

Autocomplete turn `export * from "./folderOrFileName"` to `export * from "../../ ... /../../C:/Users/lts20050703/ ... /folderOrFilename"` (`...` is not literally `...`, it's a placeholder for a bunch of `..` and a bunch of folder name, respectively)

### To Reproduce

1. Type `export * from "./folderOrFileName"`
2. Press Tab or Enter to Autocomplete
3. Observe it Autocomplete to `export * from "../../ ... /../../C:/Users/lts20050703/ ... /folderOrFilename"` (`...` is not literally `...`, it's a placeholder for a bunch of `..` and a bunch of folder name, respectively)

### Expected behavior

It autocomplete to `export * from "./folderOrFileName"`

### Recording

https://user-images.githubusercontent.com/87189679/153402239-2f48b049-7fae-4898-bfec-dca2611184e4.mp4

### Versions

windows 11

vscode 1.65.0-insider (user setup)

deno 1.18.2+2f2c778 (canary, x86_64-pc-windows-msvc)
v8 9.9.115.5
typescript 4.5.2

extension 3.10.1

**Comment by bartlomieju** [comment]
I believe this is now fixed, we have greatly improvement path handling since Deno v1.18.
