### ISSUE TITLE
Enabling Deno for a single folder in a multi-root workspace results in TS checking for all folders

### ISSUE THREAD

**Issue by khaled** [denoland/vscode_deno#624]
**Describe the bug**

If I enable Deno for a single folder in a multi-root workspace, the type checker checks TS in other folders as well.

Also, if I have multiple workspaces open (multiple vscode windows) with Deno enabled in only one, files in the other workspace(s) are checked by Deno when they shouldn't be.

I've made sure that Deno is not enabled at the user and workspace levels.

These multi-root / multi-workspace setups worked just fine until I recently installed a vscode update (within the past two weeks).  So I believe the breakage started with vscode 1.64, but I'm not 100% certain.

**To Reproduce**

1. Add two folders to a workspace
2. Add a typescript file with error(s) to each folder
3. Go to settings, and select one of the folders from the dropdown, and check the Deno:enable box.
4. Hover over errors in the typescript file within the folder for which Deno is disabled.  Notice that it says `deno-ts` in the hover popup, indicating that it came from the Deno extension.  In my case I see both `ts` and `deno-ts`, indicating that both language servers are checking the file.

**Screenshot**

<img width="890" alt="Screen Shot 2022-02-17 at 3 32 22 PM" src="https://user-images.githubusercontent.com/11412/154566147-9d07cdc5-4e8b-44f7-8ab5-4dc496d863b6.png">

**Expected behavior**

Deno checks only the folders/worskapces for which it is enabled.

**Versions**

vscode: Version: 1.64.2
deno: 1.18.1
extension: 3.10.1

**Comment by locriacyber** [comment]
this plugin does not support folder settings, only workspace settings

**Comment by Leokuma** [comment]
Related #713

**Comment by bartlomieju** [comment]
Do you still experience this problem with latest Deno version @Leokuma?

**Comment by Leokuma** [comment]
@bartlomieju It's fixed. #713 is fixed as well.

**Comment by bartlomieju** [comment]
Great, thanks for getting back to me!
