### ISSUE TITLE
Make sending initial workspace config less fragile

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#634]
Currently, when we add a config setting that the server needs to know about, we send the settings in the initial initialisation it uses the top level keys of the settings of the `deno` namespace to copy values into the response:

https://github.com/denoland/vscode_deno/blob/e5db81f2799af1896e04750b23cb8cf190b39ea6/client/src/extension.ts#L24-L39

This is fragile because if they are missed, there is no error, the server config simply is not accurate if an option has changed from its default.

See: #632

**Comment by nayeemrmn** [comment]
This is addressed: https://github.com/denoland/vscode_deno/blob/17fd0b2f327eb3e075900bced5ecce8fe73cba66/client/src/extension.ts#L129-L136
