### ISSUE TITLE
No intelisense for implementation of a interface created dynamically from an object's keys.

### ISSUE THREAD

**Issue by Khilseith** [denoland/vscode_deno#646]
**Describe the bug**
If I create an interface from all the keys of an object that's been defined I do not get intelisense for the needed properties when implementing that interface in a class.

**To Reproduce**

```ts
const object = {
    foo: "bar",
    fizz: "buzz",
};
type interfaceVar = {
    [key in (keyof typeof object)]: boolean;
};
class classVar implements interfaceVar {
    // Should get intelisense here for foo and fizz but I do not
}
```
![intelisenseNotWorking](https://user-images.githubusercontent.com/78451857/161191058-d1b3924f-7dc6-4aca-a01b-3d205d2abbf1.png)
**Expected behavior**
However if I clearly define these properties of an interface such as
```ts
type interfaceVar2 = {
    foo: boolean
    fizz: boolean
}
```
I get intelisense for its implementation
![intelisenseWorking](https://user-images.githubusercontent.com/78451857/161190986-865204e3-8985-48da-8395-8d332fb17c2a.png)

The extension seems keenly aware of what properties I am missing all the while.
![Error](https://user-images.githubusercontent.com/78451857/161191208-49402d31-e550-49b5-b6c4-2cd0bbe4f4bc.png)

**Versions**

vscode: 1.66.0 deno: 1.20.4 extension: 3.12.0

**Comment by kitsonk** [comment]
That appears to be exactly the behaviour you would get in a standard TypeScript language service.

You will get exactly the same behaviour in this [TypeScript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArApsWBeGBvAUDfMAZiCAFwwBE8AhgE4UA0eBhAlgF7vlUCunjOAL4BuHFACeAB2QxWYKMlqFqwZADU6MTLgIwA2gGtk42WBgAKI+JCEYE6TbhJUUAJQBdcvBIAbZNTBRERxgH2oICBhQ8IgNWlkAW0k-BOR5SLkFJRV1TR0CAHoCoTEpGUzFZVU4gCYtbGZ8YjIYbxA-ANFdNk4vX39AkuiIqLCI2sTk5FT00yyq3No6-PwioSA).

If you think it is an issue, you will need to raise it with TypeScript project directly, and if fixed, Deno regularly updates to the latest GA release of TypeScript.
