### ISSUE TITLE
deno.config is not relative to the workspace settings

### ISSUE THREAD

**Issue by iacore** [denoland/vscode_deno#647]
**Describe the bug**

**To Reproduce**

- Workspace at `a/sample.workspace`
- Workspace has two folders
  - `a/b`
  - `a/c`
- Workspace has `deno.config` set to "./b/deno.jsonc"
- There is a config file at "a/b/deno.jsonc"

**Expected behavior**

This extension should find the config file.

**Screenshots**

This extension cannot find the config file.

**Versions**

vscode: 1.65.2 deno: 1.20.1 extension: 3.12.0

**Comment by bartlomieju** [comment]
Hey @iacore, sorry for a slow response. Do you still experience this problem with latest Deno version?

**Comment by iacore** [comment]
Seems to be fixed
