### ISSUE TITLE
Update docs about testing code lens

### ISSUE THREAD

**Issue by cdaringe** [denoland/vscode_deno#648]
**Describe the bug**

codelens not rendered by default, against expectation.

The README and the package.json are out of sync.

**README**:

> deno.codeLens.test: Enables or disables the display of test code lens on Deno tests. boolean, default true.

**package.json**

```json
        "deno.codeLens.test": {
          "type": "boolean",
          "default": false,
```
https://github.com/denoland/vscode_deno/blob/2bcd2454a7dd9c82b81057dfd6ca3dd37ea7762b/package.json#L205-L207

Which is correct?

**To Reproduce**

1. install the ext
2. open a test in your editor
3. observe no code lens

**Expected behavior**

codelens appears.

**Screenshots**

n/a

**Versions**

n/a

**Comment by kitsonk** [comment]
This change was made in advance of the testing API coming in 1.21. We can only have one set of defaults. I will update the doc.
