### ISSUE TITLE
Files are not unconditionally treated as modules

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/vscode_deno#65]
![image](https://user-images.githubusercontent.com/28331609/83133258-2d9efa00-a115-11ea-869e-cc72566ed593.png)
![image](https://user-images.githubusercontent.com/28331609/83133288-3bed1600-a115-11ea-81cc-29e9aa3b4f71.png)

**Comment by zhmushan** [comment]
Please describe in English, if you want to get help from community.

**Comment by TTSKarlsson** [comment]
I believe it is global space unless you export something, at least in typescript.

**Comment by chenguzhen87** [comment]
vscode prompt
![image](https://user-images.githubusercontent.com/28331609/83213304-69c56f80-a194-11ea-81fd-ed5a94f4d3de.png)

**Comment by chenguzhen87** [comment]
justjavac replied：
![image](https://user-images.githubusercontent.com/28331609/83215160-d6db0400-a198-11ea-8987-728f4ce2c302.png)
Interim solutions：
export {}

**Comment by lucacasonato** [comment]
Should be resolved in version 3.x of the extension.
