### ISSUE TITLE
deno.enablePaths does not work

### ISSUE THREAD

**Issue by Jamesmjkim** [denoland/vscode_deno#652]
**Describe the bug**
I am working on a project with deno backend and react frontend. I have tsconfig file for the frontend and using the .vscode/settings.json for the backend. I am trying to use the "deno.enablePaths" for deno language on just the backend files, but for some reason its on the frontend files as well. 

**To Reproduce**

1. create settings.json file with deno.enable, deno.lint, and deno.unstable set to true
2. also in settings.json add another property deno.enablePaths with value ["./server"]
3. npm i react
4. create another folder "src" in root directory with .tsx file with import * as React from 'react'

**Expected behavior**
I expected that src folder will be ignored from the deno langauge and use the default language to vscode. Instead, I am getting deno error in the .tsx file which is in another file. Deno language is working in the server folder. 

**Screenshots**
![Screen Shot 2022-04-09 at 3 45 00 PM](https://user-images.githubusercontent.com/88161114/162589433-b4198623-be79-453b-9cde-16ccb6524162.png)
As you can see there is a deno error in a file that is not in the server file. 

![Screen Shot 2022-04-09 at 3 47 59 PM](https://user-images.githubusercontent.com/88161114/162589469-dd60f7f2-87a2-4f7a-9833-d1a52a750d64.png)
Folder structure

![Screen Shot 2022-04-09 at 3 48 06 PM](https://user-images.githubusercontent.com/88161114/162589476-48f9e068-87e4-49c2-80c5-d7dc66e5fd3f.png)
settings.json

**Versions**

vscode: 1.66.1  deno: 1.18.2 extension: 3.12.0

**Comment by kitsonk** [comment]
That version of Deno does not support the enable paths option. You need to upgrade to 1.20.2 or later for that feature to be supported.

**Comment by Jamesmjkim** [comment]
Thank you for that! It is working now!
