### ISSUE TITLE
vscode stuck in fetching buildtasks

### ISSUE THREAD

**Issue by bxantus** [denoland/vscode_deno#654]
**Describe the bug**
With the newest deno upgrade vscode is stuck in fetching build tasks. 
Everything works, but my deno tasks (from `tasks.json`) aren't available, so I can' run my build scripts using deno from vscode.

**To Reproduce**

1. Create a `"deno"` type build tasks in vscode (tasks.json), like:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build something",
            "type": "deno",

            "command": "run",
            "args": [
                "--unstable",
                "-A",
                "build/compile.ts",
              ],
            "group": "build",
            "problemMatcher":"$deno",
        }
    ]
}
```
2. Try to run your build tasks (Ctrl+Shift+B)

**Expected behavior**
Build task discovered by vscode, and able to run it.

**Notes:**
I think this probably has something to do with the tasks implementation in deno lsp. When I downgraded deno back to 1.20.4, everything works fine.

Also I have deno.jsonc files in my project, but have no tasks defined in them.

**Versions**

vscode: 1.66.1 deno: 1.20.5 extension: 3.12.0

**Comment by jespertheend** [comment]
I'm seeing this even without adding any `"deno"` type tasks. I've only added three `"npm"` type tasks but neither of them work. Any auto discovered npm tasks are affected as well.

**Comment by jespertheend** [comment]
After a quick bisect I ended up with https://github.com/denoland/deno/commit/a6e4b4297d840e9cfe4bdf373f24da8202f58e2d

**Comment by gm112** [comment]
I just want to provide a quick update, this is still an issue as of May 22nd, 2022 with Deno 1.22.0, extension v3.12.0, if that helps any.

**Comment by bxantus** [comment]
@dsherret: when can we expect a new build which includes this fix?
It's great that the fix is merged, but I still use my own .vsix package, as the latest version still doesn't include this change...
I think it's worth to create a patch release for this.

**Comment by dsherret** [comment]
Just kicked off a release now. Should be up in half an hour or so.
