### ISSUE TITLE
Extension 'Deno' .... cannot format 'JavaScript' files

### ISSUE THREAD

**Issue by piscisaureus** [denoland/vscode_deno#657]
Happened while working on Deploy; deno had not been enabled in the vscode workspace. 
However I don't think we should refuse to format files when asked.

### screenshot

![image](https://user-images.githubusercontent.com/218257/164054636-a5052345-2747-4497-a510-82d4cb5af5b4.png)

### version info

* deno v1.20.6
* vscode 1.66.2
* vscode-deno v3.12.0

**Comment by vanntile** [comment]
It might be because it can't do "modifications" type formatting, from your VSCode settings. Try adding `"editor.formatOnSaveMode": "file"` in your workspace's `settings.json`

**Comment by kitsonk** [comment]
The format function is independent from a workspace being disable or enabled for Deno.  This is effectively expected and the formatting can be configured independently.  For example, I have Deno as my default formatter, irrespective of the project being enabled, replacing prettier.

**Comment by eric-burel** [comment]
I am still a bit confused on how to pick the right formatter only for the Deno subpath, eg I have a mono repo with a Deno "/api" and a classival Vite "/webapp":
```json
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.codeLens.implementations": true,
    "deno.codeLens.referencesAllFunctions": true,
    "deno.importMap": "./api/import_map.json"
}
```
How can I use "deno" as the default formatter for the "./api" folder (if it's even possible)?

Also I hit a "Deno cannot format TypeScript files error" when trying to make it the default formatter.

**Comment by bartlomieju** [comment]
Seems exactly the same as https://github.com/denoland/vscode_deno/issues/840

**Comment by bartlomieju** [comment]
Please see https://github.com/denoland/vscode_deno/issues/860#issuecomment-1642655153
