### ISSUE TITLE
Support additional  deno fmt options

### ISSUE THREAD

**Issue by chompomonim** [denoland/vscode_deno#660]
`deno fmt` has some nice options which are not possible to set with `vscode_deno` plugin in `settings.json`.

 For most wanted are:
— options-indent-width: If specified, the provided indent width would be used. The default is 2.
— options-line-width: If specified, this sets the maximum line width for code. Once the width reaches, the line is broken into multiple lines. The default is 80 (seems a bit outdated for current standards).

**Comment by jsejcksn** [comment]
Those settings can be configured using a [configuration file](https://deno.land/manual@v1.22.0/getting_started/configuration_file):

`./deno.jsonc`:
```jsonc
{
  "fmt": {
    "options": {
      "indentWidth": 4,
      "lineWidth": 160
    }
  }
}

```

Add the config file in your VS Code config:

`./.vscode/settings.json`:

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "deno.config": "./deno.jsonc"
}

```

Then, whenever you use the command palette in VS Code to format your document (e.g. `Format Document` or `Format Document With... > Deno`), the settings in your config file will be used.

**Comment by mmazzarolo** [comment]
@jsejcksn for what is worth, I'm also seeing vscode_deno not respecting the deno config. 

`./.vscode/settings.json`:

```json
{
  "deno.enable": true,
  "deno.unstable": true,
  "deno.lint": true,
  "editor.rulers": [120],
  "deno.config": "./deno.jsonc"
}
```

`./deno.jsonc`:

```json
{
  "fmt": {
    "options": {
      "lineWidth": 120
    }
  }
}
```

Extension version: 3.13.0

Not a deal breaker for me, but if starts bothering me or if I have some time I'll investigate further 👍

**Comment by kitsonk** [comment]
As noted, these options can be applied and will be respected when the editor requests Deno to format a file.  There is an issue with things like completions and quick fixes which do not respect these settings (but will get fixed on formatting though) which is covered by denoland/deno#16083.
