### ISSUE TITLE
Complains about checking for the document

### ISSUE THREAD

**Issue by ayoreis** [denoland/vscode_deno#662]
The Deno VS Code extension gives an error when you check for the `document`. I found this when writing a condition to check if the code was being run on the browser — `if (!document)`, which gives this error:

> Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.deno-ts(2584)

I think it should complain if you are not checking, though not when you are, right?

VS Code: 1.66.2, Deno: 1.21.1, Extension: 3.12.0

**Comment by jsejcksn** [comment]
You can satisfy the compiler for this check like so:

```ts
if ((window as any).document) {
  // Do something with the document
}
```

However, the suggestion is a useful one: if you will be accessing the `document` (which is actually [`window.document`](https://developer.mozilla.org/en-US/docs/Web/API/Window/document)), you should include `"dom"` in your `compilerOptions.lib` array, else you will continue to encounter type issues when accessing properties on the `document` object.
