### ISSUE TITLE
Add custom icons for deno.json(c) files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/vscode_deno#663]
`vscode_deno` should add custom icons for `deno.json` and `deno.jsonc` files so they are easily distinguishable among other icons.

https://code.visualstudio.com/api/extension-guides/file-icon-theme

**Comment by ayoreis** [comment]
A PR for this was made to: https://github.com/vscode-icons/vscode-icons/issues/2964

**Comment by kitsonk** [comment]
This was merged upstream.
