### ISSUE TITLE
Launching server using command deno failed.

### ISSUE THREAD

**Issue by AmelloAster** [denoland/vscode_deno#667]
**Describe the bug**

**To Reproduce**

1.install deno and start vscode is not working

**Screenshots**

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/26178326/168427992-c01799a8-0f86-4c00-a995-b29978327f69.png">

**Versions**

vscode: Version: 1.68.0-insider (Universal)OS: Darwin arm64 21.4.0 deno: Deno 1.21.1

**Comment by kitsonk** [comment]
What operating system are you using and can you provide the output of:

```
> which deno
> deno --version
```

**Comment by AmelloAster** [comment]
> What operating system are you using and can you provide the output of:
> 
> ```
> > which deno
> > deno --version
> ```

<img width="196" alt="image" src="https://user-images.githubusercontent.com/26178326/177898514-555980a2-2a5f-4fff-9e34-ac511f481b4c.png">

**Comment by kitsonk** [comment]
@AmelloAster `deno --version` please as requested.

**Comment by AmelloAster** [comment]
> @AmelloAster `deno --version` please as requested.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/26178326/177905852-bbfb1cf8-cc54-43f9-9aa7-51754e37b69f.png">

**Comment by bartlomieju** [comment]
Hey @AmelloAster, sorry for a slow response. Do you still experience this problem with latest Deno version?

**Comment by nayeemrmn** [comment]
No response to the above and not much info to go on, closing for now.
