### ISSUE TITLE
Extension should not format Markdown documents on save

### ISSUE THREAD

**Issue by cinnis-vhs** [denoland/vscode_deno#676]
**Deno extension appears to apply `deno fmt` to any/all Markdown documents**

I went through the steps of disabling and reenabling various VS Code extensions to narrow down this behavior (to my surprise) to the Deno extension.

It's a bummer to have to disable the extension. Yet, unacceptable to have it enabled at the moment. The steps below describe the obvious and easy-to-witness formatting of a hard line-wrap. There are other formatting changes that are harder to accept (e.g., the `deno fmt` rules appear to ruin features of Markdown extensions such as newline handling and footnotes).

**To Reproduce**

1. Install/enabled Deno VS Code extension
2. Enable "Editor: Format On Save", or equivalent
3. Open or create a Markdown document with a line of text longer than 80 characters
4. Save document
5. Witness that the long line is wrapped at the 80 character mark

**Expected behavior**

The extension should not apply formatting to arbitrary Markdown documents.

**Screenshots**

Shouldn't be needed.

**Versions**

vscode: 1.68.0 deno: 1.20.3 - 1.22.0 extension: 3.12.0

**Comment by cinnis-vhs** [comment]
cc @coreyti (the acct this issue was meant to come from).

**Comment by ahuigo** [comment]
Duplicated with https://github.com/denoland/vscode_deno/issues/555

**Comment by cinnis-vhs** [comment]
@ahuigo, true. my apologies... did not see that one.
