### ISSUE TITLE
Extension is linting JS files like TS even when deno.enable is false

### ISSUE THREAD

**Issue by dd-pardal** [denoland/vscode_deno#69]
![image](https://user-images.githubusercontent.com/37305899/83296628-fc8ff980-a1e8-11ea-9b8d-5e9155157f74.png)

**Comment by buttercubz** [comment]
@dd-pardal 

is a previously reported issue  #60 , you can disable the extension in works space when you don't work with deno

**Comment by dd-pardal** [comment]
Yes, when the extension is disabled this does not happen, but the extension shouldn't lint JavaScript files like that, I think. Also, for some reason, now it doesn't lint anything at all. It just keeps "Initializing JS/TS language features".

**Comment by buttercubz** [comment]
which version of vscode do you have?

**Comment by dd-pardal** [comment]
@buttercubz 1.45.1

**Comment by buttercubz** [comment]
in vscode command line type typescript: restart ts server when this happen

**Comment by 0916dhkim** [comment]
@buttercubz 
I think being required to disable deno extension for every non-deno typescript project is too much. Is there a way to disable this plugin by default and enable only for my deno workspaces?

Today I was working on a nodejs workspace and VSCode gave me a weird import error in my ts file. I was surprised to find out that deno extension was parsing my ts code in a nodejs project.

**Comment by David-Else** [comment]
@0916dhkim try adding  "deno.enable": false to `settings.json`

**Comment by 0916dhkim** [comment]
@David-Else Thank you. I did not know about the setting.

**Comment by David-Else** [comment]
It still does not fix the problem of linting JS as if they were TS

**Comment by lucacasonato** [comment]
Default of `deno.enable` is false now. This should be resolved.
