### ISSUE TITLE
VSCode setting `updateImportsOnFileMove` is not working

### ISSUE THREAD

**Issue by italodeandra** [denoland/vscode_deno#692]
**Describe the bug**

VSCode doesn't prompt me to update the imports on file move.

**To Reproduce**

1. Create a function
2. Import that function in another file
3. Move the file of the function somewhere else

**Expected behavior**

VSCode should prompt to update the imports.

![image](https://user-images.githubusercontent.com/19225266/177787895-eb8aacad-4263-4a49-9885-abe0cd97f630.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/19225266/177787204-5347e070-fda0-4508-af79-b79d5a91b94d.png)

**Versions**

vscode: `1.68.1` deno: `1.23.2` extension: `3.13.0`

**Comment by elliothimmelfarb** [comment]
Bumping this, as this has been my biggest issue with using Deno so far.

**Comment by monkybrain** [comment]
Hey! Any progress on this issue?

**Comment by rmnoon** [comment]
I just ran into the same thing!

**Comment by bartlomieju** [comment]
Possibly a duplicate of https://github.com/denoland/vscode_deno/issues/410

**Comment by bartlomieju** [comment]
I'm gonna close this issue in favor of #410. Let's continue there.
