### ISSUE TITLE
JSX types aren't properly inferred

### ISSUE THREAD

**Issue by lifeiscontent** [denoland/vscode_deno#693]
**Describe the bug**

when using preact in this fresh project the JSX types say that preact.ComponentChildren is an invalid type, though the deno lint / deno fmt doesn't complain

https://github.com/lifeiscontent/deno-game

**To Reproduce**

1. checkout this branch: https://github.com/lifeiscontent/deno-game/pull/2
2. deno task start
3. code .
4. look at Game.tsx and see errors

**Expected behavior**

deno-ts doesn't warn about invalid JSX when its not invalid.

**Screenshots**

**Versions**

vscode: xxx deno: xxx extension: xxx

**Comment by kitsonk** [comment]
cc/ @lucacasonato

**Comment by lucacasonato** [comment]
I only see this error, which is valid:

![image](https://user-images.githubusercontent.com/7829205/177886977-25c3aa64-992c-43cb-830c-a0542fb20112.png)

Have you tried reload VS Code?

**Comment by lucacasonato** [comment]
You are returning `ComponentChildren | undefined` from your `Rect` component. `undefined` is not a valid return value for a JSX component. `deno check main.ts` exposes this same diagnostic.

**Comment by lifeiscontent** [comment]
@lucacasonato interesting, so where does `Element` come from? from my understanding `undefined | null | boolean | string` are all valid values and I suspect `Element` is the generic function type that represents the function call to React.createElement and whatever preact uses under the hood.

where should these types be fixed? Deno? preact?

Sorry for my naivety here, this is my first deno project 😅

**Comment by nayeemrmn** [comment]
Not an extension issue
