### ISSUE TITLE
Error fetching registry config for XXXX EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by tnrich** [denoland/vscode_deno#695]
**Describe the bug**
Hi there, I'm trying to open a deno project and am seeing the following errors in the Deno Language Server: 

```
Starting Deno language server...
  version: 1.23.3 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno
Connected to "Visual Studio Code" 1.69.1
Enabling import suggestions for: https://crux.land
  Error fetching registry config for "https://crux.land": EOF while parsing a value at line 1 column 0
Enabling import suggestions for: https://deno.land
  Error fetching registry config for "https://deno.land": EOF while parsing a value at line 1 column 0
Enabling import suggestions for: https://x.nest.land
  Error fetching registry config for "https://x.nest.land": EOF while parsing a value at line 1 column 0
Server ready.
successfully cancelled request with ID: 2
Unable to send result to client.
client asked to cancel request 3, but no such pending request exists, ignoring
client asked to cancel request 5, but no such pending request exists, ignoring
client asked to cancel request 9, but no such pending request exists, ignoring
successfully cancelled request with ID: 36
```

Not sure why this is happening for me. It seems like the deno-language-server isn't able to download the files it usually is able to... 

It doesn't happen for my coworker who also installed deno on an M1 macbook via brew. Any ideas as to what is going on would be helpful. Thanks!

**Versions**

vscode: Version: 1.69.1 (Universal)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:51.333Z (1 day ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0

deno: 1.23.3

**Comment by kitsonk** [comment]
Are you behind a corporate firewall or proxy?

**Comment by tnrich** [comment]
@kitsonk nope. On a personal computer with no firewall or proxy.

**Comment by kitsonk** [comment]
What is the output of following from within the terminal in vscode?

```
curl -I --request GET \
  --url https://deno.land/.well-known/deno-import-intellisense.json \
  --header 'Accept: application/vnd.deno.reg.v2+json'
```

**Comment by kitsonk** [comment]
It could be you have a corrupt cache for some reason.  Possibly try `deno info` and `rm -rf` the _Language server registries cache_ and reload.

**Comment by tnrich** [comment]
I'm going to try the full vscode uninstall and re-install
