### ISSUE TITLE
Does anyone think it's better to set the default value of deno.enable to false

### ISSUE THREAD

**Issue by lovefengruoqing** [denoland/vscode_deno#70]
First of all, thank you for writing such a great plugin。When I wrote deno, it helped me a lot
。

But most of my projects are nodejs or pure front-end projects. When I use vscode to open these projects, I need to set the deno.enable property in the settings.json file. Otherwise, vscode will give a lot of warnings.

I feel a little annoyed. Because I don't want to create the settings.json file in some projects. If I forget to ignore the file in .gitignore, I may accidentally upload this file to the remote repository. This may confuse my partners.

Why not consider setting the default value of deno.enable to false?

**Comment by TTSKarlsson** [comment]
You can set deno.enable to false in your global settings, and set it to true in the project settings for your deno projects.

**Comment by lovefengruoqing** [comment]
> You can set deno.enable to false in your global settings, and set it to true in the project settings for your deno projects.

Thank you, you are right. I forgot to set it like this.

However, I feel that it should be more friendly if the default setting is false.

When I first encountered this problem, I did not study the plugin in detail. I thought it was a problem with the project code. I even regarded it as a bug of vscode.

**Comment by TTSKarlsson** [comment]
I agree, but somehow I believe that when this extension/plugin gains a way to decide what's deno on a per folder basis or something similiar (include glob in tsconfig maybe), this problem also goes away. And from reading the issues, this is already in the pipe. (#39)

**Comment by garysb** [comment]
Please also see issue #75 related to this. It seems to be a common request.
