### ISSUE TITLE
VSCode should provide indication of config file being used

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#701]
Currently the status bar shows the current version of Deno, but it should also be able to identify the configuration file being used.

The built-in TypeScript status provides a good example of what could be possible:

![Cursor_and_docs_ts_—_apiland](https://user-images.githubusercontent.com/1282577/180900395-80ebae2d-4c10-4c7a-90a3-08178ef57884.png)

**Comment by mtmulch1** [comment]
I would like to work on this, please correct me if anything is wrong. The current tab that specifies Deno 1.24.0 should include a sidetab with the same icon and it should leave room to add additional icons to the top-level dropdown list?

**Comment by mtmulch1** [comment]
The file can to be altered can be found here.  client/src/status_bars.ts 

![image](https://user-images.githubusercontent.com/109058507/182765759-a5fe27d2-2296-4908-bab7-aea957aa5f4b.png)

**Comment by eric-burel** [comment]
Slightly related:
I have a config like so 
```
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.enablePaths": [
        "./api",
        "./webapp"
    ]
}
```
and configs in `./api/deno.jsonc` and `./webapp/deno.jsonc`. However, VS code doesn't seem to take the config into account, especially the import_map option, despite those folders being listed as "paths". I would expect each path to be considered its own Deno app with potentially a config of its own.

**Comment by bartlomieju** [comment]
I did some digging and it's not possible to provide such a nice popup as TypeScript, using available VSCode API. That said we still can show some info (and provide some actions) when clicking on "Deno <version>" button in the bottom right corner. I will look into it, but only if that doesn't take too much time.

**Comment by nayeemrmn** [comment]
This is now output in the panel.

**Comment by scarf005** [comment]
<img width="522" alt="image" src="https://github.com/denoland/vscode_deno/assets/54838975/25f1bba8-8406-40e7-b458-4d65382dbf4a">

@nayeemrmn could you provide screenshots? there's no config file info as of `v3.37.1`
