### ISSUE TITLE
Missing type hints for `name` and `fn` in Deno.test/bench

### ISSUE THREAD

**Issue by GJZwiers** [denoland/vscode_deno#703]
**Describe the bug**

VS Code Intellisense for `Deno.test` and `Deno.bench` does not show `name` and `fn` in the type hints.

**To Reproduce**

1. Create a project in VS Code with Deno enabled
2. Create a .ts file
3. Start writing a Deno.test:
```ts
Deno.test({
    
})
```
4. Type 'n' in the test, there is no hint of a `name?: string` property being available. Same with 'f': no 'fn' property shows up. Other properties such as the `sanitizeOps` do show up as hints

**Expected behavior**

 `name` and `fn` hints should be there, because those are the properties that are often used in Deno.test and Deno.bench and having them as suggestions would be helpful.

**Screenshots**
![shotscreen1](https://user-images.githubusercontent.com/34610306/181937678-f973c292-b35c-4e5f-a9fe-90caf7c10869.png)

**Versions**

vscode: 1.67.2 deno: 1.24.1 extension: v3.13.1

**Comment by kitsonk** [comment]
Sadly, this is "working as designed" because the `Deno.test()` method has an overload that omits then, and because of that the language server does not offer them as completions until it is clear which overload is being used:

```ts
  export function test(
    options: Omit<TestDefinition, "fn" | "name">,
    fn: (t: TestContext) => void | Promise<void>,
  ): void;
```
