### ISSUE TITLE
Warning using outdated version of Deno CLI

### ISSUE THREAD

**Issue by heartacker** [denoland/vscode_deno#706]
**Describe the bug**

**To Reproduce**

1. update vscode 1.70
2. open vscode
3. ...

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1876302/184037920-de57733e-d1bd-4fe8-8dbd-f4b5c217c82d.png)

The version of Deno language server ("1.16.2") does not meet the requirements of the extension (">=1.17.0"). Please update Deno and restart.
**Versions**
![image](https://user-images.githubusercontent.com/1876302/184038048-3fa0d14a-7287-4aad-821e-f0013ad4084f.png)

版本: 1.71.0-insider (system setup)
提交: dced70bbf36d3c53c08e791da1791ac7fc42519b
日期: 2022-08-10T05:17:53.560Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25174

**Comment by kitsonk** [comment]
What version of `deno` do you have installed locally on your machine.  It is reporting you have 1.16.2 installed, the latest is 1.24.2 and you need to update the version of `deno` and restart.

If you have multiple versions installed, the one that vscode is finding is version 1.16.2.

**Comment by heartacker** [comment]
thanks I Update the deno.exe and now there is no warning
