### ISSUE TITLE
markdown extension

### ISSUE THREAD

**Issue by jhawdga2** [denoland/vscode_deno#714]
Type: <b>Bug</b>

i installed the extension and im still getting the popup for vsc to automatically find it for me

Extension version: 3.13.1
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.20GB free)|
|Process Argv|--crash-reporter-id f04d3915-8f3b-422e-bcac-06b31fd1d791|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kitsonk** [comment]
What pop are you getting and what are you doing when the popup occurs.

The extension doesn't control installation suggestions, that is something vscode does itself.

**Comment by kitsonk** [comment]
Requested information not provided.  Closing.
