### ISSUE TITLE
TS errors shown even when Deno language server is enabled

### ISSUE THREAD

**Issue by khaosdoctor** [denoland/vscode_deno#715]
**Describe the bug**

VScode shows TS errors even with Deno enabled, it seems like the extension was never enabled

**To Reproduce**

1. Create a new directory, enter it with VSCode
2. Run "Deno: Initialize workspace" command
3. Create a mod.ts file and add `import { serve } from 'https://deno.land/std/http/server.ts'`

You'll see a TS 2691 error: `An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std/http/server' instead.ts(2691)`.

The same also happens with the `Deno` workspace.

Language Server logs:

```
Starting Deno language server...
  version: 1.24.1 (release, aarch64-apple-darwin)
  executable: /.asdf/installs/deno/1.24.1/bin/deno
Connected to "Visual Studio Code" 1.71.2
  Auto-resolved configuration file: "file:///Repositories/github.com/khaosdoctor/gh-telegram-bot/deno.json"
Setting import map from configuration file: "./import-map.json"
  Resolved import map: "/Repositories/github.com/khaosdoctor/gh-telegram-bot/import-map.json"
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Server ready.
```

**Expected behavior**

No errors shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/3200560/190501628-e5d37fb6-8a13-41f7-a6ef-ef2a6c6049d0.png)
![image](https://user-images.githubusercontent.com/3200560/190500729-9ec5ac0c-98f2-4fc4-8791-fa818794c2c8.png)
![image](https://user-images.githubusercontent.com/3200560/190500751-34fde006-56dc-4be0-81da-a279ffcf24d8.png)
![image](https://user-images.githubusercontent.com/3200560/190500861-604ce512-8c7d-48fb-a3c0-97e53bb35930.png)

**Versions**

vscode: 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7) ARM64 
deno: 1.24.1 
extension: 3.13.1

**Comment by kitsonk** [comment]
Do you have TypeScript's `enableProjectDiagnostics` enabled for the user?

**Comment by khaosdoctor** [comment]
Yes I had! Thanks a lot, this solved the issue
