### ISSUE TITLE
Reading deno.json's importMap value as deno.ImportMap

### ISSUE THREAD

**Issue by podhmo** [denoland/vscode_deno#718]
**Is your feature request related to a problem? Please describe.**

The `deno run` command is reading the import map settings from deno.json, but vscode_deno needs `deno.config` and `deno.importMap` settings. If vscode_deno reads deno.ImportMap setting from deno.json to be more useful.

**Describe the solution you'd like**

Reading the `demo.importMap` value from `deno.json` if `deno.importMap` is empty.

***More context***

Currently my vscode settings is like this:

```console
$ cat .vscode/settings.json

{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.config": "deno.json",
    "deno.importMap": "import_map.json" // this value is always needed
}
```

and deno.json is here.

```json
{
  "importMap": "import_map.json",  // if reading this value, will be happy
  "tasks": {
    "npm:add": "deno run -A https://esm.sh/v95 add",
    "npm:update": "deno run -A https://esm.sh/v95 update",
    "npm:remove": "deno run -A https://esm.sh/v95 remove"
  }
```

vscode_deno version is v3.13.1

**Comment by kitsonk** [comment]
The language server should auto discover a configuration file that is in the root of the workspace. If that is not happening, then something is going wrong with your specific environment.  You should be able to remove the `"deno.config"` and `"deno.importMap"` and reload the workspace, and it should auto discover the configuration.

If that doesn't work, please provide the output from _Deno Language Server_ which provides information about what information is detected.

**Comment by podhmo** [comment]
OK, more info later

**Comment by podhmo** [comment]
https://github.com/podhmo-sandbox/deno-sandbox/issues/1

This is the repository for reproduction issue.

**Comment by bartlomieju** [comment]
I believe this is no longer an issue - `vscode_deno` automatically picks up import map in `deno.json`.
