### ISSUE TITLE
Warning prompt in VS Code

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/vscode_deno#72]
Today, while working with some small TS files, I found this message popping up on my VS Code notification system. I don't know exactly why this happens, if it is a VS Code issue or a Deno extension issue.

```
The extension 'Deno' took a very long time to complete its last
operation and it has prevented other extensions from running.
```
![image](https://user-images.githubusercontent.com/32345702/83358963-704b1700-a34d-11ea-901a-9349d37f8423.png)

- Issue Type: `Performance`
- Extension Name: `vscode-deno`
- Extension Version: `1.24.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.45.1`

**Comment by lucacasonato** [comment]
I think this is now resolved in the latest version. If it is not please open a new issue.
