### ISSUE TITLE
Type Definitions Missing for Web Worker API in Global Scope

### ISSUE THREAD

**Issue by PeronGH** [denoland/vscode_deno#720]
**Describe the bug**

Type definitions are missing for Web Worker API in global scope when coding a web worker. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope), Web Worker should have a special global scope, but I couldn't find either `DedicatedWorkerGlobalScope` object or properties that should exist in the worker global scope.

**To Reproduce**

1. create a `worker.ts` file

2. copy and paste the following code which is from [Deno's manual](https://deno.land/manual@v1.25.4/runtime/workers):

```typescript
self.onmessage = (evt) => {
  console.log(evt.data);
};
```

3. then the plugin says that `Property 'onmessage' does not exist on type 'Window & typeof globalThis'.deno-ts(2339)`.

**Expected behavior**

The plugin should not show any errors, and everything should have its own type.

**Screenshots**

<img width="803" alt="image" src="https://user-images.githubusercontent.com/18367871/192698522-f6d90bff-adf3-41a7-9a57-a234b69f1fd6.png">

**Versions**

vscode: 1.72.0-insider deno: 1.25.4 extension: 3.13.1

**Comment by kitsonk** [comment]
The editor has no idea that you are going to load this script in a worker, therefore it needs additional information for type checking to work properly.  This is covered in the manual here: https://deno.land/manual@v1.25.4/typescript/types#type-checking-web-workers

You need to add the following to the top of your module:

```ts
/// <reference no-default-lib="true" />
/// <reference lib="deno.worker" />
```

Or you can use a configuration file if the entire workspace should be a worker (which is covered in the manual).
