### ISSUE TITLE
Inappropriate pop-up notification: Failed to retrieve config tasks

### ISSUE THREAD

**Issue by llgcode** [denoland/vscode_deno#724]
**Describe the bug**

**To Reproduce**
Every time I save a file in a workspace even not configured for deno, a pop-up notification appears.
But I can't do anything to remove it. So I disabled the extension to be quiet. 

```
Starting Deno language server...
  version: 1.26.0 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\lf5\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.71.2
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Server ready.
Error retrieving config tasks: Error: Unexpected params: {}
client asked to cancel request 9, but no such pending request exists, ignoring
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Setting Deno configuration from: "e:\deno.jsonc"
  Resolved configuration file: "file:///E:/deno.jsonc"
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
client asked to cancel request 52, but no such pending request exists, ignoring
client asked to cancel request 120, but no such pending request exists, ignoring
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
Error retrieving config tasks: Error: Unexpected params: {}
```
# Deno Language Server Status

## Workspace Settings

```json
{
  "enable": false,
  "enablePaths": [],
  "cache": null,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": false
  },
  "internalDebug": false,
  "lint": false,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://deno.land": true,
        "https://x.nest.land": true,
        "https://crux.land": true
      }
    }
  },
  "testing": {
    "args": [
      "--allow-all",
      "--no-check"
    ],
    "enable": true
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": false
}
```

## Workspace Details

  - <details><summary>Documents in memory: 4</summary>

    - file:///E:/xxxx
    - file:///E:/xxxx.md
    - file:///E:/xxx.md
    - file:///E:/xxxxx.json

  </details>

  - <details><summary>Performance measures: 105</summary>

    - update_diagnostics_ts (0ms)
    - update_diagnostics_lint (0ms)
    - update_diagnostics_deps (0ms)
    - update_diagnostics_lint (0ms)
    - update_diagnostics_deps (0ms)
    - testing_update (0ms)
    - did_change_configuration (686ms)
    - update_tsconfig (0ms)
    - request (0ms)
    - update_import_map (0ms)
    - update_registries (682ms)
    - update_cache (0ms)
    - did_close (1ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_open (0ms)
    - did_close (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - update_diagnostics_ts (0ms)
    - update_diagnostics_lint (0ms)
    - update_diagnostics_deps (0ms)
    - update_diagnostics_lint (0ms)
    - update_diagnostics_deps (0ms)
    - testing_update (0ms)
    - did_change_configuration (701ms)
    - update_tsconfig (0ms)
    - request (0ms)
    - update_import_map (0ms)
    - update_registries (697ms)
    - update_cache (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_change (0ms)
    - did_open (0ms)
    - did_close (0ms)
    - virtual_text_document (0ms)
    - did_change (0ms)
    - did_open (0ms)
    - did_open (0ms)
    - did_open (0ms)
    - initialize (929ms)
    - request (1ms)
    - update_registries (686ms)
    - update_import_map (0ms)
    - request (0ms)
    - update_tsconfig (235ms)
    - request (1ms)
    - update_cache (0ms)

  </details>

## Performance

|Name|Duration|Count|
|---|---|---|
|did_change|0ms|64|
|did_change_configuration|693ms|2|
|did_close|0ms|3|
|did_open|0ms|5|
|initialize|929ms|1|
|request|0ms|5|
|testing_update|0ms|2|
|update_cache|0ms|3|
|update_diagnostics_deps|0ms|4|
|update_diagnostics_lint|0ms|4|
|update_diagnostics_ts|0ms|2|
|update_import_map|0ms|3|
|update_registries|689ms|3|
|update_tsconfig|79ms|3|
|virtual_text_document|0ms|1|

**Expected behavior**

No notification

**Screenshots**

![image](https://user-images.githubusercontent.com/524083/193553177-73d4e721-23d0-401b-b943-ec6f24bd10dc.png)

**Versions**

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
deno 1.26.0 (release, x86_64-pc-windows-msvc)
v8 10.7.193.3
typescript 4.8.3
deno extension: v3.13.1

**Comment by lightspeedlucas** [comment]
Should be fixed by #722

**Comment by kitsonk** [comment]
Correct. Will look to release it soon.

**Comment by llgcode** [comment]
Thanks

Le mar. 4 oct. 2022, 05:20, Kitson Kelly ***@***.***> a
écrit :

**Comment by csvn** [comment]
Ah, cool. This issue should already be solved. I'll just wait for next release 😇
