### ISSUE TITLE
Property 'entries' does not exist on type 'Headers'

### ISSUE THREAD

**Issue by IAmSpudLabs** [denoland/vscode_deno#725]
**Describe the bug**
Calling the entries method on an instance of the Headers class is consistently being flagged as non-existent. 

It's defined in Typescript's source but I know the Headers definition is split between the [lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts) and [lib.dom.iterable.d.ts](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.iterable.d.ts) files. I'm not sure if that comes into play here.

Edit: Actually I've just realized that technically the Headers class doesn't show up as iterable at all even though calling `Symbol.iterator in new Headers()` will evaluate to true; 

**To Reproduce**

1. Instantiate a Headers object.
2. Call the entries method on the object.

```ts
const headers = new Headers({'user-agent': 'example'});

const entries = headers.entries();
```

**Expected behavior**

Type hinting indicates a return type of `IterableIterator<[string, string]>`

**Actual behavior**

The entries method is flagged as being invalid/not-existing on the Headers class.

**Screenshots**

![image](https://user-images.githubusercontent.com/100096377/194005695-0d6ca6cf-2b43-4f87-9df5-58e5a084b7e9.png)

**Versions**

vscode: 1.71.2 deno: 1.26.0 extension: v3.13.1

**Comment by kitsonk** [comment]
It is likely you have your project mis-configured, and are using a custom library configuration where you have included `"dom"` but haven't included `"dom.iterable"`.

Do you have custom compiler options applied to this workspace, and if so what are they?

**Comment by IAmSpudLabs** [comment]
H'awkward. I was afraid it was going to be some as simple as this. Typescript is still new to me and I had thought this was covered with "dom". Closing this out as resolved.
