### ISSUE TITLE
Deno LSP takes up a lot of CPU when importing large json file

### ISSUE THREAD

**Issue by fewkz** [denoland/vscode_deno#731]
**Describe the bug**
When importing a large json file, the Deno LSP takes up a lot of CPU and all autocomplete becomes very slow

**To Reproduce**

Put the following code in:

```ts
import apiDump from "https://raw.githubusercontent.com/CloneTrooper1019/Roblox-Client-Tracker/roblox/API-Dump.json" assert {
  type: "json",
};
```

Then any time you trigger autocomplete it will be very slow and take up a lot of CPU

**Expected behavior**

Be able to autocomplete fast and not take up that much CPU

**Versions**

vscode: 1.72.0
deno: 1.26.0
extension: v3.13.1

**Comment by LeoDog896** [comment]
Can replicate it in my enviornment -- it seems that at some step, the type information isn't being cached thus causing the types to be re-calculated every time.

**Comment by bartlomieju** [comment]
Thanks for checking @LeoDog896, I'm gonna close this issue for now, let me know if the problem persists.
