### ISSUE TITLE
Release v3.13.2 not in Marketplace

### ISSUE THREAD

**Issue by albertosantini** [denoland/vscode_deno#732]
Hey.

Any reason release `v3.13.2` is not in the Marketplace? The latest is `v3.13.1`.

**Comment by 51ngul4r1ty** [comment]
I have this question too... there's the annoying "Failed to retrieve config tasks." issue that I'd like to resolve. :-)

**Comment by kitsonk** [comment]
We had some issues with the token we were using to publish to marketplace had expired and needed to be updated.  That has been resolved.
