### ISSUE TITLE
Shift + Alt + F (VsCode Auto Format)

### ISSUE THREAD

**Issue by WingZer0123** [denoland/vscode_deno#737]
Typically when working on other TS projects withing VsCode Shift + Alt + F does an auto format of the code files. It has been a habit of mine to use the auto formatter and pressing the button combination while trying to replicate another bug produced this error.

**To Reproduce**

1. Load: vscode_deno project in VsCode
2. second step: open a TypeScript file
3. Press Shift + Alt + F

**Expected behavior**

Typical VsCode code Formatting. 

**Screenshots**

![image](https://user-images.githubusercontent.com/114699222/196309070-530e2c16-5ed3-4166-9962-5053fcad310c.png)

**Versions**

vscode: 1.72.1 deno: 1.26.1 extension: 3.13.2

**Comment by kitsonk** [comment]
This is working as expected.  You have multiple formatters installed in vscode, one of them should be configured as a default formatter.  It is not an error message, it is an instruction.  You can set the default formatter in your user settings.
