### ISSUE TITLE
Consider enabling type & parameter hints by default

### ISSUE THREAD

**Issue by matklad** [denoland/vscode_deno#744]
It's a bit hard to discover that they exist! As a case point, I (of all the people :) ) spend yesterday's evening wishing for them to exist, only to realize this morning, after reading rel-notes, that they do in fact exist, just not enabled by default.

There's two helpful guidelines here:

- by default, it makes sense to enable features, as it is much easier to disable annoying feature than to enable the feature you'd love, but don't realize exists
- there's editor-global setting `"editor.inlayHints.enabled"`, and extensions should generally honor that. It's on for me (and by default I guess), so I have the expectation of inlay hints showing up, if they exist

---

On the first point, my long-term unrealized wish for rust-analyzer is to have to settings "profiles": `default`, which enables everything and makes the editor glow like a Christmas tree, and a `recommended` profile, with a more no-frills config I'd actually use. The intention here is that new users don't miss features, while pro users get a good config without needing to know about every setting.

**Comment by andrerfcsantos** [comment]
Really disliked having this turned on by default on me after the update today. Filled the code with annotations I didn't want, and I had to track down what was causing it in the settings. Since the only thing that changed was the Deno extension updated, I managed to track it down to this issue.

It was not a good user experience for me to have to turn this off, it was perfectly fine before. I imagine other people will be annoyed by this too.

**Comment by dsherret** [comment]
I personally hate it as well, but it seems like the majority of people like it. The vscode default is for it to be on so I think it makes sense for us to follow that.

Note to others, you can easily disable it by adding:

```jsonc
{
  // etc...
   "editor.inlayHints.enabled": "off"
}
```

...to your vscode settings.json (hit f1 key, then search for `Preferences: Open User Settings (JSON)`). Or otherwise go to File > Preferences > Settings, then search for "Inlay hints" and turn it off.

**Comment by johnstonmatt** [comment]
if folks want to disable it specifically for Deno:

```jsonc
// my-project/.vscode/settings.json
{
  "deno.enable": true, 
  "deno.inlayHints.parameterNames.enabled": "none",
  "deno.inlayHints.parameterTypes.enabled": false,
  "deno.inlayHints.variableTypes.enabled": false,
  "deno.inlayHints.propertyDeclarationTypes.enabled": false,
  "deno.inlayHints.functionLikeReturnTypes.enabled": false,
  "deno.inlayHints.enumMemberValues.enabled": false
}
```

**Comment by dsherret** [comment]
That works too if you only want them off for Deno (I like them off for Rust as well). I would recommend doing that in your user settings (minus `"deno.enable": true`) instead of just the workspace so it's disabled everywhere (https://code.visualstudio.com/docs/getstarted/settings)

**Comment by curtislarson** [comment]
Also adding that being turned on by default is a huge pain, especially since it deviates from the default typescript settings so switching between node and deno projects is a bit jarring.

**Comment by curtislarson** [comment]
> I personally dislike it as well, but it seems like the majority of people like it. The vscode default is for it to be on so I think it makes sense for us to follow and honour that.
> 
> Note to others, you can easily disable it by adding:
> 
> ```js
> {
>   // etc...
>    "editor.inlayHints.enabled": "off"
> }
> ```
> 
> ...to your vscode user settings.json (hit f1 key, then search for `Preferences: Open User Settings (JSON)`). Or otherwise go to File > Preferences > Settings, then search for "Inlay hints" and turn it off.

Unless I'm misunderstanding the vscode settings I don't think all the ones that are enabled in Deno are enabled by default in TypeScript (see below for User settings)

<img width="771" alt="Screenshot 2022-12-14 at 8 33 20 PM" src="https://user-images.githubusercontent.com/2141050/207751729-e998d3ba-2229-4e19-b506-e834c6db2fe0.png">

**Comment by dsherret** [comment]
That seems to be the case. I was referring to the inlay hints default.

![image](https://user-images.githubusercontent.com/1609021/207757122-4337ed8b-0795-4982-b076-2c9365101247.png)

**Comment by njncalub** [comment]
> if folks want to disable it specifically for Deno:
> 
> ```js
> // my-project/.vscode/settings.json
> {
>   "deno.enable": true, 
>   "deno.inlayHints.parameterNames.enabled": "none",
>   "deno.inlayHints.parameterTypes.enabled": false,
>   "deno.inlayHints.variableTypes.enabled": false,
>   "deno.inlayHints.propertyDeclarationTypes.enabled": false,
>   "deno.inlayHints.functionLikeReturnTypes.enabled": false,
>   "deno.inlayHints.enumMemberValues.enabled": false
> }
> ```

Thanks for this. I guess I'm also part of the minority that dislikes the inlay hints.

For what it's worth, I think it would be slightly alright if the annotation had a muted color and was not highlighted (it's very eye-catching/distracting).

Something like [curtislarson](https://github.com/curtislarson)'s screenshot above:

![chrome_SrOqfN6AJz](https://user-images.githubusercontent.com/1902957/208826273-980d8ea5-1c10-41d7-986c-bf8dfd5f439d.png)

And not like:

![Code_YYxy19RKpx](https://user-images.githubusercontent.com/1902957/208826091-bf78b58e-dec0-4b1c-834f-a592ed4addb4.png)

**Comment by Leokuma** [comment]
> [...] it deviates from the default typescript settings so switching between node and deno projects is a bit jarring.

That's the main reason I don't like this new default. Yes the feature is more discoverable this way, but if you follow that logic you would enable every feature by default. I think defaults should be what most people use, and I guess most people don't (and wouldn't) use inlay type hints. But I could be wrong.
