### ISSUE TITLE
Doesn't work with NPM import specifiers

### ISSUE THREAD

**Issue by neezer** [denoland/vscode_deno#748]
**Describe the bug**

Does not appear to correctly resolve imports with npm specifiers: https://deno.land/manual@v1.28.1/node/npm_specifiers

**To Reproduce**

1. Import a package using an npm specifier.
2. See red squiggles under the import.

Tried running both:

- `Deno: Reload Import Registries Cache`
- `Deno: Restart Language Server`

No effect. Deno CLI commands appear to work, suggesting the packages downloaded and resolved correctly from Deno's perspective.

**Expected behavior**

VS Code should detect the import and remove the red squiggles.

**Screenshots**

<img width="594" alt="Screenshot 2022-11-16 at 10 12 03 PM" src="https://user-images.githubusercontent.com/29997/202370218-d4838536-321d-4638-b3aa-3d8b6ec9c3e5.png">

<img width="850" alt="Screenshot 2022-11-16 at 10 14 43 PM" src="https://user-images.githubusercontent.com/29997/202370538-283433dc-af3d-403b-976e-f7c0e717be80.png">

**Versions**

vscode: 1.73.1 deno: 1.28.0  extension: 3.14.1

**Comment by neezer** [comment]
Nevermind, forgot to run `Deno: Initialize Workspace Configuration` first. 🤦

**Comment by navtoj** [comment]
I got this error today: `Uncached or missing npm package: "create-svelte".` but the solution was same as above.

To clarify, the `Deno: Initialize Workspace Configuration` command must be run _before_ trying to cache the package.

I'd already cached the package so it worked after deleting the cache folder and letting it build again after running the above command.
