### ISSUE TITLE
deno.lock should have a registered JSON Schema

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#749]
Currently `deno.lock` gets written out by default, but in the editor it is an "unknown" file.  It is possible that the extension can register it with a JSON schema to make it easier to view and syntax highlight the lock file.

**Comment by bartlomieju** [comment]
For anyone interested in tackling this, here's a short list of what needs to be done:

1. `package.json` should be updated in the `jsonValidation` field, to add:
```json
    {
        "fileMatch": [
          "deno.lock",
        ],
        "url": "./schemas/lockfile.schema.json"
    },
```
2. A new file "./schemas/lockfile.schema.json" should be added that describes the structure of the lock file.
3. That would probably be enough to get syntax highlighting working.

A nice addition would be to make `deno.lock` have a Deno icon, similar to `deno.json`

**Comment by bartlomieju** [comment]
I think I might be have been wrong and it should actually use `"languages"` mapping:
```json
    "languages": [{
      "id": "json",
      "aliases": ["json"],
      "extensions": [".lock"]
    }],
```

**Comment by LeoDog896** [comment]
All good! Attempted to implement this with #766
