### ISSUE TITLE
Wildcard support for deno.enablePaths in settings.json

### ISSUE THREAD

**Issue by s19514tt** [denoland/vscode_deno#751]
**Is your feature request related to a problem? Please describe.**

In the current version, if you write multiple deno scripts in a node project, you must specify the paths to all files.

**Describe the solution you'd like**

I would like to specify the paths using wildcards, for example `"*/**.deno.ts"`.

**Comment by bartlomieju** [comment]
Let's continue in https://github.com/denoland/vscode_deno/issues/834
