### ISSUE TITLE
Launching debug still doesn't work, something always binds to 9229

### ISSUE THREAD

**Issue by bdharrington7** [denoland/vscode_deno#755]
I've taken a look through #12 and #384 and debug support still needs work. I have experience debugging with node, but this is my first time trying with deno.

Using the latest version of VSCode (1.73.1)

There are several issues, and I still haven't gotten the debugger to latch in VSCode:

* it tries to bind to port 9229 regardless of the launch config settings
* breakpoints are never hit in VSCode
* Changing the `attachSimplePort` field to `0` causes an incorrect CLI invocation.
* Changing the `attachSimplePort` field to anything other than `0` won't show up in chrome://inspect

I started from a fresh project and encountered a lot of issues when configuring a launch configuration for deno. The default snippet generated in launch.json:

```json
{
            "request": "launch",
            "name": "Launch Program",
            "type": "pwa-node",   < -- vscode suggests using type node instead. changing to `node` seems to have no effect.
            "program": "${workspaceFolder}/main.ts",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "/opt/homebrew/bin/deno",
            "runtimeArgs": [
                "run",
                "--unstable",
                "--inspect",
                "--allow-all"
            ],
            "attachSimplePort": 9229
        }
```
I have a simple `main.ts` as follows, with a breakpoint set on the `console.log` line:

```
// testing

console.log('hello world')
```

When running that configuration, the breakpoint never gets hit, and the debug listener just exits. Chrome://inspect doesn't register the app at all either.

I have other node processes that will use 9229 as a debug port, so I tried changing `"attachSimplePort": 0` so a random one is chosen each time.

Now, when running the launch configuration, this happens:

```
/opt/homebrew/bin/deno run --unstable --inspect --allow-all --inspect-brk=127.0.0.1:53153 --allow-all ./main.ts
error: The argument '--allow-all' was provided more than once, but cannot be used multiple times

USAGE:
    deno run [OPTIONS] <SCRIPT_ARG>...

For more information try --help

Process exited with code 1
```

I removed the offending runtimeArg, so now my launch config looks like the following:

```
        {
            "request": "launch",
            "name": "Launch Program",
            "type": "pwa-node",
            "program": "${workspaceFolder}/main.ts",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "/opt/homebrew/bin/deno",
            "runtimeArgs": [
                "run",
                "--unstable",
                "--inspect",
                // "--allow-all"
            ],
            "attachSimplePort": 0
        }
```

When I run this, the breakpoint is still not hit in VSCode. However, it **will** now show up in the chrome://inspect debugger. 

**Expected behavior**

I expected deno debugging to work out of the box

**Versions**

* vscode: 1.73.1 
 * deno 1.26.1 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
 * extension: 3.14.1

**Comment by JustinGrote** [comment]
You can control breakpoint resuming with the vscode API, so with inspect-brk in use you could immediately resume once connected and avoid having to step that first break every time.

**Comment by bartlomieju** [comment]
> You can control breakpoint resuming with the vscode API, so with inspect-brk in use you could immediately resume once connected and avoid having to step that first break every time. Seems to me like this should be an option that deno handles natively though and should be opened there, something like `--inspect-wait`

That's a good suggestion about `--inspect-wait` flag - somewhat related to https://github.com/denoland/deno/issues/13664 but it would be much easier to implement that way. I will look into it
