### ISSUE TITLE
Auto Import Suggestions Do Not Work Unless Original Files are Open in Another Tab

### ISSUE THREAD

**Issue by Tiernebre** [denoland/vscode_deno#761]
**Describe the bug**

When using VSCode and using a variable that is exported from another file in the workspace, the Deno extension is not offering suggestions for auto completion of importing it _unless_ I specifically have the file that contained the original export in it open in the VSCode window.

This occurs with specific error `Cannot find name _. deno-ts(2304)`

**To Reproduce**

1. Create a new empty folder.
2. Open this folder up in VSCode
3. Initialize the Deno VSconfiguration (follow[ steps here](https://deno.land/manual@v1.28.3/references/vscode_deno#deno-enabling-a-workspace))
4. Create a new file called `foo.ts`.
5. In `foo.ts`, write `export const someSpecificFooFunction = () => 'Test!'`
6. Create a new file called `baz.ts` and open it in VSCode.
7. Ensure that you do not have a tab open with `foo.ts` (close if it's still on your tab list).
8. Start typing out `someSpecificFooFunction()` in `baz.ts`.
9. Note that the editor correctly identifies that `Cannot find name 'someSpecificFooFunction'.deno-ts(2304)`
10. Use VSCode's quick fix when hovering over the error, and note that the only solution is to declare it in the file.
11. Open `foo.ts` in another tab on VSCode.
12. Go back to `baz.ts` and open the VSCode quick fix again.
13. Note that this time, the plugin was able to find the exported `someSpecificFooFunction` from `foo.ts`.

**Expected behavior**

When the specific error `Cannot find name ''.deno-ts(2304)` occurs, a quick fix solution that is able to discover the export existing in another local file should always be available **without** needing to have the original file open in a tab in the code editor.

**Screenshots**

https://user-images.githubusercontent.com/20584068/206931078-d17bdd09-93cf-444a-806c-60650c97f6f3.mp4

### copy of my `settings.json`

```json
{
    "deno.enable": true,
    "deno.unstable": true
}
```

**Versions**

vscode: 1.74.0 (using OSS version) deno: 1.28.3 extension: v3.14.1

**Comment by bartlomieju** [comment]
Appears that https://github.com/denoland/deno/issues/11190 is required to do this.
