### ISSUE TITLE
Types from deno/std/node are not treated as the same type as those in node

### ISSUE THREAD

**Issue by LemonPrefect** [denoland/vscode_deno#769]
**Describe the bug**
deno-ts treat type `Readable` from "deno.land/std@0.170.0/node/stream.ts" and node "stream" as different types, which cause the Error of the override of inherited functions.
**To Reproduce**
1. use the code from [here](https://github.com/OpenMarshal/npm-WebDAV-Server/blob/master/examples/v2/webResource/index.ts) as an example.
2. replace the import statements as follow.

```typescript
import { v2 } from 'https://esm.sh/webdav-server@2.6.2';
import * as request from 'https://esm.sh/request@2.88.2';
import { Readable } from "https://deno.land/std@0.170.0/node/stream.ts";
```

3. check the line 47.

**Expected behavior**

Readable from deno/std/node/stream might be treated as the same as the one from node/stream to make the override "correct" as the program actually works correctly with deno.

**Screenshots**

![image](https://user-images.githubusercontent.com/39020700/208726723-af3e1deb-daa7-4fbd-9dfd-3daff4510b71.png)

![image](https://user-images.githubusercontent.com/39020700/208726955-f6105d15-4630-4b28-a697-0623d008d1ea.png)

**Versions**

vscode: 1.74.1 deno: 1.29.1 extension: v3.15.0

**Comment by bartlomieju** [comment]
I'm afraid this is "wont fix" at this point... This version of `deno_std/node` has been long deprecated. Using `node:<module_name>` and `npm:<package_name>` imports is now the preferred way sets up proper typings automatically.
