### ISSUE TITLE
Inlay Hints are not rendered correctly

### ISSUE THREAD

**Issue by ggobbe** [denoland/vscode_deno#771]
**Describe the bug**

Inlay hints such as variable types and parameter names are rendered the same size and colour as code.

**To Reproduce**

1. open any .ts file
2. by default, it shows variable types and parameters names as inlay hints

**Expected behavior**

The inlay hints should have a smaller font size and a lighter colour than the code.
This allows to keep them distinct from the code.

**Screenshots**

Currently
<img width="354" alt="image" src="https://user-images.githubusercontent.com/2607273/209297104-50cd4f48-3fcd-4f51-8571-f0edfefb78f3.png">

Expected (from Inline Parameters extension)
<img width="345" alt="image" src="https://user-images.githubusercontent.com/2607273/209296981-a2f9cb77-434f-4b0f-acac-2f3748be4686.png">

**Versions**

vscode: 1.74.2 deno: 1.28.3 extension: 3.15.0

**Comment by LeoDog896** [comment]
![image](https://user-images.githubusercontent.com/26509014/209373594-8df6fabc-58f6-4973-94ce-a830540bc153.png)
I'm a bit confused, inlay hints are rendered like this in other extensions. What Inline Parameters extension are you using?

**Comment by ggobbe** [comment]
This is the extension I used in the second screenshot: `liamhammett.inline-parameters`

It is not so much about the expected style but rather the fact that with the deno extension, the inlay hints are too “strong” and make it hard to easily focus on the code only. That is to distinguish the code from the inlay hints.

In your screenshot, it looks like it is less of a problem because of the dark theme and the light gray colour of the inlay hints.

I tried the different dark and light themes installed by default with VSCode and I can see two recurring issues: 
- the inlay hints always have a different background color than the main background color.
- the inlay hints font color has a too high contract, e.g. black on white instead of gray on white.

Here are a few more screenshots from the extension with the too strong results: 

**Dark+**
<img width="445" alt="image" src="https://user-images.githubusercontent.com/2607273/209436426-19d8e089-fbf5-478b-8f7d-95dfc6874129.png">

**Monokai**
<img width="444" alt="image" src="https://user-images.githubusercontent.com/2607273/209436436-c7351c53-52aa-4ad4-ad02-37c72eed6597.png">

**Abyss**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/2607273/209436452-ac76e488-f0f4-4d79-a5ba-585503cb948b.png">

**Solarized Light**
<img width="447" alt="image" src="https://user-images.githubusercontent.com/2607273/209436462-53587edb-6e77-48e2-891e-a47f672a1172.png">


In comparison, here is a screenshot from JetBrains WebStorm which shows that the inlay hints also have a lighter contracts, are smaller than the main code, and are easy to distinguish from the code:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/2607273/209436282-6a8fcbac-b5f8-4290-abfe-5af3a1c4bef5.png">

**Comment by LeoDog896** [comment]
I think this may be a stylistic issue with vscode than a specific issue with Deno, as deno uses vscode's inlay hints API.

**Comment by bartlomieju** [comment]
> I think this may be a stylistic issue with vscode than a specific issue with Deno, as deno uses vscode's inlay hints API.

Correct, `vscode_deno` just tells VSCode to enable inlay hints, but it does not control how they are rendered.

**Comment by ggobbe** [comment]
OK, then I guess the best is to wait for VSCode to improve default rendering of inlay hints.

Can we close this issue?
