### ISSUE TITLE
Debugger: should `--inspect-wait` be default?

### ISSUE THREAD

**Issue by bartlomieju** [denoland/vscode_deno#774]
### Discussed in https://github.com/denoland/vscode_deno/discussions/772

<div type='discussions-op-text'>

<sup>Originally posted by **Leokuma** December 25, 2022</sup>
With [this addition](https://github.com/denoland/deno/pull/17001), I wonder if it would make sense to make `--inspect-wait` default instead of `--inspect` when debugging so that no breakpoints are ever missed.</div>

**Comment by bartlomieju** [comment]
That seems like a very reasonable change to me. @Leokuma do you want to try and tackle that?

**Comment by Leokuma** [comment]
Sure! I will open a PR later 👍
