### ISSUE TITLE
[Discussion] Possible solution to fix delays and versioning confusion: Merge `typescript-deno-plugin` into `vscode_deno`?

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#78]
# Versioning confusion

At the moment we have:

The `vscode_deno 1.24.0` official plugin that depends on, and is currently bundled with the 3rd party `typescript-deno-plugin 1.29`

- `typescript-deno-plugin v1.29.0` was released 19 days ago
-  It is now up to version `v1.31.0` which was released 8 days ago. `vscode_deno 1.24.0` still includes `typescript-deno-plugin 1.29`, not the new one.

There is no changelog for `vscode_deno` https://github.com/denoland/vscode_deno/releases

And the VS Marketplace one does not make sense: https://marketplace.visualstudio.com/items/denoland.vscode-deno/changelog

> Moved from https://github.com/justjavac/vscode-deno to https://github.com/denoland/vscode_deno in order to have an "official" Deno plugin. Thank you 迷渡!

# Problems of having a split codebase
It seems half the bug fixes are more relevant to the `typescript-deno-plugin`, which is not official and is not where users are directed to for reporting issues. If they do get through to that repo, and get the bug fixed, then they don't get merged into the `vscode_deno` extension right away. There is a random time-lapse that means all the error reports on the two different repos are out of sync.

I don't want to sound like I am complaining, and really appreciate the work @justjavac  and others are doing, but something seems fundamentally wrong with the way this extension is setup and operates.

There should be one central place that people report bugs, and at least a few different people with the authority to accept the pull requests for the official Deno plugin as a whole, not split up. Having the extension split over two separate codebases, one official and the other 3rd party seems very complicated and unnecessary.

I spent a while this morning puzzling over why my JS was getting treated like it was TS even with `"deno.enable": false`. When I turn off the extension then it works! I think this bug was fixed in `typescript-deno-plugin v1.30.0`, 9 days ago https://github.com/denoland/vscode_deno/issues/60,  but I don't know as it is not yet merged into `vscode_deno`

I hope this issue has not been too confused, but I am very confused by the whole VS Code Deno extension situation.

THANKS again to everyone involved!

**Comment by Coteh** [comment]
> I spent a while this morning puzzling over why my JS was getting treated like it was TS even with `"deno.enable": false`. When I turn off the extension then it works! 
Getting this as well. In addition, I am also getting the problem mentioned in #36 in non-Deno `.js` files. @justjavac already mentioned that #36 is not behaviour of the extension, but turning off extension completely gets rid of it, just like this issue. It's possible then that both of these issues are linked to the plugin, if it's not the extension itself causing them.

**Comment by Coteh** [comment]
A workaround for this problem is to clone from `master` and replace the installed VS Code Marketplace version with the cloned directory. The Marketplace version should be located in user extensions directory. To save a Google search for those who don't already know, user extensions directory is in:

**Windows** %USERPROFILE%\. vscode\extensions
**macOS** ~/. vscode/extensions
**Linux** ~/. vscode/extensions

Now just find `denoland.vscode-deno-1.24.0` and overwrite it with version from `master`.

**Comment by David-Else** [comment]
@Coteh Thanks for the info, but It seems that this dependency update was made to `vscode_deno` 9 days ago, Unfortunately it has not been published to the market place!

https://github.com/denoland/vscode_deno/commit/3bb664e3a6aa3d1a4c674c633237657a17d1d370#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
```json
  "dependencies": {
    "typescript-deno-plugin": "^1.31.0"
  }
```
Another big fix landed yesterday too, so you might want to clone this repo instead until someone updates the VS Marketplace.

**Comment by TTSKarlsson** [comment]
The marketplace denoland 1.24.0 plugin does have ^1.31.0 as dependency though, so that's not the issue at all. It also didn't work before the update 9 days ago, and it didn't work before the update yesterday either. Only the old plugins from justjavac and axetroy works (slightly).

![image](https://user-images.githubusercontent.com/9962943/83966045-3c757180-a8b8-11ea-8524-7d2c49e953d2.png)

**Comment by justjavac** [comment]
it is a good idea, `typescript-deno-plugin` is not only used in vscode, but also used by vim and idea. This week I will transfer this repo

**Comment by David-Else** [comment]
@justjavac Any update? Cheers :)

**Comment by jsejcksn** [comment]
> `typescript-deno-plugin` is not only used in vscode, but also used by vim and idea

> and we still need to publish `typescript-deno-plugin` to npm

☝️ Very important that it remains separately available to other consumers

**Comment by lucacasonato** [comment]
This is merged in the extension now.
