### ISSUE TITLE
Show source module name in auto-import suggestions

### ISSUE THREAD

**Issue by andrewbrey** [denoland/vscode_deno#783]
This is a follow-on issue related to https://github.com/denoland/vscode_deno/issues/781.

It would be very helpful if, when imports are suggested in the auto-import dropdown, if the source/originating module were displayed as secondary information in the dropdown.

Today, when importing a function from another module in Deno, the auto-import suggestions show a function signature rather than the name of the module the file will be imported from. This diverges from the behavior Node users see from the default TS Server (and in my opinion, is also not quite as useful).

For reference, here are some example screenshots from interacting with the code in https://github.com/andrewbrey/vscode_deno-lsp-import-error (first when using the Deno source code, and next after converting the same code to be used with Node):

**Deno code and auto-imports suggested by the Deno LSP**

![deno_shows_both](https://user-images.githubusercontent.com/34140052/210295196-68281997-694a-49b9-8a4a-16a8af54d351.png)

_Note how it shows the `invariant` function twice in the import suggestions (once from its original source file `utils.ts`, and once from the module where it is re-exported `mod.ts`) and there is no good way to distinguish between them except by just trying the import_

**Same code under Node and with auto-imports suggested by the default TS Server**

![no_other_imports](https://user-images.githubusercontent.com/34140052/210295404-e6896700-8eb3-41e3-a3e7-4853a7ec4dca.png)

_Note how if there are no existing imports in the file, the suggestions include **only** the original source file `./utils`_

![mod_import_present](https://user-images.githubusercontent.com/34140052/210295462-2631d57a-efc4-4fd3-b9b7-f7d738995fc5.png)

_Now note how if there is an existing import line for `./mod` how there is now **only** a suggestion for `./mod`, basically trying to be as intuitive as possible about where you intend the import to come from._

Thank you for considering, and thanks for Deno, it's great!

**Comment by bartlomieju** [comment]
Discussed this with @lucacasonato this week and we agree that it's a big pain point. We are planning on fixing this issue in the coming weeks.
