### ISSUE TITLE
Publish releases

### ISSUE THREAD

**Issue by kbarbounakis** [denoland/vscode_deno#79]
**New Feature**

It would be very useful to publish releases of extension under repo releases in *.vsix format in order to have an option to install it in IDEs like [eclipse-theia](https://github.com/eclipse-theia/theia)

**Comment by brandonkal** [comment]
@kbarbounakis The marketplace already makes these files available publically:
https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
Just click "Download extension" on the right.

**Comment by kbarbounakis** [comment]
"Download extension" is not exactly a link. It's a button which generates a link url like `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/denoland/vsextensions/vscode-deno/1.24.0/vspackage` with a content-disposition header `content-disposition: inline; filename=denoland.vscode-deno-1.24.0.vsix; filename*=utf-8''denoland.vscode-deno-1.24.0.vsix`.

I have already prepared a PR  for [theia-apps](https://github.com/theia-ide/theia-apps) 

[https://github.com/kbarbounakis/theia-apps/tree/add-theia-deno/theia-deno-docker](https://github.com/kbarbounakis/theia-apps/tree/add-theia-deno/theia-deno-docker)

It creates a Dockerfile script for enabling Deno development and it's waiting to include vscode_deno plugin under latest.package.json#theiaPlugins like other plugins.

[https://github.com/kbarbounakis/theia-apps/blob/add-theia-deno/theia-deno-docker/latest.package.json#L43](https://github.com/kbarbounakis/theia-apps/blob/add-theia-deno/theia-deno-docker/latest.package.json#L43)
