### ISSUE TITLE
Resolving global types

### ISSUE THREAD

**Issue by Roosteridk** [denoland/vscode_deno#797]
**Describe the bug**
Not sure if this is working as intended but Deno VScode doesn't resolve globally declared types unless the types file is open.

**To Reproduce**
1. Create a types.ts file.
2. Add some types inside declare global. Example: 
```ts
// types.ts
declare global {
  type Foo = { ... }
}
```
3. Try to use those types in another file.

**Expected behavior**
I would expect Deno to automatically resolve globally declared types. Maybe it's a performance thing?

**Screenshots**
![image](https://user-images.githubusercontent.com/36681229/215283285-8d1df0cd-17ab-4d8d-a42e-7bdb9eefe8ab.png)
![image](https://user-images.githubusercontent.com/36681229/215283307-589de8ec-a7e6-4d65-abcd-65c35c3f83ad.png)

**Versions**

vscode: 1.74.3 deno: 1.30.0 extension: 3.17.0

**Comment by Roosteridk** [comment]
Also tried using triple slash directives instead, still no luck...

**Comment by bartlomieju** [comment]
This is a known bug, that will be fixed by https://github.com/denoland/deno/issues/11190
