### ISSUE TITLE
A way to disable 'do you wish to enable the extension' notifications

### ISSUE THREAD

**Issue by jespertheend** [denoland/vscode_deno#800]
**Is your feature request related to a problem? Please describe.**

I often get this notification when opening projects:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/2737650/215358306-6e18fcec-782d-4792-954b-870915cc8bea.png">
Presumably because the extension has found a `deno.json` file. This notification keeps popping up every time you open the project until you either click 'yes' or 'no'. However, when you do so, a `.vscode/settings.json` file is created that stores your chosen value. But often I don't want to bother with committing this new file to version control (or .gitignoring it and then committing a changed .gitignore file).
So I usually just end up discarding the file, and then I'm bothered by the notification that pops up next time I open the project.

I guess this is partially an issue with vscode itself: do you commit the settings file or do you gitignore it. Commit it and you'll force everyone to use your preferences, ignore it and now you lose the opportunity to set sensible defaults for your project. The best option is to gitignore it and then add a `.vscode/settings.sample.json` file, though that requires work from developers whenever they check out the repository. But I digress.

**Describe the solution you'd like**

A setting to disable the notification would be nice.
Alternatively maybe the value can be stored somewhere other than `.vscode/settings.json`, like a list of projects for which the notification has been dismissed somewhere on the users system. That way the popup only shows up once per project per device.

**Comment by jsejcksn** [comment]
@jespertheend I agree — a setting for this would be an improvement! There are times when I'm frequently cloning repositories and this is yet another dialog to distract and dismiss for the most part.

Until that time, a workaround might be to disable the Deno extension globally (not ask the extension to disable itself using the configuration preference `{ "deno.enable": false }`, but actually disable the extension in VS Code):

<img width="729" alt="Screenshot 2023-07-11 at 14 04 31" src="https://github.com/denoland/vscode_deno/assets/868251/21af7985-5088-4c2d-a43f-0b8480546c0f">

and then enable it for the workspaces in which you want to use it. I use this strategy for several workflow-specific extensions to keep concerns isolated and to keep VS Code's instance startup time lightning fast. ⚡️

> Do you commit the settings file or do you gitignore it?
> …
> ignore it and now you lose the opportunity to set sensible defaults for your project

I don't think this is right: nothing prevents you from creating and using a `./.vscode/settings.json` file to configure a workspace when it's ignored by `git` in the associated repository. (However, if you're looking for git-oriented automations, you might be interested in [git hooks](https://git-scm.com/docs/githooks).)

**Comment by nayeemrmn** [comment]
This prompt was removed in #902.
