### ISSUE TITLE
Typing error when using await Promise.allSettled()

### ISSUE THREAD

**Issue by gustavocadev** [denoland/vscode_deno#802]
**Describe the bug**
Error type: Property 'value' does not exist on type 'PromiseSettledResult<{ username: string; }>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.deno-ts(2339)

**To Reproduce**
```typescript
const getUsers = () => {
	const users = [{ username: 'user1' }, { username: 'user2' }]

	const promises = [] as Promise<{ username: string }>[]

	for (const user of users) {
		promises.push(
			new Promise((resolve, _) => {
				resolve(user)
			})
		)
	}
	return promises
}

const users = await Promise.allSettled(getUsers())

for (const user of users) {
	console.log(user.value) // typing error by part of the deno vsc extension
}
```
**Screenshots**
![Screen Shot 2023-01-30 at 12 49 48 PM](https://user-images.githubusercontent.com/84424661/215554732-70cefe83-4a1e-48ee-b39f-d5629434db4a.png)

**Versions**

vscode: 1.74.3 deno: 1.30.0 extension: v3.17.0

**Comment by ayame113** [comment]
The type error should disappear if you check if `user.status` is `"fulfilled"` in the if statement.

```diff
  for (const user of users) {
+   if (user.status === "fulfilled") 
  	  console.log(user.value);
+   }
  }
```

**Comment by gustavocadev** [comment]
> The type error should disappear if you check if `user.status` is `"fulfilled"` in the if statement.
> 
> ```diff
>   for (const user of users) {
> +   if (user.status === "fulfilled") {
>   	  console.log(user.value);
> +   }
>   }
> ```

It works! Thanks!, should I close this issue?
