### ISSUE TITLE
formatter should inherit .editorconfig style

### ISSUE THREAD

**Issue by loynoir** [denoland/vscode_deno#803]
**Describe the bug**
Just give a try to no-nester style indent,  aka linux kernel style.
Found `denoland.vscode-deno` not inherit .editorconfig style, which `esbenp.prettier-vscode` inherit it by default.

**To Reproduce**

1. first step
```
indent_size = 8
```

```jsonc
    "[typescript]": {
        // "editor.defaultFormatter": "esbenp.prettier-vscode"
        "editor.defaultFormatter": "denoland.vscode-deno"
    }
```
2. second step
3. ...

**Expected behavior**

**Screenshots**

**Versions**

vscode: xxx deno: xxx extension: xxx

**Comment by nayeemrmn** [comment]
Tracked in https://github.com/denoland/deno/issues/14717.
