### ISSUE TITLE
Uncached or missing npm package: "@types/node" when import mapping a `node:` specifier

### ISSUE THREAD

**Issue by shinebayar-g** [denoland/vscode_deno#805]
**Describe the bug**

Below code works when I do `deno run example.ts`. However vscode extension is giving error if I use `deno.json` & import maps.

```
Uncached or missing npm package: "@types/node".deno(no-cache-npm)
```

**To Reproduce**

1. `deno.json`
```json
{
    "imports": {
        "fs": "node:fs"
    }
}
```
2. `example.ts`. 
```ts
import * as fs from 'fs';

function getTeams() {
    const teams = fs.readdirSync('./teams');
    console.log(teams);
}

getTeams();
```

**Expected behavior**

Import map works as expected.

However, when I do `import * as fs from 'node:fs';` it works.

**Screenshots**

<img width="652" alt="image" src="https://user-images.githubusercontent.com/3091558/217703985-188a2be3-bf5c-4ff0-a306-a00cab85eb8c.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/3091558/217704543-cd667d39-d7ba-41cf-a261-f793e41f9e11.png">

**Versions**

```
❯ deno --version
deno 1.30.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

Deno extension: v3.17.0
VSCode: Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

**Comment by Creative-Difficulty** [comment]
Any updates?

**Comment by bartlomieju** [comment]
@shinebayar-g @Creative-Difficulty sorry for a slow response. Do you still experience these problems with Deno v1.35? We fixed two big pain points around npm and import maps in that release and I'm wondering if the issue still persists.

**Comment by Creative-Difficulty** [comment]
> 

Will test it out!

**Comment by osddeitf** [comment]
@bartlomieju I think it still doesn't work
![image](https://github.com/denoland/vscode_deno/assets/37999210/a7033382-218d-462f-98ad-a9c01c1e0b21)
If I remember correctly, it worked alright after `node:` prefix stabilized (without installing `@types/node`), and the location of `node:` packages type definitions were not `.cache/deno/npm/registry.npmjs.org/@types/node`.

**Comment by bartlomieju** [comment]
@dsherret can you advise here? I thought this would work out-of-the box now.

**Comment by reggi** [comment]
This recently just broke for me without import maps 😭

deno 1.35.2 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6

(Deno VSCODE v3.19.1)

![Screen Shot 2023-07-26 at 3 22 31 PM](https://github.com/denoland/vscode_deno/assets/296798/01554f75-63ee-456f-bcba-4a68c87c00e3)

**Comment by dsherret** [comment]
@reggi what happens why you cache it by using the quick fix or the `Deno: Cache Dependencies` command? If that doesn't work, maybe try `deno cache your_file.ts` then run `Deno: Restart Language Server`

**Comment by reggi** [comment]
@dsherret thanks a bunch!
running `deno cache` then restarting didn't do it ❌
using the quick fix solution worked ✅
