### ISSUE TITLE
`denoland.vscode-deno` formatter ignores `// deno-fmt-ignore` comments

### ISSUE THREAD

**Issue by RB-Lab** [denoland/vscode_deno#806]
**Describe the bug**
`denoland.vscode-deno` formatter ignores `deno-fmt-ignore` and formatting is different from what `deno fmt` produces.

I have a file where I have couple of long lines and it is easier to read them when they are long:
```ts
    // deno-fmt-ignore
    const expected = [
      [
        jam[0][0][0] * grad[0][0] + jam[0][0][1] * grad[0][1] + jam[0][0][2] * grad[0][2],
        jam[0][1][0] * grad[0][0] + jam[0][1][1] * grad[0][1] + jam[0][1][2] * grad[0][2],
        jam[0][2][0] * grad[0][0] + jam[0][2][1] * grad[0][1] + jam[0][2][2] * grad[0][2],
      ],
    ];
```
However, when I run VSCode formatter, it doesn't respect `// deno-fmt-ignore` and turn it into:
```ts
    // deno-fmt-ignore
    const expected = [
      [
        jam[0][0][0] * grad[0][0] +
          jam[0][0][1] * grad[0][1] +
          jam[0][0][2] * grad[0][2],
        jam[0][1][0] * grad[0][0] +
          jam[0][1][1] * grad[0][1] +
          jam[0][1][2] * grad[0][2],
        jam[0][2][0] * grad[0][0] +
          jam[0][2][1] * grad[0][1] +
          jam[0][2][2] * grad[0][2],
      ],
    ];
```
Furthermore, when I remove that comment and run `deno fmt` it produces a different result:
```ts
    const expected = [
      [
        jam[0][0][0] * grad[0][0] + jam[0][0][1] * grad[0][1] +
        jam[0][0][2] * grad[0][2],
        jam[0][1][0] * grad[0][0] + jam[0][1][1] * grad[0][1] +
        jam[0][1][2] * grad[0][2],
        jam[0][2][0] * grad[0][0] + jam[0][2][1] * grad[0][1] +
        jam[0][2][2] * grad[0][2],
      ],
    ];
```
Which is no better than extension's formatting in this case, but at least `deno fmt` respects `// deno-fmt-ignore` comment.

**To Reproduce**

1. Create VSCode project with `"deno.enable": true,` and `"editor.defaultFormatter": "denoland.vscode-deno"` in settings.
2. Write some badly formatted code
3. Disable formatting of a statement with `// deno-fmt-ignore` or disable formatting of the whole file with `// deno-fmt-ignore-file`
4. Run command "Format document" (⇧⌥F on Mac)

**Expected behavior**

File is formatted except disable statement or file is not formatted if formatter was disabled for the whole file.

**Versions**

vscode: 1.75.0 deno: 1.27.1  extension: v3.17.0

**Comment by bartlomieju** [comment]
Hey @RB-Lab, sorry for a slow response. Do you still experience this issue when using Deno v1.35?

**Comment by RB-Lab** [comment]
@bartlomieju, NP, I guess I'm not paying you, as the saying goes. =)
Yes, the problem is still there. Now I have: VSCode: 1.80.0, Deno: 1.31.2, extension: v3.19.1

**Comment by nayeemrmn** [comment]
I cant reproduce. My guess is the Deno formatter isn't in use because there's a language-specific preference in your user settings overriding it. See https://github.com/denoland/vscode_deno/issues/933#issuecomment-1731884519.
