### ISSUE TITLE
Operator '+' cannot be applied to types 'BigInt' and 'BigInt'.deno-ts(2365)

### ISSUE THREAD

**Issue by gflarity** [denoland/vscode_deno#810]
**Describe the bug**

VSCode seems to be highlighting valid code as having an error in it. Specifically '+' operators around built types that are supposed to support them. 

**To Reproduce**
```
const a: BigInt = BigInt(1);
const b: BigInt = BigInt(2);
console.log(a+b)
```
^ The a+b will get a red squiggly underneath it with the error 
`Operator '+' cannot be applied to types 'BigInt' and 'BigInt'.deno-ts(2365)`. But this works when you run it. Seems like BigInt support was added to V8 a long time ago, it also doesn't show up in the deno lint output. 

**Expected behavior**

Seems like this is legit typescript. So shouldn't be tagged. 

**Screenshots**
<img width="1007" alt="Screenshot 2023-02-13 at 1 32 45 PM" src="https://user-images.githubusercontent.com/253636/218544278-e3972ae4-e74d-489d-890a-7acc3dc17002.png">

**Versions**
deno: 1.30.3
vscode:  1.75.1
extension: 3.17.0

**Comment by ayame113** [comment]
It seems that uppercase (BigInt) represents a different type and should be changed to lowercase (bigint).

https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAhgLhgIQJYHMCSZYF4UbZQAUAjAJQDcAUKJLAEZJpY4z4tHEBMVt4EEABsApgDohIdMTgBqBn370YwJAwyo2HQjjJ860GABM1GrQVYleNA8PGTpwWUb5A

**Comment by gflarity** [comment]
Oh wow, that's counter intuitive! Thanks for the info!
