### ISSUE TITLE
Rename Symbol only works in open files

### ISSUE THREAD

**Issue by mhanuszh** [denoland/vscode_deno#811]
**Describe the bug**

Rename Symbol only works in open files

**To Reproduce**
1. Create two files, one exporting a value and another imporing it
2. Close the file that imports
3. Use the "Rename Symbol" command on the exported symbol

**Expected behavior**

All symbols in all files should be replaced with the new value, just as they do in "vanilla" typescript (when deno is disabled)

**Versions**

`code --version`
> 1.75.1
> 441438abd1ac652551dbe4d408dfcec8a499b8bf
> x64

`code --list-extensions --show-versions | grep deno`
> denoland.vscode-deno@3.17.0

`deno --version`
> deno 1.30.3 (release, x86_64-unknown-linux-gnu)
> v8 10.9.194.5
> typescript 4.9.4

**Comment by bartlomieju** [comment]
This is the same cause as https://github.com/denoland/deno/issues/11190

**Comment by mhanuszh** [comment]
> This is the same cause as [denoland/deno#11190](https://github.com/denoland/deno/issues/11190)

@bartlomieju
Thanks for the information. Should this issue be closed as duplicate?

**Comment by bartlomieju** [comment]
Let's keep it open so we can test when implementing the feature.
