### ISSUE TITLE
Debug test run profile

### ISSUE THREAD

**Issue by brentropy** [denoland/vscode_deno#812]
**Is your feature request related to a problem? Please describe.**

I recently started experimenting with Deno. This extension has been great. The one big thing I am missing is the ability to debug specific tests. That is a major part of my normal workflow. I looked through the code and found:

https://github.com/denoland/vscode_deno/blob/main/client/src/testing.ts#L204

```js
// TODO(@kitsonk) add debug run profile
```

Where does this sit on your roadmap? Are there any major blockers on implementing this? I am happy to contribute if this is something I could help with.

**Describe the solution you'd like**

I would like to be able to debug specific `Deno.test()`s via the Testing API integration.

**Comment by brentropy** [comment]
I spent a little more time looking in to this this weekend. It looks like since since the Testing API integration uses the Deno language server via the `deno/testRun` extension, this would be dependent on the Deno supporting debug test runs. But...

> Currently Deno only supports the "run" kind of test run. Both "debug" and "coverage" are planned to be supported in the future.
\- https://deno.land/manual@v1.30.3/advanced/language_server/testing_api#denotestrun

That probably isn't something that would be an easy first contribution.

However, I think implementing a test run profile that just executes `deno test --inspect --filter <test name> [file]` probably wouldn't be too bad. Would there be any interest in merging something like that as a short term solution until debug test runs are supported by the language server?

**Comment by SindreSvendby** [comment]
If I understand you correctly you want to debug specific test from vscode. I did not find the ability to debug one test by default but by enabling the setting `deno.codeLens.test": true`

![image](https://user-images.githubusercontent.com/1047421/223101675-f379dc44-f886-4125-a64d-ce9990e972e8.png)

I was able to get up the possibility to debug on the line before the test:
![image](https://user-images.githubusercontent.com/1047421/223221707-de645383-dd0f-489f-a02b-e846dbce4500.png)


Why the testing pane or the left side of  the editor do not have the ability to debug in addition to debug I do not know.

**Comment by brentropy** [comment]
Thanks for pointing that out @SindreSvendby. I didn't see the need for the lens since it had the testing API integration, but it looks like the test run/debug from the lens is independent of the Testing API integration and executes the test via the cli instead of the language server like I was suggesting.

It should be possible to make the CLI based test debug work via the Testing API integration, but this fits my need well enough for now. Hopefully the language server will support the "debug" kind for the `testRun` message soon, but I will go ahead and close this issue since the language server docs already say support is planned.
