### ISSUE TITLE
Support Visual Studio Code for the web (aka github.dev)

### ISSUE THREAD

**Issue by justinmchase** [denoland/vscode_deno#814]
**Is your feature request related to a problem? Please describe.**

github.dev is basically visual studio code running in the browser which knows how to load a git repo automatically. It supports extension installation but the deno extension does not work there right now.

![Screen Shot 2023-02-28 at 11 53 55 AM](https://user-images.githubusercontent.com/10974/221940457-58cee946-f801-4a42-915a-1900b8345828.png)

**Describe the solution you'd like**

I would like it to work, I'm not sure whats involved or how difficult it will be but it would be nice.

Here is the link to the docs mentioned in the screenshot above:
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

**Comment by GJZwiers** [comment]
Duplicate of https://github.com/denoland/vscode_deno/issues/515

**Comment by justinmchase** [comment]
Closing in favor of duplicate.
