### ISSUE TITLE
Add a command for deno disable

### ISSUE THREAD

**Issue by cojmeister** [denoland/vscode_deno#816]
Just add a command palette command that allows to disable deno linting.

The current solution is to manually make a `.vscode/settings.json` file and set `"deno.enable": false`

**Comment by You-saku** [comment]
This Issue sounds interesting. I'd like to work on resolving this issue as my first contribution.

I'm not sure if I can achieve it, but I want to try.

**Comment by nayeemrmn** [comment]
@You-saku Thanks! A similar command is registered here: https://github.com/denoland/vscode_deno/blob/cf0a2a99cb201ce5224ff7e232266d727d452384/client/src/extension.ts#L444-L447

https://github.com/denoland/vscode_deno/blob/cf0a2a99cb201ce5224ff7e232266d727d452384/client/src/commands.ts#L96-L104

**Comment by jsejcksn** [comment]
Just a note: This functionality previously existed and was removed. Ref: https://github.com/denoland/vscode_deno/issues/170

**Comment by You-saku** [comment]
Thanks. I saw the past issue and discussion. I thought it wasn't enough to add it as a command too.

So, This issue close ?

**Comment by jsejcksn** [comment]
> Thanks. I saw the past issue and discussion. I thought it wasn't enough to add it as a command too.
> 
> So, This issue close ?

Given the extension's current default behavior, I think it makes sense for a "disable" command to exist again.

**Comment by bartlomieju** [comment]
@nayeemrmn this seems reasonable. Could you add it?
