### ISSUE TITLE
Option for deno.disablePaths

### ISSUE THREAD

**Issue by pxslip** [denoland/vscode_deno#817]
**Is your feature request related to a problem? Please describe.**

I have a project that I intend to write exclusively using Deno, however, I plan to accompany it with the deploy tools written using cdktf (Typescript). After beating my head against getting cdktf to work under Deno I have temporarily moved on, but the typescript code in the subdirectory is still being linted by Deno. I would like to be able to do the opposite of the `deno.enablePaths` configuration option and disable Deno for some chosen path(s).

**Describe the solution you'd like**

Add a `deno.disablePath` configuration option to disable Deno in a subdirectory of a project.

I think I can see a solution and am happy to open a PR with said solution.

**Comment by benatkin** [comment]
I saw this on Discord except it suggests `disablePaths`. It makes sense to me.

**Comment by bartlomieju** [comment]
@nayeemrmn is it something you could look at? Seems like a common problem for folks and before we get workspace support landed it might be good solution as a band aid.
