### ISSUE TITLE
Error deno-ts 18046 is displayed for type guard check of unknown parameter

### ISSUE THREAD

**Issue by sgohlke** [denoland/vscode_deno#818]
**Describe the bug**

I tried to check with a type guard that a parameter of type "unknown" contains a specific field. In VSCode with Deno VSCode extension this results in the following error being displayed:
`'data' is of type 'unknown'.deno-ts(18046)`
Running `deno lint` and `deno run` does work without an error.

**To Reproduce**

Code: From repository https://github.com/sgohlke/deno-ts-unknown
```typescript
export function prepareResponse(data: unknown): string {
    if ('message' in data) {
        console.log('Message in data: ', data.message)
    }
    return JSON.stringify(data)
}

console.log('Response is', prepareResponse({abc: 'test'}))
```

**Expected behavior**

No error message should be displayed as there is no actual error.

**Screenshots**

![typeIssue](https://user-images.githubusercontent.com/52039897/222798374-be698c8e-306a-4312-82b8-b5e7ff7d17d4.jpg)

**Versions**

vscode: 1.76.0 deno: 1.30.3 extension: Deno v3.17.0

**Comment by 0f-0b** [comment]
The `in` operator requires the right operand to be an object, so there would be an error at runtime if `data` is a primitive value. To fix the error, either check if `data` is an object (`data !== null && typeof data === "object"`), or change the signature of `prepareResponse` to only accept objects (`function prepareResponse(data: object): string`).

**Comment by sgohlke** [comment]
Did not know that, I changed the null/typeof object check and the error disappeared. Thank you!
