### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vreddhi** [denoland/vscode_deno#821]
Type: <b>Bug</b>

Crashed 5 times in 5 minutes

Extension version: 3.17.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (2.19GB free)|
|Process Argv|--crash-reporter-id 3024b8b8-737a-4c87-a445-173669a2bda5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bartlomieju** [comment]
Hey @vreddhi, sorry for a slow response. Do you still experience the same problem when using latest Deno version (v1.35)? 

If so, any chance you could share the code and output of the extension when the crash happens?

**Comment by bartlomieju** [comment]
I'm gonna close this issue for now, due to lack of info. I'll reopen it once we can get more information.
