### ISSUE TITLE
Intellisense/autocompletion is broken

### ISSUE THREAD

**Issue by thonkinator** [denoland/vscode_deno#825]
**Describe the bug**

Any TypeScript or JavaScript file that is enabled with the Deno extension has no autocomplete/intellisense at all. I know that the Deno extension disables the default TypeScript intellisense, but it's supposed to add it's own. I am running Linux on a Chromebook, so I suppose it could be a processing power problem although in non-Deno files Intellisense works just fine. So either Deno's intellisense is incredibly slow or just completely broken.

Here's my Deno-specific settings:
```json
{
	"deno.inlayHints.parameterNames.enabled": "none",
	"deno.inlayHints.propertyDeclarationTypes.enabled": true,
	"deno.inlayHints.variableTypes.enabled": true,
	"deno.inlayHints.parameterTypes.enabled": true,
	"deno.suggest.completeFunctionCalls": true
}
```
**Expected behavior**

Default intellisense should be replaced with Deno intellisense.

**Screenshots**

![image](https://user-images.githubusercontent.com/51034477/225938967-ddf6984b-915f-4335-b169-7303cbdb3169.png)
My cursor is right after the `gif.`
I should be getting intellisense for the Response object, but I'm not.

**Versions**

vscode: 1.76.1 deno: 1.31.1 extension: 3.17.0

**Comment by bartlomieju** [comment]
@thonkinator sorry for a slow response. Do you still experience the same problem when using latest Deno (v1.35)?

**Comment by thonkinator** [comment]
> @thonkinator sorry for a slow response. Do you still experience the same problem when using latest Deno (v1.35)?

i actually no longer have the machine that i referenced in the original issue, so i can't say. i'll just close this issue
