### ISSUE TITLE
Format Selection

### ISSUE THREAD

**Issue by mfulton26** [denoland/vscode_deno#829]
**Is your feature request related to a problem? Please describe.**

VSCode's "Format Document" is mostly what I use but occasionally I want to format only a few lines and leave other lines alone to reduce noise in pull requests where others aren't using the same formatter as me, etc.

VSCode's "Format Selection" feature can be used for this but when I try to use it with Deno set as my default formatter then I am surprisingly prompted to "**Configure Default Formatter**" with the message: "Extension 'Deno' is configured as formatter but it cannot format 'TypeScript'-files"

A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

![image](https://user-images.githubusercontent.com/5588957/227375422-86fb8286-c078-4f75-8ba3-0565de6a2898.png)

**Describe the solution you'd like**

I'm guessing some additional changes need to be made for `vscode_deno` to support "Format Selection" which I'd like to see made so that I can use it as needed.

**Comment by bartlomieju** [comment]
Hey @mfulton26, sorry for a slow response.

This looks exactly like https://github.com/denoland/vscode_deno/issues/840. Can you repeat it with latest Deno and VSCode?

**Comment by bartlomieju** [comment]
Please see https://github.com/denoland/vscode_deno/issues/860#issuecomment-1642655153

**Comment by mfulton26** [comment]
I'm still seeing this issue on the latest VSCode and Deno extension versions.
