### ISSUE TITLE
Plugin doesn't work at all

### ISSUE THREAD

**Issue by tahmid-hasan** [denoland/vscode_deno#83]
I've downloaded and enabled the Deno plugin for VSCode. But unfortunately, it doesn't work at all.
![1](https://user-images.githubusercontent.com/34867248/84317386-7bdce000-ab8e-11ea-81f3-0a811833f73a.png)

![2](https://user-images.githubusercontent.com/34867248/84317479-a6c73400-ab8e-11ea-895d-e7207f0a8e91.png)

This is the user setting of my editor and I'm using VSCode version of TypeScript.
![3](https://user-images.githubusercontent.com/34867248/84317622-e7bf4880-ab8e-11ea-88da-7cfde15abc31.png)

Can anyone know what to do?

**Comment by torquato-nathan** [comment]
In my case the only thing it does is to get rid of the red  squiggly lines, other than that, nothing at all!
It's impossible to work without Intellisense.

I've got the lastest version of VS Code.

Hope it gets fixed soon, I'm extremely excited to make some cool things with deno!

**Comment by ry** [comment]
Fixed in

**Comment by tahmid-hasan** [comment]
> Fixed in [158112b](https://github.com/denoland/vscode_deno/commit/158112b3eb5a8642cf985a8a263b09f0805f01ef)

Don't understand. If I have to use plugin from NPM then why I install plugin in VSCode since the plugin says that it works with latest version?

**Comment by tahmid-hasan** [comment]
> In my case the only thing it does is to get rid of the red squiggly lines, other than that, nothing at all!
> It's impossible to work without Intellisense.
> 
> I've got the lastest version of VS Code.
> 
> Hope it gets fixed soon, I'm extremely excited to make some cool things with deno!

Me too :)

**Comment by tahmid-hasan** [comment]
> Fixed in [158112b](https://github.com/denoland/vscode_deno/commit/158112b3eb5a8642cf985a8a263b09f0805f01ef)

Working now. Thank You :)

**Comment by torquato-nathan** [comment]
Amazing! Thank you!!!

**Comment by torquato-nathan** [comment]
> Fixed in [158112b](https://github.com/denoland/vscode_deno/commit/158112b3eb5a8642cf985a8a263b09f0805f01ef)

Amazing, THANKS!!!
