### ISSUE TITLE
This code breaks deno lang server

### ISSUE THREAD

**Issue by al6x** [denoland/vscode_deno#830]
When code below typed in the editor, the code highlight stops working

**To Reproduce**

Type this in your editor

```TypeScript
export class Obj {
  is_equal(o: this): boolean { return false }
}

declare global {
  interface Function extends Obj {
  }
}

let a: string = 1
```

**Expected behavior**

Line `let a: string = 1` should have red underline, marked as error. But it's not.

**Screenshots**

Notice, the line with the bug is not highlighted:

<img width="411" alt="Screen Shot 2023-03-29 at 10 17 35 am" src="https://user-images.githubusercontent.com/94196/228388070-e304420e-3a72-4c60-9761-c9b0db1058b6.png">

Here's how it should look like

<img width="437" alt="Screen Shot 2023-03-29 at 10 19 46 am" src="https://user-images.githubusercontent.com/94196/228388283-5b8cf8f7-20c3-488b-b5eb-a8bc6afd32e3.png">

**Versions**

vscode: 1.76.2 deno: 1.32.1 extension: v3.17.0

**Comment by nhrones** [comment]
Error highlights as expected in my editor?
Running same versions as above!

**Comment by al6x** [comment]
Hmm, it disappeared in my editor too, after I reloaded it, strange, closing for now, will reopen with more info if get more data.
