### ISSUE TITLE
Cannot import npm specifier modules due to firewall

### ISSUE THREAD

**Issue by justinmchase** [denoland/vscode_deno#837]
**Describe the bug**
I cannot configure `NPM_CONFIG_REGISTRY` in the vscode extension.

https://deno.com/blog/v1.29#custom-registry-support-via-environment-variable

**To Reproduce**

1. Connect to a corporate VPN which blocks npm
2. Setup an Artifactory proxy
3. Attempt to import something with an npm specifier
```ts
import * as express from "npm:express";
```

**Expected behavior**

I expect to be able to have this succeed by importing through the proxy.

I would imagine it could be as simple as adding an option `npmRegistry` to the settings which would set that env variable before invoking deno.

```json
{
  "deno.npmRegistry": "<url>"
}
```

**Screenshots**

![Screen Shot 2023-04-13 at 9 38 02 AM](https://user-images.githubusercontent.com/10974/231794588-68583ee5-4e31-4650-89b3-314f0e7d6ea2.png)

![Screen Shot 2023-04-13 at 9 37 55 AM](https://user-images.githubusercontent.com/10974/231794620-c46ac0df-eca3-4751-a696-ae2e3ccbde77.png)

**Versions**

vscode: ` 1.67.2` deno: `1.32.4` extension: `v3.17.0`

**Comment by oscar6echo** [comment]
I reach a similar wall.

Config: vscode: `1.89.1`, deno: `1.43.3`, extension: `3.37.1`

Behind a corp proxy I can use deno CLI with [specific env variables](https://docs.deno.com/runtime/manual/basics/env_variables#special-environment-variables):
+  `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` 
+ `DENO_CERT` to use certificates including corp ones

But vscode deno extension does not seem aware of proxy env variables. As a result remote links appear underlined in red wiggle and "Uncached or missing remote URL" on hover e.g.:

![image](https://github.com/denoland/vscode_deno/assets/2219383/3614433a-f230-42bc-810e-5785eb6bbaeb)

![image](https://github.com/denoland/vscode_deno/assets/2219383/8ac8a6b8-9c41-4d24-aff0-e3fc870fa46a)

_NOTE_: Here they look ok as I write from **outside corp env** 

An unfortunate consequence for dev exp is that all objects from these outside links are considered `any` which breaks type checks and forces to use `// deno-lint-ignore no-explicit-any` in the rest of the code.

On the other hand the certificate config can be set in `.vscode/settings.json`: 

```json
{
    "deno.enable": true,
    "deno.cache": ".cache",
    "deno.tlsCertificate": "/path/to/corp/ca-certificates.crt",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "[typescript]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    }
}
```

A surprising fact is that even if vscode proxy settings are explicitly set (in field below) this does not help vscode deno extension - as opposed to other extensions of vscode. 

![image](https://github.com/denoland/vscode_deno/assets/2219383/701f287f-70e8-44f0-90eb-2bb22fcaa7cf)

This limitation is a serious drag for deno use in a corp env I'm afraid.  
Surely you know it already but just wanted to describe this problem precisely.

**Comment by nayeemrmn** [comment]
@oscar6echo I've checked that `HTTP_PROXY` and all other env vars are passed from the user's env to the language server (which handles module downloads) by the extension. How do you set the env vars, and have you tried clearing the cache?

**Comment by nayeemrmn** [comment]
@justinmchase Is it acceptable to set `NPM_CONFIG_REGISTRY` in your user profile before opening VSCode? That will be passed to the language server.

**Comment by justinmchase** [comment]
I'm pretty sure I do have it set that way but will check again and yeah it would be ok to pick it up that way in my case, since it's a machine global. But I could see someone still wanting a per repo setting.

**Comment by oscar6echo** [comment]
> @oscar6echo I've checked that HTTP_PROXY and all other env vars are passed from the user's env to the language server (which handles module downloads) by the extension. How do you set the env vars, and have you tried clearing the cache?

What do you call user's env ? Do you mean the terminal from which to start VS Code ? If so, it may not apply in my case as I use [VS Code remote SSH](https://code.visualstudio.com/docs/remote/ssh) to connect to a machine. The [doc](https://code.visualstudio.com/docs/remote/ssh#_remote-ssh-limitations) warns about it, if I understand well. This is why I explicitly tried the `HTTP(S)_PROXY` env vars via VS Code settings (see last part of my comment , keeping in mind I could not screen shot the exact thing as I write from outside corp env - in particular the visual is a bit different for a remote host) but it did not work while it **does** for other extensions (tested).  

*Suggestion*: the vscode_deno extension could read env vars from an env file passed in deno settings say (or similar):

 ```json
{
  "deno.proxyEnvFile": "path/to/env/file.env"
}
``` 

This optional setting would override the current behavior - and  be pleasantly explicit and easy to understand,  
What do you think ?

**Comment by nayeemrmn** [comment]
@oscar6echo Version 3.38.0 of the extension has been released. You can now have settings like:
```json
{
  "deno.envFile": "path/to/env/file.env"
}
```

```json
{
  "deno.env": {
    "HTTP_PROXY": "http://localhost:8080"
  }
}
```

@justinmchase Please try this with `NPM_CONFIG_REGISTRY` also. But if you had it configured on your machine it should have already worked. It may be a separate issue.

**Comment by oscar6echo** [comment]
@nayeemrmn thx for the super fast release !  :clap: Much appreciated !  
I'll test next week when back in the office.

**Comment by oscar6echo** [comment]
> I'll test next week when back in the office.
 
@nayeemrmn  It does work fine (unsurprisingly) and this is really pleasant. Thx again !

**Comment by bartlomieju** [comment]
Great to hear that @oscar6echo, I'll close this issue for now. Let me know if you face any other problems.
