### ISSUE TITLE
`denoland.vscode-deno` should have support for `--node-modules-dir=false`

### ISSUE THREAD

**Issue by loynoir** [denoland/vscode_deno#839]
**Describe the bug**

`deno(no-cache-npm)`

**To Reproduce**

1. `deno(no-cache-npm)`
2. mv package.json{,.bak}
3. `Deno: restart language server"
4. `deno(no-cache-npm)` is gone

**Expected behavior**

**Screenshots**

**Versions**

vscode: xxx deno: xxx extension: xxx

**Related**

https://github.com/denoland/vscode_deno/issues/819

https://github.com/denoland/deno/issues/17930

https://github.com/denoland/deno/issues/17930#issuecomment-1462434807

https://github.com/denoland/deno/issues/17829

https://github.com/denoland/deno/issues/18438

**Comment by bartlomieju** [comment]
Hey @loynoir, sorry for a slow response. Do you still experience this problem when using latest Deno?
