### ISSUE TITLE
Support formatting json with comments

### ISSUE THREAD

**Issue by matklad** [denoland/vscode_deno#840]
I have the following in my VsCode's `settings.json` (which is a "json-with-comments file despite the extension"):

```jsonc
    "[json]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    },
    "[jsonc]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    },
```

However, if I try to format it I get 

![image](https://user-images.githubusercontent.com/1711539/233633776-e5334a96-7f68-4226-b716-528a4de97737.png)

It feels like this should just work, and perhaps there's some config somewhere  missing to enable this?

**Comment by dsherret** [comment]
I'm not sure what's causing that for you because when I try that it works for me :/

**Comment by matklad** [comment]
Aha, that's very curious. When I open my settings.json as a file, formatting works. However, if I open it via `Ctrl+Shift+P > Open User Settings (JSON)`, then I see the above dialog. So it looks like vscode bug

**Comment by bartlomieju** [comment]
Hey @matklad, have you experience the same problem again? I'm not sure if we should investigate it on our side or if that's been fixed.

**Comment by bartlomieju** [comment]
Please see https://github.com/denoland/vscode_deno/issues/860#issuecomment-1642655153
