### ISSUE TITLE
`imports` from `deno.json` causing `deno(import-prefix-missing)` in multi-root workspaces

### ISSUE THREAD

**Issue by KrofDrakula** [denoland/vscode_deno#845]
**To Reproduce**

**NOTE:** This works when opening a deno project in an exclusive VS Code window. Using this in a multi-root project breaks.

After enabling Deno for the workspace, use the following `deno.json` configuration:

```json
{
  "imports": {
    "streams/": "https://deno.land/std@0.185.0/streams/"
  }
}
```

In a file in the workspace, try importing the bare identifier:

```ts
import { TextLineStream } from "streams/text_line_stream.ts";
new TextLineStream(); // just to avoid the warning
```

Running this file with Deno works as expected, so the import identifier works.

**Expected behavior**

Import maps should resolve using the LSP in the editor to match how Deno runs.

**Screenshots**

![image](https://user-images.githubusercontent.com/112161/235727977-afbaf6c8-f3a7-4805-80e4-4229c462c214.png)

**Versions**

vscode: 1.77.3
deno: 1.33.1
extension: 3.17.0

**Comment by KonghaYao** [comment]
Hello, when I encountered this issue, I checked the official documentation and solved it in this way.
![image](https://user-images.githubusercontent.com/68177907/236653938-1e656be2-58ee-421e-8f45-168097e585fa.png)

**Comment by KrofDrakula** [comment]
@KonghaYao `imports` within `deno.json` are detected automatically without having to set that configuration value. The problem is not in a single-root workspace like you have in your example — I've already mentioned this in the original description.

The problem are multi-root workspaces.

**Comment by jeslinmx** [comment]
Hi @KrofDrakula,

Can I check if you performed any special configuration to allow this to work in a single-root workspace? Based on the comment by @KonghaYao, #718, #805, #833, and my own usage, it seems to be broken there as well.

**Comment by KrofDrakula** [comment]
@jeslinmx No, I just opened a new window (which I guess creates a blank workspace that I don't save) and the Deno project within in as a folder, no special configuration necessary for me.

**Comment by leighmcculloch** [comment]
> **NOTE:** This works when opening a deno project in an exclusive VS Code window. Using this in a multi-root project breaks.

This issue happens in another case: when a new window is opened for an empty directory, when building a new single-root project. After adding the deno.json file with an import, the same error displays about import prefixes. The deno extension fails to pickup the imports from the deno.json file. Reloading the window gets it working again.

<img width="1040" alt="Screenshot 2023-07-08 at 10 26 06 PM" src="https://github.com/denoland/vscode_deno/assets/351529/7c7eb89b-866a-437f-b16f-60386401e14d">

**Comment by bartlomieju** [comment]
Thanks for the report folks. Do you still experience these problems with Deno v1.35? [There were](https://deno.com/blog/v1.35#language-server-improvements) several improvements to the import map handling in the LSP and I'm wondering if this problem still persists.

**Comment by leighmcculloch** [comment]
I'm experiencing these problems with Deno v1.35.0, Deno VSCode Extension v3.19.1. Note I don't see this error when building with Deno v1.35.0 on the command line. I only see the issue in VSCode.

**Comment by luisfontes** [comment]
Experiencing the same issue on Deno v1.35.0. I had it "working" by using
```"deno.config": "./packages/database/deno.json",```
in the code-workspace file.

**Comment by kaiba42** [comment]
+1 on this issue. I've got a limited understanding, but perhaps it's worthwhile to consider enabling the `deno.importPath` setting in `.vscode/settings.json` files within the folders specified in a multi-root workspace (`.vscode/projects.code-workspace`)

For example
```jsonc
// workspace/.vscode/projects.code-workspace
{
  "folders": [
    {
      "name": "Workspace",
      "path": "../"
    },
    {
      "name": "Project 1",
      "path": "../project1"
    },
    {
      "name": "Project 2",
      "path": "../project2"
    }
  ],
  "settings": {
    // Deno
    "deno.enable": true,
    "deno.enablePaths": ["./project1", "./project2"],
    "deno.unstable": true,
    "deno.suggest.imports.autoDiscover": true,
    "deno.lint": true,
    "deno.path": "./.devenv/profile/bin/deno",
    // -- This doesn't work today because it can only be specified for a single project --
    // "deno.importMap": "./project1/deno.jsonc",
  }
}
```

```jsonc
// workspace/project1/.vscode/settings.json
{
    "deno.enable": true,
    "deno.importPath": "./deno.jsonc" // <----------- ADD SUPPORT FOR THIS
    "[typescript]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    }
}
```

**Comment by nayeemrmn** [comment]
Closing in favour of #787.
