### ISSUE TITLE
deno vscode extension - deno.enablePaths not working with relative paths in windows

### ISSUE THREAD

**Issue by cpakken** [denoland/vscode_deno#851]
> > Hello. I have just tested v3.14.1 on Windows and the language server doesn't start. I reversed back to v3.14.0 and everything worked fine again.
> 
> Same, enablePaths doesn't work for me either in Windows 10 (Deno v1.33.4) How do you see Deno's language server version?

deno.enablePaths seems to activate when I use the full absolute paths on windows. But the typescript server isn't disabled.
![image](https://github.com/denoland/vscode_deno/assets/61718569/3841a75c-d5b6-4579-bccf-5898f4c40a2b)

Here is using relative paths. Deno is not enabled
![image](https://github.com/denoland/vscode_deno/assets/61718569/91457af3-831c-4475-b5fc-328aa8686e87)
Works without deno.enablePaths
![image](https://github.com/denoland/vscode_deno/assets/61718569/f7c1d3c4-a511-43c7-b109-84d15949c44a)

But other files in my workspace breaks

_Originally posted by @cpakken in https://github.com/denoland/vscode_deno/issues/745#issuecomment-1553841343_

**Comment by dsherret** [comment]
> How do you see Deno's language server version?

Check the bottom left status bar or View > Output > then select "Deno Language Server" on the dropdown in the output window.

It works for me. Do you have a repo I could try this in?

**Comment by cpakken** [comment]
I fixed it. I was using multiple sub folders in my workspace. I needed to specify the deno settings in .vscode/settings.json inside that specific subfolder.
![image](https://github.com/denoland/vscode_deno/assets/61718569/fc435d93-126a-4c56-a722-3599dd108b51)

Here's the repo if anyone is interested the setup
https://github.com/cpakken/deno-enablePaths
