### ISSUE TITLE
Deno Tasks Sidebar (NPM Scripts)

### ISSUE THREAD

**Issue by ArmaanAS** [denoland/vscode_deno#852]
**Is your feature request related to a problem? Please describe.**

Node.js projects have an "NPM Scripts" section in the VSCode Explorer sidebar with buttons that allow us to quickly run scripts contained in package.json. I usually use it to quickly lint the project, run the dev server or run the tests. 

**Describe the solution you'd like**

It would be really nice for Deno extension to add the same feature, maybe called "Deno Tasks". This should only show when there is a deno.json/c file present in the project / in a directory in the project. There should be a run button and possibly a debug button. If you double click a task it takes you to the definition in deno.json/c file.

NPM Scripts also allow for monorepos where each package.json found in the project creates a nested section in the sidebar area.

Finally NPM Scripts include an "npm install" button at the bottom of the list of scripts. I propose a "deno cache" button which does a similar thing.

![image](https://github.com/denoland/vscode_deno/assets/38160090/7767e34a-bfff-4c08-a3b2-aebab15b5a9c)

**Comment by bartlomieju** [comment]
This is certainly a desirable feature, but no one had looked into implementing it yet.

A few pointers for anyone interested:
- here's some intel how it works in VSCode: https://code.visualstudio.com/api/ux-guidelines/sidebars
- We need to add contributions to "view containers": https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers
- An example extension that implements such feature: https://github.com/Duroktar/vscode-npm-scripts (can be used for inspiration or getting started with writing this feature)

**Comment by ArmaanAS** [comment]
I’ve opened a Pull Request (#958) which adds this feature. It’s a large pull request because I added as many features as possible to match the functionality of NPM Scripts. Please take your time to review it. Thanks
