### ISSUE TITLE
respect `fmt` option in `deno.json` for auto imports

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#856]
**Is your feature request related to a problem? Please describe.**

i use following `deno.jsonc`:
```jsonc
// deno.jsonc
{ "fmt": { "semiColons": false } }
```

however auto import feature will not respect `"semiColons": false` option and add semicolons at the end.

**Describe the solution you'd like**

while the problem can be easily solved with `format on save`, respecting `fmt` options would be appreciated.

**Comment by scarf005** [comment]
I'm (also) willing to open a PR, @bartlomieju could you provide me some pointers on where to look at?

**Comment by bartlomieju** [comment]
@scarf005 I'll get back to you soon. I'm not entirely sure how to fix it yet.

**Comment by dsherret** [comment]
@scarf005 we are currently not providing formatting settings to function calls like `getCompletionsAtPosition` and `getCompletionEntryDetails`

https://github.com/denoland/deno/blob/80331d1fe5b85b829ac009fdc201c128b3427e11/cli/tsc/99_main_compiler.js#L1037
https://github.com/denoland/deno/blob/80331d1fe5b85b829ac009fdc201c128b3427e11/cli/tsc/dts/typescript.d.ts#L6179

Probably providing the format settings there would fix this. We'd need to pass them into typescript via https://github.com/denoland/deno/blob/main/cli/lsp/tsc.rs

**Comment by dsherret** [comment]
@scarf005 are you interested in looking at this one? Otherwise I can look into it sometime in the next few weeks.

**Comment by scarf005** [comment]
I'll take a look this weekend

**Comment by scarf005** [comment]
indeed this was a lot more complex than i could handle. sorry i couldn't help more.

**Comment by bartlomieju** [comment]
Thanks for the info @scarf005. We'll look into it then.
