### ISSUE TITLE
wrong auto-import path when importing from npm 

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#857]
**Describe the bug**

**To Reproduce**

```ts
// main.ts
import { match, P } from "npm:ts-pattern"
```
```
// other.ts
match // auto-import
```

**Expected behavior**

```ts
import { match } from "npm:ts-pattern"
```
however, auto import will write:
```ts
import { match } from "../../.cache/deno/npm/registry.npmjs.org/ts-pattern/4.3.0/dist/match.d.ts";
```

**Videos**

https://github.com/denoland/vscode_deno/assets/54838975/d8b56f9e-fe18-4559-a2d8-bda748891045

**Versions**

vscode: 1.75.0 deno: 1.34.0 extension: 3.19.1

**Comment by ooyay** [comment]
same, my deno.json file
```json
{
  "imports": {
    "koa": "https://esm.sh/koa@2.14.2?target=denonext",
    "koa-router": "https://esm.sh/@koa/router@12.0.0?target=denonext",
    "koa-bodyparser": "https://esm.sh/v120/koa-bodyparser@4.4.0?target=denonext",
    "koa-cors": "https://esm.sh/@koa/cors@4.0.0?target=denonext",
    "zod": "https://esm.sh/zod@3.21.4",
    "mongodb": "npm:mongodb",
    "jwt": "npm:jsonwebtoken"
  }
}
```
auto import always from cached files, am getting this warning sometimes.

<img width="546" alt="image" src="https://github.com/denoland/vscode_deno/assets/91382501/59e46d11-fe44-4456-9506-a199fc61eb17">
