### ISSUE TITLE
vscode_deno consumes over 700MB memory on Windows

### ISSUE THREAD

**Issue by liigo** [denoland/vscode_deno#859]
**Describe the bug**

When working with a fresh project, vscode_deno consumes over 700MB memory.

**To Reproduce**

1. create a fresh project: `deno run -A -r https://fresh.deno.dev my-project` (enable Tailwind CSS and VS Code)
2. run `deno task start` in a terminal
3. open the project in VS Code
4. install vscode extensions Deno and Twind Intellisense if you haven't
5. open `index.tsx` and `[name].tsx` file in VS Code

**Expected behavior**
vscode_deno consumes memory less than 200MB, not more than 700MB.

**Screenshots**

![deno-mem](https://github.com/denoland/vscode_deno/assets/346530/e4bccebb-0fb5-4748-bb00-c873268eaa9c)

**Versions**

extension: v3.19.1
deno: 1.34.1
vscode: 1.78.2

**Comment by nayeemrmn** [comment]
We've made significant optimisations to memory usage. Please comment if it's still not acceptable, closing for now.
