### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by newtack** [denoland/vscode_deno#86]
I use this: 
import ky from "https://unpkg.com/ky/index.js";

(copied directly from https://deno.land/x/ky)

I get this error message:

Cannot find module 'https://unpkg.com/ky/index.js' or its corresponding type declarations.ts(2307)

I use the latest version of Deno (1.1) and this extension on the latest version VCode on Ubuntu 18.04.

**Comment by lucacasonato** [comment]
This is the intended behaviour. After installing the extension you should restart VS Code to initialize it. You can now use the `Fetch source file` quickfix to fetch a module that you do not have cached yet.

**Comment by mvasin** [comment]
I'm still running into this with the extension [this one, to avoid confusion](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno), even after restarting VS Code. Versions:

```
> deno --version
deno 1.29.1 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

The extension:
Last released 14/12/2022, 15:04:18
Last updated 17/12/2022, 16:50:12

**Comment by bartlomieju** [comment]
Does the problem persist if you run `Cache dependencies` action?

**Comment by mvasin** [comment]
Yes:

![Screenshot 2022-12-17 at 22 21 01](https://user-images.githubusercontent.com/12434833/208266399-5cb750ba-6571-46ed-bcb4-4fb0152f6775.png)

**Comment by LeoDog896** [comment]
By the way, I don't think this file exists in this module - [whenever visiting it](https://unpkg.com/ky@0.33.0/index.js), I get this error:

```
Cannot find "/index.js" in ky@0.33.0
```

**Comment by Almenon** [comment]
Same issue, but then I realized that I needed to run the `Deno: Initialize Workspace Configuration` command in VSCode. Once I ran that it worked.

**Comment by PhoneDroid** [comment]
@bartlomieju 

***This issue should be closed.***

<br>

-   The library's entrypoint moved to
    `/distribution/index.js` instead  
    of `/index.js`

-   If a user initializes the workspace
    with the Deno setup command and  
    caches the library, it works.

<br>

#### Example for reference

```ts
import ky from 'https://unpkg.com/ky/distribution/index.js'

console.log('KY',ky)
```

<br>

**Comment by bartlomieju** [comment]
Thanks for the ping @PhoneDroid!

**Comment by mindplay-dk** [comment]
> Same issue, but then I realized that I needed to run the `Deno: Initialize Workspace Configuration` command in VSCode. Once I ran that it worked.

I don't know what this does, but apparently this is still required in 2024.

Since this is required, shouldn't the extension just make sure this command gets run when you open your new Deno project for the first time? Or at least issue one of those prompts VS Code gives for certain suggested commands at certain times?

I'm just following the "Getting started" tutorial, installing Deno and the VS Code extension, and running `deno init my_project` - and my editor is already full of errors. I'm sure this is not the intended onboarding experience for new users?

(I'm on Windows 11 with WSL2 and Ubuntu.)

**Comment by nayeemrmn** [comment]
@mindplay-dk You may have `"deno.enable": false` in your global/user settings. Please check for this and remove it.

**Comment by mindplay-dk** [comment]
> @mindplay-dk You may have `"deno.enable": false` in your global/user settings. Please check for this and remove it.

no, `deno init` does not include a `.vscode/settings.json` file in a new project - this gets added by the VS Code extension (when you run the "initialize workspace" command) which initializes it as follows:

```
{
  "deno.enable": true,
  "typescript.tsserver.experimental.enableProjectDiagnostics": false
}
```

that's sort of the issue I'm pointing at - even with the VS Code extension for Deno installed, when you open a new Deno project for the first time, it's showing errors everywhere.

**Comment by nayeemrmn** [comment]
Oh right it's because of `typescript.tsserver.experimental.enableProjectDiagnostics` in your user settings probably. This is incompatible with the extension because we can't suppress the diagnostics caused by that setting.

**Comment by mindplay-dk** [comment]
> Oh right it's because of `typescript.tsserver.experimental.enableProjectDiagnostics` in your user settings probably. This is incompatible with the extension because we can't suppress the diagnostics caused by that setting.

you can't?

isn't that exactly what the `Deno: Initialize Workspace Configuration` command does? by adding that option to the local `.vscode/settings.json` file in the project?

I didn't add that myself. 🙂

so again:

> shouldn't the extension just make sure this command gets run when you open your new Deno project for the first time? Or at least issue one of those prompts VS Code gives for certain suggested commands at certain times?

that way no one needs to adventure through the interwebs to find this thread. 🙂
