### ISSUE TITLE
Not working, confusing error message with"editor.formatOnSaveMode": "modificationsIfAvailable" 

### ISSUE THREAD

**Issue by rotu** [denoland/vscode_deno#860]
**Describe the bug**

I have my project set up to use Deno as a formatter, but it doesn't format on save, instead giving the error message:
> "Extension 'Deno' is configured as formatter but it cannot format 'TypeScript'-files"

This error message is extra confusing since the extension *can* format a file with "Format Document" or "Format Document With..." commands.

1. open a workspace under git source control
2. add the following to workspace setup:
   ```json
	"[typescript]": {
		"editor.defaultFormatter": "denoland.vscode-deno"
	},
	"[javascript]": {
		"editor.defaultFormatter": "denoland.vscode-deno"
	},
	"editor.formatOnSave": true,
	"editor.formatOnSaveMode": "modificationsIfAvailable"
   ```
3. Edit and save a typescript file.

If I disable the builtin plugin `vscode.git`, or if I set mode="file", format on save works again.

**Expected behavior**

I expect one of the following in decreasing order of preference:

1. Format the modified section of the file
2. Format the whole file
3. Give an explanatory message to change `"editor.formatOnSaveMode"`

**Screenshots**

<img width="425" alt="image" src="https://github.com/denoland/vscode_deno/assets/119948/4000d3a6-e214-40d5-b7a2-41eaa9623384">

**Versions**

vscode: 1.78.2 deno: 1.34.1 extension: 3.19.1

**Comment by bartlomieju** [comment]
Appears related to https://github.com/denoland/vscode_deno/issues/840, https://github.com/denoland/vscode_deno/issues/829 and https://github.com/denoland/vscode_deno/issues/657

**Comment by dsherret** [comment]
I'm not sure if there's much that can be easily done here. Deno doesn't support range formatting (modifications/modificationsIfAvailable) so the vscode-languageclient sees that Deno says it doesn't support range formatting, then doesn't range format, and that message box appears. It would be nice if there were an instructional message box to remove the ` "editor.formatOnSaveMode": "modificationsIfAvailable"`, but I'm not sure if there's a way to inject that somewhere. If anyone knows a way or has some suggestion based on knowing how vscode and vscode-languageclient works, please let me know.

So unfortuantely I'm going to close this one as "wontfix". The workaround to get this to work is to remove `"editor.formatOnSaveMode": "modificationsIfAvailable"`. The extension should be fast enough at formatting individual files that you shouldn't really need this option anyway.

**Comment by rotu** [comment]
@dsherret I think you're right and this is a bug upstream. Namely, the Deno language server says [it supports document formatting](https://github.com/denoland/deno/blob/da709729e3dd6f310182581ca1c6380ad51443fc/cli/lsp/capabilities.rs#L110C1-L112) and the [integration layer `vscode-languageclient`](https://github.com/microsoft/vscode-languageserver-node) should understand this since the protocol differentiates between [document formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) and [range formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rangeFormatting), but [vscode](https://github.com/microsoft/vscode/blob/696f9682f38055b0d82a076450a46b2ed5958cbe/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L110-L144) is spitting out an error message that misrepresents the situation.
