### ISSUE TITLE
deno.testing.enable setting does nothing

### ISSUE THREAD

**Issue by jespertheend** [denoland/vscode_deno#864]
**Describe the bug**

The `deno.testing.enable` preference doesn't seem to have any effect.

**To Reproduce**

1. Go to settings
2. Uncheck the deno.testing.enable preference
3. Open a test file
4. Restart language server just in case

**Expected behavior**

Test file does not show testing icons in the gutter. And the testing explorer view is not visible.

**Versions**

vscode: 1.78.2 deno: 1.34.2 extension: v3.19.1

**Comment by nayeemrmn** [comment]
We should remove this setting. I think during initial development of the test server, it was replaced by `ClientCapabilities::testing_api` but accidentally left in. We have `deno.codeLens.test` to disable the code lens. No way to disable the explorer for now.
