### ISSUE TITLE
Unable to rename symbols

### ISSUE THREAD

**Issue by CalvinWilkinson** [denoland/vscode_deno#865]
**Describe the bug**

On a regular basis, I will be working with typescript files and attempt to rename a variable, class, or function and I will get the tooltip saying that _**The element can't be renamed.**_.  I cannot repeat this.  Usually, I have to reload the VSCode to get it to go away to allow me to rename symbols again.  But this doesn't work all the time either.  Sometimes as soon as it is done reloading, I attempt to do a rename and it won't let me.

This happens VERY frequently.  I wish I could tell you how to repeat it but I do not know how.  😔

**To Reproduce**

1. Can't repeat, it just happens very often.

**Expected behavior**

I expected to be able to choose any typescript symbol and be allowed to rename it with no issues.

**Screenshots**
<img width="718" alt="image" src="https://github.com/denoland/vscode_deno/assets/85414302/316fc261-39d3-4aa2-a293-58a1d1080075">

**Versions**

vscode: v1.79.0
deno: v1.34.2
extension: v3.19.1

**Comment by CalvinWilkinson** [comment]
**Quick Update**
I was setting up some custom VSCode profiles the other day and I set one up that had only the extensions that I needed for deno/typescript projects.   Since I have done that, I have not had a single issue.  

My thoughts are that somehow, the previous default profile that I was using which had many more extensions installed and enabled, was causing conflicts.  I cannot tell you exactly what was causing the problem though.

As of right now, I am good to go. 😀

**Comment by bartlomieju** [comment]
Thanks for the report @CalvinWilkinson, these problems are really tricky to debug. I'm gonna close the issue for the time being, but we'll revisit it if we get more reports.
