### ISSUE TITLE
Disable extension for a subdirectory

### ISSUE THREAD

**Issue by taigah** [denoland/vscode_deno#87]
I know how to disable the extension in a project by using a `.vscode/settings.json` file but it does not seem to work for subdirectories of a project.

My problem is that I have a project in which there is deno code and browser javascript but because of the deno extension I have lint errors like "Could not find name 'alert'".

How can I prevent that?

**Comment by adekau** [comment]
What I've been doing as a workaround is having two VSCode windows open, one with my backend code folder opened and one with my frontend code folder opened. Then using the commands for enabling and disabling Deno from the command palette puts a .vscode folder in each so you can control them separately.

**Comment by Flaque** [comment]
We're using Deno inside a monorepo, so I'm going to try and play around with building a config option for this. No guarantees or anything, first time doing a VS Code extension, so don't let me stop anyone else from taking this.

## Proposal 

Deno VS Code should support a `deno.paths` variable that lets you specify folders or files via blob syntax as deno enabled.

For example, a config like this:
```
{
  "deno.paths": ["packages/deno-project/**", "*.deno.ts"]
}
```

Would set anything in the `packages/deno-project` folder as well as any file like `foo.deno.ts`.

**Comment by lucacasonato** [comment]
Closing in favor of https://github.com/denoland/vscode_deno/issues/314
