### ISSUE TITLE
Auto import suggestion ignores `"imports"` field in `deno.json`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/vscode_deno#870]
**Describe the bug**

When running the quick fix command to add missing imports for types the extension disregards the `"imports"` configuration in `deno.json`. It only suggests the full URL instead of the aliased path.

**To Reproduce**

1. Create  `deno.json` with the content:
  ```json
  {
    "imports": {
      "preact": "https://esm.sh/preact@10.15.1",
    }
  }
  ```
2. Create `foo.tsx` with the content:
  ```tsx
  import { ComponentChildren } from "preact";

  export interface Props {
    children?: ComponentChildren;
  }
  
  export function Foo(props: Props) {
    return props.children;
  }
  ```
3. Run `deno run -A foo.tsx` to cause deno to download Preact and its types.
4. Delete the `import` statement
  ```diff
  - import { ComponentChildren } from "preact";

    export interface Props {
      children?: ComponentChildren;
    }
  
    export function Foo(props: Props) {
      return props.children;
    }
  ```
5. VSCode will complain that an import for `ComponentChildren` is missing in the `Props` interface correctly.
6. Now click on `ComponentChildren` and run vscode's `Quick Fix...` command.

**Expected behavior**

It should suggest importing the `ComponentChildren` type from `preact`, meaning the aliased value from `deno.json`. Instead it suggest to import from `https://esm.sh/v118/preact@10.15.1/src/index.js`

**Screenshots**

<img width="618" alt="Screenshot 2023-06-18 at 17 20 14" src="https://github.com/denoland/vscode_deno/assets/1062408/ef165185-1131-4c7a-824b-80014ee7dcfc">

**Versions**

- vscode: 1.80.0-insider 61ba389b0a7108af0411c73ab30c7e4350051645 (16th June 2023)
- deno: 1.34.3
- extension: v3.19.1

**Comment by bartlomieju** [comment]
This is now fixed when using Deno v1.35 - https://deno.com/blog/v1.35#language-server-improvements
