### ISSUE TITLE
Deno logo for vscode ext has poor quality

### ISSUE THREAD

**Issue by gokulkrishh** [denoland/vscode_deno#88]
I just noticed the quality of icon in vscode ext in store is in low quality.

Can we have higher quality image?

I created one, feel free to use this or bump the quality existing of image.

![vscode-deno](https://user-images.githubusercontent.com/2944237/84758163-b73e3b00-afe2-11ea-85bc-9434594960be.png)

**Comment by lucacasonato** [comment]
Resolved in version 3.x of the extension.
