### ISSUE TITLE
Auto-enable extension when deno.json/deno.jsonc is present

### ISSUE THREAD

**Issue by boywithkeyboard** [denoland/vscode_deno#880]
It'd be awesome if the extension could by default look for a deno.json or deno.jsonc file and if one of the two is available, set `deno.enable` automatically to `true`.

**Why?**

A lot of Deno projects (e.g. the std library) don't configure `deno.enable` for just the workspace, making it annoying for people who don't have  `deno.enable` set to `true` globally.

Also, this would allow us to have one file less in our codebases. :)

**Comment by bartlomieju** [comment]
@dsherret and I discussed this recently and it's something we definitely want to look at. Having `deno.json` in the root of the workspace should enable the extension automatically without any configuration from VSCode.

**Comment by boywithkeyboard** [comment]
@bartlomieju awesome to hear!

**Comment by felipecrs** [comment]
@bartlomieju has this been assigned to someone already?

**Comment by bartlomieju** [comment]
@felipecrs, no, not yet.
