### ISSUE TITLE
V8 Fatal error when trying to debug test

### ISSUE THREAD

**Issue by amitlevy-bu** [denoland/vscode_deno#882]
**Describe the bug**
Hi,
I get a fatal error from v8 when trying to debug a simple test in Deno with vs code.
Please note, I'm using an M1 Mac, and haven't tried it on x86.

I tried using `deno.unstable` true and false options in settings.json of vscode.

**To Reproduce**

1. copy the simple test code
```typescript
import { assertEquals } from "https://deno.land/std@0.129.0/testing/asserts.ts"

Deno.test("example test", () => {
  const x = 1
  assertEquals(x, 2)
})
```
2. copy the settings.json to .vscode/settings.json
```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "deno.codeLens.test": true,
  "editor.formatOnSave": true,
  "[typescript]": { "editor.defaultFormatter": "denoland.vscode-deno" }
}

```
3. press on debug button
4. get the following error
```
#
# Fatal error in v8::Context::GetMicrotaskQueue
# Must be called on a native context
#
```

**Expected behavior**

Should able to debug with stopping on a breakpoint, step in, step out, next line, etc.

**Screenshots**

![image](https://github.com/denoland/vscode_deno/assets/98011907/6e753659-beca-4e8c-979e-7352f8ef9653)
**Versions**

```
extension: 3.19.1
```

```
❯ deno --version       
deno 1.35.2 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```

```
❯ code --version         
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
arm64
```

Thank you for taking a look!

**Comment by ooker777** [comment]
I get the same error today

**Comment by Leokuma** [comment]
This is a bug in Deno v1.35.2. You can downgrade to v1.35.1 in the meantime.

Issue: https://github.com/denoland/deno/issues/19907
