### ISSUE TITLE
Cannot get internal TypeScript plugin configuration API. 

### ISSUE THREAD

**Issue by yeonjulee1005** [denoland/vscode_deno#883]
hello, my friend! 

I using deno in vscode
but some error occur like below,

```
Error: The Deno extension cannot load the built in TypeScript Language Features. Please try restarting Visual Studio Code.
```

<img width="479" alt="스크린샷 2023-07-26 오전 8 49 28" src="https://github.com/denoland/vscode_deno/assets/57179957/1779d65b-6d2d-4619-87e5-df59984378e8">

i try reinstall deno, vscode, deno extension.. but it dosen't work

also finish worksapce setting like this

```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
}
```

how should i fix ? please help me~~!
my enviroment is below,

```
vscode
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
arm64
```

```
deno 1.35.2 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```

**Comment by bartlomieju** [comment]
Does your VSCode installation have TSServer available?

**Comment by mersocarlin** [comment]
I had the same after updating my VS Code to 1.80.2. Reverting it back to [1.79](https://code.visualstudio.com/updates/v1_79) solved it for now.
