### ISSUE TITLE
deno.disablePaths

### ISSUE THREAD

**Issue by callumlocke** [denoland/vscode_deno#889]
**Is your feature request related to a problem? Please describe.**

I want to enable Deno *except* in certain directories. I have a project that is primarily Deno-based, including some Deno scripts in the project root as well as in subdirectories, but I also have one subdirectory that contains TS/JS files intended for bundling for the browser, which I do not want Deno trying to lint etc.

**Describe the solution you'd like**

A `deno.disablePaths` array option (which would be applied to un-enable paths after they have been enabled via `deno.enable` or `deno.enablePaths`), or really any other solution that would let me keep the root directory Deno-enabled while excluding subdirectories from it.

Simply using `deno.enablePaths` (listing all the subdirectories containing Deno scripts) doesn't work if you also have files intended for Deno in the root of the project.

**Comment by bartlomieju** [comment]
Let's continue in https://github.com/denoland/vscode_deno/issues/817 as it looks like the same request.
