### ISSUE TITLE
Running a particular test via code lens runs unrelated tests

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/vscode_deno#897]
**Describe the bug**

Clicking on the `Run Test` code lens runs every test matching with the same prefix instead of only the one of the current code lens.

**To Reproduce**

1. Create a file with the following content:
  ```js
  Deno.test("foo", () => console.log("runs: 'foo'"));
  Deno.test("foo bar", () => console.log("runs: 'foo bar'"));
  ```
2. Click on `Run Test` of the first code lens in vscode 
<img width="588" alt="Screenshot 2023-08-27 at 09 31 51" src="https://github.com/denoland/vscode_deno/assets/1062408/80cc224a-5e06-40c2-8e8f-efdce368ac5e">

Output:

```sh
running 2 tests from ./foo_test.ts
foo ...
------- output -------
runs: 'foo'
----- output end -----
foo ... ok (8ms)
foo bar ...
------- output -------
runs: 'foo bar'
----- output end -----
foo bar ... ok (4ms)

ok | 2 passed | 0 failed (33ms)
```

**Expected behavior**

Only the first test should run, but instead both test `foo` and test `foo bar` are executed.

**Versions**

- vscode: `1.82.0 insiders` from 2023-08-25
- deno: `1.36.3`
- extension: `v3.20.0`

**Comment by bartlomieju** [comment]
Fixed by #798, wilk be released in a few days.
