### ISSUE TITLE
Language server crashes when creating new file

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/vscode_deno#901]
**Describe the bug**

Language server crashes when creating new file

**To Reproduce**

1. Create an empty folder `mkdir test-project`
1. Navigate into that via the terminal and create a new deno project `cd test-project && deno init`
1. Open that folder in vscode `code .`
1. Delete all `.ts` files in the project inside vscode via the "Explorer" sidebar
1. Create a new `foo.tsx` file via the "Explorer" sidebar -> LSP crashes

**Expected behavior**

The language server should not crash.

**Screenshots**

**Versions**

vscode: insiders from today 30.08.2023 deno: 1.36.3 extension: v3.20.0

**Comment by nayeemrmn** [comment]
@marvinhagemeister IIRC we couldn't reproduce this one again. Have you seen it since?
