### ISSUE TITLE
VSCode documentation out of date

### ISSUE THREAD

**Issue by CoenraadS** [denoland/vscode_deno#904]
**Describe the bug**

The documentation at https://deno.land/manual@v1.0.0/tools/debugger#vscode says to use the following configuration:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Deno",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": ["run", "--inspect-brk", "-A", "<entry_point>"],
      "port": 9229
    }
  ]
}
```

VSCode shows the following message:

![image](https://github.com/denoland/vscode_deno/assets/5593825/6606c842-c9c9-4643-a972-bccbd7636769)

Furthormore, people on stackoverflow https://stackoverflow.com/questions/61853754/how-to-debug-deno-in-vscode
Also recommend to add `"outputCapture": "std"`

**To Reproduce**

I now have the following config:

```
{
            "name": "Deno",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": ["run", "--inspect-brk", "-A", "main.js"],
            "outputCapture": "std",
        }
```

I get the following message in the terminal:

![image](https://github.com/denoland/vscode_deno/assets/5593825/1137a593-ecb6-43ce-b6a3-5b50b32dcbbe)

**Expected behavior**

When I run, I expect the vscode debugger to attach and my breakpoint to be hit

**Versions**

vscode: 1.81.1 deno: 1.36.3 extension: Deno: v3.20.0

**Comment by dsherret** [comment]
Note the version in the URL `https://deno.land/manual@v1.0.0`. That is for version 1.0.0 of Deno.

I don't see this url in the latest version of the manual https://deno.land/manual so I'm going to close this issue.
