### ISSUE TITLE
`const` syntax highlighting not a dark blue color

### ISSUE THREAD

**Issue by csjh** [denoland/vscode_deno#920]
Type: <b>Bug</b>

With the `deno` extension installed, `const` variables lose the blue color that differentiates them from `var` or `let` variables.

Expected:
<img width="116" alt="image" src="https://github.com/denoland/vscode_deno/assets/61282104/5a7c683a-b794-4638-a684-f1452d0947f5">

Got:
<img width="115" alt="image" src="https://github.com/denoland/vscode_deno/assets/61282104/11511ae9-6d79-408c-b883-e8cb0ff276e5">

Notice `abc` in `abc.all` is a light blue, instead of dark.

Extension version: 3.22.0
VS Code version: Code - Insiders 1.79.0-insider (02298ef4180f2a5db39e0cb6288382860b96a596, 2023-05-11T05:50:16.683Z)
OS version: Darwin arm64 22.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 3, 2|
|Memory (System)|16.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id f668b343-94bd-4273-9fd2-fcf08abcf560|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

**Comment by bartlomieju** [comment]
Already fixed bt https://github.com/denoland/deno/pull/20440
