### ISSUE TITLE
Wrong formatting for import attributes using the `with` keyword

### ISSUE THREAD

**Issue by velut** [denoland/vscode_deno#934]
**Describe the bug**

Format on save does not work with import attributes using the `with` keyword, which are supported by Deno 1.37 (https://deno.com/blog/v1.37#import-attributes).

**To Reproduce**

1. Use an import attribute using the `with` keyword like `import data from "./data.json" with { type: "json" };`.
2. Save the file with format on save enabled.
3. After formatting the statement will be broken in two statements: an import statement and an unrelated `with` statement.

**Expected behavior**

The statement is formatted correctly as done when using `deno fmt mod.ts`.

**Screenshots**

Before formatting:

![Screenshot from 2023-09-22 16-58-21](https://github.com/denoland/vscode_deno/assets/12040076/4459ddfc-27f9-42dd-8947-a379fb10c388)

After pressing save and auto-formatting:

![Screenshot from 2023-09-22 16-59-18](https://github.com/denoland/vscode_deno/assets/12040076/7330b953-e71f-4b84-bf77-b05c38cfc73d)

**Versions**

VSCode: 1.82.2
Deno: 1.37.0
Extension: 3.23.1

**Comment by bartlomieju** [comment]
@dsherret does dprint plugin we use already support import attributes?

**Comment by dsherret** [comment]
This works fine for me with Deno 1.37.0.

@velut can you confirm that your Deno version is 1.37.0? It should say in the lower right hand corner

**Comment by velut** [comment]
My bad, sorry! 

I tried everything in a new profile and formatting works correctly.

The issue is caused by having the `Organize Imports` action run on save in my existing profile.
If anyone else is having this issue, you can disable this setting by adding the following to the `settings.json` file:

```json
"[typescript]": {
  "editor.codeActionsOnSave": {
    "source.organizeImports": false
  }
}
```

**Comment by dsherret** [comment]
Ah, yeah so import attributes aren't fully supported in TypeScript yet, but will be in TS 5.3. We added some extra code to make them work with `deno check`. They'll be available sometime in vscode after November 14th.
