### ISSUE TITLE
"Cache dependencies" command seems broken in 1.37.0 and vscode_deno 3.23.1

### ISSUE THREAD

**Issue by dsherret** [denoland/vscode_deno#939]
**Describe the bug**

**To Reproduce**

1. Add an import for something not cached (ex. "https://deno.land/x/code_block_writer/mod.ts")
2. Run "Cache dependencies" command in the command palette (not the quick fix)
3. It will error.

```
Starting Deno language server...
  version: 1.37.0 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\david\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.82.2
  Auto-resolved configuration file: "file:///C:/Users/david/dev/scratch/deno.json"
Enabling import suggestions for: https://deno.land
Server ready.
[Error - 4:12:14 PM] Request workspace/executeCommand failed.
  Message: invalid type: null, expected a sequence
  Code: -32602 
Download https://apiland.deno.dev/completions/resolve/code_block_writer/__latest__/mod.ts
[Error - 4:13:36 PM] Request workspace/executeCommand failed.
  Message: invalid type: null, expected a sequence
  Code: -32602
```

**Expected behavior**

No error

**Screenshots**

![image](https://github.com/denoland/vscode_deno/assets/1609021/00ea8562-d5d1-4263-8239-0c93a4ce9965)

**Versions**

deno: 1.37.0 extension: 3.23.1

**Comment by dsherret** [comment]
I tried on two separate computers and got the same result.

**Comment by nayeemrmn** [comment]
Already fixed by #930. I'll cut a release soon.

**Comment by dsherret** [comment]
Ok awesome. We should release as soon as we can.

**Comment by dsherret** [comment]
Fixed now. Thanks @nayeemrmn!
