### ISSUE TITLE
Extension not compatible with VSCode Version 1.33.1

### ISSUE THREAD

**Issue by pranjul-sharma** [denoland/vscode_deno#94]
Hi, when I am trying to install this extension, I am getting the below error:
![image](https://user-images.githubusercontent.com/19874005/85142217-a6512c00-b265-11ea-8f1a-d736e4a99892.png)

Could you resolve this issue?

**Comment by pranjul-sharma** [comment]
Also using the below tsconfig file is not resolving the deno modules. I am seeing the old VS Code error marking scheme 

// tsconfig.json
```
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-deno-plugin",
        "enable": true, // default is `true`
        "importmap": "import_map.json"
      }
    ]
  }
}
```


![image](https://user-images.githubusercontent.com/19874005/85142680-5d4da780-b266-11ea-83c4-1dfc14984b03.png)

**Comment by buttercubz** [comment]
@pranjul-sharma  you should install a version of vscode 1.45 or higher.
then install the deno extension
