### ISSUE TITLE
Refresh status each time requested.

### ISSUE THREAD

**Issue by mgenereu** [denoland/vscode_deno#944]
**Is your feature request related to a problem? Please describe.**

VS Code appears to be caching `deno.client.status`.  Even if `deno.client.restart`.  I activated `deno.internalDebug` and only see the initial request for `deno:/status.md` and no additional requests after that.

**Describe the solution you'd like**

All calls to `deno.client.status` aquire a fresh copy of `deno:/status.md`.

**Comment by mgenereu** [comment]
Heads up.  I'm still learning how to edit VS Code extensions in VS Code but I was able to research this.  Apparently it's a known issue with markdown preview caching and if you add something like `?random={random_value}` to the URL, it forces a refresh.  I wasn't able to confirm/test but this might help.

**Comment by nayeemrmn** [comment]
Yes! I'm currently working on that. It requires a change in the LSP to accept query strings though.
