### ISSUE TITLE
Deno.stdout when debugging

### ISSUE THREAD

**Issue by Reububble** [denoland/vscode_deno#947]
Writing to Deno.stdout does not appear in the debug console

**To Reproduce**

1. Open new window
2. Place this in a new file
```ts
await Deno.stdout.write(new TextEncoder().encode("cya"));
```
3. F5 to debug with Deno

**Expected behavior**

The debugger should show the string `"cya"`, since it should be identical behaviour (for all intents and purposes) to `console.log("cya")` and writes it correctly when run without debugger.

**Versions**

vscode: 1.82.2 deno: 1.37.0 extension: 3.24.0

**Comment by Reububble** [comment]
`Deno.write` and `Deno.writeSync` also show the same issue.
```ts
await Deno.write(Deno.stdout.rid, new TextEncoder().encode("cya"));
```

**Comment by Reububble** [comment]
I should also mention that I found the issue while trying to `pipeTo` `Deno.stdout`, which also shows the same issue.

**Comment by nayeemrmn** [comment]
This is intended behaviour. The 'console' is piped to any debugger clients as well as stdout, `Deno.stdout` is just stdout.

**Comment by Reububble** [comment]
With that information I was able to fix my issue. Adding `"outputCapture": "std"` to the launch config captures stdout. It's not particularly well documented unless one looks to nodejs specific vscode documentation, but hopefully this helps others with the same issue.
