### ISSUE TITLE
Importing from npm packages?

### ISSUE THREAD

**Issue by bitjson** [denoland/vscode_deno#95]
Thanks for the plugin!

I'm importing using the experimental `npm:` syntax, which works with `deno run`, but shows an error in vscode:

```ts
import { hexToBin } from 'https://deno.land/x/npm:@bitauth/libauth/build/module/index.js';

console.log(hexToBin('beef'));
```

Produces the error: `Cannot find module 'https://deno.land/x/npm:@bitauth/libauth/build/module/index.js' or its corresponding type declarations.` (The declarations are also in the expected location: `https://deno.land/x/npm:@bitauth/libauth/build/module/index.d.ts`.)

Is this expected to work?

**Comment by brandonkal** [comment]
The https://deno.land/x/npm:project style redirects are deprecated and will be removed on August 1st 2020. Instead of importing via deno.land you can import this module directly from unpkg.com via the URL via the URL https://unpkg.com/@bitauth/libauth/build/module/index.js.

**Comment by lucacasonato** [comment]
This syntax is deprecated now. Please use unpkg or simmilar.
