### ISSUE TITLE
Relative imports resolved from import_map.json fail with "import path is not prefixed with / or ./ or ../"

### ISSUE THREAD

**Issue by evelant** [denoland/vscode_deno#961]
**Describe the bug**

If you have a relative import defined in import_map.json the vscode_deno extension will fail to resolve imports with an error like

```
Relative import path "app/index.ts" not prefixed with / or ./ or ../ at file:///Users/imagio/dev/vscode_deno_bug/deno/main.ts:1:21
```

Deno has no problem running the code, it is valid. This makes working with shared code in a monorepo painful/impossible.

**To Reproduce**
https://github.com/evelant/vscode_deno_relative_import_map_bug

**Expected behavior**

vscode_deno should match Deno's behavior and properly support relative imports in import_map.json

**Screenshots**

N/A see repro

**Versions**

vscode: 1.80.0-insider deno: 1.36.0  extension: 3.25.1

**Comment by nayeemrmn** [comment]
This is caused by https://github.com/denoland/deno/issues/20210
