### ISSUE TITLE
Type information (module augmentation) doesn't work properly with the library `effect`

### ISSUE THREAD

**Issue by evelant** [denoland/vscode_deno#967]
**Describe the bug**
When importing [effect](https://github.com/Effect-TS/effect/) from `https://esm.sh/effect@2.0.0-next.46?target=denonext` the extension fails to provide correct types to the editor. `effect` uses standard [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) for many of its types. `effect` works fine with normal typescript, and Deno can run it without issue, it is only the vscode_deno extension that fails to load the types correctly.

```
Argument of type 'Tag<Foo, Foo>' is not assignable to parameter of type 'Effect<unknown, unknown, unknown>'.
  Type 'Tag<Foo, Foo>' is missing the following properties from type 'Effect<unknown, unknown, unknown>': [EffectTypeId], [symbol], [symbol]deno-ts(2345)
```

**To Reproduce**

Reproduction here: https://github.com/evelant/deno_effect_test

**Expected behavior**

vscode_deno should load types correctly

**Screenshots**

N/A

**Versions**

vscode: 1.84.0-insider  deno: 1.37.1 extension: 3.25.1

**Comment by evelant** [comment]
@nayeemrmn or @bartlomieju any ideas about how to move this one forward? All of my code uses `effect` so I get no type checking anywhere I have to use Deno.

**Comment by nayeemrmn** [comment]
@evelant Have you tried using `npm:effect`?

**Comment by evelant** [comment]
@nayeemrmn any update on this? I still can't import effect from esm.sh and have types work in vscode_deno. It runs without issue but it's nearly impossible to develop effect code without typescript support.

**Comment by nayeemrmn** [comment]
@evelant I also get these errors from running `deno check main.ts`. Have you tried that? It's probably a problem with esm.sh.
