### ISSUE TITLE
@deno-types does not work on first load

### ISSUE THREAD

**Issue by Ciantic** [denoland/vscode_deno#97]
**postcsstest.ts**
```typescript
import autoprefixer from "https://jspm.dev/autoprefixer";

// @deno-types="./postcss.d.ts"
import postcss from "https://jspm.dev/postcss";

postcss().use(autoprefixer).process(".something { appearance: none; }", {
    from: undefined
}).then((f: any) => {
    console.log(f.css);
})
```

**postcss.d.ts**
```typescript
export default function(): any;
```

VSCode problem:

![image](https://user-images.githubusercontent.com/64731/85237504-2a570f80-b430-11ea-9e12-b1ab7242cecc.png)

Notice that it runs correctly, and *deno* understands the `@deno-types` just fine, it's just this VSCode extension that doesn't understand these.

Also I think this is the reason for errors elsewhere, e.g. https://github.com/keroxp/servest/issues/133

**Comment by Grunet** [comment]
I kept thinking something was wrong with my declaration file setup, but I've been running into the same thing (with cheerio instead).

As far as I can tell this might be related to @ry 's recent [PR](https://github.com/denoland/vscode_deno/pull/84) that downgraded the version of the typescript-deno-plugin package being used to before the [1.31.0 version](https://github.com/justjavac/typescript-deno-plugin/blob/master/CHANGELOG.md) where support for deno-types seems to have been introduced in [this PR](https://github.com/justjavac/typescript-deno-plugin/pull/46) from @justjavac .

But I haven't found any other discussion around this yet so that might not be an entirely accurate skeleton of a story.

**Comment by HoffmannP** [comment]
Same problem here:

```typescript
import jsdom from "https://jspm.dev/jsdom";

const dom = new jsdom.JSDOM("<h1>Hello World!</h1>", { url: "http://localhost "})
console.log(dom.window.document.querySelector("h1").textContent)
```

**Comment by Soremwar** [comment]
Might be related as well

```javascript
// @deno-types="https://denopkg.com/soremwar/deno_types/react/v16.13.1/react.d.ts"
export * from "https://cdn.skypack.dev/react";
```

Shows no types for either React or its named imports, even though JavaScript can see them just fine when I log them out

**Comment by axetroy** [comment]
### Report current progress

**Known issues**

On the first load, @deno-types failed to load correctly

You only need to make any changes to trigger a refresh

![1](https://user-images.githubusercontent.com/9758711/91651552-ad47b680-eac0-11ea-8bd4-2330b1b87d61.gif)


I have been aware of this problem for a long time, but I’m not sure if it’s a bug in typescript or I’m using it incorrectly.

### How @deno-types works in typescript-deno-plugin

In fact, `typescript-deno-plugin` proxy the typescript method of finding modules.

https://github.com/denoland/vscode_deno/blob/5b379fb995e402ef1fbd808d6f8385ebeca87d62/typescript-deno-plugin/src/plugin.ts#L353-L362

When the `import xxx from "xxx"` statement is detected, and there is `// @deno-types="xxxx"` in the previous line of code, it will look for the module specified by deno-types.

And return this path

https://github.com/denoland/vscode_deno/blob/5b379fb995e402ef1fbd808d6f8385ebeca87d62/typescript-deno-plugin/src/plugin.ts#L469-L487

https://github.com/denoland/vscode_deno/blob/5b379fb995e402ef1fbd808d6f8385ebeca87d62/typescript-deno-plugin/src/plugin.ts#L530-L542

But it’s very strange that it didn’t take effect the first time it was run, and it only took effect the second.

If someone is good at typescript, please don't be stingy with your help

**Comment by Grunet** [comment]
Wow thank you for that awesome workaround @axetroy + the investigation into this. 

It also seems to work for me if I open the cached d.ts file in VS Code and then save it without making any changes (and then the red squiggles go away and the intellisense from the typings comes in), but as soon as I close the cached d.ts file the squiggles/lack of intellisense comes back. Not sure if others are seeing that behavior as well (deno 1.1.0, typescript 3.9.2, Deno VS Code extension 2.0.16)

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/94640249-af47a400-0310-11eb-9418-42062ab46b00.png)

first time run the typescript-deno-plugin already give the right result, but tsserver didn't pick it up yet  ...until resolveModuleNames retriggered second time

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/94640588-bb803100-0311-11eb-89d4-82a013a90151.png)

really annoying when something should work but didn't

**Comment by CGQAQ** [comment]
![KXgQj81unt](https://user-images.githubusercontent.com/15936231/94641119-f171e500-0312-11eb-80ec-c6457d4ce7ab.gif)

really? Microsoft?

**Comment by CGQAQ** [comment]
![lTGP5Llsvj](https://user-images.githubusercontent.com/15936231/94642384-888c6c00-0316-11eb-931a-da0d36562f81.gif)

**Comment by lucacasonato** [comment]
Resolved in version 3.x of the extension.
