### ISSUE TITLE
If import a js file, should automatically find and import the d.ts file

### ISSUE THREAD

**Issue by ieavid** [denoland/vscode_deno#970]
**Is your feature request related to a problem? Please describe.**

Sometimes I only have js source files and declaration files, and when I import the js files, I can't get the type information

**Describe the solution you'd like**

For example

mod.js
```js
export function add(a, b) {
    return a + b
}
```
mod.d.ts
```ts
export declare function add(a: number, b: number): number;
```

main.ts
```ts
import { add } from "./mod.js";  // It should import type information for ./mod.d.ts,
const result = add(1, 2);  //The result should be of type number, not any

```

**Comment by nayeemrmn** [comment]
You have to specify `/// <reference types="./mod.d.ts" />` at the top of `mod.js`. The extension won't automatically discover declaration files since CLI (`deno check`) doesn't. Does that solution work for you?
