### ISSUE TITLE
Nit: Space is missing in intellisense information

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/vscode_deno#972]
**Describe the bug**

Missing space in intellisense.

**To Reproduce**

1. Create a file `foo.ts` with these contents:
  ```tsx
  class Foo {}
  export { Foo }
  ```
2. Create a file `main.ts` with these contents:
  ```tsx
  import * as foo from "./foo.ts";
  
  // Press dot here to trigger intellisense
  foo.
  ```
3. Popup will have missing space

**Expected behavior**

A space between the class name and the export

**Screenshots**

<img width="516" alt="Screenshot 2023-10-12 at 12 41 56" src="https://github.com/denoland/vscode_deno/assets/1062408/6d4ced52-7b65-438d-9684-081bb7266460">

**Versions**

vscode: insiders from 2023-10-11 deno: 1.37.1 extension: 3.26.0

**Comment by nayeemrmn** [comment]
This seems to be just how vscode renders the detail string when it's inlined (press the `>` at the end of the suggestion line to pop it out into a separate box). It strips newlines. And this detail string is generated by the embedded TS server. So the same can be observed with the Node TS language server.

It's not actionable for us.
