### ISSUE TITLE
Cannot use “deno.enablePaths” in a multi-root workspace

### ISSUE THREAD

**Issue by ymeine** [denoland/vscode_deno#974]
*Related issues: I found multiple issues related to `enablePaths`, but none seemed to be fully relevant (use cases and expectations can greatly vary).*

Hi,

After a few hours of investigation, I finally understood why my `enablePaths` configuration didn’t work in my simple multi-root workspace.

To explain that I’ll unfortunately have to spend a bit of time explaining what kind of project structure I manage, and what I understood about the behavior of the Deno extension.

## My projects structure

I have a lot of repositories, and all of them have a root vscode workspace file. Each workspace contains a bunch of root folders, because all projects are made of many deep branches of folders and files.

Some projects are applications monorepos, so *usually* the root folders will correspond to the different components (frontend, server, tools, db, etc.)

Some are playgrounds where I may test different, similar tools, so *usually* the root folders will correspond to each of those tools.

In any case, I can have “complex” structures involving: 

- deeply nested components (many nested folders for a better organization)
- a mix of technologies (therefore requiring specific configuration *per* folder)

Above, I insisted on the term “usually”, but that’s actually where I have issues: *often*, I do not put one root folder per isolated component/domain, I can indeed use a root folder for multiple of them. So for example, I could have a root folder that contains one folder for Deno, one for Node.js.

But what’s more is that I can often ***change*** the structure of my workspace, and update root folders, sometimes going one level up, one level down, commenting out some in the JSON workspace configuration, etc. So with the same example as above, I could from time to time turn the Deno and Node.js folder into workspace root folders, and later on go back to a single ancestor root folder. I do that to focus on specific features at a given point in time.

The real problem I have with the vscode extensions ecosystem is that they all assume - at best - that those root folders are stable, and correspond exactly to one properly isolated component (e.g. no mix of technologies) .

## A quick example of something I tried to do

*The example here is not a real project, I try to simplify as much as possible here for the sake of the issue.*

Take that structure of project: 

```
my-workspace-root/
├── component-for-node/
│   └── main.ts
├── component-for-deno/
│   └── main.ts
└── my-workspace.code-workspace
```

And that workspace configuration: 

```json
{
	"folders": [
		{
			"path": "./component-for-deno"
		},
		{
			"path": "./component-for-node"
		},
		{
			"name": "<root>",
			"path": "."
		}
	],
	"settings": {}
}
```

Which makes it appear as: 

```
component-for-deno/
└── my-other-script.ts
component-for-node/
└── my-script.ts
<root>/
├── component-for-deno/
├── component-for-node/
└── my-workspace.code-workspace
```

Try to enable Deno only for `./component-for-deno`.

Attempt 1: 

in `./my-workspace.code-workspace:` 

```json
"settings": {
	"deno.enablePaths": ["/my-workspace-root/component-for-deno"]
}
```

Attempt 2: 

in `./my-workspace.code-workspace:` 

```json
"settings": {
	"deno.enablePaths": ["./component-for-deno"]
}
```

Attempt 3: 

in `./my-workspace.code-workspace:` 

```json
"settings": {
	"deno.enablePaths": ["./"]
}
```

Attempt 4: 

in `./component-for-deno/.vscode/settings.json`: 

```json
{
	"deno.enablePaths": ["./"]
}
```

Attempt 5: 

in `./.vscode/settings.json`

```json
{
	"deno.enablePaths": ["./component-for-deno"]
}
```

Here are the results: 

- in all attempts except the 5th I do manage to get Deno to apply to `./component-for-deno/main.ts`
- now, per attempt:
    - attempt 1: can’t get rid of the default TypeScript behavior
    - attempt 2: ditto
    - attempt 3: gets rid of it, but also enables Deno on `./component-for-node`, which I don't want
    - attempt 4: works, but only as long as `./component-for-deno` remains a workspace root folder (which is incompatible when the structure changes often as I explained in previous section)
    - attempt 5: does disable the default TypeScript behavior, but strangely also the Deno one!

To explain why, I need to explain how the extension works (from my understanding after investigation).

## How the Deno extension works

- there’s the vscode extension itself, `denoland.vscode-deno`
- this extension, among many other things, registers a tsserver plugin to override some of the default TypeScript behavior with custom Deno logic. That plugin is implemented in a dependency `typescript-deno-plugin` (btw, there are two copies of this plugin under `denoland.vscode-deno`, one at the root, and one under `node_modules`: it’s the latter that gets effectively registered).
- to know whether the default TypeScript behavior should be overridden or not, the plugin checks the path associated to the LSP request, and compares it to the configuration given to the `denoland.vscode-deno` extension
    - if Deno is enabled with `enable: true`, it’s simple, it always overrides
    - but if `enablePaths` is used, it requires a bit more checking, and that’s where the trouble begins

<details><summary>How to investigate?</summary>
<p>
To understand what happens, in addition to checking the implementation I added manual logs in the file <code>denoland.vscode-deno-3.26.0/node_modules/typescript-deno-plugin/dist/index.js</code>. To see those logs, activate the tsserver logs and open them with the command <code>TypeScript: Open TS Server log</code> (warning: you need to be focusing an editor with TypeScript language for that command to appear in the command palette). It helped me investigate. However the configurations I extracted are already logged by the plugin, so no need to edit anything to get those.
</p>
</details> 

Here’s basically the kind of configuration passed to the tsserver plugin (I cropped the structure to focus on what matters): 

```typescript
interface Configuration {
  documents: {
    // each key is an absolute path to a TypeScript document
    [key: string]: {
      settings: {
        enable: boolean | null;
        disablePaths: string[];
        enablePaths: string[];
      };
    };
  };
  pathFilters: {
    workspace: string; // the absolute path of what is actually a workspace root folder (not a workspace)
    disabled: string[]; // we'll ignore that for the sake of this issue, but it may suffer from the same bugs
    enabled: string[]; // built from the enabledPaths settings
  }[];
}
```

Now, the plugin checks if default TypeScript behavior must be overridden by using the configuration of the first matched `pathFilters` item. To find that one, it will take **the first instance** where the LSP request path starts with the `workspace` path.

If one is found, it will check if that LSP request path matches any of the enabled path in that `pathFilter`, again by checking if it starts with that.

## Application to my attempts

For each attempt I will show an excerpt of the configuration received by the plugin, and explain why it didn't work.

### Attempt 1: absolute paths don’t work

Not a big deal, hardcoding absolute paths is a non-sense here, but still it shouldn’t be broken.

Configuration: 

```json
{
    "documents": {
        "c:\\my-workspace-root\\component-for-deno\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "C:/my-workspace-root/component-for-deno"
                ]
            }
        },
        "c:\\my-workspace-root\\component-for-node\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "C:/my-workspace-root/component-for-deno"
                ]
            }
        }
    },
    "pathFilters": [
        {
            "workspace": "c:\\my-workspace-root\\component-for-deno",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno\\C:\\my-workspace-root\\component-for-deno"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root\\component-for-node",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-node\\C:\\my-workspace-root\\component-for-deno"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\C:\\my-workspace-root\\component-for-deno"
            ]
        }
    ]
}
```

What should be done: don’t join two absolute paths together.

### Attempt 2: relative path is applied to each workspace root

Configuration: 

```json
{
    "documents": {
        "c:\\my-workspace-root\\component-for-deno\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "./component-for-deno"
                ]
            }
        },
        "c:\\my-workspace-root\\component-for-node\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "./component-for-deno"
                ]
            }
        }
    },
    "pathFilters": [
        {
            "workspace": "c:\\my-workspace-root\\component-for-deno",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno\\component-for-deno"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root\\component-for-node",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-node\\component-for-deno"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno"
            ]
        }
    ]
}
```

What should be done: I would just not do that. If the configuration comes from the workspace, and not a root folder, why treating the path as relative to *every* root folders? It barely makes sense.

Btw, if I put my highest level folder first in the list of root folders, it will now work, because the algorithm checks for the first matching `pathFilters` item, and the only one which is correct is the one for the workspace root (since that’s how the path was logically/mentally specified by the user).

### Attempt 3: adapted relative path works but is too generic

So if the path gets joined for every root, then let’s reason and find one relative path that will work once joined: `./` of course, since it means “that current folder”.

Configuration: 

```json
{
    "documents": {
        "c:\\my-workspace-root\\component-for-deno\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "./"
                ]
            }
        },
        "c:\\my-workspace-root\\component-for-node\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "./"
                ]
            }
        }
    },
    "pathFilters": [
        {
            "workspace": "c:\\my-workspace-root\\component-for-deno",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno\\"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root\\component-for-node",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-node\\"
            ]
        },
        {
            "workspace": "c:\\my-workspace-root",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\"
            ]
        }
    ]
}
```

But then the issue is obvious: it becomes completely equivalent to enabling Deno globally, because every workspace root folder will now match!

### Attempt 4: a local root folder configuration will be properly joined

So, intuitively I suspected some generic aggregation of the possible sources of configuration to be the culprit of this weird behavior.

Therefore I thought: “if the configuration is coming from a workspace root folder, maybe the relative path specified in it will be joined only with that root folder”. Therefore I could use the previous `./` trick, without impacting the other root folders.

Configuration: 

```json
{
    "documents": {
        "c:\\my-workspace-root\\component-for-deno\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": [
                    "./"
                ]
            }
        },
        "c:\\my-workspace-root\\component-for-node\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": []
            }
        }
    },
    "pathFilters": [
        {
            "workspace": "c:\\my-workspace-root\\component-for-deno",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno\\"
            ]
        }
    ]
}
```

And yes, it works. But I’m pretty sure one will find it weird that the extension actually requires any path that needs to be enabled to become a workspace root folder, and to have the same `enablePaths` configuration for, that is with a single `./` entry.

### Attempt 5: if a local folder configuration is isolated, maybe the root’s one will be

So to follow my intuition again (and honestly, this one came while writing that issue), I tried a mix between attempt 2 and 4, simply moving the configuration from `./my-workspace.code-workspace` to `./.vscode/settings.json`, to see if the implementation treats it differently.

Configuration: 

```json
{
    "documents": {
        "c:\\my-workspace-root\\component-for-deno\\main.ts": {
            "settings": {
                "enable": null,
                "disablePaths": [],
                "enablePaths": []
            }
        }
    },
    "pathFilters": [
        {
            "workspace": "c:\\my-workspace-root",
            "disabled": [],
            "enabled": [
                "c:\\my-workspace-root\\component-for-deno"
            ]
        }
    ]
}
```

And it does! So I could get rid of the default TypeScript behavior only on `./component-for-deno`, as I wanted. But unfortunately it also made the Deno behavior not work (looks like the document entry gets no `enablePaths`)… So, another failure on my side.

## Conclusion

At that stage, I found no workaround despite all my attempts. To me it looks like a combination of many “small” issues linked to the consolidation of the settings, and some edge cases handling. I’m personally blocked (so I use [Node.js](https://nodejs.org/en) with [tsx](https://github.com/esbuild-kit/tsx) but that’s really not the same performance ***at all*** and it lacks the specific DX of Deno regarding dependencies management).

I don’t even know what to suggest, because I’m unsure of two things: 

- what’s the real intent of the extension regarding how to interpret and aggregate the enable/disable path filters
- what is the part of responsibility coming from vscode itself, because it’s not the first time I see issues like that in vscode extensions ([had some trouble to configure some C++ include paths per folder](https://github.com/microsoft/vscode-cpptools/discussions/8226#discussioncomment-2338521)).

At least for the first bullet point, a more [detailed documentation here](https://docs.deno.com/runtime/manual/references/vscode_deno#partially-deno-enabling-a-workspace) could be beneficial.

This leaves me with my own interpretation of what the feature should be. In general, I would tend to identify this: 

- what is the point of reference for the tool: here I would say it’s the actual file system, with actual folder paths
- what is the perspective of the user (developer): here it’s the different ways to configure the extension in vscode, meaning global settings, user settings, workspace settings (with two ways to do it), and root folder settings

With that I would normalize the settings, taking into account their context in a sensible way (e.g. treat relative paths as relative to the configuration path), to reach a normalized reference model which would look like a global, flat set of enabled or disabled paths. Here I really don’t understand the purpose of having a list `pathFilters` corresponding to each workspace root folder, plus a dictionary of `documents` including themselves enabled/disabled paths (which all looks like duplicate information), when eventually what Deno needs to know is just what absolute paths are enabled or disabled.

Let me know what you think, and thanks in advance for your time spent reading that long post.

## Versions

- vscode: 1.83.0
- deno: 1.37.1
- extension: 3.26.0

**Comment by nayeemrmn** [comment]
This should be fixed by #1086. I'll cut a release shortly.
