### ISSUE TITLE
jupyter: lsp is not keeping state across cells

### ISSUE THREAD

**Issue by sigmaSd** [denoland/vscode_deno#977]
If I define a variable on a cell, I get `cannot find variable ` an other cells, (only for lsp, the actual running does work)

![image](https://github.com/denoland/vscode_deno/assets/22427111/87246151-e1b6-41c8-9f3b-b83267ce0e5b)

deno 1.37.2+bd238be (canary, x86_64-unknown-linux-gnu)

**Comment by nayeemrmn** [comment]
Duplicate of #932
