### ISSUE TITLE
Solution style tsconfig.json causes language server to crash

### ISSUE THREAD

**Issue by muuvmuuv** [denoland/vscode_deno#98]
I have migrated my Angular 9 project to 10 today and noticed that they changed the tsconfig.json and introduced "Solution style" tsconfig. VS Code itself is aware of this change but the deno extension causes a crash of the language server.

Ref: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig

Idk how to reproduce it with Deno but anyway I think it should be better tested if the current workspace is a Deno project or Node/basic JavaScript/TypeScript project. Checking if a package.json is exists and not activate the deno extension would be a good first step.

**Comment by lucacasonato** [comment]
Should be resolved in version 3.x of the extension.
