### ISSUE TITLE
The task provider for "denoTasks" tasks unexpectedly provided a task of type "deno"

### ISSUE THREAD

**Issue by zerodegress** [denoland/vscode_deno#983]
**Describe the bug**
Like **Screenshots** the warning as title said always pop every time when the vscode_deno extension is loaded.
It is not critical but it really annoys me every time I open a Deno project.

**To Reproduce**

1. Ensure the vscode_deno extension installed
2. Open any folder with vscode and ensure enabled 'deno.enable'

**Expected behavior**

There comes the warning like **Screenshots**, with texts like 'The task provider for "denoTasks" tasks unexpectedly provided a task of type "deno"'.

**Screenshots**
![图片](https://github.com/denoland/vscode_deno/assets/60560055/2bb5350a-629f-4b20-8430-a1a7a8d799cd)

**Versions**

vscode: 1.83.1 deno: 1.37.2 extension: v3.26.0

**Comment by bartlomieju** [comment]
@nayeemrmn please take a look

**Comment by nayeemrmn** [comment]
I think this is fixed in vscode_deno 3.27.0, can you upgrade and check @luminr?

**Comment by nayeemrmn** [comment]
Oh, it looks like 3.27 had failed to publish
![image](https://github.com/denoland/deno/assets/29990554/f5c991c8-7f3a-4272-906b-538427d2adea)

Looking into it

**Comment by nhrones** [comment]
I get this error msg all the time, but thought it was because I never use a deno.json file??
Only on start of new deno enabled project with /.vscode/tasks.json/ with deno tasks in it..
I have boilerplate with tasks in tasks.json
```
      {
         "label": "TEST",
         "type": "deno",
         "command": "test",
         "args": ["tests/"],
         "problemMatcher": [
            "$deno-test"
         ]
      },
```
Do I need to use `deno.json`?

**Comment by nhrones** [comment]
Think I've commented on the wrong issue.  Sorry.

**Comment by pillowsoft** [comment]
It's still an issue in v3.28.0 with deno 1.38.4
