### ISSUE TITLE
Command 'Deno: Restart Deno Language server' resulted in an error

### ISSUE THREAD

**Issue by alexweininger** [denoland/vscode_deno#99]
Getting this error when trying to run the Restart command from the command palette.
![image](https://user-images.githubusercontent.com/12476526/86194707-12ece600-bb04-11ea-9941-5ebd80a83762.png)

Steps I took to get to this error:

1. Open VS Code Stable
2. Install Deno extension
3. Command palette (F1) > Restart Deno

**Comment by lucacasonato** [comment]
This has been resolved in version 3.x of the extension.
