### ISSUE TITLE
Glob support for enable/disable path

### ISSUE THREAD

**Issue by bombillazo** [denoland/vscode_deno#990]
**Is your feature request related to a problem? Please describe.**

At the moment, it seems it is only possible to determine absolute paths for Deno to recognize or ignore. If we have deno files colocated with other TS files (node or front end for example) then we cant narrow down the Deno plguin to only focus on certain files.

```json
"deno.enablePaths": [
    "./scr",
    "./scripts/script1.deno.ts",
    "./scripts/script2.deno.ts",
    "./scripts/script3.deno.ts"
  ],
```

**Describe the solution you'd like**

It would be great to support globs to be able to filter files that Deno recognizes inside the IDE.

```json
"deno.enablePaths": [
    "./scr",
    "./scripts/**/*.deno.ts"
  ],
```

**Comment by d9k** [comment]
See also #834

I [wrote a CLI script](https://github.com/denoland/vscode_deno/issues/834#issuecomment-1817740558) to configure `.vscode/settings.json ` as a temporary solution

**Comment by nayeemrmn** [comment]
Closing in favour of #834.
