### ISSUE TITLE
Task panel doesn't show any tasks (works w/3.26 but not 3.27)

### ISSUE THREAD

**Issue by pjeby** [denoland/vscode_deno#991]
**Describe the bug**
No tasks appear in the pane when VSCode starts.  Downgrading manually to 3.26 fixes the issue.

**To Reproduce**
1. Put tasks in deno.jsonc at project root.
2. Open VSCode w/deno extension 3.27

**Expected behavior**
Tasks appear in tasks pane.

**Versions**
vscode: 1.84.2 deno: 1.38.1 extension: 3.27

**Comment by bartlomieju** [comment]
CC @nayeemrmn please take a look

**Comment by nayeemrmn** [comment]
I can't reproduce, can you share your `deno.jsonc`?

**Comment by pjeby** [comment]
```jsonc
{
    "tasks": {
        "test": "deno test",
        "dev": "deno test --watch",
        "coverage": "rm -rf cov_profile; deno test --coverage=cov_profile; deno coverage --lcov --output=lcov.info cov_profile"
    },
    "compilerOptions": {
        "strict": false,
        "strictBindCallApply": true
    }
}
```

**Comment by Nedgeva** [comment]
Comparing two uris can lead to this issue in some environments like Windows. I opened PR which (hopefully) should beat this issue.
