### ISSUE TITLE
`invalid type: null, expected a boolean` since 3.27.0

### ISSUE THREAD

**Issue by umajho** [denoland/vscode_deno#994]
## **Describe the bug**

Since 3.27.0, this plugin doesn't work for me anymore.
If I rolled back to use 3.26.0, everything worked fine again.

## **To Reproduce**

I can always reproduce this problem, but I don't know what leads to that.
As long as I open a new VSCode window and touch some files that activates this plugin, the errors will occur.
I have tried close and restart VSCode entirely, but it doesn't help.

## **Expected behavior**

This plugin works.

### 3.28.0

<img width="1916" alt="3 28 0-final" src="https://github.com/denoland/vscode_deno/assets/107099960/4cba3878-9b20-4c20-84b0-818dce38a316">

<details>
<summary>Output of Deno Language Server</summary>

```
Starting Deno language server...
  version: 1.34.2 (release, x86_64-apple-darwin)
  executable: /usr/local/bin/deno
Connected to "Visual Studio Code" 1.84.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 6:11:56 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 6:11:56 PM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
```

</details>

### 3.27.0

<img width="1916" alt="3 27 0" src="https://github.com/denoland/vscode_deno/assets/107099960/19a81201-1d50-45bf-88e7-1b4368404a07">

<details>
<summary>Output of Deno Language Server</summary>

```
Starting Deno language server...
  version: 1.34.2 (release, x86_64-apple-darwin)
  executable: /usr/local/bin/deno
Connected to "Visual Studio Code" 1.84.2
Enabling import suggestions for: https://deno.land
Error converting specifier settings (untitled:Untitled-1): Error converting specifier settings: invalid type: null, expected a boolean
Server ready.
```

(although it says “Server ready”, It still doesn't work: I have tried to let it to format a markdown file, but nothing happened.)

</details>

### 3.26.0

<img width="1916" alt="3 26 0" src="https://github.com/denoland/vscode_deno/assets/107099960/b7e49464-9e4e-413b-ba14-3bbcd133ad89">

<details>
<summary>Output of Deno Language Server</summary>

```
Starting Deno language server...
  version: 1.34.2 (release, x86_64-apple-darwin)
  executable: /usr/local/bin/deno
Connected to "Visual Studio Code" 1.84.2
Enabling import suggestions for: https://deno.land
Server ready.
```

</details>

## **Versions**

vscode: 1.84.2 deno: 1.34.2 extension: 3.28.0

**Comment by TaxBusby** [comment]
I hit this as well on an older verison of deno (1.30.x); updating to latest 1.38.2 seemed to resolve the issue

**Comment by umajho** [comment]
> I hit this as well on an older verison of deno (1.30.x); updating to latest 1.38.2 seemed to resolve the issue

You are absolutely right. After installing deno 1.38.2, this problem has gone. Thank you!

Should I close this issue?
